:_newdoc-version: 2.18.3
:_template-generated: 2024-11-13

:_mod-docs-content-type: CONCEPT

[id="using-a-dedicated-service-to-provide-data-to-the-quick-access-card_{context}"]
= Using a dedicated service to provide data to the Quick access card

When using a dedicated service, you can do the following tasks:

* Use the same service to provide the data to all configurable {product-short} pages or use a different service for each page.
* Use the https://github.com/redhat-developer/red-hat-developer-hub-customization-provider[`red-hat-developer-hub-customization-provider`] as an example service, which provides data for both the Home and Tech Radar pages. The `red-hat-developer-hub-customization-provider` service provides the same data as default {product-short} data. You can fork the `red-hat-developer-hub-customization-provider` service repository from GitHub and modify it with your own data, if required.
* Deploy the `red-hat-developer-hub-customization-provider` service and the {product-short} Helm chart on the same cluster.

.Prerequisites

* You have installed the {product} using Helm chart.
For more information, see xref:{installing-on-ocp-book-url}#assembly-install-rhdh-ocp-helm[{installing-on-ocp-book-title} with the Helm chart].

.Procedure

To use a separate service to provide the Home page data, complete the following steps:

. From the *Developer* perspective in the {ocp-brand-name} web console, click *+Add* > *Import from Git*.
. Enter the URL of your Git repository into the *Git Repo URL* field.
+
--
To use the `red-hat-developer-hub-customization-provider` service, add the URL for the https://github.com/redhat-developer/red-hat-developer-hub-customization-provider[red-hat-developer-hub-customization-provider] repository or your fork of the repository containing your customizations.
--

. On the *General* tab, enter `red-hat-developer-hub-customization-provider` in the *Name* field and click *Create*.
. On the *Advanced Options* tab, copy the value from *Target Port*.
+
[NOTE]
====
*Target Port* automatically generates a Kubernetes or {ocp-short} service to communicate with.
====
+
. Add the following code to the `app-config-rhdh.yaml` file:
+
[source,yaml]
----
proxy:
  endpoints:
    # Other Proxies
    # customize developer hub instance
    '/developer-hub':
      target: ${HOMEPAGE_DATA_URL} <1>
      changeOrigin: true
      # Change to "false" in case of using self-hosted cluster with a self-signed certificate
      secure: true
----
<1> `pass:c[http://<SERVICE_NAME>:8080]`, for example, `pass:c[http://rhdh-customization-provider:8080]`.
+
[NOTE]
====
The `red-hat-developer-hub-customization-provider` service contains the 8080 port by default. If you are using a custom port, you can specify it with the 'PORT' environmental variable in the `app-config-rhdh.yaml` file.
====
+
. Replace the `HOMEPAGE_DATA_URL` by adding the URL to `rhdh-secrets` or by directly replacing it in your custom ConfigMap.
+
. Delete the {product-short} pod to ensure that the new configurations are loaded correctly.

.Verification
* To view the service, go to the *Administrator* perspective in the {ocp-short} web console and click *Networking* > *Service*.
+
[NOTE]
====
You can also view *Service Resources* in the Topology view.
====

* Ensure that the provided API URL for the Home page returns the data in JSON format as shown in the following example:
+
[source,json]
----
[
  {
    "title": "Dropdown 1",
    "isExpanded": false,
    "links": [
      {
        "iconUrl": "https://imagehost.com/image.png",
        "label": "Dropdown 1 Item 1",
        "url": "https://example.com/"
      },
      {
        "iconUrl": "https://imagehost2.org/icon.png",
        "label": "Dropdown 1 Item 2",
        "url": ""
      }
    ]
  },
  {
    "title": "Dropdown 2",
    "isExpanded": true,
    "links": [
      {
        "iconUrl": "http://imagehost3.edu/img.jpg",
        "label": "Dropdown 2 Item 1",
        "url": "http://example.com"
      }
    ]
  }
]
----
+
[NOTE]
====
If the request call fails or is not configured, the {product-short} instance falls back to the default local data.
====

* If the images or icons do not load, then allowlist them by adding your image or icon host URLs to the content security policy (csp) `img-src` in your custom ConfigMap as shown in the following example:

[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
    backend:
      csp:
        connect-src:
          - "'self'"
          - 'http:'
          - 'https:'
        img-src:
          - "'self'"
          - 'data:'
          - <image host url 1>
          - <image host url 2>
          - <image host url 3>
    # Other Configurations
----


