[id='con-relnotes-notable-features_{context}']
= New features

This section highlights new features in {product} {product-version}.

== Backstage version update

{product} is now based on the upstream Backstage project v{product-backstage-version}.

== Telemetry
With this update, you can use the telemetry data collection feature, which is enabled by default. Analyzing the collected data helps in improving your experience with {product}. You can disable this feature based on your needs. For more information, see the link:{LinkAdminGuide}#disabling-telemetry-data-collection_assembly-install-rhdh-ocp[Disabling telemetry data collection in {product-very-short}] section.

== Audit logging

Administrators can view details about application changes, including the name and role of the user who made the change and the time that the change was made. Audit log data is captured by the RBAC plugin and scaffolder actions by default.

Administrators can now use the audit logs to view changes to the catalog database. Tracking changes that add, remove, or update data in the catalog database helps ensure the accountability and transparency of actions.

== RBAC conditional policies
You can now use RBAC conditional policies in {product}, enabling access control based on dynamic conditions. These conditions act as content filters for {product-short} resources that are managed by the RBAC plugin.

You can specify the conditional policies for the Keycloak and Quay Actions plugins. Also, you must consider reviewing your security needs for components that do not have RBAC controls.

For more information, see link:{LinkAdminGuide}#con-rbac-overview_assembly-rhdh-integration-aks[Role-Based Access Control (RBAC) in {product}].

== RBAC permissions for OCM and Topology plugins
Basic permissions for OCM and Topology plugins are now added to the {product}. You must consider reviewing your security needs for components that do not have RBAC controls.

== Support for corporate proxy

With this update, you can run the {product-very-short} application behind a corporate proxy by setting the `HTTP_PROXY` or `HTTPS_PROXY` environment variable. Also, you can set the `NO_PROXY` environment variable to exclude certain domains from proxying.  For more information, see the link:{LinkAdminGuide}#assembly-running-rhdh-behind-a-proxy[Running the {product-very-short} application behind a corporate proxy] section.

== Support for external PostgreSQL databases

With this update, you can configure and use external PostgreSQL databases in {product}. Based on your needs, you can use a PostgreSQL certificate file to configure an external PostgreSQL instance using the Operator or Helm Chart. For more information, see the link:{LinkAdminGuide}#assembly-configuring-external-postgresql-databases[Configuring external PostgreSQL databases] section.

You can configure an {product-very-short} instance with a Transport Layer Security (TLS) connection in a Kubernetes cluster, such as an Azure Red Hat OpenShift (ARO) cluster, any cluster from a supported cloud provider, or your own cluster with proper configuration. For more information, see the link:{LinkAdminGuide}#proc-configuring-an-rhdh-instance-with-tls-in-kubernetes_assembly-installing-rhdh-on-ocp-by-using-the-operator[Configuring an RHDH instance with a TLS connection in Kubernetes].

== New plugins included in {product} {product-version}

The following additional plugins are included in {product} {product-version}:

* HTTP Request action - `@roadiehq/scaffolder-backend-module-http-request`
* Microsoft Azure repository actions for the scaffolder-backend - `@parfuemerie-douglas/scaffolder-backend-module-azure-repositories`
* Catalog backend module for GitLab organizational data - `@backstage/plugin-catalog-backend-module-gitlab-org`
* Catalog backend module for scaffolder relation catalog processor - `@janus-idp/backstage-plugin-catalog-backend-module-scaffolder-relation-processor`
* A second ArgoCD frontend plugin - `@janus-idp/backstage-plugin-argocd`

For a comprehensive list of supported dynamic plugins, see the link:{LinkPluginsGuide}#con-preinstalled-dynamic-plugins[Preinstalled dynamic plugins].

== Theme updates in {product}

With this update, theme configurations are enhanced to change the look and feel of different UI components so that they almost resemble the theme that is usually used in designing {company-name} applications. You might notice changes in UI components, such as buttons, tabs, sidebars, cards, and tables along with some changes in background color and font used on the {product-very-short} pages.

You can update the `app-config.yaml` file to change the look of multiple {product-short} theme components for enhanced customization.

== `scaffolderFieldExtensions` configuration option

You can now use the `scaffolderFieldExtensions` configuration option in a dynamic plugin's front-end configuration. The `scaffolderFieldExtensions` option allows a dynamic plugin to specify one or more exported components to be provided to the scaffolder plugin as field extensions. These scaffolder field extensions provide custom form field components for the software template wizard.

== Enhancement to ConfigMap or Secret configuration

In previous versions, updating ConfigMaps or Secrets specified in `Backstage.spec.Application` required recreating the Pod to apply changes. Beginning with version {product-version}, this process is automated.

== Ability to configure learning paths

You can now configure Learning Paths in {product-short} to create a dynamic experience tailored to your specific learning needs.

== Plugin version upgrades in {product} 1.2.2

In {product} 1.2.2, the following plugin versions are upgraded as follows:

[cols="50%,25%,25%", frame="all", options="header"]
|===
|Plugin
|Version in 1.2.0
|Version in 1.2.2

|`@janus-idp/backstage-plugin-3scale-backend`
|1.5.13
|1.5.15

|`@janus-idp/backstage-plugin-aap-backend`
|1.6.13
|1.6.15

|`@janus-idp/backstage-plugin-acr`
|1.4.11
|1.4.13

|`@janus-idp/backstage-plugin-analytics-provider-segment`
|1.4.7
|1.4.9

|`@janus-idp/backstage-plugin-argocd`
|1.1.6
|1.2.3

|`@janus-idp/backstage-plugin-jfrog-artifactory`
|1.4.9
|1.4.11

|`@janus-idp/backstage-plugin-keycloak-backend`
|1.9.10
|1.9.12

|`@janus-idp/backstage-plugin-nexus-repository-manager`
|1.6.8
|1.6.10

|`@janus-idp/backstage-plugin-ocm`
|4.1.6
|4.1.8

|`@janus-idp/backstage-plugin-ocm-backend`
|4.0.6
|4.0.8

|`@janus-idp/backstage-plugin-quay`
|1.7.6
|1.7.8

|`@janus-idp/backstage-scaffolder-backend-module-quay`
|1.4.10
|1.4.12

|`@janus-idp/backstage-plugin-rbac`
|1.20.11
|1.23.2

|`@janus-idp/backstage-scaffolder-backend-module-regex`
|1.4.10
|1.4.12

|`@janus-idp/backstage-plugin-catalog-backend-module-scaffolder-relation-processor`
|1.0.1
|1.0.3

|`@janus-idp/backstage-scaffolder-backend-module-servicenow`
|1.4.12
|1.4.14

|`@janus-idp/backstage-scaffolder-backend-module-sonarqube`
|1.4.10
|1.4.12

|`@janus-idp/backstage-plugin-tekton`
|3.7.5
|3.7.7

|`@janus-idp/backstage-plugin-topology`
|1.21.7
|1.21.10

|===
