[id='con-relnotes-notable-features_{context}']
= New features

This section highlights new features in {product} {product-version}.

== {product} Operator is now generally available (GA)

You can use the {product} Operator to install {product-short} on your {ocp-short}cluster. For more information, see the link:{LinkAdminGuide}#proc-install-rhdh-ocp-operator_admin-rhdh[Installing {product} using the Operator] section in the _Administration guide_.

== Backstage version update

{product} is now based on the upstream Backstage project v{product-backstage-version}.

== New plugins included in {product} {product-version}

The following additional plugins are included in {product} {product-version}:

* HTTP Request

For a comprehensive list of supported dynamic plugins, see the link:{LinkPluginsGuide}#con-preinstalled-dynamic-plugins[Preinstalled dynamic plugins] section in the _Configuring plugins_ guide.

== {product-short} Theme for Backstage
With this update, theme configurations are enhanced to change the look and feel of different UI components in the {product} application. These UI components include buttons, tabs, sidebars, cards, and tables. This update also includes changes to background color and font used on the {product-short} pages.

== Telemetry [WIP]
This version enables telemetry collection. More information in <RHDH telemetry docs link>. link:{LinkRHIDPIssue}RHIDP-58[(RHIDP-58)]

== Audit logging [WIP]
The following components have currently been vetted for RBAC/Audit logging capabilities: 

* RBAC
* OCM
* Topology
* Keycloak
* Quay Actions

You should consider your security hardening requirements before using plugins that have not been vetted yet. link:{LinkRHIDPIssue}RHIDP-1914[(RHIDP-1914)]

