[id='con-relnotes-fixed-issues_{context}']
= Fixed issues

This section lists fixed issues with {product} {product-version}:

Dynamic Plugins Fail to Load in showcase Post-Upstream Backstage Update to 1.25::
+
--
Moving to Backstage 1.25 caused an issue where dynamic plugin UI elements became unavailable. This occurred due to an upstream security fix that required authentication tokens for all backend endpoints, including static assets used by dynamic plugins.

As a result of this bug, users could not access dynamic plugin UI elements, leading to a degraded user experience and decreased functionality within the application.

In this release, the security requirement for dynamic plugin static assets has been removed, which restores access to dynamic plugin UI elements.

Following the implementation of this fix, users can view and interact with dynamic plugin UI elements, resulting in improved usability and functionality within the application. link:{LinkRHIDPIssue}RHIDP-2044[(RHIDP-2044)]
--

API throwing error upon adding conditions for scaffolder-action resource-type::
+
--
In earlier versions of {product}, defining conditional policies with a policy action of 'use' would result in an error.

This issue led to difficulties in defining conditional policies, hindering the configuration of permissions within the application.

With this fix, you can now define conditional policies in {product-short} with permission policy actions of 'use'. link:{LinkRHIDPIssue}RHIDP-2237[(RHIDP-2237)]
--

Setting a custom route not working when using the {product-short} Operator on OpenShift::
+
--
In earlier versions of the {product} Operator, setting a custom Route host on OpenShift Container Platform by using the `spec.application.route.host` field in the Custom Resource was not possible.

This issue was caused by inconsistent permissions between downstream and upstream CSVs.

This limitation prevented users from configuring custom Route hosts, limiting their ability to customize the deployment environment.

With this release, you can now set a custom Route host on OpenShift Container Platform by using the specified field in the Custom Resource. link:{LinkRHIDPIssue}RHIDP-2325[(RHIDP-2325)]
--

Mounting a secret/configmap with a '.' in its name::
+
--
In earlier versions of the {product} Operator, it was not possible to reference a ConfigMap or Secret object in the Custom Resource if that object contained a dot (`.`) character in its name. 

This issue prevented the {product} instance from starting correctly.

With this update, this issue is fixed. link:{LinkRHIDPIssue}RHIDP-2246[(RHIDP-2246)]
--

Upgrading {product-short} Operator from 1.1 to 1.2 causes an existing instance use a new empty database::
+
--
When upgrading the {product} Operator from version 1.1 to 1.2 with an already-running operator-backed instance of {product-short}, the instance was configured to use a new empty local database pod and volume. 

The existing database data was retained but this misconfiguration caused the existing {product-short} instance to use a new empty local database pod and volume, resulting in data redundancy and potential data inconsistency issues.

This update ensures that an existing {product-short} instance continues to use the existing local database when the Operator is upgraded to a newer version. link:{LinkRHIDPIssue}RHIDP-2434[(RHIDP-2432)]
--

Adding corporate proxy support to {product-short}::
+
--
In earlier versions of the {product}, the support for conventional *HTTP_PROXY*, *HTTPS_PROXY*, and *NO_PROXY* environment variables was not properly implemented. This led to issues when running {product-short} behind a corporate proxy, causing authentication failures and other access-related issues.

The absence of support for these environment variables resulted in the inability to authenticate with public GitHub authentication provider and other access-related issues when {product-short} was deployed behind a corporate proxy.

This update addresses this issue by adding support for the conventional *HTTP_PROXY*, *HTTPS_PROXY*, and *NO_PROXY* environment variables. Setting these variables by using either the Helm Chart or the Operator will change the behavior of {product-short}, ensuring that all backend calls are routed through the corporate proxy specified. link:{LinkRHIDPIssue}RHIDP-1958[(RHIDP-1958)]
--