[id='con-relnotes-known-issues_{context}']
= Known issues

This section lists known issues with {product} {product-version}:

link:https://access.redhat.com/security/cve/CVE-2024-35195[CVE-2024-35195]::
An incorrect control flow implementation vulnerability was found in Requests. If the first request in a session is made with `verify=False`, all subsequent requests to the same host will continue to ignore cert verification. link:xxxx[RHIDP-1343]

link:https://access.redhat.com/security/cve/CVE-2024-27307[CVE-2024-27307]::
A vulnerability was found in JSONata. A malicious expression can exploit the transform operator to override properties on the Object constructor and prototype. This issue can result in denial of service, remote code execution, or other unforeseen behavior in applications that assess user-provided JSONata expressions. link:{LinkRHIDPIssue}RHIDP-1524[RHIDP-1524]

link:https://access.redhat.com/security/cve/CVE-2024-34064[CVE-2024-34064]::
A flaw was found in jinja2. The `xmlattr filter` accepts keys containing non-attribute characters. XML/HTML attributes cannot contain spaces, /, >, or =, as each would then be interpreted as starting a separate attribute. If an application accepts keys (as opposed to only values) as user input, and renders these in pages that other users see as well, an attacker could inject other attributes and perform cross-site scripting (XSS). link:{LinkRHIDPIssue}RHIDP-2315[RHIDP-2315]

link:https://access.redhat.com/security/cve/CVE-2023-45288[CVE-2023-45288]::
A vulnerability was discovered with the implementation of the HTTP/2 protocol in the Go programming language. There were insufficient limitations on the amount of CONTINUATION frames sent within a single stream. An attacker could potentially exploit this to cause a Denial of Service (DoS) attack. link:{LinkRHIDPIssue}RHIDP-2760[RHIDP-2760]

link:https://access.redhat.com/security/cve/CVE-2024-27316[CVE-2024-27316]::
A vulnerability was found in how Apache httpd implements the HTTP/2 protocol. There are insufficient limitations placed on the amount of CONTINUATION frames that can be sent within a single stream. This issue could allow an unauthenticated remote attacker to send packets to vulnerable servers, which could use up memory resources to cause a Denial of Service. link:{LinkRHIDPIssue}RHIDP-2327[RHIDP-2327]

