[id='con-relnotes-known-issues_{context}']
= Known issues

This section lists known issues with {product} {product-version}:

// There are no known issues at this time. 
// Want to report a known issue? Use https://issues.redhat.com/browse/RHIDP or https://issues.redhat.com/browse/RHDHBUGS.

Deprecation warning: The backend.auth.keys config has been replaced by backend.auth.externalAccess"::
+
--
Due to changes to the backend service-to-service authentication, you will see a deprecation warning if you have set up your deployment to use the `backend.auth.keys` field configured in `upstream.backstage.appConfig` This warning is harmless for now and no action is needed. 
//link:{LinkRHIDPIssue}RHIDP-2716[(RHIDP-2716)]
--

IP addresses may appear in application logs::
+
--
If you deploy {product-short} without a proxy, there is the potential for IP addresses to appear in the audit logs. If your organization's security policies restrict you from retaining IP addresses, you can take one or both of the following actions:

* Delete the IP addresses after they are collected.
* Prevent collection of IP addresses by configuring a reverse proxy in front of {product-short}.
//link:{LinkRHIDPIssue}RHIDP-2766[RHIDP-2766]
--

Rollbacks are not supported::
+
--
If you deploy {product-short} using either Helm or the Operator, rollbacks to earlier versions are not supported.
Performing regular backups of your {product-short} PostgreSQL database helps you to restore the application to a recent state in case of issues.
In future versions of {product-short}, we plan to provide guidance on how to perform rollbacks from existing backups.
//link:{LinkRHIDPIssue}RHIDP-2958[(RHIDP-2958)]
--
