[id='con-breaking-changes_{context}']
= Breaking changes

This section lists breaking changes with {product} {product-version}:

== Guest authentication must now be explicitly enabled

In previous versions of Backstage, guest authentication was enabled and available by default until disabled. As of {product} {product-version}, guest authentication needs to be explicitly enabled.
The guest login is provided by a special authentication provider that must be explicitly enabled. This authentication provider should be used for *development purposes only* and is *not intended for production*, as it creates a default user that has user-level access to the Backstage instance. link:{LinkRHIDPIssue}RHIDP-2043[(RHIDP-2043)]

* To enable the guest provider for local development with `yarn start`:
+
```yaml
auth:
  providers:
    guest: {}
```

* To enable the guest provider when running an existing container:
+ 
```yaml
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
```
