[id='con-breaking-changes_{context}']
= Breaking changes

This section lists breaking changes with {product} {product-version}:

== Guest authentication must now be explicitly enabled

In previous versions of Backstage, guest authentication was enabled by default. As of {product} {product-version}, guest authentication is disabled by default and needs to be explicitly enabled for use.

The guest login is provided by a special authentication provider that must be explicitly enabled. This authentication provider should be used for *development purposes only* and is *not intended for production*, as it creates a default user that has user-level access to the Backstage instance. 
//link:{LinkRHIDPIssue}RHIDP-2043[(RHIDP-2043)]

* To enable the guest provider for local development with `yarn start`:
+
```yaml
auth:
  providers:
    guest: {}
```

* To enable the guest provider when running an existing container:
+ 
```yaml
auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
```

== Improved validation permission policies from different sources
In this release, {product-short} provides more strict validation on the source of permission policies and roles based on how you define the first role.

This update improves the validation of the different sources of permission policies and roles and provides more consistent policy definition. If a permission policy or role with a new member does not match the originating role's source, {product-short} prevents any update to permissions. Sources include 'REST, 'CSV', 'Configuration', and 'legacy'.

Before updating your {product} application, you should migrate all permission policies and roles to a single source based on their respective roles. This can be done by using the GET roles endpoint to review the source information and by querying the role-metadata table of the permission database. You can make updates to permission policies by using one of the following: REST API, CSV file, and the database.
