= Single-sourcing release notes

== Single-sourcing general purpose release notes

The general purpose release notes content is single-sourced from link:https://issues.redhat.com/browse/RHIDP[the JIRA project].

.Prerequisites
* In link:https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12364101#SIGwKWmOqDCVBoapBCJiDqhoiKInaroYEg9j2PldSYMUcQVVVdrFHVDUxs1uBtQolXVZgDTdZwjXSCNOA1u11Xeog9Xjb100DUNCh2jwi0TVgzWteeg2FC1TmbT1TUrftGiFHa2CjQtp2TX1DnIGgGCIgEKI+iQfrUlV2AvkJQA[the JIRA project]:
** *Fix Version/s* is set.
** *Release Notes Text* is set using following format: a level 0 title followed by descriptive content, such as:
+ 
.*Release Notes Text* sample
----
= Configurable PVC mounting for containers

Previously, the default Persistent Volume Claim (PVC) could only be mounted to the Backstage container. With this update, you can now configure which container(s) the PVC should be mounted to, providing greater flexibility in storage management. 
----
** *Release Notes Type* is set to `Enhancement`, `Feature`, `Removed Functionality`, `Deprecated Functionality`, `Developer Preview`, `Technology Preview`, `Known Issue`, or `Bug Fix`.
** *Release Notes Status* is set to `Done`.

* On the single-sourcing environment: Bash, Git, Python, and Pip are installed.

.Procedure
. Verify the `product-version` and `product-bundle-version` attributes values in the `artifacts/attributes.adoc` file.

. Open a terminal and change directory to the Git repository root.

. Install required python modules.
+
----
$ pip3 install --requirement requirements.txt
----

. Single-source content from JIRA.
+
----
$ python modules/release-notes/single-source-release-notes.py
----

.Verification
* Verify the changed content:
+
----
$ git diff
----

