:_content-type: REFERENCE
[id="fixed-issues"]
= Fixed issues

This section lists issues fixed in {product} {product-version}.

== Fixed issues in 1.7.0

[id="bug-fix-rhidp-6536"]
=== Improved keyboard accessibility

In this release, various fixes and improvements have been made to improve the keyboard accessibility in {product}.


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-6536[RHIDP-6536]

== Fixed issues in 1.7.1

[id="bug-fix-rhdhbugs-1878"]
=== Fixed incorrect version detection for local plugin updates

Before this update, local plugins within the image were incorrectly detected for updates due to version misidentification. This led to users being unable to update local plugins from wrappers, resulting in outdated functionality. With this release, local plugin updates are now automatically detected, eliminating the need for manual adjustments and ensuring seamless plugin version updates for end users.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-1878[RHDHBUGS-1878]

== Fixed issues in 1.7.0

[id="bug-fix-rhdhbugs-249"]
=== Fixed `techdocs-module-addons-contrib` plugin not displayed as preinstalled plugin

Previously, the `techdocs-module-addons-contrib` plugin was not displayed as preinstalled in Extensions. With this update, the plugin is displayed as preinstalled.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-249[RHDHBUGS-249]


[id="bug-fix-rhdhbugs-322"]
=== Excessive queries to the `relations` database table from the `rbac-backend` plugin

Before this update, excessive queries from the `rbac-backend` plugin to the `relations` database table caused performance issues. As a consequence, users experienced slow performance. With this release, the RBAC backend plugin has been optimized to improve performance by preventing excessive queries to the &#39;relations&#39; database table. 


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-322[RHDHBUGS-322]


[id="bug-fix-rhdhbugs-503"]
=== The Operator reverts the number of replicas set automatically by a Horizontal Pod Autoscaler (HPA)

Previously the {product-very-short} Operator enforced `replicas: 1` from its default deployment config, which overrode scaling decisions. 

With this update, `replicas: 1` is removed from the default deployment profile and the DB-statefulset manifest. 

This update allows HPA to control scaling as expected, so that {product-very-short} instances can now scale dynamically with HPA without being reset by the operator.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-503[RHDHBUGS-503]


[id="bug-fix-rhdhbugs-512"]
=== Improved error messaging for bulk imports

Before this update, when users selected 100 or more repositories simultaneously, the create pull request action could fail with a generic error message. In this release, we provide a more informative error message when creating pull requests for multiple repositories. This bug fix helps users to understand the issue by providing more information about what caused the error.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-512[RHDHBUGS-512]


[id="bug-fix-rhdhbugs-622"]
=== Excessive authorize requests generated by the RBAC backend API

Before this update, excessive authorize requests in the REST API for creating/editing roles, permissions, and conditions in rbac-backend led to performance issues. With this release, the excessive authorization requests in the REST API have been fixed by reducing permissions to only &#39;user&#39; credentials. 


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-622[RHDHBUGS-622]


[id="bug-fix-rhdhbugs-632"]
=== Custom title not persisting on refresh of visited cards

Previously, the custom title set via `app.title` in the _Top Visited_ and _Recently Visited_ cards did not persist after a page refresh, instead it defaulted back to _{product}_.

With this update, after each refresh, the cards correctly display the custom title defined in the `app.title` configuration.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-632[RHDHBUGS-632]


[id="bug-fix-rhdhbugs-834"]
=== Fixed role name updates via API to correctly propagate to permissions, metadata, and conditions

Previously, when a role name was updated using the RBAC API, existing permissions, conditions, and metadata were not updated and remained mapped to the old role name.
With this update, role name changes are now correctly updated.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-834[RHDHBUGS-834]


[id="bug-fix-rhdhbugs-903"]
=== Fixed role actions tooltip delay issue

Previously, tooltips on action icons in the Role list table of the Role-Based Access Control (RBAC) page were slow to appear on hover.

This issue has been fixed, ensuring that tooltips now appear immediately when hovering over action icons in the RBAC page.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-903[RHDHBUGS-903]


[id="bug-fix-rhdhbugs-1110"]
=== The Extensions catalog does not show an error when the backend plugin is not installed

Previously, if the backend Extensions was not installed, {product-very-short} showed the skeleton &#34;forever&#34; instead of an error message.

With this update, the UI shows an empty state with a message to enable the backend plugin.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-1110[RHDHBUGS-1110]


[id="bug-fix-rhdhbugs-1139"]
=== Fixed Profile dropdown showing Guest instead of user&#39;s name with OIDC authentication 

Previously, the *Profile dropdown* in the Global Header showed `Guest` instead of the logged-in user’s display name when logging in using the OIDC authentication.

With this update, the *Profile dropdown* now correctly displays the user&#39;s name by first checking `spec.profile.displayName`, then `metadata.title`, and finally falls back to the name shown on the *Profile card* in the *Settings* page if neither is available.



.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-1139[RHDHBUGS-1139]


[id="bug-fix-rhdhbugs-1162"]
=== Excessive filter arguments generated by the RBAC backend `enforcerDelegate.getFilteredPolicy`

Before this update, {product-very-short} performance was affected by the duplication of filter arguments in `enforcerDelegate.getFilteredPolicy`.  With this release, the duplication of filter arguments in `enforcerDelegate.ts` is avoided.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-1162[RHDHBUGS-1162]


[id="bug-fix-rhdhbugs-1213"]
=== Fixed Jenkins permissions not being displayed in RBAC UI

Previously, Jenkins permissions were not exposed by Jenkins at `/api/jenkins/.well-known/backstage/permissions/metadata` with the change to `JenkinsBuilder`. As a result, RBAC UI did not display the permissions. In this release, users can configure Jenkins permissions by using the RBAC UI.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHBUGS-1213[RHDHBUGS-1213]



