:_content-type: REFERENCE

[id="breaking-changes"]
= Breaking changes

This section lists breaking changes in {product} {product-version}.

[id="removed-functionality-rhidp-5309"]
== Argo CD, Tekton, and Topology plugins require the Kubernetes Frontend and Kubernetes Backend plugins

With this update, the Argo CD, Tekton, and Topology plugins requires the Kubernetes Frontend and Kubernetes Backend plugins. Before this update, these plugins depended only on the Kubernetes Backend plugin, and the feature provided by the Kubernetes Frontend plugin where provided by the removed `@janus-idp/shared-react` package.

.Procedure
. Enable the Kubernetes Frontend and Kubernetes Backend plugins.
+
[source,yaml]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
----

. The Kubernetes Frontend plugin shows automatically a *Kubernetes* tab for Software Catalog entities with the annotation `backstage.io/kubernetes-id` or `backstage.io/kubernetes-namespace`.
+
Optionally, to hide the *Kubernetes* tab in the Software Catalog, disable the feature with this dynamic plugin configuration:
+
[source,yaml]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-kubernetes:
                mountPoints: []
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
----




