:_content-type: REFERENCE

[id="technology-preview"]
= Technology Preview

This section lists Technology Preview features in {product} {product-version}.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

[id="technology-preview-rhidp-7059"]
== Bulk import GitLab projects

With this update, users can bulk import entities from GitLab into {product}, enhancing onboarding efficiency. 

== Additional resources
* {integrating-with-github-book-link}#importing-multiple-repositories-from-gitlab[Importing multiple GitLab repositories]

// Link in comment to facilitate reviews: https://issues.redhat.com/browse/RHIDP-7059


