:_content-type: REFERENCE
[id="new-features"]
= New features

This section highlights new features in {product} {product-version}.

[id="enhancement-rhidp-2200"]
== Added an individual `mountPath`

This update adds an additional individual `mountPath` for extra configmaps or secrets.

[id="feature-rhidp-3621"]
== `PersistentVolumeClaims` support is available

With this update, link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/configuration.md#persistentvolumeclaims[`PersistentVolumeClaims` (PVC)] support is available.

[id="feature-rhidp-3817"]
== Added Configuration Profiles

With this update, there are additional link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/profiles.md[configuration profiles].

[id="enhancement-rhidp-4384"]
== Enhanced use of `kube-rbac-proxy`

This update removes the `kube-rbac-proxy` sidecar container from the RHDH Operator Pod. This sidecar container protected the operator metrics endpoint. However, the main container now provides this functionality out-of-the-box. Removing this sidecar container allows for reducing the resources required to run the Operator.

[id="feature-rhidp-4414"]
== Identifying Backstage flavor for plugins by using the `developerHub.flavor` field

With this update, you can use the `developerHub.flavor` field to identify whether plugins are running on {product-very-short}, RHTAP, or vanilla Backstage, as shown in the following example:

.`app-config.yaml` fragment with the `developerhub.flavor` field

[source,yaml]
----
developerHub:
  flavor: &lt;flavor&gt;
----

`flavor`::
Identify the flavor of Backstage that is running. Default value: `rhdh`


[id="feature-rhidp-4805"]
== Authenticating with Red Hat Build of Keycloak

With this update, you can use Red Hat Build of Keycloak as an authentication provider. The Keycloak plugin will now support ingesting users and groups with Red Hat Build of Keycloak. For more details, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0/html-single/getting_started_guide/index#getting-started-zip-start-red-hat-build-of-keycloak[Authentication with Red Hat Build of Keycloak].





[id="feature-rhidp-5156"]
== `backstage-plugin-catalog-backend-module-logs` is enabled

With this update, the `backstage-plugin-catalog-backend-module-logs` is enabled and converted to a static plugin improving performance and stability. The dynamic plugin was disabled in version `1.3`.

[id="feature-rhidp-5218"]
== RHSSO `7.6` is deprecated as an authentication provider

RHSSO `7.6` is deprecated as an authentication provider. You can continue to use RHSSO until the end of maintenance support. For details, see link:https://access.redhat.com/support/policy/updates/jboss_notes/#p_sso[RHSSO lifecycle dates]. As an alternative, migrate to RHBK `v24`.



