:_content-type: REFERENCE
[id="breaking-changes"]
= Breaking changes

This section lists breaking changes in {product} {product-version}.

[id="breaking-change-rhidp-5958"]
== Change in sign-in resolver configuration location

Previously, configuring the sign-in resolver to bypass user provisioning in the {product-short} software catalog required setting `dangerouslyAllowSignInWithoutUserInCatalog: true` at the root of the `{my-app-config-file}` file.

In this release, the previous root level configuration has been moved to the resolver level. For more details, see link:{authentication-book-url}[{authentication-book-title}].

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5958[RHIDP-5958]

[id="breaking-change-rhidp-5812"]
== The `scopes` parameter is now required for GitLab project deploy token creation

The `scopes` parameter is now mandatory for the `gitlab:projectDeployToken:create` action. A valid value, such as `['read_repository']`, must be provided.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5812[RHIDP-5812]

[id="breaking-change-rhidp-5568"]
== The `dynamicPlugins.cache.volumeClaimSpec` field is removed from the Helm Chart, dynamic plugin storage is now ephemeral by default

The `dynamicPlugins.cache.volumeClaimSpec` field has been removed from `values.yaml`, making dynamic plugin storage ephemeral by default. If you want to enable plugin caching persistence, you must now manually configure a `PersistentVolumeClaim` and mount it using the `extraVolumes` and `extraVolumeMounts` fields in the Helm chart values.

This change also resolves issues with running multi-replica {product-very-short} deployments, as using a PVC for the Dynamic Plugins cache previously led to potential write conflicts.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5568[RHIDP-5568]