:_content-type: REFERENCE
[id="deprecated-functionalities"]
= Deprecated functionalities

This section lists deprecated functionalities in {product} {product-version}.

[id="deprecated-functionality-rhidp-6917"]
== Backstage CR versions `v1alpha1` and `v1alpha2`

Backstage CR versions `v1alpha1` and `v1alpha2` are deprecated in 1.7 and will be removed in 1.9


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-6917[RHIDP-6917]

[id="deprecated-functionality-rhidp-8525"]
== Deprecation of Bundled Plugin Wrappers

To enhance performance, decrease image size, and reduce maintenance, the method of including &#34;wrapped&#34; dynamic plugins within the main {product} container image is being deprecated as of release 1.7.0. We are transitioning to a model where all dynamic plugins will be distributed as independent OCI artifacts.

For the 1.7.0 release, this is a deprecation notice only; there are no breaking changes, and all previously bundled plugins will continue to be bundled. However, we encourage customers to prepare for the removal of wrappers in a future release by beginning to use the new OCI artifacts in 1.8.0. Documentation will be updated to guide this migration.

For more information, see {installing-and-viewing-plugins-book-url}#proc-load-plugin-oci-image_assembly-install-third-party-plugins-rhdh[Loading a plugin packaged as an OCI image].

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8525[RHIDP-8525]
