:_content-type: REFERENCE
[id="technology-preview"]
= Technology Preview

This section lists Technology Preview features in {product} {product-version}.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

[id="technology-preview-rhidp-2757"]
== Extensions for {company-name} and community plugins

The new Extensions feature enables you to browse available {company-name} and community plugins. The initial version displays all plugins and includes filtering options. Future updates will introduce additional features, such as installation directly from the front-end.

For more information about Extensions, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html-single/installing_and_viewing_plugins_in_red_hat_developer_hub/index#rhdh-extensions-plugins_assembly-install-third-party-plugins-rhdh[Extensions in {product}].

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-2757[RHIDP-2757]


[id="technology-preview-rhidp-4676"]
== New dynamic plugin for Kubernetes scaffolder actions

{product-short} introduces the `@backstage-community/plugin-scaffolder-backend-module-kubernetes` plugin as a dynamic plugin, enabling Backstage template actions for Kubernetes. Currently, it includes the `create-namespace` action. The plugin for Kubernetes scaffolder actions is disabled by default.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html-single/configuring_dynamic_plugins/index#con-Kubernetes-custom-actions_title-plugins-rhdh-configure[Kubernetes custom actions in {product}].

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-4676[RHIDP-4676]

