:_content-type: REFERENCE
[id="developer-preview"]
= Developer Preview

This section lists Developer Preview features in {product} {product-version}.

[IMPORTANT]
====
Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.

For more information about the support scope of Red Hat Developer Preview features, see https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

[id="developer-preview-rhdhpai-510"]
== Adoptions Insights in {product}

The Adoption Insights plugin is now available as a Developer Preview feature in {product}, providing key metrics and trends to help you understand {product-short} usage.

Currently, the Adoption Insights plugin cannot be used alongside the built-in `plugin-analytics-provider-segment` plugin. While a fix is in progress, you can enable Adoption Insights by first disabling the `plugin-analytics-provider-segment` plugin. To disable the `plugin-analytics-provider-segment` plugin, add the following configuration to the `dynamic-plugins.yaml` file or your configuration ConfigMap:

.Example configuration in `dynamic-plugins.yaml` file
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
    disabled: true
----

After disabling the `plugin-analytics-provider-segment` plugin, you can configure the Adoption Insights plugin using the link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html-single/adoption_insights_in_red_hat_developer_hub/index[Adoption Insights in {product}] documentation.

.Additional resources
* link:https://issues.redhat.com/browse/RHDHPAI-510[RHDHPAI-510]



