:_content-type: REFERENCE
[id="fixed-issues"]
= Fixed issues

This section lists issues fixed in {product} {product-version}.

== Fixed issues in 1.4

[id="bug-fix-rhidp-2727"]
=== [backstage/community-plugins] Github issues plugin does not allow usage of multiple github hosts

Previously, the GitHub issues plugin defaulted to using the first GitHub integration it detected for all components. This behavior made it incompatible with setups involving multiple GitHub integration hosts.

Now, GitHub issues plugin supports multiple GitHub integration hosts. It uses the well-known entity slug annotation `backstage.io/source-location` or `backstage.io/managed-by-location` to determine the appropriate GitHub integration for a component. If no integration matches the slug, the first GitHub integration is selected, maintaining the previous behavior.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-2727[RHIDP-2727]


[id="bug-fix-rhidp-2903"]
=== [janus-idp/backstage-plugins] 3scale backend plugin - Only first spec gets imported

Previously, some API documentation defined in the 3scale backend plugin was not accessible in {product-very-short}.

With this update, all API documentation defined in the 3scale backend plugin is imported and merged in the {product-very-short}.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-2903[RHIDP-2903]


[id="bug-fix-rhidp-3115"]
=== RHDH helm chart deployment throws NotAllowedError due to origin mismatch

Previously, when deploying with the Helm Chart, there could be a mismatch between the Route hostname and the `baseUrl` fields added to the generated app-config ConfigMap. This could sometimes cause failure to authenticate against some providers due to an origin mismatch.

This update fixes this issue by ensuring no mismatch between those values.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3115[RHIDP-3115]


[id="bug-fix-rhidp-3849"]
=== Prevent the creation of permission policies and roles when disabled

Previously, disabling the RBAC backend plugin created roles and permission policies, whether the permission framework was enabled or not.

With this update, disabling the RBAC backend plugin no longer creates roles and permission policies.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3849[RHIDP-3849]


[id="bug-fix-rhidp-3931"]
=== Entities of repositories under a configured org in catalog-backend-module-github-org plugin are not deleted from the catalog when the imported repository is deleted from bulk imports

Before this update, repositories were added to {product-short} from various sources, such as `app-config` files or GitHub discovery. The Bulk Import plugin only tracked repositories accessible using the configured GitHub integrations. When both plugins were enabled, repositories discovered by GitHub Discovery appeared on Bulk Import pages. However, deleting these repositories from Bulk Import Jobs had no effect, as entities from discovery or `app-config.yaml` file remained in the {product-short} catalog.

With this update, an alert on the deletion icon notifies the user to modify the source (either the `catalog-info` within the repository or the `app-config.yaml` file if the file originates from there) to remove the catalog entity.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3931[RHIDP-3931]


[id="bug-fix-rhidp-4240"]
=== [Topology] RHDH users can see tekton warnings even if they haven&#39;t configured the custom resources in k8s

Before this update, the custom resources in Kubernetes configuration were pre-configured. As a result, users could see Tekton warnings without configuring the custom resources in Kubernetes.

This update removes the pre-configured custom resources from the Kubernetes configuration. Therefore, users can customize resources to the Kubernetes configuration based on their requirements, preventing unrelated warnings from appearing.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-4240[RHIDP-4240]


[id="bug-fix-rhidp-4241"]
=== RBAC Plugin is broken with latest Backstage version (1.31)

Before this update, RBAC backend plugin broke in Backstage 1.31 with an error.

This update resolves compatibility issues with RBAC backend plugin on Backstage versions 1.31 and 1.32 without displaying any errors. 
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-4241[RHIDP-4241]


[id="bug-fix-rhidp-4732"]
=== Bug after RBAC Backend upgrade to 5.1.0

Before this update, the backstage instance failed to start in version 5.1.0, showing an error.

With this update, the RBAC Backend plugin now starts successfully in version 5.1.0 without displaying any errors.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-4732[RHIDP-4732]


[id="bug-fix-rhidp-4734"]
=== When scaling the deployment to 3 pods + redis cache, RBAC roles are not synced

Before this update, scaling the deployment to more than one pod caused RBAC roles to remain unsynced, allowing only the pod that created the resource to serve it.

With this update, RBAC roles are now properly synced across all pods, with Redis cache and traffic routing configured to ensure consistency across the deployment.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-4734[RHIDP-4734]


[id="bug-fix-rhidp-5014"]
=== `export-dynamic-plugin` fails to find dependencies nested deeper than one level in `node_modules`

Previously, the CLI examined the dependencies of embedded packages during the export process to know if other packages should be embedded. One of the methods was calling {{require}} when the CLI encountered a built embedded package, which was the case when wrapping an existing plugin. 

This update changes the parent directory that the {{require}} uses from the monorepo root to the embedded package. Therefore, the dependent package found is the dependency that is most relevant to the embedded package.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5014[RHIDP-5014]


[id="bug-fix-rhidp-5062"]
=== Error migrating techdocs-backend wrapper to export-dynamic-plugin embed-as-dependencies method

Previously, the CLI failed with a message that native modules are not supported.  

This update introduces two new CLI flags that help dynamic plugin developers handle native modules. Both flags accept a list of packages. The `--suppress-native-package` flag does not require the native module at runtime. It replaces the native module with an empty package that displays an error. The `--allow-native-package` flag instructs the CLI to allow the native package during checks, and tests a plugin that uses a native module.



.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5062[RHIDP-5062]


[id="bug-fix-rhidp-5120"]
=== Huge icon when techdoc text is selected, and report a doc issue feature didn&#39;t worked [1.4]

Previously, the feature to report a documentation (TechDoc) issue failed. Therefore, when a user selected a text in a TechDoc, a large icon appeared instead of a tooltip button.

With this update, users can select texts when reporting a documentation (TechDoc) issue.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5120[RHIDP-5120]


[id="bug-fix-rhidp-5136"]
=== cli exits with error &#34;RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded&#34;

Previously, the `export-dynamic-plugin` failed with an error that the `stdout maxBuffer` length was exceeded.

With this update, the CLI redirects the output of the {{yarn install}} command it performs during the export process to a file. Therefore, a successful completion of the {{yarn install}} command and verification of the `export-dynamic-plugin`, cleans up the file. The file is available for troubleshooting when the dynamic plugin validation checks fail.
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5136[RHIDP-5136]


[id="bug-fix-rhidp-5141"]
=== Add a flag to relax version range checks on the main package

Previously, exporting a plugin that has not been updated to a newer backstage version failed due to a semver check performed on dependencies of the dynamic plugin package.

With this update, an `--ignore-version-check` flag accepts a list of package names causing the CLI to selectively ignore the semver check the CLI performs when evaluating the plugin package dependencies. Therefore, a plugin that has not been updated works because it relies on unchanged interfaces and functions. 
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5141[RHIDP-5141]



