:_content-type: REFERENCE
[id="technology-preview"]
= Technology Preview

This section lists Technology Preview features in {product} {product-version}.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

<<<<<<< HEAD:modules/release-notes/ref-release-notes-technology-preview.adoc
[
=======


None.

>>>>>>> 16addb943 (Update release note texts):assemblies/assembly-release-notes-technology-preview.adoc
