:_content-type: REFERENCE
[id="technology-preview"]
= Technology Preview

This section lists Technology Preview features in {product} {product-version}.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

[id="technology-preview-rhidp-5070"]
== [Doc] Version Compatibility Matrix

.Version Compatibility Matrix

The following tables list products and their versions compatible with RHDH 1.4:

[cols=&#34;75%,25%&#34;, frame=&#34;all&#34;, options=&#34;header&#34;]
|===
|Hosting Operating System
|Version

| OpenShift Container Platform
| `4.16-4.17`
|===

[cols=&#34;75%,25%&#34;, frame=&#34;all&#34;, options=&#34;header&#34;]
|===
| Product
| Version

| Backstage
| `1.31.3`

| Amazon Elastic Kubernetes Service (EKS)
| Supported for Kubernetes version `1.24`

| Microsoft Azure Kubernetes Service (AKS)
| Supported for Kubernetes version `1.24`

| Google Kubernetes Engine (GKE)
|  Supported for Kubernetes version `1.24`
|===
.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5070[RHIDP-5070]



