:_content-type: REFERENCE
[id="new-features"]
= New features

This section highlights new features in {product} {product-version}.

[id="enhancement-rhidp-2200"]
== Added an individual `mountPath`

This update adds an additional individual `mountPath` for extra configmaps or secrets.

[id="feature-rhidp-3621"]
== `PersistentVolumeClaims` support is available

With this update, link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/configuration.md#persistentvolumeclaims[`PersistentVolumeClaims` (PVC)] support is available.

[id="feature-rhidp-3817"]
== Added Configuration Profiles

With this update, there are additional link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/profiles.md[configuration profiles].

[id="enhancement-rhidp-4384"]
== Enhanced use of `kube-rbac-proxy`

This update removes the `kube-rbac-proxy` sidecar container from the RHDH Operator Pod. This sidecar container protected the operator metrics endpoint. However, the main container now provides this functionality out-of-the-box. Removing this sidecar container allows for reducing the resources required to run the Operator.

[id="feature-rhidp-4414"]
== Identifying Backstage flavor for plugins by using the `developerHub.flavor` field

With this update, you can use the `developerHub.flavor` field to identify whether plugins are running on {product-very-short}, {rhtap-very-short}, or vanilla Backstage, as shown in the following example:

.`app-config.yaml` fragment with the `developerhub.flavor` field

[source,yaml]
----
developerHub:
  flavor: <flavor>;
----

`flavor`::
Identify the flavor of Backstage that is running. Default value: `rhdh`


[id="feature-rhidp-4419"]
== Ability to manage PVCs in RHDH Operator

You can now mount directories from pre-created PersistentVolumeClaims (PVCs) using the `spec.application.extraFiles.pvcs` field, while configuring RHDH Operator.
For more information, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html-single/administration_guide_for_red_hat_developer_hub/index#proc-rhdh-deployment-config_assembly-admin-templates[Persistent Volume Claim (PVC)].


[id="feature-rhidp-4805"]
== Authenticating with {rhbk-brand-name}

With this update, you can use {rhbk-brand-name} as an authentication provider. The Keycloak plugin will now support ingesting users and groups with {rhbk-brand-name}. For more details, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0/html-single/getting_started_guide/index#getting-started-zip-start-red-hat-build-of-keycloak[Authentication with {rhbk-brand-name}].


[id="feature-rhidp-4806"]
== Ability to install third-party plugins in {product-very-short}

You can now install third-party plugins in {product} without rebuilding the {product-very-short} application.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.3/html-single/introduction_to_plugins/index[Third party plugins].


[id="feature-rhidp-4853"]
== Plugins with updated scope

Some plugins previously under the `@janus-idp` scope have moved to `@backstage/community`:

[cols=2,%header]
|===
| Plugin Name
| Plugin Name

| `@janus-idp/backstage-plugin-acr`
| `@backstage-community/plugin-acr`

| `@janus-idp/backstage-plugin-keycloak-backend`
| `@backstage-community/plugin-catalog-backend-module-keycloak`

| `@janus-idp/backstage-plugin-tekton`
| `@backstage-community/plugin-tekton`

| `@janus-idp/backstage-plugin-nexus-repository-manager`
| `@backstage-community/plugin-nexus-repository-manager`

| `@janus-idp/backstage-plugin-topology`
| `@backstage-community/plugin-topology`

| `@janus-idp/backstage-plugin-jfrog-artifactory`
| `@backstage-community/plugin-jfrog-artifactory`

| `@janus-idp/backstage-plugin-ocm`
| `@backstage-community/plugin-ocm`

| `@janus-idp/backstage-plugin-ocm-backend`
| `@backstage-community/plugin-ocm-backend`

| `@janus-idp/backstage-plugin-rbac`
| `@backstage-community/plugin-rbac`

| `@janus-idp/backstage-plugin-rbac-backend`
| `@backstage-community/plugin-rbac-backend`

| `@janus-idp/backstage-scaffolder-backend-module-regex`
| `@backstage-community/plugin-scaffolder-backend-module-regex`

| `@janus-idp/backstage-plugin-quay`
| `@backstage-community/plugin-quay`

| `@janus-idp/backstage-scaffolder-backend-module-sonarqube`
| `@backstage-community/plugin-scaffolder-backend-module-sonarqube`

| `@janus-idp/backstage-scaffolder-backend-module-servicenow`
| `@backstage-community/plugin-scaffolder-backend-module-servicenow`

| `@janus-idp/backstage-plugin-analytics-provider-segment`
| `@backstage-community/plugin-analytics-provider-segment`

| `@janus-idp/backstage-plugin-scaffolder-backend-module-quay`
| `@backstage-community/plugin-scaffolder-backend-module-quay`
|===

Two plugins previously under the @janus-idp scope have moved to @red-hat-developer-hub:

[cols=2,%header]
|===
| Plugin Name
| {product-very-short}

| `@janus-idp/backstage-plugin-bulk-import`
| `@red-hat-developer-hub/backstage-plugin-bulk-import`

| `@janus-idp/backstage-plugin-bulk-import-backend`
| `@red-hat-developer-hub/backstage-plugin-bulk-import-backend`
|===


[id="feature-rhidp-5156"]
== The catalog backend module logs plugin is enabled

With this update, the `backstage-plugin-catalog-backend-module-logs` is enabled and converted to a static plugin improving performance and stability. The dynamic plugin was disabled in version `1.3`.

[id="feature-rhidp-5218"]
== {rhsso-brand-name} `7.6` is deprecated as an authentication provider

{rhsso-brand-name} ({rhsso}) `7.6` is deprecated as an authentication provider. You can continue to use {rhsso} until the end of maintenance support. For details, see link:https://access.redhat.com/support/policy/updates/jboss_notes/#p_sso[RHSSO lifecycle dates]. As an alternative, migrate to {rhbk-brand-name} `v24`.



