:_content-type: REFERENCE

[id="developer-preview"]
= Developer Preview

This section lists Developer Preview features in {product} {product-version}.

[IMPORTANT]
====
Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.

For more information about the support scope of Red Hat Developer Preview features, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

[id="developer-preview-rhdhpai-1087"]
== Interacting with Model Context Protocol tools for Red Hat Developer Hub

You can enhance your Red Hat Developer Hub integration by leveraging the Model Context Protocol (MCP) server. This integration enables seamless communication with various Artificial Intelligence (AI) clients, facilitating efficient data exchange and expanding the functionality of the platform.



.Additional resources
* link:https://issues.redhat.com/browse/RHDHPAI-1087[RHDHPAI-1087]

[id="developer-preview-rhdhpai-1089"]
== OpenShift AI Connector for Red Hat Developer Hub

You can use OpenShift AI Connector for RHDH to enable users to use Red Hat Developer Hub (RHDH) to surface AI Models and Model Servers from Red Hat OpenShift AI (RHOAI) directly into the RHDH/Backstage Catalog.



.Additional resources
* link:https://issues.redhat.com/browse/RHDHPAI-1089[RHDHPAI-1089]

[id="developer-preview-rhidp-8290"]
== Built-in TechDocs for RHDH Local
With this update, RHDH Local includes essential _Getting Started_ and _How-To_ documentation about RHDH Local which is embedded as TechDocs. In RHDH Local, you can access this built-in documentation directly within the application.

Additional information about configuring {product-very-short} for its supported platforms can be found at https://docs.redhat.com/en/documentation/red_hat_developer_hub/.

[id="developer-preview-rhdhpai-1091"]
== {ls-brand-name} now uses Lightspeed Core (LCORE)

The {ls-short} plugin has completed its migration from the Road-Core Service to Lightspeed Core (LCORE). This architectural change provides enhanced stability and prepares the plugin for future feature development during the Developer Preview.


.Additional resources
* link:https://issues.redhat.com/browse/RHDHPAI-1091[RHDHPAI-1091]

[id="developer-preview-rhidp-8296"]
== Tech Radar and Quay plugins in RHDH Local

With this update, RHDH Local integrates the Tech Radar and Quay plugins, for a better out of the box experience for users. The Tech Radar plugin provides a visually engaging element on the homepage or via navigation, and showcases the dynamic plugins loading mechanism for simple {product-short} extension. The Quay plugin demonstrates integration with external services and provides a practical example of extending the {product-short} software catalog.


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8296[RHIDP-8296]

[id="developer-preview-rhidp-8297"]
== RHDH Local default homepage enhancements

With this update, RHDH Local default homepage integrates a floating action button with quick links for easy access to documentation and information.


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8297[RHIDP-8297]

[id="developer-preview-rhidp-8298"]
== Enhanced customization and collaboration with pre-loaded templates in RHDH Local

With this update, RHDH Local integrates pre-loaded essential templates, enabling  users to create their own custom plugins and add TechDocs or software components to existing projects within {product}. This enhancement demonstrates {product-short} extensibility, empowers users to extend the platform, and enhances the overall user experience by promoting collaboration and customization.


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8298[RHIDP-8298]

[id="developer-preview-rhidp-8709"]
== Configurable Key Performance Indicators (KPIs) by using the Scorecard plugin

With this release, {product} integrates the Scorecard plugin, enabling users to visualize software quality and health metrics directly in {product-short}.

Developers can visualize scorecards with the metrics available to the their role in a tab on component detail pages, allowing them to quickly check the quality of their code and ensure it meets team standards.

Platform engineers can configure Key Performance Indicators (KPIs) from various data sources, with initial support for GitHub open pull requests and Jira open issues. Custom metric providers will allow for the addition of more data sources.

This simplifies the monitoring of applications by offering a single, clear report on health, security, and compliance.

// RN already in https://issues.redhat.com/browse/RHIDP-8709


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8709[RHIDP-8709]

[id="dynamic-plugin-factory"]
== Dynamic Plugin Factory to convert plugins into dynamic plugins
You can automate the conversion and packaging of standard {product-custom-resource-type} plugins into {product-very-short} dynamic plugins by using the {product-very-short} Dynamic Plugin Factory tool.

The core function of the Dynamic Plugin Factory tool is to streamline the dynamic plugin build process, offering the following capabilities:

Source Code Handling:: Manages cloning, checking out, and applying custom patches to the plugin source.
Dependency Management:: Handles yarn installation and TypeScript compilation.
Packaging:: Uses the {product-very-short} CLI to build, export, and package the final dynamic plugin.
Deployment:: Offers an option to push the resulting container image to registries like Quay or OpenShift.

The Dynamic Plugin Factory tool provides a simplified, reproducible method for developers and platform engineers to create and test dynamic plugins using a pre-configured _dynamic plugin factory_ container and documentation, significantly easing migration and testing.

For more information, see link:https://github.com/redhat-developer/rhdh-dynamic-plugin-factory/blob/main/README.md[{product-very-short} Dynamic Plugin Factory].

[id="events-module-support"]
== Events Module available

With this release, you can use the Events Module together with scheduled updates to make sure your GitHub user or catalog entities are updated whenever changes occur in the external system. See {configuring-dynamic-plugins-book-link}#configuring-rhdh-events-module[Configuring Events module]. 

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8196[RHIDP-8196]
