:_content-type: REFERENCE

[id="developer-preview"]
= Developer Preview

This section lists Developer Preview features in {product} {product-version}.

[IMPORTANT]
====
Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.

For more information about the support scope of Red Hat Developer Preview features, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

[id="developer-preview-rhidp-8709"]
== Configurable Key Performance Indicators (KPIs) by using the Scorecard plugin

With this release, {product} integrates the Scorecard plugin, enabling users to visualize software quality and health metrics directly in {product-short}.

Developers can visualize scorecards with the metrics available to the their role in a tab on component detail pages, allowing them to quickly check the quality of their code and ensure it meets team standards.

Platform engineers can configure Key Performance Indicators (KPIs) from various data sources, with initial support for GitHub open pull requests and Jira open issues. Custom metric providers will allow for the addition of more data sources.

This simplifies the monitoring of applications by offering a single, clear report on health, security, and compliance.

// RN already in https://issues.redhat.com/browse/RHIDP-8709


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-8709[RHIDP-8709]



