:_content-type: REFERENCE

[id="deprecated-functionalities"]
= Deprecated functionalities

This section lists deprecated functionalities in {product} {product-version}.

[id="deprecated-functionality-rhidp-6917"]
== Backstage CR versions `v1alpha1` and `v1alpha2`

Backstage CR versions `v1alpha1` and `v1alpha2` were deprecated in 1.7 and will be removed in 1.9.

// Link in comment to facilitate reviews: https://issues.redhat.com/browse/RHIDP-6917

[id="deprecated-functionality-rhidp-8525"]
== Deprecation of Bundled Plugin Wrappers

To enhance performance, decrease image size, and reduce maintenance, the method of including wrapped dynamic plugins within the main {product} container image was deprecated in {product-very-short} 1.7.0.
{product} is transitioning to a model where all dynamic plugins will be distributed as independent OCI artifacts.

This is a deprecation notice only; there are no breaking changes in 1.8.0 related to plugins, wrappers, or support for OCI artifacts. 
All previously bundled plugins will continue to be bundled in this release. {product-very-short} 1.9.0 will deliver the new OCI artifacts, which we encourage customers to begin using in preparation for a future release that will remove the wrappers. Documentation will be updated to guide this migration.

In {product-very-short} 1.9.0, community-supported plugins will no longer be distributed as bundled wrappers in the RHDH container image. These plugins will be built using GitHub Actions and published exclusively to the GitHub Container Registry (link:http://ghcr.io/).



.Additional resources
* {installing-and-viewing-plugins-book-link}#proc-load-plugin-oci-image_assembly-install-third-party-plugins-rhdh[Loading a plugin packaged as an OCI image]

// Link in comment to facilitate reviews: https://issues.redhat.com/browse/RHIDP-8525

[id="deprecated-functionality-rhidp-9180"]
== Deprecation of OCM Plugins

The Open Cluster Management (OCM) plugins integrates your {product} instance with the MultiClusterHub and MultiCluster engines of OCM.
The OCM plugins are deprecated as of RHDH 1.8, and will be removed in a future release. 

// Link in comment to facilitate reviews: https://issues.redhat.com/browse/RHIDP-9180



