:_content-type: REFERENCE
[id="known-issues"]
= Known issues

This section lists known issues in {product} {product-version}.

[id="known-issue-rhidp-5344"]
== Multi-Attached error for Volume (PVC)

Currently, when deploying {product-short} using the Helm Chart, two replicas cannot run on different cluster nodes. This might also affect the upgrade from 1.3 to 1.4.0 if the new pod is scheduled on a different node.

A possible workaround for the upgrade is to manually scale down the number of replicas to 0 before upgrading your Helm release. Or manually remove the old {product-short} pod after upgrading the Helm release. However, this would imply some application downtime. You can also leverage a Pod Affinity rule to force the cluster scheduler to run your {product-short} pods on the same node.


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-5344[RHIDP-5344]

[id="known-issue-rhidp-3396"]
== Topology plugin permission is not displayed in the RBAC front-end UI

Permissions associated only with front-end plugins do not appear in the UI because they require a backend plugin to expose the permission framework&#39;s well-known endpoint. As a workaround, you can apply these permissions by using a CSV file or directly calling the REST API of the RBAC backend plugin. Affected plugins include Topology (`topology.view.read`), Tekton (`tekton.view.read`), ArgoCD (`argocd.view.read`), and Quay (`quay.view.read`).


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3396[RHIDP-3396]

