:_content-type: REFERENCE
[id="new-features"]
= New features

This section highlights new features in {product} {product-version}.

<<<<<<< HEAD
None.
=======
[id="enhancement-rhidp-2200"]
== Added an individual `mountPath`

This update adds an individual `mountPath` for link:{configuring-book-url}#proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator[extra ConfigMaps or Secrets].

[id="feature-rhidp-3621"]
== `PersistentVolumeClaims` support is available

With this update, link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/configuration.md#persistentvolumeclaims[`PersistentVolumeClaims` (PVC)] support is available.

[id="feature-rhidp-3817"]
== Added Configuration Profiles

With this update, there are additional link:https://github.com/redhat-developer/rhdh-operator/blob/main/docs/profiles.md[configuration profiles].

[id="enhancement-rhidp-4384"]
== Enhanced use of `kube-rbac-proxy`

This update removes the `kube-rbac-proxy` sidecar container from the RHDH Operator Pod. This sidecar container protected the operator metrics endpoint. However, the main container now provides this functionality out-of-the-box. Removing this sidecar container allows for reducing the resources required to run the Operator.

[id="feature-rhidp-4414"]
== Identifying Backstage flavor for plugins by using the `developerHub.flavor` field

With this update, you can use the `developerHub.flavor` field to identify whether plugins are running on {product-very-short}, {rhtap-very-short}, or vanilla Backstage, as shown in the following example:

.`app-config.yaml` fragment with the `developerhub.flavor` field

[source,yaml,subs="+quotes"]
----
developerHub:
  flavor: &lt;flavor&gt;;
----

`flavor`::
Identify the flavor of Backstage that is running. Default value: `rhdh`


[id="feature-rhidp-4419"]
== Ability to manage PVCs in RHDH Operator

You can now mount directories from pre-created PersistentVolumeClaims (PVCs) using the `spec.application.extraFiles.pvcs` field, while configuring {product-very-short} Operator.


[id="feature-rhidp-4805"]
== Authenticating with {rhbk-brand-name}

With this update, you can use {rhbk-brand-name} as an authentication provider. The Keycloak plugin will now support ingesting users and groups with {rhbk-brand-name}. For more details, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0/html-single/getting_started_guide/index#getting-started-zip-start-red-hat-build-of-keycloak[Authentication with {rhbk-brand-name}].

[id="feature-rhidp-4806"]
== Ability to install third-party plugins in RHDH

You can now install third-party plugins in {product} without rebuilding the {product-very-short} application.

For more information, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html-single/introduction_to_plugins/index[Third party plugins].

[id="feature-rhidp-5156"]
==  The catalog backend module logs plugin is enabled

With this update, the `backstage-plugin-catalog-backend-module-logs` is enabled and converted to a static plugin improving performance and stability. The dynamic plugin was disabled in version `1.3`.


>>>>>>> 623ce3642 (Incorporated comments)

