= RHEL 9 platform RPM updates

link:https://access.redhat.com/security/cve/CVE-2024-0450[CVE-2024-0450]::
A flaw was found in the Python/CPython 'zipfile' that can allow a zip-bomb type of attack. An attacker may craft a zip file format, leading to a Denial of Service when processed.

link:https://access.redhat.com/security/cve/CVE-2024-2236[CVE-2024-2236]::
A timing-based side-channel flaw was found in libgcrypt's RSA implementation. This issue may allow a remote attacker to initiate a Bleichenbacher-style attack, which can lead to the decryption of RSA ciphertexts.

link:https://access.redhat.com/security/cve/CVE-2024-3596[CVE-2024-3596]::
A vulnerability in the RADIUS (Remote Authentication Dial-In User Service) protocol allows attackers to forge authentication responses when the Message-Authenticator attribute is not enforced. This issue arises from a cryptographically insecure integrity check using MD5, enabling attackers to spoof UDP-based RADIUS response packets. This can result in unauthorized access by modifying an Access-Reject response to an Access-Accept response, thereby compromising the authentication process.

link:https://access.redhat.com/security/cve/CVE-2024-3727[CVE-2024-3727]::
A flaw was found in the github.com/containers/image library. This flaw allows attackers to trigger unexpected authenticated registry accesses on behalf of a victim user, causing resource exhaustion, local path traversal, and other attacks.

link:https://access.redhat.com/security/cve/CVE-2024-6104[CVE-2024-6104]::
A vulnerability was found in go-retryablehttp. The package may suffer from a lack of input sanitization by not cleaning up URL data when writing to the logs. This issue could expose sensitive authentication information.

link:https://access.redhat.com/security/cve/CVE-2024-8088[CVE-2024-8088]::
A flaw was found in Python's zipfile module. When iterating over the entries of a zip archive, the process can enter into an infinite loop state and become unresponsive. This flaw allows an attacker to craft a malicious ZIP archive, leading to a denial of service from the application consuming the zipfile module. Only applications that handle user-controlled zip archives are affected by this vulnerability.

link:https://access.redhat.com/security/cve/CVE-2024-24788[CVE-2024-24788]::
A flaw was found in the net package of the Go stdlib. When a malformed DNS message is received as a response to a query, the Lookup functions within the net package can get stuck in an infinite loop. This issue can lead to resource exhaustion and denial of service (DoS) conditions.

link:https://access.redhat.com/security/cve/CVE-2024-24791[CVE-2024-24791]::
A flaw was found in Go. The net/http module mishandles specific server responses from HTTP/1.1 client requests. This issue may render a connection invalid and cause a denial of service.

link:https://access.redhat.com/security/cve/CVE-2024-30203[CVE-2024-30203]::
A flaw was found in Emacs. When Emacs is used as an email client, inline MIME attachments are considered to be trusted by default, allowing a crafted LaTeX document to exhaust the disk space or the inodes allocated for the partition where the /tmp directory is located. This issue possibly results in a denial of service.

link:https://access.redhat.com/security/cve/CVE-2024-30204[CVE-2024-30204]::
A flaw was found in Emacs. When Emacs is used as an email client, a preview of a crafted LaTeX document attached to an email can exhaust the disk space or the inodes allocated for the partition where the /tmp directory is located. This issue possibly results in a denial of service.

link:https://access.redhat.com/security/cve/CVE-2024-30205[CVE-2024-30205]::
A flaw was found in Emacs. Org mode considers the content of remote files, such as files opened with TRAMP on remote systems, to be trusted, resulting in arbitrary code execution.

link:https://access.redhat.com/security/cve/CVE-2024-42283[CVE-2024-42283]::
In the Linux kernel, the following vulnerability has been resolved:
net: nexthop: Initialize all fields in dumped nexthops

link:https://access.redhat.com/security/cve/CVE-2024-45005[CVE-2024-45005]::
In the Linux kernel, the following vulnerability has been resolved:
KVM: s390: fix validity interception issue when gisa is switched off

link:https://access.redhat.com/security/cve/CVE-2024-46824[CVE-2024-46824]::
In the Linux kernel, the following vulnerability has been resolved:
iommufd: Require drivers to supply the cache_invalidate_user ops

link:https://access.redhat.com/security/cve/CVE-2024-46858[CVE-2024-46858]::
In the Linux kernel, the following vulnerability has been resolved:
mptcp: pm: Fix uaf in __timer_delete_sync

link:https://access.redhat.com/security/cve/CVE-2024-50602[CVE-2024-50602]::
A security issue was found in Expat (libexpat). A crash can be triggered in the XML_ResumeParser function due to XML_StopParser's ability to stop or suspend an unstarted parser, which can lead to a denial of service.
