[id="removed-functionality-rhidp-2796"]
= Breaking changes in Backstage release 1.27

Removed some database helper functions::
The helper functions `createDatabaseClient` and `ensureDatabaseExists` have been removed from the public interface, since they have no usage within the repository and never were suitable for calling from the outside. Switch to using `coreServices.database` or `DatabaseManager` instead.

Deprecated the backend system utilities::
Utilities in the backend system (@backstage/backend-common) are being deprecated with the intent to remove the package entirely in a future release

Removed the requirement to configure a secret for backend authentication::
The requirement to configure a secret for backend authentication in production has been removed. It is now only needed if you rely on the legacy authentication mechanism (https://backstage.io/docs/auth/service-to-service-auth#external-callers-legacy). If you do not configure any secrets you will also not be able to generate tokens with the TokenManager service, although use of this service is discouraged as the AuthService has replaced it.

Added a user authentication extension point::
The authentication backend plugin now provides an authOwnershipResolutionExtensionPoint that lets you override the default ownership resolution used by sign-in resolvers. This allows you to customize this logic for all sign-in resolvers without replacing them.

.Additional resources

* link:https://github.com/backstage/backstage/releases/tag/v1.27.0[Backstage 1.27 release notes]
* link:https://github.com/backstage/backstage/blob/237d7e832541fb990bdee0bd5af1840c3b790e1b/docs/releases/v1.27.0-changelog.md[Backstage 1.27 changelog]


.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-2796[RHIDP-2796]
