[id="bug-fix-rhidp-3580"]
= Creating RBAC role with name that contains ':' or '/' creates a role that does nothing and cannot be deleted

Before this update, creating an RBAC role with name that contains ':' or '/' through the REST API (or RBAC admin panel in the UI) created a role that did nothing and could not be deleted.
Although the name of the role showed up in full as written in the POST request, when clicked on for more information about the role it showed only the part of the name written before the first ':' or '/'.
Also while the list of RBAC roles did list how many policies were added to the role, when clicking on the role for more information it displayed no users or policies.


With this udpate, {product-short} validates more strictly role and namespace names in accordance with backstage validation:

{product-short} invalidates role names that do not conform with the format:

- Strings of length at least 1, and at most 63.
- Must consist of sequences of `[a-z0-9A-Z]` possibly separated by one of `[-_.]`.

{product-short} invalidates namespaces that do not conform with the format:

- Strings of length at least 1, and at most 63.
- Must be sequences of `[a-zA-Z0-9]`, possibly separated by `-`.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3580[RHIDP-3580]
