= RHEL 9 platform RPM updates

link:https://access.redhat.com/security/cve/CVE-2024-6119[CVE-2024-6119]::
A flaw was found in OpenSSL. Applications performing certificate name checks (e.g., TLS clients checking server certificates) may attempt to read an invalid memory address resulting in abnormal termination of the application process.

link:https://access.redhat.com/security/cve/CVE-2024-6923[CVE-2024-6923]::
A vulnerability was found in the email module that uses Python language. The email module doesn't properly quote new lines in email headers. This flaw allows an attacker to inject email headers that could, among other possibilities, add hidden email destinations or inject content into the email, impacting data confidentiality and integrity.

link:https://access.redhat.com/security/cve/CVE-2024-37370[CVE-2024-37370]::
A vulnerability was found in the MIT Kerberos 5 GSS krb5 wrap token, where an attacker can modify the plaintext Extra Count field, causing the unwrapped token to appear truncated to the application, occurs when the attacker alters the token data during transmission which can lead to improper handling of authentication tokens.

link:https://access.redhat.com/security/cve/CVE-2024-37371[CVE-2024-37371]::
A vulnerability was found in Kerberos. This flaw is due to an issue with message token handling.

link:https://access.redhat.com/security/cve/CVE-2024-39331[CVE-2024-39331]::
A flaw was found in Emacs. Arbitrary shell commands can be executed without prompting when an Org mode file is opened or when the Org mode is enabled, when Emacs is used as an email client, this issue can be triggered when previewing email attachments.

link:https://access.redhat.com/security/cve/CVE-2024-45490[CVE-2024-45490]::
A flaw was found in libexpat's xmlparse.c component. This vulnerability allows an attacker to cause improper handling of XML data by providing a negative length value to the XML_ParseBuffer function.

link:https://access.redhat.com/security/cve/CVE-2024-45491[CVE-2024-45491]::
An issue was found in libexpat’s internal dtdCopy function in xmlparse.c, It can have an integer overflow for nDefaultAtts on 32-bit platforms where UINT_MAX equals SIZE_MAX.

link:https://access.redhat.com/security/cve/CVE-2024-45492[CVE-2024-45492]::
A flaw was found in libexpat's internal nextScaffoldPart function in xmlparse.c. It can have an integer overflow for m_groupSize on 32-bit platforms where UINT_MAX equals SIZE_MAX.
