[id="bug-fix-rhidp-3931"]
= Added alert on the deletion icon during bulk imports

Before this update, repositories would be added to Developer Hub from various sources (like statically in an app-config file or dynamically when enabling GitHub discovery). By design, the bulk import plugin would only track repositories that are accessible from the configured GitHub integrations. When both the Bulk Import and the GitHub Discovery plugins were enabled, the repositories the latter discovers would be listed in the Bulk Import pages. However, attempting to delete a repository added by the discovery plugin from the Bulk Import Jobs would have no effect, as any entities registered by the discovery plugin or app-config would still be present in the Developer Hub catalog.

With this update, an alert on the deletion icon notifies the user to modify the source (either the catalog-info within the repository or the app-config if the file originates from there) to remove the catalog entity.

.Additional resources
* link:https://issues.redhat.com/browse/RHIDP-3931[RHIDP-3931]
