= {product} dependency updates

link:https://access.redhat.com/security/cve/CVE-2024-21536[CVE-2024-21536]::
A flaw was found in the http-proxy-middleware package. Affected versions of this package are vulnerable to denial of service (DoS) due to an UnhandledPromiseRejection error thrown by micromatch. This flaw allows an attacker to kill the Node.js process and crash the server by requesting certain paths.

link:https://access.redhat.com/security/cve/CVE-2024-21538[CVE-2024-21538]::
A Regular Expression Denial of Service (ReDoS) vulnerability was found in the cross-spawn package for Node.js. Due to improper input sanitization, an attacker can increase CPU usage and crash the program with a large, specially crafted string.

link:https://access.redhat.com/security/cve/CVE-2024-45296[CVE-2024-45296]::
A flaw was found in path-to-regexp package, where it turns path strings into regular expressions. In certain cases, path-to-regexp will output a regular expression that can be exploited to cause poor performance. Because JavaScript is single-threaded and regex matching runs on the main thread, poor performance will block the event loop and lead to a denial of service (DoS).

link:https://access.redhat.com/security/cve/CVE-2024-45590[CVE-2024-45590]::
A flaw was found in body-parser. This vulnerability causes denial of service via a specially crafted payload when the URL encoding is enabled.

link:https://access.redhat.com/security/cve/CVE-2024-45815[CVE-2024-45815]::
A flaw was found in the backstage/plugin-catalog-backend package. A malicious actor with authenticated access to a Backstage instance with the catalog backend plugin installed is able to interrupt the service using a specially crafted query to the catalog API.

link:https://access.redhat.com/security/cve/CVE-2024-45816[CVE-2024-45816]::
A directory traversal vulnerability was found in the backstage/plugin-techdocs-backend package. When using the AWS S3 or GCS storage provider for TechDocs, it is possible to access content in the entire storage bucket. This can leak contents of the bucket that are not intended to be accessible, as well as bypass permission checks in Backstage.

link:https://access.redhat.com/security/cve/CVE-2024-46976[CVE-2024-46976]::
A flaw was found in the backstage/plugin-techdocs-backend package. An attacker with control of the contents of the TechDocs storage buckets may be able to inject executable scripts in the TechDocs content that will be executed in the victim's browser when browsing documentation or navigating to an attacker provided link.

link:https://access.redhat.com/security/cve/CVE-2024-47762[CVE-2024-47762]::
A flaw was found in the backstage/plugin-app-backend package. Configurations supplied through APP_CONFIG_* environment variables unexpectedly ignore the visibility defined in the configuration schema, potentially exposing sensitive configuration details intended to remain private or restricted to backend processes.
