[id="bug-fix-rhidp-3471"]
= Theme issues with plugins using material 5

Before this update, {product-short} had theme issues with plugins using Material UI (MUI) 5.

With this update, {product-short} includes additional MUI 5 related packages, added to the application shell as shared modules.
Therefore, dynamic plugins that use MUI 5 components and tss-react can properly load the currently selected theme.
This ensures that MUI 5 components have the correct colors and styling applied to them.

While not strictly a requirement, if a dynamic plugin relies on MUI 5 components with a class name prefix, that behavior can be added to a frontend dynamic plugin by adding the following code to the plugin's index.ts:

----
import { unstable_ClassNameGenerator as ClassNameGenerator } from '@mui/material/className';

ClassNameGenerator.configure(componentName => {
  return componentName.startsWith('v5-')
    ? componentName
    : `v5-${componentName}`;
})
----

This update requires using a version of the @janus-idp/cli package > 1.13.1.

// .Additional resources
// * link:https://issues.redhat.com/browse/RHIDP-3471[RHIDP-3471]
