= RHEL 9 platform RPM updates

link:https://access.redhat.com/security/cve/CVE-2021-47385[CVE-2021-47385]::
In the Linux kernel, the following vulnerability has been resolved:
hwmon: (w83792d) Fix NULL pointer dereference by removing unnecessary structure field

link:https://access.redhat.com/security/cve/CVE-2023-28746[CVE-2023-28746]::
A vulnerability was found in some Intel Atom Processor's microcode. This issue may allow a malicious actor to achieve a local information disclosure, impacting the data confidentiality of the targeted system.

link:https://access.redhat.com/security/cve/CVE-2023-52658[CVE-2023-52658]::
CVE-2023-52658 is a vulnerability in the Linux kernel's Mellanox MLX5 driver, specifically related to the switchdev mode. A previous commit intended to block entering switchdev mode due to namespace inconsistencies inadvertently caused system crashes. To address this, the problematic commit was reverted, restoring stability. Users should update their Linux kernel to a version that includes this reversion to ensure reliable operation.

link:https://access.redhat.com/security/cve/CVE-2024-6232[CVE-2024-6232]::
A regular expression denial of service (ReDos) vulnerability was found in Python's tarfile module. Due to excessive backtracking while tarfile parses headers, an attacker may be able to trigger a denial of service via a specially crafted tar archive.

link:https://access.redhat.com/security/cve/CVE-2024-9355[CVE-2024-9355]::
A vulnerability was found in Golang FIPS OpenSSL. This flaw allows a malicious user to randomly cause an uninitialized buffer length variable with a zeroed buffer to be returned in FIPS mode. It may also be possible to force a false positive match between non-equal hashes when comparing a trusted computed hmac sum to an untrusted input sum if an attacker can send a zeroed buffer in place of a pre-computed sum.  It is also possible to force a derived key to be all zeros instead of an unpredictable value.  This may have follow-on implications for the Go TLS stack.

link:https://access.redhat.com/security/cve/CVE-2024-27403[CVE-2024-27403]::
In the Linux kernel, the following vulnerability has been resolved:
netfilter: nft_flow_offload: reset dst in route object after setting up flow

link:https://access.redhat.com/security/cve/CVE-2024-34156[CVE-2024-34156]::
A flaw was found in the encoding/gob package of the Golang standard library. Calling Decoder.Decoding, a message that contains deeply nested structures, can cause a panic due to stack exhaustion. This is a follow-up to CVE-2022-30635.

link:https://access.redhat.com/security/cve/CVE-2024-35989[CVE-2024-35989]::
This is a vulnerability in the Linux kernel's Data Movement Accelerator (DMA) engine, specifically affecting the Intel Data Streaming Accelerator (IDXD) driver. The issue arises during the removal (rmmod) of the idxd driver on systems with only one active CPU. In such scenarios, the driver's cleanup process attempts to migrate performance monitoring unit (PMU) contexts to another CPU. However, with no other CPUs available, this leads to a kernel oops—a serious error causing the system to crash.

link:https://access.redhat.com/security/cve/CVE-2024-36889[CVE-2024-36889]::
In the Linux kernel, the following vulnerability has been resolved:
mptcp: ensure snd_nxt is properly initialized on connect

link:https://access.redhat.com/security/cve/CVE-2024-36978[CVE-2024-36978]::
An out-of-bounds write flaw was found in the Linux kernel's multiq qdisc functionality. This vulnerability allows a local user to crash or potentially escalate their privileges on the system.

link:https://access.redhat.com/security/cve/CVE-2024-38556[CVE-2024-38556]::
In the Linux kernel, the following vulnerability has been resolved:
net/mlx5: Add a timeout to acquire the command queue semaphore

link:https://access.redhat.com/security/cve/CVE-2024-39483[CVE-2024-39483]::
In the Linux kernel, the following vulnerability has been resolved:
KVM: SVM: WARN on vNMI + NMI window iff NMIs are outright masked

link:https://access.redhat.com/security/cve/CVE-2024-39502[CVE-2024-39502]::
In the Linux kernel, the following vulnerability has been resolved:
ionic: fix use after netif_napi_del()

link:https://access.redhat.com/security/cve/CVE-2024-40959[CVE-2024-40959]::
In the Linux kernel, the following vulnerability has been resolved:
xfrm6: check ip6_dst_idev() return value in xfrm6_get_saddr()

link:https://access.redhat.com/security/cve/CVE-2024-42079[CVE-2024-42079]::
In the Linux kernel, the following vulnerability has been resolved:
gfs2: Fix NULL pointer dereference in gfs2_log_flush

link:https://access.redhat.com/security/cve/CVE-2024-42272[CVE-2024-42272]::
In the Linux kernel, the following vulnerability has been resolved:
sched: act_ct: take care of padding in struct zones_ht_key

link:https://access.redhat.com/security/cve/CVE-2024-42284[CVE-2024-42284]::
A flaw was found in Linux kernel tipc. tipc_udp_addr2str() does not return a nonzero value when UDP media address is invalid, which can result in a buffer overflow in tipc_media_addr_printf().
