:_mod-docs-content-type: PROCEDURE

= Create destination databases on the external server to receive the migrated RHDH plugin data

[role="_abstract"]
Create destination databases on the external PostgreSQL server and populate them with the data extracted from the local instance.

.Prerequisites

* You have configured port forwarding for the local PostgreSQL database pod.
* You have created and configured the `db_copy.sh` script.
* You have PostgreSQL admin privileges to create databases on the external server.

.Procedure

. Run the database copy script to create the destination databases and transfer the data:
+
[source,terminal]
----
$ /bin/bash TO_PSW=<destination_db_password> /path/to/db_copy.sh
----
+
Replace `<destination_db_password>` with the password to connect to the destination database.

. When the data copy is complete, stop port forwarding.

[NOTE]
====
For more information about handling large databases and using compression tools, see the link:https://www.postgresql.org/docs/current/backup-dump.html#BACKUP-DUMP-LARGE[Handling Large Databases] section on the PostgreSQL website.
====
