:_mod-docs-content-type: REFERENCE

[id="ref-enrich-ai-model-metadata_{context}"]
= Enrich AI model metadata for enhanced {product} experience

While {rhoai-short} provides essential data, an AI platform engineer using {rhoai-short} can enrich the {backstage}/{product-very-short} experience by adding custom properties to the `ModelVersion` or `RegisteredModel` (or annotations to the `KServe InferenceService` if the model registry is not used) so that the {openshift-ai-connector-name} can add the information to the {product-very-short} entities it creates. For more details, see https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.25/html/working_with_model_registries/working-with-model-registries_model-registry#editing-model-version-metadata-in-a-model-registry_model-registry[Editing model version metadata in a model registry].

|===
|Property Key |Entity Field Populated |Description

|`API Spec`
|API Definition Tab
|The OpenAPI / Swagger JSON specification for the model REST API.

|`API Type`
|API Type
|Correlates to supported {product-very-short}/{backstage} API types (defaults to `openapi`).

|`TechDocs`
|TechDocs
|URL pointing to a Git repository that follows {product-very-short} TechDocs conventions for the Model Card. Use this setting only if the *Model Card to TechDocs* mapping is not active.

|`Homepage URL`
|Links
|A URL considered the home page for the model.

|`Owner`
|Owner
|Overrides the default OpenShift user as the entity owner.

|`Lifecycle`
|Lifecycle
|Serves a means to express the lifecycle notion of {product-very-short}/{backstage}.

|`How to use`
|Links
|A URL that points to usage documentation.

|`License`
|Links
|A URL to the license file of the model.
|===