:_mod-docs-content-type: CONCEPT

[id="providing-custom-scaffolder-field-extensions_{context}"]
= Providing custom Scaffolder field extensions

[role="_abstract"]
With the Scaffolder component in {product} ({product-very-short}), you can create software components by using templates through a guided wizard. You can extend the functionality of the Scaffolder by adding custom form fields as dynamic plugins by using the `scaffolderFieldExtensions` configuration.

With custom field extensions, you can add specialized form fields that capture domain-specific data during the scaffolding process, such as environment selectors, input validations, or repository checks.

When you configure custom Scaffolder field extensions:

* The dynamic plugin exposes the field extension component using `createScaffolderFieldExtension`.
* Each field extension requires a unique `importName` for registration.
* You register many field extensions by listing each in the configuration.

[source,yaml]
----
dynamicPlugins:
  frontend:
    my-plugin: # The plugin package name
      scaffolderFieldExtensions:
        - importName: MyNewFieldExtension # References the exported Scaffolder field extension component from your plugin
----

[NOTE]
====
The `module` field is optional and specifies which set of assets to access within the plugin. By default, the system uses the `PluginRoot` module, consistent with the `scalprum.exposedModules` key in the `package.json` file of your package.
====
