:_mod-docs-content-type: CONCEPT

[id="installing-dynamic-plugins-using-the-helm-chart_{context}"]
= Installing dynamic plugins using the Helm chart

[role="_abstract"]
You can deploy a {product-short} instance by using a Helm chart, which is a flexible installation method. With the Helm chart, you can load dynamic plugins into your {product-short} instance without having to recompile your code or rebuild the container.

To install dynamic plugins in {product-short} using Helm, add the following `global.dynamic` parameters in your Helm chart:

* `plugins`: the dynamic plugins list intended for installation. By default, the list is empty. You can populate the plugins list with the following fields:
** `package`: a package specification for the dynamic plugin package that you want to install. You can use a package for either a local or an external dynamic plugin installation. For a local installation, use a path to the local folder containing the dynamic plugin. For an external installation, use a package specification from a public NPM repository.
** `integrity` (required for external packages): an integrity checksum in the form of `<alg>-<digest>` specific to the package. Supported algorithms include `sha256`, `sha384` and `sha512`.
** `pluginConfig`: an optional plugin-specific `{my-app-config-file}` YAML fragment. See plugin configuration for more information.
** `disabled`: disables the dynamic plugin if set to `true`. Default: `false`.
** `forceDownload`: Set the value to `true` to force a reinstall of the plugin, bypassing the cache. The default value is `false`.

** `pullPolicy`: Similar to the `forceDownload` parameter and is consistent with other image container platforms. You can use one of the following values for this key:

*** `Always`: This value compares the image digest in the remote registry and downloads the artifact if it has changed, even if you downloaded the plugin before.
*** `IfNotPresent`: This value downloads the artifact if it is not already present in the dynamic-plugins-root folder, without checking image digests.
+
[NOTE]
The `pullPolicy` setting is also applied to the NPM downloading method, although `Always` will download the remote artifact without a digest check. The existing `forceDownload` option remains functional, however, the `pullPolicy` option takes precedence. The `forceDownload` option might be deprecated in a future {product-short} release.

* `includes`: a list of YAML files using the same syntax.

[NOTE]
====
The system merges the `plugins` list in the `includes` file with the `plugins` list in the main Helm values. If both `plugins` lists mention a plugin package, the `plugins` fields in the main Helm values override the `plugins` fields in the `includes` file. The default configuration has the `dynamic-plugins.default.yaml` file, which has all of the dynamic plugins preinstalled in {product-short}, whether enabled or disabled by default.
====
