:_mod-docs-content-type: PROCEDURE

[id="configure-a-default-scorecard-aggregation-card_{context}"]
= Configure a default scorecard aggregation card

[role="_abstract"]
Add a standard scorecard summary card to your homepage using default, out-of-the-box configurations.

.Prerequisites

* The scorecard plugin is installed and configured in your {product} instance.

* You have administrator permissions to update application configuration files.

.Procedure
. Open your dynamic plugin configuration file.

. Navigate to your scorecard card block under the `home.page/cards` mount point.

. Update the configuration to use the `aggregationId` property with an established system metric name:
+
[source,yaml]
----
- mountPoint: home.page/cards
  importName: ScorecardHomepageCard
  config:
    props:
      aggregationId: "github.open_prs"
    layouts:
      xl: { w: 3, h: 6, x: 3 }
      lg: { w: 4, h: 6, x: 4 }
      md: { w: 6, h: 6, x: 6 }
      sm: { w: 12, h: 6 }
      xs: { w: 12, h: 6 }
      xxs: { w: 12, h: 6 }
----

. Save the modified configuration file and restart your {product} instance.

.Verification
* Access your {roduct-short} homepage interface.

* Verify that the standard scorecard summary card displays with default metrics.