:_mod-docs-content-type: PROCEDURE

[id="exclude-or-include-scorecard-metrics-globally_{context}"]
= Exclude or include scorecard metrics globally

[role="_abstract"]
You can exclude or include specific scorecard metrics across all catalog entities by adding configuration to your {product-very-short} application configuration file. This applies to metrics from any provider, including GitHub, Jira, and OpenSSF.

.Prerequisites

* You have {install-category-link}[installed your {product-very-short} instance].
* You have {scorecard-plugin-book-link}#set-up-scorecards-to-monitor-your-project-health_{context}[set up the Scorecard plugin].
* You have {configuring-book-link}[added a custom {product-short} application configuration].

.Procedure

* Add the following configuration to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml,subs="+quotes,+attributes"]
----
scorecard:
  excludeMetrics:
    - openssf.code_review
  includeMetrics:
    - openssf.packaging
----
+
where:

`excludeMetrics`:: Enter a list of metric IDs to exclude globally. For available values, see xref:available-scorecard-metric-ids_{context}[Available scorecard metric IDs].
`includeMetrics`:: Enter a list of metric IDs to include. When set, only listed metrics are displayed.

.Additional resources

* {scorecard-plugin-book-link}#ref-supported-scorecard-metrics-providers_{context}[Supported scorecard metrics providers]
