:_mod-docs-content-type: PROCEDURE

[id="exclude-specific-scorecard-metrics-per-entity_{context}"]
= Disable specific scorecard metrics per entity

[role="_abstract"]
You can disable specific scorecard metrics for an individual catalog entity by adding an annotation to its `catalog-info.yaml` file. This applies to metrics from any provider, including GitHub, Jira, and OpenSSF. Disabled metrics are not calculated.

.Prerequisites

* You have {install-category-link}[installed your {product-very-short} instance].
* You have {scorecard-plugin-book-link}#set-up-scorecards-to-monitor-your-project-health_{context}[set up the Scorecard plugin].

.Procedure

* Add the `scorecard.io/disabled-metrics` annotation to the `catalog-info.yaml` file for your {product-very-short} entity:
+
[source,yaml]
----
metadata:
  annotations:
    scorecard.io/disabled-metrics: openssf.maintained,filecheck.readme,filecheck.license
----
+
where:

`scorecard.io/disabled-metrics`:: Enter a comma-separated list of metric IDs to disable for this entity. You can use IDs from any provider. For available values, see xref:available-scorecard-metric-ids_{context}[Available scorecard metric IDs].

.Additional resources

* {scorecard-plugin-book-link}#ref-supported-scorecard-metrics-providers_{context}[Supported scorecard metrics providers]
