[id="quicklinks-and-starred-items-in-global-header_{context}"]
= Enable *Quicklinks* and *Starred Items* by default in the global header

The *Quicklinks* matrix and *Starred Items* drop-down are enabled by default and are visible without any additional configuration when you deploy a new {product} instance.

The *Quicklinks* matrix, organized by sections (for example, Documentation or Developer Tools), allows users to quickly access internal or external resources. The *Starred Items* drop-down contains entities and pages that the user has starred.

The default configuration includes the following components:

*StarredDropdown*: Ensures that the `Starred Items` menu appears by default, as shown in the following configuration:

[source,yaml]
----
# Group: Global Header
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  - mountPoint: global.header/component
    importName: StarredDropdown
    config:
      priority: 85
----

*ApplicationLauncherDropdown*: Provides the `Quicklinks` matrix (application launcher), as shown in the following configuration:

[source,yaml]
----
# Group: Global Header
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  - mountPoint: global.header/component
    importName: ApplicationLauncherDropdown
    config:
      priority: 82
----

*MenuItemLink entries*: Define a section, title, icon, and link. The default configuration includes links to the {product-short} documentation and an {product-very-short} Local instance, as shown in the following configurations:

[source,yaml]
----
- mountPoint: global.header/application-launcher
  importName: MenuItemLink
  config:
    section: Documentation
    priority: 150
    props:
      title: Developer Hub
      icon: developerHub
      link: https://docs.redhat.com/en/documentation/red_hat_developer_hub

- mountPoint: global.header/application-launcher
  importName: MenuItemLink
  config:
    section: Developer Tools
    priority: 100
    props:
      title: RHDH Local
      icon: developerHub
      link: https://github.com/redhat-developer/rhdh-local
----

[NOTE]
====
When upgrading from previous versions, the installer does not overwrite your existing `dynamic-plugins.yaml` configuration. If you had not configured *Starred Items* or *Quicklinks* previously, they remain disabled after the upgrade.
====




