[id="quicklinks-and-starred-items-in-global-header_{context}"]
= Quicklinks and Starred Items in the global header

The *Quicklinks* matrix and *Starred Items* drop-down list are enabled by default and appear in the global header without requiring additional configuration.

The *Quicklinks* matrix, organized by sections (for example, Documentation or Developer Tools), allows users to quickly access internal or external resources. The *Starred Items* drop-down list contains entities and pages that the user has starred.

The default configuration includes the following components:

*StarredDropdown*: Displays the *Starred Items* menu in the global header by default, as shown in the following configuration:

[source,yaml]
----
# Group: Global Header
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  - mountPoint: global.header/component
    importName: StarredDropdown
    config:
      priority: 85
----

*ApplicationLauncherDropdown*: Provides the *Quicklinks* matrix (application launcher) by default, as shown in the following configuration:

[source,yaml]
----
# Group: Global Header
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  - mountPoint: global.header/component
    importName: ApplicationLauncherDropdown
    config:
      priority: 82
----

*MenuItemLink entries*: Define sections, titles, icons, and links within the *Quicklinks* matrix. The default configuration includes links to the {product-short} documentation and an {product-very-short} Local, as shown in the following configurations:

[source,yaml,subs="+attributes"]
----
- mountPoint: global.header/application-launcher
  importName: MenuItemLink
  config:
    section: Documentation
    priority: 150
    props:
      title: {product-short}
      icon: developerHub
      link: https://docs.redhat.com/en/documentation/red_hat_developer_hub

- mountPoint: global.header/application-launcher
  importName: MenuItemLink
  config:
    section: Developer Tools
    priority: 100
    props:
      title: RHDH Local
      icon: developerHub
      link: https://github.com/redhat-developer/rhdh-local
----

[NOTE]
====
When upgrading from previous versions, the installer does not overwrite your existing `dynamic-plugins.yaml` configuration. If you had not configured *Starred Items* or *Quicklinks* previously, they remain disabled after the upgrade and must be manually enabled.
====




