[id="displaying-preferred-username-in-global-header-profile-drop-down_{context}"]
= Displaying the preferred username in the profile dropdown

You can display the preferred username in the global header profile drop-down list by configuring `spec.profile.displayName` in the user entity. When not configured, the application falls back to a `metadata.title`. If neither is configured, it defaults to a user-friendly name generated by the `useProfileInfo` hook.

.Procedure

* When you configure `spec.profile.displayName`, use the following code:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  # Required unique username
  name: _<my_display_name>_
  # Optional preferred title
  title: _<display_name_title>_
spec:
  profile:
    # Optional preferred display name (highest priority)
    displayName: _<my_display_name>_
  memberOf: [janus-authors]
----

* When you do not configure `spec.profile.displayname` but configure `metadata.title`, use the following code:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  # Required unique username
  name: _<my_display_name>_
  # Optional preferred title
  title: _<display_name_title>_
spec:
  memberOf: [janus-authors]
----

* When you do not configure the `spec.profile.displayname` and the `metadata.title`, use the following code:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  # Required unique username
  name: _<my_display_name>_
spec:
  memberOf: [janus-authors]
----

[NOTE]
====
The application falls back to `metadata.name` when you do not register the user entity.
====