[id="configuring-theme-specific-company-logos-for-global-header.adoc_{context}"]
= Configuring theme-specific company logos for global header and sidebar

You can configure theme-specific company logos in {product} ({product-very-short}) to align with the company's branding and improve visibility across light and dark themes.

The {product-short} theme update changed the *Sidebar* and *Global Header* to use white backgrounds in the light theme.
Previously, both used black backgrounds in light and dark modes. This change needs theme-aware logos to ensure strong contrast and consistent branding.

.Prerequisites
You have the required permissions to modify {product} configuration.

.Procedure

.Updating *Global Header* logo
* Use the `red-hat-developer-hub.backstage-plugin-global-header` configuration block:

[source,yaml]
----
red-hat-developer-hub.backstage-plugin-global-header:
  mountPoints:
    - mountPoint: global.header/component
      importName: CompanyLogo
      config:
        priority: 200
        props:
          to: '/'
          logo: <string> or <object> # Use a single image string for both themes or an object with theme-specific logos
            dark: <base64_dark_logo> # Used in dark theme
            light: <base64_light_logo> # Used in light theme
----

.Updating *Sidebar* logo

* Configure the sidebar logos in the `app.branding` section:

[source,yaml]
----
app:
  sidebar:
    search: true
    settings: true
    logo: true
  branding:
    fullLogo: <string > or <object>
      dark: <base64_dark_logo>
      light: <base64_light_logo>
----

By default, if you do not provide `fullLogoLightTheme` or `logoLightTheme`, the application uses `logo` or `fullLogo` for both themes.

If you enable `app.sidebar.logo`, ensure you configure `app.branding.fullLogoLightTheme` to display the correct logo in the light theme.

If you skip configuration, the *Sidebar* displays the default {product} icon for both light and dark themes.

.Verification
. Switch between light and dark themes in the UI.
. Confirm that the correct logo displays in both the *Global Header* and *Sidebar* according to the theme.