[id="proc-enabling-logo-in-the-sidebar.adoc_{context}"]
= Enabling logo in the sidebar

You can configure a logo in the sidebar of the {product} ({product-very-short}).

.Procedure

. To display the logo in the sidebar, set the value of the `app.sidebar.logo` parameter to `true` as shown in the following example:
+
.Example: Displaying the logo in only the sidebar
+
[source,yaml,subs="+attributes,+quotes"]
----
# ...rest of the global header configuration
app:
  sidebar:
    logo: true
  branding:
    fullLogoWidth: 220
    fullLogo: 'data:image/svg+xml;base64,...'

    - mountPoint: global.header/component
      importName: CompanyLogo
      config:
        priority: 200
        props:
          # Path to navigate when users click the logo:
          to: '/catalog'
          width: 300
          height: 200
          logo: <string> or <object> # Logo can be a base64 string or theme-specific object
            # Example 1: Single logo for all themes
            # logo: "<base64_encoded_images>"

            # Example 2: Theme-specific logos
            # logo:
                dark: 'data:image/png;base64,...' # Used in dark theme
                light: 'data:image/png;base64,...' # Used in light theme
----
+
To display the logo in only the sidebar, remove the `CompanyLogo` component from the configuration.

. To display the logo in the sidebar for all themes, update the configuration as shown in the following configuration:
+
.Example: Configuring sidebar logo for all themes
+
[source,yaml,subs="+attributes,+quotes"]
----
app:
  sidebar:
    logo: true
  branding:
    fullLogoWidth: 220
    fullLogo: 'data:image/svg+xml;base64,...'
----

. For theme-specific logos, you can configure the sidebar logo as shown in the following configuration:
+
.Example: Theme-specific logos
+
[source,yaml,subs="+attributes,+quotes"]
----
app:
  sidebar:
    logo: true
  branding:
    fullLogoWidth: 220
    fullLogo:
      light: 'data:image/svg+xml;base64,...'
      dark: 'data:image/svg+xml;base64,...'
----

.Verification
. The logo appears correctly in the sidebar.
. Toggle between `light` and `dark` themes to ensure the correct logo loads in each.