[id="displaying-company-logo-in-the-global-header.adoc_{context}"]
= Displaying company logo in the global header

You can configure a company logo in the *Global Header* of the {product} ({product-very-short}) to reflect your company's branding.

The `CompanyLogo` supports strict display constraints to ensure visual consistency:

* Maximum dimensions: 150px wide, 40px high.
* The logo must retain its original proportions.
* The component layout remains fixed and cannot be moved from its mount point.
* Supports the following props:
** `logo`: Encoded logo image.
** `to`: The redirect path where the logo is clicked.

.Procedure

To display a custom company logo in the *Global Header*, update the configuration with a mount point for `CompanyLogo`:

.Example: Configuring company logo

[source,yaml,subs="+attributes,+quotes"]
----
red-hat-developer-hub.backstage-plugin-global-header:
      mountPoints:
        - mountPoint: global.header/component
          importName: CompanyLogo
          config:
            priority: 200  # <1>
            props:
            logo:
            fullLogo:
              to: '/' # <2>
#...Rest of the Global Header Configuration
----
<1> Specify the position of the company logo in the global header.
<2> The redirect path. The logo should display the custom image or icon.

To ensure the logo appears in the correct location, configure the Global Header’s `position` value as shown in the example below:

[source,yaml]
----
red-hat-developer-hub.backstage-plugin-global-header:
  mountPoints:
    - mountPoint: application/header
      importName: GlobalHeader
      config:
        position: above-sidebar
----

By default, `position` is set to `above-main-content`.

.Verification
. The logo appears correctly in the Global Header.
. Click the logo to confirm it redirects to the path you defined in `props.to`.
