[id="customizing-your-product-global-header_{context}"]
= Customizing your {product} global header

Using dynamic plugins, you can extend the global header with additional buttons and customize the order and position of icons and features. For more information on enabling dynamic plugins, see link:{installing-and-viewing-dynamic-plugins-url}[{installing-and-viewing-dynamic-plugins-title}].

Include the following attributes in your global header entry:

`mountPoint`::
Defines where the header will be added. Use `application/header` to specify it as a global header.

`importName`::
Specifies the component exported by the global header plugin.

`config.position`::
Determines the header's position. Supported values are `above-main-content` and `above-sidebar`.

[NOTE]
====
You can configure several global headers at different positions by adding entries to the `mountPoints` field.
====

.Prerequisites
* You have configured your {product-custom-resource-type} instance.
* You have configured the support URL in the `{my-app-config-file}` file.
* You have installed the notification plugin.

.Procedure

. Install your own header as a dynamic plugin. For example, add the following plugin definition to your `dynamic-plugins.default.yaml` file:
+
.`dynamic-plugins.yaml` fragment
[source,yaml,subs="+attributes,+quotes"]
----
- package: `_<npm_or_oci_package-reference>_`
  disabled: false
  pluginConfig:
    dynamicPlugins:
      frontend:
        <package_name>:
          mountPoints:
            - mountPoint: application/header
              importName: `_<Header_component_name>_`
              config:
                position: above-main-content
----
+
[NOTE]
====
`importName` is an optional name referencing the value returned by the scaffolder field extension API.
====
. To disable the global header, disable the right plugin in your `dynamic-plugins.yaml` file as follows:
+
.`dynamic-plugins.yaml` fragment
[source,yaml,subs="+attributes,+quotes"]
----
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  disabled: true
----