[id="mount-points-for-dynamic-plugin-intergration_{context}"]
= Mount points for dynamic plugin integration

You can customize the application header in {product-short} using mount points for dynamic plugins. These mount points give flexibility in configuring the position of the header, its components and dropdown menus. You can create a customized experience with the following enhancements:

application/header::
Controls the header position. Use `config.position` to set placement as either `above-main-content` or `above-sidebar`.

global.header/component::
Configures header components. Use `config.priority` to set the order of components, and pass properties (including CSS styles) via `config.props`.

.Example adding a *Self-service* button
[source,yaml,subs="attributes,quotes"]
----
- mountPoint: global.header/component
  importName: HeaderIconButton
  config:
    priority: 80
    props:
      title: *Self-service*
      icon: add
      to: create
----

.Example adding a spacer element
[source,yaml]
----
- mountPoint: global.header/component
  importName: Spacer
  config:
    priority: 99
    props:
      growFactor: 0
----

global.header/profile::
Configures the profile dropdown list when the `ProfileDropdown` component is enabled.

.Example adding a settings link to the profile dropdown
[source,yaml]
----
- mountPoint: global.header/profile
  importName: MenuItemLink
  config:
    priority: 100
    props:
      title: Settings
      link: /settings
      icon: manageAccounts
----

global.header/create::
Configures the create dropdown list when the `CreateDropdown` component is enabled.

.Example adding a section for registering a component
[source,yaml]
----
- mountPoint: global.header/create
  importName: RegisterAComponentSection
  config:
    props:
      growFactor: 0
----