[id="displaying-preferred-username-in-global-header-profile-dropdown_{context}"]
= Displaying the preferred username in the profile dropdown

You can display the preferred username in the global header's profile dropdown by configuring `spec.profile.displayName` in the user entity. When not configured, the application falls back to a `metadata.title`. If neither is configured, it defaults to a user-friendly name generated by the `useProfileInfo` hook.

.Procedure
.Example when you configure `spec.profile.displayName`

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: _<my_display_name>_ # <1>
  title: _<display_name_title>_ # <2>
spec:
  profile:
    displayName: _<my_display_name>_ # <3>
  memberOf: [janus-authors]
----
<1> Required: Specify the unique username (`metadata.name`).
<2> Optional: Specify the preferred title (`metadata.title`).
<3> Optional: Specify the preferred display name (`spec.profile.displayName`). This takes the highest priority.

.Example when you do not configure `spec.profile.displayname` but configure `metadata.title`

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: _<my_display_name>_ # <1>
  title: _<display_name_title>_ # <2>
spec:
  memberOf: [janus-authors]
----
<1> Required: Specify the unique username (`metadata.name`).
<2> Optional: Specify the preferred title (`metadata.title`).

.Example when you do not configure the `spec.profile.displayname` and the `metadata.title`

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: _<my_display_name>_ # <1>
spec:
  memberOf: [janus-authors]
----
<1> Required: Specify the unique username (`metadata.name`).

[NOTE]
====
The application falls back to `metadata.name` when you do not register the user entity.
====