[id="customizing-your-product-global-header_{context}"]
= Customizing your {product} global header

You can use dynamic plugins to extend the global header with additional buttons and customize the order and position of icons and features. For more information on enabling dynamic plugins, see link:{installing-and-viewing-dynamic-plugins-url}[{installing-and-viewing-dynamic-plugins-title}].

To extend the functionality of the default global header, include any the following attributes in your global header entry:

`mountPoint`::
Specifies the location of the header. Use `application/header` to specify it as a global header.

`importName`::
Specifies the component exported by the global header plugin.
+
Below is a list of available header components that you can configure using the `config` field:

- **`SearchComponent`**: Adds a search bar (enabled by default).
- **`Spacer`**: Adds spacing in the header to position buttons at the end. Useful when you disable `SearchComponent`.
- **`HeaderIconButton`**: Adds an icon button. By default, the *Create* icon button remains enabled.
- **`SupportButton`**: Adds a support icon button, allowing users to configure a link to an internal or external page. Enabled by default but requires additional configuration to display.
- **`NotificationButton`**: Adds a notifications icon button to display unread notifications in real time and navigate to the Notifications page. Enabled by default (requires the notifications plugin).
- **`Divider`**: Adds a vertical divider. By default, a divider appears between the profile dropdown and other header components.
- **`ProfileDropdown`**: Adds a profile dropdown showing the logged-in user's name. By default, it contains two menu items.
- **`MenuItemLink`**: Adds a link item in a dropdown menu. By default, the profile dropdown includes a link to the "Settings" page.
- **`LogoutButton`**: Adds a logout button in the profile dropdown (enabled by default).
- **`CreateDropdown`**: Adds a *Create* dropdown button (disabled by default). The menu items are configurable.
- **`SoftwareTemplatesSection`**: Adds a list of software template links to the "Create" dropdown menu (disabled by default). You must enable `CreateDropdown`.
- **`RegisterAComponentSection`**: Adds a link to the "Register a Component" page in the "Create" dropdown menu (disabled by default). You must enable `CreateDropdown`.

`config.position`::
Specifies the position of the header. Supported values are `above-main-content` and `above-sidebar`.

[NOTE]
====
You can configure several global headers at different positions by adding entries to the `mountPoints` field.
====

.Prerequisites
* You have configured your {product} instance.
* You have configured the support URL in the `{my-app-config-file}` file.
* You have installed the notifications plugin.

.Procedure

. Install your custom header as a dynamic plugin by adding your custom plugin configuration to your `dynamic-plugins.default.yaml` file. For example:
+
[source,yaml,subs="+attributes,+quotes"]
----
- package: `_<npm_or_oci_package-reference>_`
  disabled: false
  pluginConfig:
    dynamicPlugins:
      frontend:
        <package_name>:
          mountPoints:
            - mountPoint: application/header
              importName: `_<Header_component_name>_`
              config:
                position: above-main-content
----
+
[NOTE]
====
`importName` is an optional name referencing the value returned by the scaffolder field extension API.
====
. Optional: To disable the global header, set the value of the `disabled` field to `true` in your `dynamic-plugins.yaml` file. For example:
+
[source,yaml,subs="+attributes,+quotes"]
----
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-global-header
  disabled: true
----