:_mod-docs-content-type: PROCEDURE

[id="configure-mcp-clients-to-access-the-rhdh-server_{context}"]
= Configure MCP clients to access the {product-very-short} server

[role="_abstract"]
Configure Model Context Protocol (MCP) client applications with server URLs and authentication to enable interaction with the {product-very-short} server.

You must configure an MCP client before it can interact with the MCP server. For a list of supported clients and their specific configurations, see link:https://modelcontextprotocol.io/clients[Example Clients].

.Prerequisites

* You have one of the following endpoints for the server URL, where `pass:c,a,q[{my-product-domain}]` is the hostname of your {product-very-short} instance.

** Streamable: `pass:c,a,q[{my-product-url}/api/mcp-actions/v1]`
** SSE (Legacy): `pass:c,a,q[`{my-product-url}/api/mcp-actions/v1/sse]`
+
[NOTE]
====
If a client does not yet support the Streamable endpoint, you must use the SSE endpoint.
====

* You have set the `MCP_TOKEN` environment variable in your MCP server configuration as the bearer token for authentication.

.Procedure

. Configure *{ls-short}* as a client. For more details, see {developer-lightspeed-link}[{ls-brand-name}].
.. In the `lightspeed-stack.yaml` configuration, add the following `mcp_servers` configuration:
+
[source,yaml,subs="+attributes,+quotes"]
----
mcp_servers:
  - name: mcp::backstage
    provider_id: model-context-protocol
    url: {my-product-url}/api/mcp-actions/v1
    authorization_headers:
      Authorization: "client"
----
+

`model-context-protocol`:: Enter the tool runtime provider defined in the llama-stack `run.yaml` configuration for {lcs-short}.

.. Optional: To use a custom Llama Stack configuration, add the following code to the `run.yaml` Llama Stack configuration file.
+
[source,yaml]
----
providers:
  tool_runtime:
  - provider_id: model-context-protocol
    provider_type: remote::model-context-protocol
    config: {}
----

.. To authorize requests to the MCP endpoint using `_<MCP_TOKEN>_`, add one or more servers to the `mcpServers` list in the {ls-short} `{my-app-config-file}` file, to make POST requests to {lcs-short}:
+
[source,yaml]
----
lightspeed:
  mcpServers:
  - name: mcp::backstage
    token: ${MCP_TOKEN}
  - name: _<mcp_server_name>_
    token: ${MCP_TOKEN_2}
----
where:

`name`:: Enter the server name. This must match the name configured in the {lcs-short}.
`token`:: Optional: Enter the static token used to authorize requests. You can also configure the token through the *MCP Server Settings* in the *Developer Lightspeed* user interface. The setting remains disabled until you configure the token.

.. Optional: Query the {lcs-short} `/v1/streaming_query` endpoint directly by providing the `MCP_TOKEN` in the header:
+
[source,yaml]
----
curl -X POST \
  -H `Content-Type: application/json` \
  -H `MCP-HEADERS: {"mcp::backstage": {"Authorization": "Bearer <MCP_TOKEN>"}}` \
  -d `{"query": "Can you give me all catalog templates of type 'service', "model": "gpt-4o-mini", "provider": "openai"}` \
  _<url>_/v1/streaming_query
----
+
where:

`<url>`:: Enter the {lcs-short} endpoint. Use `localhost` or the service name `pass:c,a,q:[<{product-very-short}_servicename>.{my-product-namespace}.svc.cluster.local:8080]` if you are inside the {backstage} container.

. Configure *Cursor* as a client.
.. From your Desktop app, navigate to *Cursor Settings*, select *MCP Tools* > *New MCP Server* and add the following configuration:
+
[source,yaml,subs="+attributes,+quotes"]
----
{
  "mcpServers": {
    "backstage-actions": {
      "url": "{my-product-url}/api/mcp-actions/v1",
      "headers": {
        "Authorization": "Bearer _<mcp_token>_"
      }
    }
  }
}
----
where:

`_<mcp_token>_`:: Enter the previously configured static token
`pass:c,a,q[{my-product-domain}]`:: Enter the hostname of your {product-very-short} instance

. Configure *Continue* as a client.

.. In your agent yaml configuration file, add the following configuration:
+
[source,yaml,subs="+attributes,+quotes"]
----
mcpServers:
  - name: backstage-actions
    type: sse
    url: {my-product-url}/api/mcp-actions/v1/sse
    requestOptions:
      headers:
        Authorization: "Bearer _<mcp_token>_"
----
+
where:

`_<mcp_token>_`:: Enter the previously configured static token
`pass:c,a,q[{my-product-domain}]`:: Enter the hostname of your {product-very-short} instance