:_mod-docs-content-type: CONCEPT

[id="role-based-access-control-in-rhdh_{context}"]
= Role-based access control in {product-short}

[role="_abstract"]
Administrators can authorize users to perform actions and define what users can do in {product-short}.

Role-based access control (RBAC) is a security concept that defines how to control access to resources in a system by specifying a mapping between users of the system and the actions that those users can perform on resources in the system.
You can use RBAC to define roles with specific permissions and then assign the roles to users and groups.

RBAC on {product-short} is built on top of the Permissions framework, which defines RBAC policies in code.
Rather than defining policies in code, you can use the {product-short} RBAC feature to define policies in a declarative fashion by using a simple CSV based format.
You can define the policies by using {product-short} web interface or REST API instead of editing the CSV directly.

An administrator can define authorizations in {product-short} by taking the following steps:

. Enable the RBAC feature and give authorized users access to the feature.

. Define roles and policies by combining the following methods:

* The {product-short} policy administrator uses the {product-short} web interface or REST API.
* The {product-short} administrator edits the main {product-short} configuration file.
* The {product-short} administrator edits external files.
