:_mod-docs-content-type: CONCEPT

[id="using-a-custom-signinpage-component_{context}"]
= Using a custom SignInPage component

[role="_abstract"]
In {product} ({product-very-short}), the `SignInPage` component manages authentication flow. By default, {product-short} uses a static `SignInPage`.

When you configure a custom `SignInPage`:

* The system loads the specified `importName` component from your dynamic plugin.
* The component returns a configured `SignInPage` that connects the required authentication provider factories.
* You specify only one `signInPage` for the application at a time.

[source,yaml]
----
dynamicPlugins:
  frontend:
    my-plugin: # The plugin package name
      signInPage:
        importName: CustomSignInPage
----

[NOTE]
====
The `package_name` specified under `dynamicPlugins.frontend` must match the `scalprum.name` value in the `package.json` file of your plugin to ensure the dynamic plugin loads correctly at runtime.

The `module` field is optional and specifies the set of assets that you must access within the dynamic plugin. By default, the system uses the `PluginRoot` module.
====
