:_mod-docs-content-type: CONCEPT

[id="using-a-custom-signinpage-component_{context}"]
= Using a custom SignInPage component

[role="_abstract"]
In {product} ({product-very-short}), the `SignInPage` component manages authentication flow. By default, {product-short} uses a static `SignInPage`.

When you configure a custom `SignInPage`:

* Only one `signInPage` is specified and used by the application.
* The system loads the specified `importName` component from your dynamic plugin.
* The component returns a configured `SignInPage` that connects the required authentication provider factories.
* The optional `module` field specifies the set of assets that should be accessed within the dynamic plugin. By default, the system uses the `PluginRoot` module.

[source,yaml,subs="+quotes"]
----
dynamicPlugins:
  frontend:
    __<package_name>__: # The plugin package name
      signInPage:
        importName: CustomSignInPage
----

[IMPORTANT]
====
The `package_name` specified under `dynamicPlugins.frontend` must match the `scalprum.name` value in the `package.json` file of your plugin to ensure the dynamic plugin loads correctly at runtime.
====



