:_mod-docs-content-type: PROCEDURE

[id="import-users-and-groups-from-rhbk_{context}"]
= Import users and groups from {rhbk-brand-name} ({rhbk})

[role="_abstract"]
Import {rhbk-brand-name} ({rhbk}) users and groups to the {product} software catalog.

.Prerequisites
* You have xref:share-a-secret-with-rhbk_share-a-secret-with-your-identity-provider[shared a secret with {rhbk}].

.Procedure

. Enable the Keycloak catalog provider plugin in your `dynamic-plugins.yaml` file.
+
The plugin is named after {rhbk} upstream project.
+
This plugin imports {rhbk} users and groups to the {product-short} software catalog.
+
[source,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic'
    disabled: false
----

. Enable provisioning {rhbk} users and groups to the {product-short} software catalog, by adding the `catalog.providers.keycloakOrg` section to your `{my-app-config-file}` file:
+
[id=keycloakOrgProviderId]
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        realm: ${KEYCLOAK_REALM}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
----

`baseUrl`::
Enter your {rhbk} server URL, defined earlier.

`clientId`::
Enter your {product-short} application client ID in {rhbk}, defined earlier.

`clientSecret`::
Enter your {product-short} application client secret in {rhbk}, defined earlier.

`realm`::
Enter the realm name to provision users.

`loginRealm`::
Enter the realm name to authenticate users.

. Optional: Add optional fields to the `keycloackOrg` catalog provider section in your `{my-app-config-file}` file:
+
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_BASE_URL}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        realm: ${KEYCLOAK_REALM}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        userQuerySize: 100
        groupQuerySize: 100
        schedule:
          frequency: { hours: 1 }
          timeout: { minutes: 50 }
          initialDelay: { seconds: 15}
----

`userQuerySize`::
Enter the user count to query simultaneously.
Default value: `100`.

`groupQuerySize`::
Enter the group count to query simultaneously.
Default value: `100`.

`schedule`::
`frequency`:::
Enter the schedule frequency.
Supports cron, ISO duration, and "human duration" as used in code.

`timeout`:::
Enter the timeout for the user provisioning job.
Supports ISO duration and "human duration" as used in code.

`initialDelay`:::
Enter the initial delay to wait for before starting the user provisioning job.
Supports ISO duration and "human duration" as used in code.

.Verification
* To verify user and group provisioning, check the console logs.
+
Successful synchronization example:
+
[source]
----
2025-06-27T16:02:34.647Z catalog info Read 5 Keycloak users and 3 Keycloak groups in 0.4 seconds. Committing... class="KeycloakOrgEntityProvider" taskId="KeycloakOrgEntityProvider:default:refresh" taskInstanceId="db55c34b-46b3-402b-b12f-2fbc48498e82" trace_id="606f80a9ce00d1c86800718c4522f7c6" span_id="7ebc2a254a546e90" trace_flags="01"

2025-06-27T16:02:34.650Z catalog info Committed 5 Keycloak users and 3 Keycloak groups in 0.0 seconds. class="KeycloakOrgEntityProvider" taskId="KeycloakOrgEntityProvider:default:refresh" taskInstanceId="db55c34b-46b3-402b-b12f-2fbc48498e82" trace_id="606f80a9ce00d1c86800718c4522f7c6" span_id="7ebc2a254a546e90" trace_flags="01"
----
