:_mod-docs-content-type: PROCEDURE

[id="add-new-components-to-your-rhdh-instance_{context}"]
= Add new components to your {product} instance

[role="_abstract"]
You can add new components to expand your {product-short} Software Catalog by registering them manually, creating them from Software Templates, or using bulk import.

.Prerequisites

* You have installed and configured the {product} instance.
* If RBAC is enabled, you have a role with the following permissions: `catalog.entity.create`, `catalog.location.create`, `bulk.import`.

.Procedure

* Add components to your {product-very-short} instance using the following methods:

** Register components manually using the GUI or by using your `{my-app-config-file}` with the required permissions.
** Create new components by using Software Templates.
* Use the bulk import plugin with the required permissions. For more information, see {configuring-dynamic-plugins-book-link}#bulk-importing-in-red-hat-developer-hub[Bulk importing GitHub repositories].
