:_mod-docs-content-type: PROCEDURE
[id="mirror-images-for-helm-deployments-on-ocp_{context}"]
= Mirror Intelligent Assistant images for Helm deployments on {ocp-short}

[role="_abstract"]
Mirror the required Intelligent Assistant container images to your local registry by using the `oc-mirror` plugin when deploying the Helm chart on an {ocp-short} cluster.

.Prerequisites
* You have a target mirror registry accessible to your disconnected {ocp-short} cluster.
* You authenticated to the {rhcr} and your target mirror registry.
* You have configured image pull authentication for your mirror registry as described in {installing-in-air-gap-book-link}#install-rhdh-on-ocp-in-an-air-gapped-environment-with-the-helm-chart[Install {product} on {ocp-short} in an air-gapped environment with the Helm chart]. The `kubelet` requires these credentials to pull all {product} container images, including the Intelligent Assistant sidecar and Offline Knowledge Portal (OKP) images.

.Procedure

. Identify the sidecar and OKP container images from the default values file of the chart:
+
[source,terminal,subs=attributes]
----
helm show values redhat-developer-hub --repo https://charts.openshift.io/ --version {product-chart-version} > values.default.yaml

LS_CORE_IMAGE=$(yq '.intelligentAssistant.core.image | .registry + "/" + .repository' values.default.yaml)
LS_CORE_DIGEST=$(yq '.intelligentAssistant.core.image.tag' values.default.yaml)
OKP_IMAGE=$(yq '.intelligentAssistant.okp.image | .registry + "/" + .repository' values.default.yaml)
OKP_DIGEST=$(yq '.intelligentAssistant.okp.image.tag' values.default.yaml)
----

. Add these images to the `additionalImages` section of your `ImageSetConfiguration` file:
+
[source,yaml,subs=+attributes]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  additionalImages:
    - name: ${LS_CORE_IMAGE}:${LS_CORE_DIGEST}
    - name: ${OKP_IMAGE}:${OKP_DIGEST}
  helm:
    repositories:
      - name: openshift-charts
        url: https://charts.openshift.io
        charts:
          - name: redhat-developer-hub
            version: "{product-version}"
----

.Additional resources
* {installing-in-air-gap-book-link}[{installing-in-air-gap-book-title}]
* {installing-and-viewing-plugins-book-link}#mirror-rhdh-dynamic-plugins-in-disconnected-environments_install-dynamic-plugins-in-rhdh[Mirroring {product} dynamic plugins in disconnected environments]
