:_mod-docs-content-type: PROCEDURE

[id="customize-the-chat-history-storage-in_{context}"]
= Customize the chat history storage in {ls-short}

[role="_abstract"]
By default, {ls-short} stores chat history in a non-persistent local database within the {lcs-short} container. You can configure {ls-short} to use PostgreSQL for persistent chat history storage.

[WARNING]
====
Configuring {ls-short} to use PostgreSQL records prompts and responses, which platform administrators can review.
You must assess any data privacy and security implications if user chat history contains private, sensitive, or confidential information.
For users that want to have their chat data removed, they must request their platform administrator to perform this action.
{company-name} does not collect or access this chat history data.
====

.Procedure
. Configure the chat history storage type in the {lcs-short} configuration file (`lightspeed-stack.yaml`) using any of the relevant options:
** To enable persistent storage with PostgreSQL, add the following configuration:
+ 
[source,yaml]
----
 conversation_cache:
    type: postgres
    postgres:
      host: _<your_database_host>_
      port: _<your_database_port>_
      db: _<your_database_name>_
      user: _<your_user_name>_
      password: _<postgres_password>_
----
* To retain the default, non-persistent SQLite storage, make sure the configuration is set as shown in the following example:
+
[source,yaml]
----
conversation_cache:
  type: "sqlite"
  sqlite:
    db_path: "/tmp/data/conversations/lcs_cache.db"
----

. Restart your {lcs-short} service to apply the new configuration.