:_mod-docs-content-type: PROCEDURE

[id="configure-rhdh-local-to-install-plugins-by-using-extensions_{context}"]
= Configure {product-local-very-short} to install plugins by using Extensions

[role="_abstract"]
You can use {product-local-very-short} to test installing plugins by using Extensions.

[IMPORTANT]
====
{company-name} maintains {product-local-very-short} as an open source project, but does not support it or subject it to any service level agreement (SLA).
====

[IMPORTANT] 
====
{product-local-very-short} is maintained as an open-source project by {company-name}, but is not supported or subject to any service level agreement (SLA).
====

.Prerequisites
* You have installed {product-local-very-short}. For more information about setting up {product-local-very-short}, see link:https://github.com/redhat-developer/rhdh-local/tree/main?tab=readme-ov-file#what-youll-need-before-you-get-started[Test locally with {product}].

.Procedure
. Update your `dynamic-plugins.override.yaml` file:
+
[source,yaml]
----
includes:
  - dynamic-plugins.default.yaml

plugins:
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-extensions
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          red-hat-developer-hub.backstage-plugin-marketplace:
            translationResources:
              - importName: marketplaceTranslations
                ref: marketplaceTranslationRef
                module: Alpha
            appIcons:
              - name: pluginsIcon
                importName: PluginsIcon
            dynamicRoutes:
              - path: /extensions
                importName: DynamicMarketplacePluginRouter
                menuItem:
                  icon: pluginsIcon
                  text: Extensions
                  textKey: menuItem.extensions
            menuItems:
              extensions:
                parent: default.admin
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-extensions-backend-dynamic
    disabled: false
    pluginConfig:
      extensions:
        installation:
          enabled: true
          saveToSingleFile:
            file: /opt/app-root/src/configs/dynamic-plugins/dynamic-plugins.override.yaml
----
where:

`translationResources`:: Sets the extension point for localization.

. Update your `compose.yaml` file:
+
[source,yaml]
----
rhdh:
  container_name: rhdh
  environment:
    NODE_OPTIONS: "--inspect=0.0.0.0:9229"
    NODE_ENV: "development"
----

.Verification
Enable a plugin by using the Extensions UI, restart your {product-very-short} application, and refresh the UI to confirm that you enabled the plugin.
