:_mod-docs-content-type: PROCEDURE

[id="set-up-the-guest-authentication-provider_{context}"]
= Set up the guest authentication provider

[role="_abstract"]
Enable guest authentication for testing RBAC features without configuring a full authentication provider.

You can enable guest authentication and use it alongside the RBAC front-end plugin.

.Prerequisites
* You have installed the `@backstage-community/plugin-rbac` plugin in {product-short}. For more information, see {configuring-dynamic-plugins-book-link}[{configuring-dynamic-plugins-book-title}].

.Procedure

* In the `{my-app-config-file}` file, add the user entity reference to resolve and enable the `dangerouslyAllowOutsideDevelopment` option, as shown in the following example:
+
[source,yaml,subs="+attributes,+quotes"]
----
auth:
  environment: development
  providers:
    guest:
      userEntityRef: user:default/guest
      dangerouslyAllowOutsideDevelopment: true
----
+
[NOTE]
====
You can use `user:default/guest` as the user entity reference to match the added user under the `permission.rbac.admin.users` section of the `{my-app-config-file}` file.
====
