:_mod-docs-content-type: PROCEDURE

[id="create-a-custom-transformer-to-provision-users-from-github-to-the-software-catalog_{context}"]
= Create a custom transformer to provision users from GitHub to the software catalog

[role="_abstract"]
Customize how {product} provisions users and groups to {product-short} software catalog entities,
by creating a backend module plugin that uses the `githubOrgEntityProviderTransformsExtensionPoint` to offer custom user and group transformers for the GitHub backend.

.Prerequisites
* You have xref:import-users-and-groups-from-github_{context}[imported users and groups from GitHub to the software catalog].

.Procedure
. Create a new backend module:
+
[source,shell]
----
$ yarn new
? What type of module would you like to create? backend-plugin-module
? Enter the ID if the plugin [required]? catalog
? Enter the ID of the module [required]? github-org-transformer
----
+
The command creates a plugin named `catalog-backend-module-github-org-transformer`.

. Install required packages:
+
[source,shell]
----
$ yarn --cwd plugins/catalog-backend-module-github-org-transformer add @backstage/plugin-catalog-backend-module-github-org
----

. (Optional) Install recommended packages to extend the default transformers or Transformer type checking:
+
[source,shell]
----
$ yarn --cwd plugins/catalog-backend-module-github-org-transformer add @backstage/plugin-catalog-backend-module-github
----

. (Optional) Install recommended packages for `UserEntity` or `GroupEntity` type checking:
+
[source,shell]
----
$ yarn --cwd plugins/catalog-backend-module-github-org-transformer add @backstage/catalog-model
----

. Refer to the link:https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-github-org-transformer[sample plugin] and implement your custom `plugins/catalog-backend-module-github-org-transformer/src/module.ts` and make your required transformations to user and group entities.

. Package and export the plugin as a Dynamic Plugin, and embed the required package for the custom transformer.
+
[source,shell]
----
$ npx @red-hat-developer-hub/cli@latest plugin export \
  --embed-package @backstage/plugin-catalog-backend-module-github \
  --embed-package @backstage/plugin-catalog-backend-module-github-org
----
+
[IMPORTANT]
====
Verify that the installed plugin version is compatible with the {backstage} version.

See the {dynamic-plugins-reference-book-link}[{dynamic-plugins-reference-book-title}] for the version to import.
====

. Publish and enable the plugin in {product-short}.
For more information, see {installing-and-viewing-plugins-book-link}#add-a-custom-dynamic-plugin-to-rhdh_installing-and-viewing-plugins-in-rhdh[{installing-and-viewing-plugins-book-title}].

.Verification

.  Every time that {product-short} starts, it imports the users and groups.
Check the console logs to verify the synchronization result.

. After the first import is complete, go to the *Catalog* page and select **User** to view the list of users.

. When you select a user, you see the information imported from GitHub.
Verify that the user entities reflect the custom transformations you defined in the plugin.

. You can select a group, view the list, and access or review the information imported from GitHub.
Verify that the group entities reflect the custom transformations you defined in the plugin.

. You can log in with a GitHub account.
