:_mod-docs-content-type: PROCEDURE

[id="import-multiple-github-repositories_{context}"]
= Import multiple GitHub repositories

[role="_abstract"]
Select and import multiple GitHub repositories to the {product} catalog, automatically creating pull requests with required catalog-info.yaml files.

.Prerequisites
* You have xref:enable-and-authorize-bulk-import-capabilities-in-rhdh_{context}[enabled the Bulk Import feature and given access to it].

.Procedure
. Click *Bulk Import* in {product-short} left sidebar.
. If your {product-very-short} instance has multiple source control tools configured, select *GitHub* from the *Source control tool* list.
. Select the repositories to import, and validate.
+
{product-short} creates a pull request in each selected repository to add the required `catalog-info.yaml` file.
. For each repository to import, click *PR* to review and merge the changes in GitHub.

.Verification
. Click *Bulk Import* in {product-short} left sidebar.
. Verify that each imported GitHub repository in the *Selected repositories* list has the status _Waiting for approval_ or _Imported_.
. For each _Waiting for approval_ repository, click the pull request link to review and merge the `catalog-info.yaml` file in the corresponding repository.

