:_mod-docs-content-type: PROCEDURE

[id="add-a-label-selector-query-annotation_{context}"]
= Add a label selector query annotation

[role="_abstract"]
Add a custom label selector annotation so that {product-very-short} uses your custom labels to find Kubernetes resources.

.Procedure

. Add the `backstage.io/kubernetes-label-selector` annotation to the `catalog-info.yaml` file of the entity. The label selector takes precedence over the ID annotations:
+
[source,yaml]
----
annotations:
  backstage.io/kubernetes-label-selector: 'app=my-app,component=front-end'
----

. Optional: If you have many entities while Red Hat Dev Spaces is configured and want multmanyities to support the edit code decorator that redirects to the Red Hat Dev Spaces instance, add the `backstage.io/kubernetes-label-selector` annotation to the `catalog-info.yaml` file for each entity:
+
[source,yaml]
----
annotations:
  backstage.io/kubernetes-label-selector: 'component in (<BACKSTAGE_ENTITY_NAME>,che)'
----

. If you are using the previous label selector, add the following labels to your resources so that the Kubernetes plugin gets the Kubernetes resources from the requested entity:
+
[source,yaml]
----
labels:
  component: che # add this label to your che cluster instance
labels:
  component: <BACKSTAGE_ENTITY_NAME> # add this label to the other resources associated with your entity
----
+
You can also write your own custom query for the label selector with unique labels to differentiate your entities. However, you need to ensure that you add those labels to the resources associated with your entities including your `CheCluster` instance.
