:_mod-docs-content-type: PROCEDURE

[id="install-dynamic-plugins-in-an-air-gapped-environment-by-using-the-operator_{context}"]
= Install in an air-gapped environment using the Operator

[role="_abstract"]
To install external dynamic plugins in an air-gapped environment, configure a custom NPM registry by mounting a secret into the {product-short} Operator.

.Prerequisites

* An {ocp-short} administrator has installed the {product} Operator.
* You have set up a custom NPM registry that is accessible from within your cluster and contains the required dynamic plugin packages.

.Procedure

. Create a secret containing your `.npmrc` configuration that points to your internal NPM registry:
+
[source,yaml,subs="+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: dynamic-plugins-npmrc
type: Opaque
stringData:
  .npmrc: |
    registry=https://_<your_internal_registry>_
    //_<your_internal_registry>_:_authToken=_<your_auth_token>_
----

. Apply the secret to your namespace:
+
[source,terminal,subs="+attributes"]
----
$ oc apply -f dynamic-plugins-npmrc.yaml -n {my-product-namespace}
----

. Add the secret to the `spec.application.extraFiles.secrets` field in your `{product-custom-resource-type}` custom resource, targeting the `install-dynamic-plugins` init container:
+
[source,yaml,subs="+attributes"]
----
apiVersion: rhdh.redhat.com/v1alpha5
kind: {product-custom-resource-type}
metadata:
  name: my-rhdh
spec:
  application:
    extraFiles:
      secrets:
        - name: dynamic-plugins-npmrc
          mountPath: /opt/app-root/src/.npmrc.dynamic-plugins
          containers:
            - install-dynamic-plugins
----
+
The `install-dynamic-plugins` init container reads the `.npmrc` file from `/opt/app-root/src/.npmrc.dynamic-plugins/.npmrc` to resolve plugin packages from your internal registry.

. Apply the updated custom resource:
+
[source,terminal,subs="+attributes"]
----
$ oc apply -f my-rhdh.yaml -n {my-product-namespace}
----

.Verification

* Verify that the init container used your custom registry by checking the init container logs:
+
[source,terminal]
----
$ oc logs -c install-dynamic-plugins deploy/backstage-my-rhdh
----
