:_mod-docs-content-type: PROCEDURE

[id="send-requests-to-the-rbac-rest-api-by-using-an-external-service_{context}"]
= Send requests to the RBAC REST API by using an external service

[role="_abstract"]
Send GET requests to the RBAC REST API from an external service authenticated with a service-to-service token.

You can send GET requests to the RBAC REST API by using an external service authenticated by using a service-to-service token.

.Prerequisites
* xref:enable-and-give-access-to-the-role-based-access-control-rbac-feature_authorization-in-rhdh[You have access to the RBAC feature].

* The external service can send HTTP GET requests, and is {authentication-book-link}#service-to-service-authentication[authenticated by using a service-to-service token].

.Procedure

. The external service sends a GET request to the RBAC REST API with the service-to-service token in the `Authorization` header.

. The RBAC REST API validates the service-to-service token, and then processes the request if the token is valid.
Otherwise, the RBAC REST API returns an error response.

. The RBAC REST API returns the response to the external service.

. The external service processes the response from the RBAC REST API.
