:_mod-docs-content-type: PROCEDURE

[id="enable-the-nexus-repository-manager-plugin_{context}"]
= Enable the Nexus Repository Manager plugin

[role="_abstract"]
Enable the Nexus Repository Manager plugin and configure its front-end mount point to view build artifact details on entity pages in {product-short}.

.Prerequisites
* You have a running Nexus Repository Manager instance.

.Procedure
* Add the following configuration to your `dynamic-plugins.yaml` file to enable the plugin and configure its front-end mount point:
+
[source,yaml,subs="+quotes"]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-nexus-repository-manager:__<tag>__
    enabled: true
    pluginConfig:
      dynamicPlugins:
        front-end:
          backstage-community.plugin-nexus-repository-manager:
            mountPoints:
              - mountPoint: entity.page.image-registry/cards
                importName: NexusRepositoryManagerPage
                config:
                  layout:
                    gridColumn: 1 / -1
                  if:
                    anyOf:
                      - isNexusRepositoryManagerAvailable
----
+
include::{docdir}/artifacts/snip-tag-for-OCI-package-paths.adoc[]
+
where:

`pluginConfig`:: Configures how the front-end component renders in {product-short}.
`mountPoint: entity.page.image-registry/cards`:: Mounts the artifact view on the *Image Registry* tab of the entity page.
`importName: NexusRepositoryManagerPage`:: The front-end component that displays artifact information.
`isNexusRepositoryManagerAvailable`:: A condition that renders the component only for entities that have Nexus Repository Manager annotations.
