:_mod-docs-content-type: PROCEDURE

[id="create-a-role-in-the-rhdh-web-ui_{context}"]
= Create a role in the {product} Web UI

[role="_abstract"]
Create a role in {product-short} by using the Web UI to define permissions, users, and groups.

You can create a role in the {product} using the Web UI.

.Prerequisites
* If RBAC is enabled, you have a role with the following permissions: `policy.entity.create`, `policy.entity.read`, `catalog.entity.read`.

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
The *RBAC* tab is displayed, showing all the created roles in the {product-short}.

. (Optional) Click any role to view the role information on the *OVERVIEW* page.
. Click *CREATE* to create a role.
. Enter the name and description of the role in the given fields and click *NEXT*.
. Add users and groups using the search field, and click *NEXT*.
. Select *Plugin* and *Permission* from the drop-downs in the *Add permission policies* section.
. Select or clear the *Policy* that you want to set in the *Add permission policies* section, and click *NEXT*.
. Review the added information in the *Review and create* section.
. Click *CREATE*.

.Verification

The created role is displayed in the list available in the *RBAC* tab.


