:_mod-docs-content-type: PROCEDURE

[id="enable-authentication-with-github_{context}"]
= Enable authentication with GitHub

[role="_abstract"]
Configure GitHub as your {product} sign-in provider.

.Prerequisites
* You have xref:share-a-secret-with-github_{secrets-context}[shared a secret with GitHub].
* You have {authentication-book-link}#import-users-and-groups-from-your-identity-provider_authentication-in-rhdh[provisioned users and groups to the software catalog].

.Procedure

. Add a GitHub authentication provider section to your `{my-app-config-file}` file:
+
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
signInPage: github
----

`environment`::
Enter `production` to disable the Guest login option in the {product-short} login page.

`clientId`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_SECRET}`.

`signInPage`::
Enter `github` to enable the GitHub provider as your {product-short} sign-in provider.

. Optional: Add optional fields to the GitHub authentication provider section in your `{my-app-config-file}` file:
+
[source,yaml,subs="+quotes"]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        callbackUrl: __<your_intermediate_service_url/handler>__
        sessionDuration: { hours: 24 }
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: github
----

`callbackUrl`::
Enter the callback URL that GitHub uses when initiating an OAuth flow, such as: __<your_intermediate_service_url/handler>__.
Define it when {product-short} is not the immediate receiver, such as in cases when you use one OAuth app for many {product-short} instances.

`sessionDuration`::
Enter the user session lifespan, in `ms` library format (such as '24h', '2 days'), ISO duration, or "human duration".

`signIn`::

`resolvers`:::
After successful authentication, {product-short} resolves the user signing in to an existing user in the {product-short} catalog.
Configure a specific resolver to best match users securely for your use case..
+
Enter the resolver list to override the default resolver: `usernameMatchingUserEntityName`.
+
The authentication provider tries each sign-in resolver in order until it succeeds. If none of the attempts succeed, the sign-in fails.
+
[WARNING]
====
In production mode, configure only one resolver to make sure users are securely matched.
====

`resolver`::::
Enter the sign-in resolver name.
Available resolvers: `usernameMatchingUserEntityName`, `preferredUsernameMatchingUserEntityName`, `emailMatchingUserEntityProfileEmail`.

`dangerouslyAllowSignInWithoutUserInCatalog`::::
Enter `true` to configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
[WARNING]
====
In production mode, do not enable `dangerouslyAllowSignInWithoutUserInCatalog`.
====

. To disable the guest login option, in the `{my-app-config-file}` file, set the authentication environment to `production`:
+
[source,yaml]
----
auth:
  environment: production
----

.Verification
. Go to the {product-short} login page.
. Your {product-short} sign-in page displays *Sign in using GitHub* and the Guest user sign-in is disabled.
. Log in with a GitHub account.
