:_mod-docs-content-type: PROCEDURE

[id="enable-kubernetes-custom-actions-plugin-in-rhdh_{context}"]
= Enable Kubernetes custom actions plugin in {product}

[role="_abstract"]
Enable the preinstalled Kubernetes custom actions plugin by updating the dynamic plugins configuration.

In {product}, the Kubernetes custom actions are provided as a preinstalled plugin, which is disabled by default. You can enable the Kubernetes custom actions plugin by updating the `disabled` key value in your `dynamic-plugins.yaml` file.

.Procedure

* Add a `package` with the Kubernetes custom action plugin name and update the `disabled` field in your `dynamic-plugins.yaml` file to enable the plugin. For example:
+
--
[source,yaml,subs="+quotes"]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-scaffolder-backend-module-kubernetes-dynamic:__<tag>__
    disabled: false
----

include::{docdir}/artifacts/snip-tag-for-OCI-package-paths.adoc[]

[NOTE]
====
The default configuration for a plugin is extracted from the `dynamic-plugins.default.yaml` file, however, you can use a `pluginConfig` entry to override the default configuration.
====
--
