:_mod-docs-content-type: PROCEDURE

[id="share-secrets-with-gitlab_{context}"]
= Share credentials with GitLab

[role="_abstract"]
Register a GitLab OAuth 2 application and store the credentials in {product} to enable user authentication with GitLab as a sign-in provider.

.Prerequisites
include::snip-enable-user-authentication-with-gitlab-common-prerequisites.adoc[]
* You have {integrating-with-your-git-provider-book-link}#configure-the-gitlab-integration_integrate-with-gitlab[configured the GitLab integration].

.Procedure

. Register the GitLab OAuth 2 application.
+
[IMPORTANT]
====
You must use the required callback URL and permissions.
====
+
.. link:https://docs.gitlab.com/integration/oauth_provider/[Register a GitLab OAuth 2 application] using the following configuration:
+
--
GitLab OAuth 2 application name::
Enter a unique name, such as `authenticating-with-rhdh-_<GUID>_`.

Redirect URI::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/gitlab/handler/frame]`.

Authorized application scope::
Enable `email`, `profile`, `openid`, and `read_user`.
--
.. Save the application and record these values for the next step:

. **OAuth 2 Client ID**, available in the *Application ID* field
. **OAuth 2 Client secret**, accessible by selecting *Copy* in the *Secret* field

. Add your GitLab OAuth credentials to {configuring-book-link}#provisioning-your-custom-configuration[your {product-very-short} secrets] using the following key/value pairs.
Use these environment variables in your {product-very-short} configuration files.

`GITLAB_CLIENT_ID`::
Enter the saved *OAuth 2 Client ID*.

`GITLAB_CLIENT_SECRET`::
Enter the saved *OAuth 2 Client Secret*.

`GITLAB_URL`::
Enter the GitLab host domain: _`<gitlab_host_domain>`_.

`GITLAB_PARENT_ORG`::
Enter your GitLab organization name, such as `_<your_gitlab_organization_name>_`.

.Verification
* Verify that the secret key-value pairs are stored in your {product-short} secrets.
