:_mod-docs-content-type: PROCEDURE

[id="edit-a-role-in-the-rhdh-web-ui_{context}"]
= Edit a role in the {product} Web UI

[role="_abstract"]
Edit a role in {product-short} by using the Web UI to change role details, users, groups, and permission policies.

You can edit a role in the {product} using the Web UI.

[NOTE]
====
The policies generated from a `policy.csv` or ConfigMap file cannot be edited or deleted using the {product-short} Web UI.
====

.Prerequisites
* You {authorization-book-link}#enabling-and-giving-access-to-rbac_title-authorization[have enabled RBAC, have a policy administrator role in {product-short}, and have added plugins with permission].

* The role that you want to edit is created in the {product-short}.

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
The *RBAC* tab is displayed, showing all the created roles in the {product-short}.

. (Optional) Click any role to view the role information on the *OVERVIEW* page.

. Select the edit icon for the role that you want to edit.

. Edit the details of the role, such as name, description, users and groups, and permission policies, and click *NEXT*.

. Review the edited details of the role and click *SAVE*.

.Verification
. After saving the changes, you can view the edited details of the role on the *OVERVIEW* page of the role.

. You can also edit a role's users and groups or permissions by using the edit icon on the Users and Groups or Permissions cards on the *OVERVIEW* page.

