:_mod-docs-content-type: PROCEDURE

[id="enable-software-template-version-update-notifications-in-rhdh_{context}"]
= Enable Software Template version update notifications in {product}

[role="_abstract"]
Enable notification alerts for template version updates so that component owners are automatically notified when the Software Template used to generate their components is updated to a new version.


.Prerequisites

* You have installed and configured the {product-very-short} notification plugins:
** backend: `@backstage/plugin-notifications-backend`
** front-end: `@backstage/plugin-notifications`

.Procedure

. Open your {product-very-short} `{my-app-config-file}` file.
. Add the following configuration to the `scaffolder` section to enable Software Template update notifications
. Optional: To customize the notification title and description, add the `message` block:
+
[source,yaml]
----
scaffolder:
  notifications:
    templateUpdate:
      enabled: true
      message:
        title: 'Custom title for $ENTITY_DISPLAY_NAME'
        description: 'Custom description'
----
+
where:

`enabled`:: Set to `true` to enable the notification. Default value is `false`.
`message:title`:: Enter the notification title.
`message:description`:: Enter the notification description.
+
[NOTE]
====
The `message:title` and `message:description` fields support the `$ENTITY_DISPLAY_NAME` variable. The system replaces this variable with the title (or the name, if the title is missing) of the scaffolded entity.
====

.Verification
. Log in to your `{product}` instance.
. In the left navigation menu, verify that the *Notifications* item is displayed.
. Update the version of a Software Template and verify that the owner of a component scaffolded from that template receives a notification.