:_mod-docs-content-type: PROCEDURE

[id="load-a-plugin-packaged-as-an-oci-image_{context}"]
= Load a plugin packaged as an OCI image

[role="_abstract"]
Use this procedure to load a dynamic plugin from an OCI image into {product}.

.Prerequisites
* You packaged the {plugin-type-name} plugin as a dynamic plugin in an OCI image.
+
For more information about packaging a {plugin-type-name} plugin, see xref:package-and-publish-plugins-as-dynamic-plugins_plugins-in-rhdh[].

.Procedure
. To retrieve plugins from an authenticated registry, complete the following steps:
.. Log in to the container image registry.
+
[source,yaml]
----
podman login <registry>
----
.. Verify the content of the `auth.json` file created after the login.
+
[source,yaml]
----
cat ${XDG_RUNTIME_DIR:-~/.config}/containers/auth.json
----
.. Create a secret file using the following example:
+
[source,yaml]
----
oc create secret generic _<secret_name>_ --from-file=auth.json=${XDG_RUNTIME_DIR:-~/.config}/containers/auth.json <1>
----
+
** For an Operator-based deployment, replace _<secret_name>_ with `dynamic-plugins-registry-auth`.
** For a Helm-based deployment, replace _<secret_name>_ with `<Helm_release_name>_-dynamic-plugins-registry-auth`.

. Define the plugin with the `oci://` prefix by using one of the following formats in your `dynamic-plugins.yaml` file:

Standard definition:: Use the format `oci://<image_name>:<tag>`, as shown in the following example. The installation program automatically extracts the plugin path from the image metadata.
+
Example configuration in `dynamic-plugins.yaml` file:
+
[source,yaml]
----
plugins:
  - disabled: false
    package: oci://quay.io/example/image:v1.0.0
----
+
[NOTE]
====
You must package images with the `@red-hat-developer-hub/cli` to ensure the system applies the `io.backstage.dynamic-packages` annotation.

You must define exactly one plugin from that OCI image in the configuration files. The system returns an error if the configuration files contain many plugins or no matching plugins.
====

Using image digests:: To perform an integrity check, use the image digest in place of the tag in the `dynamic-plugins.yaml` file as shown in the following example:
+
Example configuration in `dynamic-plugins.yaml` file:
+
[source,yaml]
----
plugins:
  - disabled: false
    package: oci://quay.io/example/image@sha256:28036abec4dffc714394e4ee433f16a59493db8017795049c831be41c02eb5dc
----

Using version inheritance:: To inherit a version from a base configuration file, for example, `dynamic-plugins.default.yaml`, use the `{{inherit}}` placeholder to inherit the `v0.0.2` tag, as shown in the following example:
+
Example configuration in `dynamic-plugins.default.yaml` file:
+
[default-source,yaml]
----
plugins:
  - disabled: false
    package: oci://quay.io/example/image:v0.0.2
----
+
Example configuration in `dynamic-plugins.yaml` file:
+
[source,yaml]
----
includes:
  - dynamic-plugins.default.yaml
plugins:
  - disabled: false
    package: oci://quay.io/example/image:{{inherit}}
----
+
[NOTE]
====
An error occurs if you use `{{inherit}}` in the includes file itself or if no matching plugin key exists in the base configuration.
====

. To apply the changes, restart the {product-very-short} application.
