:_mod-docs-content-type: PROCEDURE
[id="mirror-images-for-air-gapped-environments_{context}"]
= Mirror {ls-short} images for air-gapped environments

[role="_abstract"]
To provide chat assistance in a network environment without internet access, you must mirror the required {ls-short} container images to your local registry in addition to the standard {product-short} images. 

This action ensures your secure environment can pull the necessary images inside your network perimeter.

You must mirror the following {ls-short} images:
* The {lcs-name}({lcs-short}) sidecar container
* The initialization container for retrieval-augmented generation (RAG) data

.Prerequisites
* You have a target mirror registry accessible to your disconnected cluster.
* You authenticated to the {rhcr} and your target mirror registry.
* You updated the cluster install secret (the 'pull-secret' in the 'openshift-config' namespace) to include the authentication credentials to your mirror registry. The `kubelet` requires these credentials to pull the sidecar images when starting up the {product-very-short} pod.

.Procedure
. Extract or identify the image digests for the {ls-short} sidecar and initialization container images.
. Mirror the images directly to your internal mirror registry by running the `skopeo copy` command:
+
[source,terminal]
----

----

.Additional resources
* {installing-in-air-gap-book-link}[{installing-in-air-gap-book-title}]
