:_mod-docs-content-type: PROCEDURE

[id="provision-your-custom-rhdh-configuration_{context}"]
= Provision your custom {product} configuration

[role="_abstract"]
Provision custom config maps and secrets on {platform-long} to configure {product} before running the application.

include::snip-provision-configuration-tip.adoc[]

.Prerequisites
include::snip-provision-configuration-common-prerequisite.adoc[]

.Procedure
include::snip-provision-configuration-secrets-intro.adoc[]
+
{authentication-book-link}[Enter your authentication secrets].
include::snip-provision-configuration-appconfig-intro.adoc[]
+
--
** To prepare a deployment with the {product} Operator on {ocp-short}, you can start with an empty file.

** To prepare a deployment with the {product} Helm chart, or on Kubernetes, enter the {product-short} base URL in the relevant fields in your `{my-app-config-file}` file to ensure proper functionality of {product-short}.
The base URL is what a {product-short} user sees in their browser when accessing {product-short}.
The relevant fields are `baseUrl` in the `app` and `backend` sections, and `origin` in the `backend.cors` subsection:
+
Configuring the `baseUrl` in `{my-app-config-file}`:
+
[source,yaml,subs="+attributes,+quotes"]
----
app:
  title: {product}
  baseUrl: {my-product-url}

backend:
  auth:
    externalAccess:
      - type: legacy
        options:
          subject: legacy-default-config
          secret: "${BACKEND_SECRET}"
  baseUrl: {my-product-url}
  cors:
    origin: {my-product-url}
----

** Optionally, enter your configuration such as:

*** {authentication-book-link}[{authentication-book-title}].
*** {authorization-book-link}[{authorization-book-title}].
*** {customizing-book-link}[Customization].
*** {customizing-book-link}#configuring-an-rhdh-instance-with-tls-in-kubernetes_{context}[Configure your {ocp-short} integration].
--
include::snip-provision-configuration-final-steps.adoc[]

.Next steps
* {configuring-book-link}#configuring-external-postgresql-databases[Provision your PostgreSQL database secrets]
* {installing-and-viewing-plugins-book-link}[Provision your dynamic plugins config map]
* {authorization-book-link}#managing-authorizations-by-using-external-files[Provision your RBAC policies config map]
