:_mod-docs-content-type: PROCEDURE

[id="send-requests-to-the-rbac-rest-api-by-using-a-rest-client_{context}"]
= Send requests to the RBAC REST API by using a REST client

[role="_abstract"]
Send RBAC REST API requests by using any REST client with authorization tokens and appropriate HTTP methods.

You can send RBAC REST API requests by using any REST client.

.Prerequisites
* xref:enable-and-give-access-to-the-role-based-access-control-rbac-feature_authorization-in-rhdh[You have access to the RBAC feature].

.Procedure
include::snip-finding-bearer-token.adoc[]

. In your REST client, run a command with the following parameters and review the response:
+
Authorization::
Enter your saved authorization token.

HTTP method::
Enter the HTTP method for your xref:supported-rbac-rest-api-endpoints_{context}[API endpoint].

`GET`:::
To retrieve specified information from a specified resource endpoint.
`POST`:::
To create or update a resource.
`PUT`:::
To update a resource.
`DELETE`:::
To delete a resource.

URL::
Enter your {product-short} URL and xref:supported-rbac-rest-api-endpoints_{context}[API endpoint]: pass:c,a,q[{my-product-url}/__<endpoint>__], such as
`pass:c,a,q[{my-product-url}/api/permission/policies]`.

Body::
Enter the JSON body with data that your xref:supported-rbac-rest-api-endpoints_{context}[API endpoint] might need with the HTTP `POST` request.

