:_mod-docs-content-type: PROCEDURE

[id="create-an-oci-image-with-dynamic-packages_{context}"]
= Create an OCI image with dynamic packages

[role="_abstract"]
Use this procedure to package a dynamic plugin as an OCI image and push it to a container registry.

.Prerequisites
* You have installed `podman` or `docker`.

ifeval::["{context}" == "assembly-package-publish-third-party-dynamic-plugin"]
* You have exported a {plugin-type-name} dynamic plugin package. For more information, see xref:export-plugins-in-rhdh_plugins-in-rhdh[].
endif::[]

.Procedure
. Navigate to the plugin's root directory (not the `dist-dynamic` directory).
. Run the following command to package the plugin into an OCI image:
+
--
[source,terminal]
----
$ npx @red-hat-developer-hub/cli@latest plugin package --tag quay.io/example/image:v0.0.1
----

In the earlier command, the `--tag` argument specifies the image name and tag.
--
. Run one of the following commands to push the image to a registry:
+
--
[source,terminal]
----
$ podman push quay.io/example/image:v0.0.1
----

[source,terminal]
----
$ docker push quay.io/example/image:v0.0.1
----

The output of the `package-dynamic-plugins` command provides the plugin's path for use in the `dynamic-plugin-config.yaml` file.
--
