:_mod-docs-content-type: PROCEDURE

[id="determine-permission-policy-and-role-configuration-source_{context}"]
= Determine permission policy and role configuration source

[role="_abstract"]
Identify the source of permission policies and roles to keep data consistency and find which source controls each resource.

You can configure {product} policy and roles by using different sources.
To keep data consistency, {product-short} associates each permission policy and role with one unique source.
You can only use this source to change the resource.

The available sources are:

Configuration file::
Configure roles and policies in the {product-short} `{my-app-config-file}` configuration file, for instance to xref:enable-and-give-access-to-the-role-based-access-control-rbac-feature_authorization-in-rhdh[declare your policy administrators].
+
The Configuration file pertains to the default `role:default/rbac_admin` role provided by the RBAC plugin.
The default role has limited permissions to create, read, update, delete permission policies or roles, and to read catalog entities.
+
[NOTE]
====
In case the default permissions are insufficient for your administrative requirements, you can create a custom admin role with the required permission policies.
====

REST API::
Configure roles and policies xref:manage-role-based-access-controls-rbac-using-the-rhdh-web-ui_{context}[by using the {product-short} Web UI] or by using the REST API.

CSV file::
Configure roles and policies by using external CSV files.

Legacy::
The legacy source applies to policies and roles defined before RBAC backend plugin version `2.1.3`, and is the least restrictive among the source location options.
+
IMPORTANT: Replace the permissions and roles using the legacy source with the permissions using the REST API or the CSV file sources.

.Procedure
* To find the source of a role or policy, use a `GET` request.
