:_mod-docs-content-type: PROCEDURE

[id="share-a-secret-with-rhbk_{context}"]
= Share a secret with {rhbk-brand-name} ({rhbk})

[role="_abstract"]
Register your {product} application in {rhbk-brand-name} ({rhbk}) and store the credentials in {product-short} to enable secure communication.

.Prerequisites
include::snip-enabling-user-authentication-with-rhbk-common-prerequisites.adoc[]

.Procedure

. Register your {product-short} app in {rhbk}:

.. Use an existing realm, or {rhbk-docs-link}/html-single/getting_started_guide/index#getting-started-zip-create-a-realm[create a realm], with a distinctive **Name** such as __<my_realm>__.
Save the value for the next step:
. **{rhbk} realm base URL**, such as: __<your_rhbk_URL>__/realms/__<your_realm>__.

.. In the created realm, {rhbk-docs-link}/html-single/getting_started_guide/index#getting-started-zip-secure-the-first-application[secure the first application], with:
... **Client ID**: A distinctive client ID, such as __<{product-very-short}>__.
... **Valid redirect URIs**: Set to the OIDC handler URL: `pass:c,a,q[{my-product-url}/api/auth/oidc/handler/frame]`.
... Go to the **Credentials** tab and copy the **Client secret**.
... Save the values for the next step:
. **Client ID**
. **Client Secret**

.. In the same realm, get the credential information for an existing user or {rhbk-docs-link}/html-single/getting_started_guide/index#getting-started-zip-create-a-user[create a user].
Save the user credential information for the verification steps.

. Create a long, complex, and unique string to use as the {product-short} session secret key.

. Add the following key-value pairs to {configuring-dynamic-plugins-book-link}#provisioning-your-custom-configuration[your {product-short} secrets].
You can use these secrets in the {product-short} configuration files by using their environment variable name.
+
`KEYCLOAK_CLIENT_ID`::
Enter the saved **Client ID**.

`KEYCLOAK_CLIENT_SECRET`::
Enter the saved **Client Secret**.

`KEYCLOAK_BASE_URL`::
Enter the saved **{rhbk} realm base URL**.

`KEYCLOAK_REALM`::
Enter the realm name to provision users.

`KEYCLOAK_LOGIN_REALM`::
Enter the realm name to authenticate users.

`SESSION_SECRET`::
Enter the created session secret key.

.Verification
* Verify that the secret key-value pairs are stored in your {product-short} secrets.
