:_mod-docs-content-type: PROCEDURE

[id="disable_{context}"]
= Disable {ls-short}

[role="_abstract"]
Disable the {ls-short} chat interface and stop associated container processes by updating your deployment configuration.

.Prerequisites
* You have access to the cluster where your instance is deployed.
* You have cluster administrator privileges.

.Procedure
Complete the steps for your specific deployment method:

* Disabling {ls-short} by using the Operator:
. Open your {backstage} custom resource (CR) YAML file.
. In the `spec` section, set the `enabled` flag to `false` for the `lightspeed` flavour. This disables the chat interface and prevents the Operator from injecting unconfigured sidecar containers:
+
[source,yaml]
----
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: lightspeed-disabled
spec:
  flavours:
    - name: lightspeed
      enabled: false
----
. Apply the updated custom resource manifest to your cluster:
+
[source,bash]
----
oc apply -f <backstage_cr_file>.yaml
----

* Disabling {ls-short} by using the Helm chart:
. Open your Helm `values.yaml` file.
. Update the `global.lightspeed.enabled` parameter to `false` to disable the chat interface:
+
[source,yaml]
----
global:
  lightspeed:
    enabled: false
----
. Run the `helm upgrade` command to apply the configuration change to your cluster.

.Verification
. Log in to your console instance.
. Verify that the *Open Lightspeed* floating action button (FAB) no longer appears on the home page.
