:_mod-docs-content-type: PROCEDURE

[id="enable-users-to-use-the-topology-plugin_{context}"]
= Enable users to use the Topology plugin

[role="_abstract"]
The Topology plugin is defining additional permissions. When {authorization-book-link}[{authorization-book-title}] is enabled, to enable users to use the Topology plugin, grant them:

* The `kubernetes.clusters.read` and `kubernetes.resources.read`, `read` permissions to view the Topology panel.
* The `kubernetes.proxy` `use` permission to view the pod logs.
* The `catalog-entity` `read` permission to view the {product} software catalog items.

.Prerequisites
* You are {authorization-book-link}#managing-authorizations-by-using-external-files[managing {authorization-book-title} by using external files].

.Procedure
* Add the following permission policies to your `rbac-policy.csv` file to create a `topology-viewer` role that has access to the Topology plugin features, and add the role to the users requiring this authorization:
+
[source]
----
g, user:default/<YOUR_USERNAME>, role:default/topology-viewer
p, role:default/topology-viewer, kubernetes.clusters.read, read, allow
p, role:default/topology-viewer, kubernetes.resources.read, read, allow
p, role:default/topology-viewer, kubernetes.proxy, use, allow
p, role:default/topology-viewer, catalog-entity, read, allow
----
+
`kubernetes.clusters.read` and `kubernetes.resources.read, read, allow`:: Grants the user the ability to see the Topology panel.
`kubernetes.proxy, use, allow`:: Grants the user the ability to view the pod logs.
`catalog-entity, read, allow`:: Grants the user the ability to see the catalog item.
