:_mod-docs-content-type: PROCEDURE

[id="enable-the-argo-cd-plugin_{context}"]
= Enable the Argo CD plugin

[role="_abstract"]
The Argo CD plugin provides a visual overview of the application{apos}s status, deployment details, commit message, author of the commit, container image promoted to environment and deployment history.

.Procedure

. Add Argo CD instance information to your `app-config.yaml` configmap as shown in the following example:

+
[source,yaml]
----
argocd:
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: argoInstance1
          url: https://argoInstance1.com
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}
        - name: argoInstance2
          url: https://argoInstance2.com
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}
----
+
[NOTE]
====
Avoid using a trailing slash in the `url`, as it might cause unexpected behavior.
====

. Add the following annotation to the entity{apos}s `catalog-info.yaml` file to identify the Argo CD applications.

+
[source,yaml]
----
annotations:
  ...
  # The label that Argo CD uses to fetch all the applications. The format to be used is label.key=label.value. For example, rht-gitops.com/janus-argocd=quarkus-app.

  argocd/app-selector: '${ARGOCD_LABEL_SELECTOR}'
----

. (Optional) Add the following annotation to the entity{apos}s `catalog-info.yaml` file to switch between Argo CD instances as shown in the following example:

+
[source,yaml]
----
 annotations:
   ...
    # The Argo CD instance name used in `app-config.yaml`.

    argocd/instance-name: '${ARGOCD_INSTANCE}'
----

+
[NOTE]
====
If you do not set this annotation, the Argo CD plugin defaults to the first Argo CD instance configured in `app-config.yaml`.
====

. To enable the Argo CD plugin, set the `disabled` property to `false` in your `dynamic-plugins.yaml` file as follows:
+
[IMPORTANT]
====
Argo CD contains multiple plugin options you can choose from for your Argo CD configuration:

* Community Argo CD:
** `@backstage-community/plugin-argocd`
** `@backstage-community/plugin-argocd-backend`
* Roadie Argo CD:
** `@roadiehq/backstage-plugin-argo-cd`
** `@roadiehq/backstage-plugin-argo-cd-backend`

Community and Roadie plugins are comparable in functionality but have different features.
For example, both versions feature scaffolder actions,
however their implementation is different:
the Community version contains scaffolder actions by default, the Roadie version requires an additional plugin.

The recommended combination is to use `@backstage-community/plugin-argocd` together with `@backstage-community/plugin-argocd-backend`.

However,
you can also combine `@roadiehq/backstage-plugin-argo-cd` together with `@roadiehq/backstage-plugin-argo-cd-backend`.

Mixing Community and Roadie plugins is *not recommended*.
====
+
[source,yaml,subs="+quotes"]
----
<<<<<<< RHDHBUGS-521-plugin-enable-snippets
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/roadiehq-backstage-plugin-argo-cd-backend:__<tag>__
    disabled: false
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd:__<tag>__
    disabled: false
=======
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd-backend:__<tag>__
        disabled: false
      - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/backstage-community-plugin-argocd:__<tag>__
        disabled: false
>>>>>>> main
----

include::{docdir}/artifacts/snip-tag-for-OCI-package-paths.adoc[]
