:_mod-docs-content-type: PROCEDURE

[id="configure-the-rbac-backend-plugin_{context}"]
= Configure the RBAC backend plugin

[role="_abstract"]
Enable the permission framework and configure admin users by updating the app-config-rhdh.yaml file.

You can configure the RBAC backend plugin by updating the `{my-app-config-file}` file to enable the permission framework.

.Prerequisites
* You have installed the `@backstage-community/plugin-rbac` plugin in {product-short}. For more information, see {configuring-dynamic-plugins-book-link}[{configuring-dynamic-plugins-book-title}].

.Procedure
* Update the `{my-app-config-file}` file to enable the permission framework as shown:
+
[source,yaml,subs=+quotes]
----
permission
  enabled: true
  rbac:
    admin:
      users:
        - name: user:default/guest
    pluginsWithPermission:
      - catalog
      - permission
      - scaffolder
----
+
[NOTE]
====
The `pluginsWithPermission` section of the `{my-app-config-file}` file includes only three plugins by default. Update the section as needed to include any additional plugins that also incorporate permissions.
====
