:_mod-docs-content-type: PROCEDURE

[id="troubleshoot-a-pod-startup-failure-after-enabling-a-plugin_{context}"]
= Troubleshoot a pod startup failure after enabling a plugin

[role="_abstract"]
If the {product-very-short} pod fails to start after enabling a plugin, you can inspect the pod logs and configure the required environment variables.

.Procedure
. Inspect your {product-very-short} pod logs to identify if the plugin requires specific environment variables or additional configuration, for example:
+
[source,terminal]
----
Plugin '<PLUGIN_NAME>' threw an error during startup, waiting for X other plugins to finish before shutting down the process. Plugin '<PLUGIN_NAME>' startup failed; caused by Error: Missing required config value at '<concretePluginRequiredVariable.name>' in 'app-config.local.yaml' type="initialization"
----
. Verify the required configuration by inspecting the `dynamic-plugins.default.yaml` file that lists the required environment variables for each plugin.
The variables for each plugin are in the format of `${PLUGIN_VARIABLE_NAME}`.
. If any required environment variables are missing, set the environment variables by using a *secret*. For example:
+
[source,yaml]
----
kind: Secret
apiVersion: v1
metadata:
  name: rhdh-secrets
  labels:
    backstage.io/kubernetes-id: developer-hub
data:
  PLUGIN_VARIABLE_NAME: 'dummy-value'
type: Opaque
----
. Mount the secret:
.. If you deployed {product-very-short} by using the Operator, update your `{product-custom-resource-type}` CR, as follows:
+
[source,yaml]
----
spec:
  application:
    extraEnvs:
      secrets:
        - name: rhdh-secrets
----
.. If you deployed {product-very-short} by using the Helm chart, in the `upstream.backstage` key in your Helm chart values, enter the name of the {product-short} `rhdh-secrets` secret as the value for the `extraEnvVarsSecrets` field. For example:
+
[source,yaml]
----
upstream:
  backstage:
    extraEnvVarsSecrets:
      - rhdh-secrets
----
