:_mod-docs-content-type: REFERENCE

[id="ocm-permissions_{context}"]
= OCM permissions

[role="_abstract"]
Reference information about Red Hat OpenShift Cluster Manager permissions for reading OCM plugin and cluster information.

Basic OCM permissions only restrict access to the cluster view, but they do not prevent access to the Kubernetes clusters in the resource view.
For more effective permissions, consider applying a conditional policy to restrict access to catalog entities that are of type `kubernetes-cluster`.
Access restriction is dependent on the set of permissions granted to a role.
For example, if the role had full permissions (`read`, `update`, and `delete`), then you must specify all its permissions in the `permissionMapping` field.

[source,csv]
----
result: CONDITIONAL
roleEntityRef: 'role:default/<YOUR_ROLE>'
pluginId: catalog
resourceType: catalog-entity
permissionMapping:
  - read
  - update
  - delete
conditions:
  not:
    rule: HAS_SPEC
    resourceType: catalog-entity
    params:
      key: type
      value: kubernetes-cluster
----

[cols="15%,25%,15%,45%", frame="all", options="header"]
|===
|Name
|Resource type
|Policy
|Description

|`ocm.entity.read`
|
|`read`
|Enables a user or role to read from the OCM plugin

|`ocm.cluster.read`
|
|`read`
|Enables a user or role to read the cluster information in the OCM plugin
|===
