:_mod-docs-content-type: REFERENCE

[id="customizing-and-extending-entity-tabs_{context}"]
= Customizing and extending entity tabs

[role="_abstract"]
You can customize and extend the set of tabs by using the `entityTabs` configuration as in the following example:

[source,yaml,subs="+quotes"]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: <plugin_path_or_url>
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          __<package_name>__: # The plugin package name
            entityTabs:
              # Specifies a new tab
              - path: /new-path
                title: My New Tab
                mountPoint: entity.page.my-new-tab
              # Changes an existing tab's title or mount point
              - path: /
                title: General
                mountPoint: entity.page.overview # Can be customized
                # Specifies the sub-path route in the catalog where this tab is available
              - path: "/pr"
                title: "Changed Pull/Merge Requests" # Specifies the title you want to display
                priority: 1
                # The base mount point name available on the tab
                mountPoint: "entity.page.pull-requests"
              - path: "/"
                title: "Changed Overview"
                mountPoint: "entity.page.overview"
                # Specifies the order of tabs. The tabs with higher priority values appear first
                priority: -6
----

Each entity tab entry requires the following attributes:
* `path`: Specifies the sub-path route in the catalog where this tab is available.
* `title`: The title displayed to the user.
* `mountPoint`: The base mount point name available on the tab.
This name is expanded to create two mount points per tab,
one appended with `/context` and the second appended with `/cards`.
* `priority`: (Optional): Determines the order of tabs. Tabs with higher priority values appear first. You can set a negative priority to hide default tabs.

You can configure dynamic front-end plugins to target the mount points exposed by the entityTabs configuration. The following are the default catalog entity routes in the default order:

[cols="20%,20%,30%,30%", frame="all", options="header"]
|===
|Route
|Title
|Mount Point
|Entity Kind

|`/`
|Overview
|`entity.page.overview`
|Any

|`/topology`
|Topology
|`entity.page.topology`
|Any

|`/issues`
|Issues
|`entity.page.issues`
|Any

|`/pr`
|CPull/Merge Requests
|`entity.page.pull-requests`
|Any

|`/ci`
|CI
|`entity.page.ci``
|VAny

|`/cd`
|CD
|`entity.page.cd`
|Any

|`/kubernetes`
|Kubernetes
|`entity.page.kubernetes`
|Any

|`/image-registry`
|Image Registry
|`entity.page.image-registry`
|Any

|`/monitoring`
|Monitoring
|`entity.page.monitoring`
|Any

|`/lighthouse`
|Lighthouse
|`entity.page.lighthouse`
|Any

|`/api`
|Api
|`entity.page.api`
|kind: Service or kind: Component

|`/dependencies`
|Dependencies
|`entity.page.dependencies`
|kind: Component

|`/docs`
|Docs
|`entity.page.docs`
|Any

|`/definition`
|Definition
|`entity.page.definition`
|kind: API

|`/system`
|Diagram
|`entity.page.diagram`
|kind: System
|===

[NOTE]
====
Mount points within Catalog such as _`entity.page.*`_ render as tabs and become visible only if at least one plugin contributes to them, or if they can render static content.
====
