:_mod-docs-content-type: REFERENCE

[id="customizing-menu-items-in-the-sidebar-navigation_{context}"]
= Customizing menu items in the sidebar navigation

[role="_abstract"]
You can customize the order and parent-child relationships of plugin menu items in the main sidebar navigation by using the menu items configuration as shown in the following example:

[source,yaml,subs="+quotes"]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: __<plugin_path_or_url>__
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          my-plugin:
            menuItems:
              __<menu_item_name>__:
                icon: __<icon_name>__Icon
                title: __<plugin_name>__ Plugin Page
                priority: 10
                parent: favorites
                enabled: false
----

where:

`my-plugin`:: The plugin package name.
`__<menu_item_name>__`:: The unique name in the main sidebar navigation. Represents either a standalone menu item or a parent menu item.
`icon`:: Optional: The icon for the menu item, which refers to a {backstage} system icon. If you have already defined the icon in the `dynamicRoutes` configuration under `menuItem.icon`, you can omit it in the `menuItems` configuration.
`title`:: Optional: The display title of the menu item. If you have already defined the title in the `dynamicRoutes` configuration under `menuItem.text`, you can omit it in the `menuItems` configuration.
`priority`:: Optional: The order in which menu items appear. The default priority is `0`, which places the item at the bottom of the list.
`parent`:: Optional: Defines the parent menu item to nest the current item under.
`enabled`:: Optional: When you set this to `false`, you can remove a `menuItem` from the sidebar.

[IMPORTANT]
====
If `menu_item_name` represents a plugin menu item, the name must match the corresponding path in `dynamicRoutes`. For example, if `dynamicRoutes` defines `path: /my-plugin`, the `menu_item_name` must be `my-plugin`.
====

Handling simple paths::

* For simple paths such as `path: /my-plugin`, the `menu_item_name` should be `my-plugin`.

Handling Complex Paths::

* For complex paths such as `path: /metrics/users/info`, the `menu_item_name` should represent the full path in dot notation (for example `metrics.users.info`).
* Ignore trailing and leading slashes in paths as follows:
+
** For `path: /docs`, the `menu_item_name` is `docs`.
** For `path: /metrics/users`, the `menu_item_name` is `metrics.users`.

[NOTE]
====
{product} supports up to three levels of nested menu items.
====
