:_mod-docs-content-type: SNIPPET
. Download the plugin mirroring script by running the following command:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/mirror-plugins.sh
----

. Export the plugin catalog index and all referenced plugin OCI artifacts to disk by running the following command:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ bash mirror-plugins.sh \
  --plugin-index oci://registry.access.redhat.com/rhdh/plugin-catalog-index:{product-version} \
  --to-dir _<my_plugin_mirror_dir>_
----
+
where:
+
`_<my_plugin_mirror_dir>_`:: Enter the absolute path to a directory where you want to export the plugin artifacts, for example, `/home/user/rhdh-plugins-mirror`.
+
[NOTE]
====
The script can take several minutes to complete. It mirrors the catalog index image and all plugin OCI artifacts that the index references.
====

. Transfer the directory specified by the `--to-dir` option to your disconnected environment.

. From a machine in your disconnected environment that has access to the target mirror registry, import the plugin artifacts by running the following command:
+
[source,terminal,subs="+quotes"]
----
$ bash mirror-plugins.sh \
  --from-dir _<my_plugin_mirror_dir>_ \
  --to-registry _<target_registry>_
----
+
where:
+
`_<my_plugin_mirror_dir>_`:: Enter the path to the directory containing the exported plugin artifacts.
`_<target_registry>_`:: Enter the URL of the target mirror registry, for example, `registry.example.com`.
