// Module included in the following assemblies:
//
// * assemblies/assembly-about-software-catalogs.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-searching-and-filtering-software-catalogs_{context}"]
= Searching and filtering software catalogs

You can search and filter Software Catalogs by its *Kind* or by using the *Filter* field.

.Procedure

* In the `{my-app-config-file}` configuration file, modify the `catalog.rules` section to include a rule for templates, and configure the `catalog.locations` section to point to the template that you want to add, as shown in the following example:
+
[source,yaml]
----
# ...
catalog:
  rules:
    - allow: [Template] # <1>
  locations:
    - type: url # <2>
      target: https://<repository_url>/example-template.yaml # <3>
# ...
----
<1> To allow new templates to be added to the catalog, you must add a `Template` rule.
<2> If you are importing templates from a repository, such as GitHub or GitLab, use the `url` type.
<3> Specify the URL for the template.

.Verification

. Click the *Catalog* tab in the navigation panel.
. In the *Kind* drop-down menu, select *Template*.
. Confirm that your template is shown in the list of existing templates.
