:_mod-docs-content-type: PROCEDURE

[id="set-up-trust-for-certificate-authority_{context}"]
= Configure trust for corporate Certificate Authority in {product}

[role="_abstract"]
The best practice for configuring {product-very-short} to trust a certificate issued by your Certificate Authority (CA) is
to use the `NODE_EXTRA_CA_CERTS` environmental variable.

[NOTE]
====
The steps
to set up {product-very-short} to trust a CA may vary
depending on how your specific {product-very-short} deployment is configured.
The following instructions capture only the general outline of the procedure.
====

.Prerequisites
* You have a CA-issued certificate.


.Procedure
. Export the certificate from its source.
. Convert the certificate to `.pem` format.
+
[IMPORTANT]
====
The maximum of file paths in `.pem` format supported by `NODE_EXTRA_CA_CERTS` is *one*.
You cannot concatenate multiple file paths as values of the environment variable.
====
. Create a secret  containing the CA.
. Mount the secret into {product-very-short} environment. Follow the steps specific for your deployment method: Helm or Orchestrator.
. Set the `NODE_EXTRA_CA_CERTS` to point to the mount path of the secret.
+
[IMPORTANT]
====
You can only use the file path of the CA in this step.
Setting the CA directly as an environmental value is not supported.
====
//Add link!!!!!
. OPTIONAL: Set up {rhbk} metrics.



If you want to inject multiple CAs or certificates chains, you have to:
extract all certificates and certificate chains
convert them into .pem format
concatenate them into a single file
create a secret with the concatenated file
mount the secret
set  NODE_EXTRA_CA_CERTS to the .pem file mount path
