:_mod-docs-content-type: PROCEDURE

[id="install-kubernetes-frontend-plugin_{context}"]
= Install Kubernetes front-end plugin

[role="_abstract"]
Install the Kubernetes front-end plugin to add a *Kubernetes* tab to entity pages. Together with the Kubernetes back-end plugin, the 

[NOTE]
====
The Kubernetes front-end plugin is installed but disabled by default.
====

.Prerequisites
* You have installed and configured the Kubernetes back-end plugin.

.Procedure
. Enable the `./dynamic-plugins/dist/backstage-plugin-kubernetes` plugin by your `dynamic-plugins.yaml` with the following content:
+
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
    disabled: false
----
. Install the plugin in your {product-very-short} root directory with the following command:
+
[code,terminal]
----
yarn --cwd packages/app add @backstage/plugin-kubernetes
----
. In the `app-config.yaml` file, enable the associated entity-content:
+
[code,terminal]
----
app:
  extensions:
    - entity-content:kubernetes/kubernetes
----
+
[NOTE]
====
By default, the Kubernetes tab appears only for entities that have a `backstage.io/kubernetes-id` or `backstage.io/kubernetes-label-selector` annotation.
====
+
. (Optional) Define which additional entities should display the *Kubernetes* tab by adding a `config` block to the extension:
+
[code,terminal]
----
app:
extensions:
- entity-content:kubernetes/kubernetes:
config:
filter:
kind:
$in:
- component
- api
- resource
- system
----

.Verification
* Pages of entities with Kubernetes resources have a *Kubernetes* tab.

