---
# .htmltest.yml
# Defines htmltest configuration
# See: https://github.com/wjdp/htmltest
#
DirectoryPath: titles-generated/main
CheckDoctype: false
ExternalTimeout: 30
OutputDir: .cache/htmltest
IgnoreDirectoryMissingTrailingSlash: true
IgnoreSSLVerify: true
IgnoreURLs: # List URLS that are not published, false positives, websites refusing crawlers
  - https://docs.github.com/
