---
# .htmltest.yml
# Defines htmltest configuration
# See: https://github.com/wjdp/htmltest
#
DirectoryPath: titles-generated
CheckDoctype: false
ExternalTimeout: 60
OutputDir: .cache/htmltest
IgnoreDirectoryMissingTrailingSlash: true
IgnoreSSLVerify: true
IgnoreURLs: # List URLS that are not published, false positives, websites refusing crawlers
  # Unauthorized (403)
  - "^./pr-.*/index.html$"
  - "^index.html$"
  - http://creativecommons.org/licenses/by-sa/3.0/
  - https://developers.redhat.com
  - https://docs.github.com/
  - https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.9
  - https://entra.microsoft.com
  - https://npm.registry.redhat.com
  - https://npmjs.com/package/
  - https://openai.com/api/
  - https://platform.openai.com/docs/overview
