---
# .htmltest.yml
# Defines htmltest configuration
# See: https://github.com/wjdp/htmltest
#
DirectoryPath: titles-generated
CheckDoctype: false
ExternalTimeout: 60
OutputDir: .cache/htmltest
IgnoreDirectoryMissingTrailingSlash: true
IgnoreSSLVerify: true
IgnoreURLs: # List URLS that are not published, false positives, websites refusing crawlers
  # Unauthorized (403)
  - "^./main/index.html$"
  - "^./1.1.x/index.html$"
  - "^./1.2.x/index.html$"
  - "^./pr-.*/index.html$"
  - "^./release-1..*/index.html$"
  - "^./rhdh-1.0/index.html$"
  - "^./rhdh-1.1.x/index.html$"
  - "^index.html$"
  - "^pulls.html$"
  - http://creativecommons.org/licenses/by-sa/3.0/
  - https://developers.redhat.com
  - https://docs.github.com/
  - https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.9
  - https://entra.microsoft.com
  - https://github.com/redhat-developer/rhdh-chart/blob/release-1.9/charts/backstage/values.yaml
  - https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-github-org-transformer
  - https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-gitlab-org-transformer
  - https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-keycloak-org-transformer
  - https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-ldap-transformer
  - https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-msgraph-transformer
  - https://github.com/redhat-developer/rhdh-operator/blob/release-1.9/docs/dynamic-plugins.md#dynamic-plugins-dependency-management
  - https://github.com/redhat-developer/rhdh/blob/release-1.9/dynamic-plugins.default.yaml
  - https://grafana.com/docs/loki/latest/query/log_queries/#log-stream-selector
  - https://npm.registry.redhat.com
  - https://npmjs.com/package/
  - https://openai.com/api/
  - https://platform.openai.com/docs/overview
  - https://raw.githubusercontent.com/redhat-developer/rhdh/release-1.9/packages/app/public/learning-paths/data.json
