---
# .htmltest.yml
# Defines htmltest configuration
# See: https://github.com/wjdp/htmltest
#
DirectoryPath: titles-generated/main
CheckDoctype: false
ExternalTimeout: 30
OutputDir: .cache/htmltest
IgnoreDirectoryMissingTrailingSlash: true
IgnoreSSLVerify: true
IgnoreURLs: # List URLS that are not published, false positives, websites refusing crawlers
  # Unauthorized (403)
  - https://docs.redhat.com/en/documentation/red_hat_developer_hub
  - https://developers.redhat.com
  - https://docs.github.com/
  - https://entra.microsoft.com
  - https://openai.com/api/
  - https://platform.openai.com/docs/overview
