# .vale.ini
# Specifies Vale configuration
# See: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/installing-vale-cli/
#

# Download and search Vale styles in this directory:
StylesPath = ".vale-styles"

# Minimum alert level to display:
MinAlertLevel = suggestion

# Styles to download:
Packages = RedHat,https://github.com/jhradilek/asciidoctor-dita-vale/releases/latest/download/AsciiDocDITA.zip

Vocab = RHDH

# Display alerts on AsciiDoc files:
[*.adoc]
# Apply these styles:
BasedOnStyles = RedHat,DeveloperHub,AsciiDocDITA

# AsciiDocDITA rules (default level from .yml shown in comment):
AsciiDocDITA.AdmonitionTitle = warning # default: warning
AsciiDocDITA.AssemblyContents = warning # default: warning
AsciiDocDITA.AttributeReference = suggestion # default: suggestion
AsciiDocDITA.AuthorLine = warning # default: warning
AsciiDocDITA.BlockTitle = warning # default: warning
AsciiDocDITA.CalloutList = warning # default: warning
AsciiDocDITA.ConceptLink = warning # default: warning
AsciiDocDITA.ConditionalCode = suggestion # default: suggestion
AsciiDocDITA.ContentType = error # default: warning
AsciiDocDITA.DiscreteHeading = warning # default: warning
AsciiDocDITA.DocumentId = warning # default: warning
AsciiDocDITA.DocumentTitle = warning # default: warning
AsciiDocDITA.EntityReference = error # default: error
AsciiDocDITA.EquationFormula = warning # default: warning
AsciiDocDITA.ExampleBlock = error # default: error
AsciiDocDITA.IncludeDirective = suggestion # default: suggestion
AsciiDocDITA.LineBreak = warning # default: warning
AsciiDocDITA.MismatchedId = error # default: error
AsciiDocDITA.NestedSection = error # default: error
AsciiDocDITA.PageBreak = warning # default: warning
AsciiDocDITA.RelatedLinks = warning # default: warning
AsciiDocDITA.ShortDescription = warning # default: warning
AsciiDocDITA.SidebarBlock = warning # default: warning
AsciiDocDITA.TableFooter = warning # default: warning
AsciiDocDITA.TagDirective = suggestion # default: suggestion
AsciiDocDITA.TaskContents = warning # default: warning
AsciiDocDITA.TaskDuplicate = warning # default: warning
AsciiDocDITA.TaskExample = error # default: error
AsciiDocDITA.TaskInclude = warning # default: warning
AsciiDocDITA.TaskSection = error # default: error
AsciiDocDITA.TaskStep = warning # default: warning
AsciiDocDITA.TaskTitle = warning # default: warning
AsciiDocDITA.ThematicBreak = warning # default: warning
