# .vale.ini
# Specifies Vale configuration
# See: https://redhat-documentation.github.io/vale-at-red-hat/docs/main/user-guide/installing-vale-cli/
#

# Download and search Vale styles in this directory:
StylesPath = ".vale-styles"

# Minimum alert level to display:
MinAlertLevel = warning

# Styles to download:
Packages = RedHat,https://github.com/jhradilek/asciidoctor-dita-vale/releases/latest/download/AsciiDocDITA.zip

Vocab = RHDH

# Display alerts on AsciiDoc files:
[*.adoc]
# Apply these styles:
BasedOnStyles = AsciiDocDITA

# AsciiDocDITA rules (default level from .yml shown in comment):
AsciiDocDITA.AdmonitionTitle = error # default: warning
AsciiDocDITA.AssemblyContents = error # default: warning
AsciiDocDITA.AttributeReference = NO # default: suggestion
AsciiDocDITA.AuthorLine = error # default: warning
AsciiDocDITA.BlockTitle = error # default: warning
AsciiDocDITA.CalloutList = error # default: warning
AsciiDocDITA.ConceptLink = error # default: warning
AsciiDocDITA.ConditionalCode = suggestion # default: suggestion
AsciiDocDITA.ContentType = error # default: warning
AsciiDocDITA.DiscreteHeading = error # default: warning
AsciiDocDITA.DocumentId = error # default: warning
AsciiDocDITA.DocumentTitle = error # default: warning
AsciiDocDITA.EntityReference = error # default: error
AsciiDocDITA.EquationFormula = error # default: warning
AsciiDocDITA.ExampleBlock = error # default: error
AsciiDocDITA.IncludeDirective = NO # default: suggestion
AsciiDocDITA.LineBreak = error # default: warning
AsciiDocDITA.MismatchedId = error # default: error
AsciiDocDITA.NestedSection = error # default: error
AsciiDocDITA.PageBreak = error # default: warning
AsciiDocDITA.RelatedLinks = error # default: warning
AsciiDocDITA.ShortDescription = error # default: warning
AsciiDocDITA.SidebarBlock = error # default: warning
AsciiDocDITA.TableFooter = error # default: warning
AsciiDocDITA.TagDirective = error # default: suggestion
AsciiDocDITA.TaskContents = error # default: warning
AsciiDocDITA.TaskDuplicate = error # default: warning
AsciiDocDITA.TaskExample = error # default: error
AsciiDocDITA.TaskInclude = NO # default: warning
AsciiDocDITA.TaskSection = error # default: error
AsciiDocDITA.TaskStep = error # default: warning
AsciiDocDITA.TaskTitle = error # default: warning
AsciiDocDITA.ThematicBreak = error # default: warning

