:_mod-docs-content-type: CONCEPT

= Find software components to discover assets

[role="_abstract"]
To integrate with existing software, check ownership, or prevent duplicate development, use the Software Catalog in {product} ({product-very-short}). You can use this centralized inventory to discover assets without searching through many documentation sources or repositories.

By using the Software Catalog, you can achieve the following outcomes:

Reuse existing code::
Locate shared libraries and components to prevent duplication of effort.

Understand dependencies::
Visualize connections between services and API contracts.

Identify ownership::
Find the team or individual responsible for an asset to allow collaboration.

[NOTE]
====
Your administrator must grant specific permissions if you want to add the products you are working on to this catalog. Contact your administrator for more information.
====

[role="_additional-resources"]
== Additional resources

* {about-book-link}[{about-book-title}]
* {customizing-book-link}[{customizing-book-title}]
