[id="proc-create-plugin"]

= Creating a plugin for the {product}

You can create a plugin for the {product-short} application.

.Prerequisites

* {product} application is installed and running. For more information, see link:{LinkAdminGuide}({NameOfAdminGuide}).
* `yarn` command and associated dependencies are installed.

.Procedure

. In the terminal application, run the following command from the root of your {product-short} project:
+
--
[source,bash]
----
yarn new --select plugin
----

The previous command creates a new plugin based on the provided ID. The plugin is added to the {product-short} application automatically.
--

. If your {product-short} application is running, navigate to `http://localhost:3000/my-new-plugin` to access the default page of your new plugin.

. Optional: To access the plugin in isolation, run `yarn start` command in the plugin directory or using the `yarn workspace` command as follows:
+
--
[source,bash]
----
yarn workspace {pluginID} start # Also supports --check <1>
----

<1> ID of the new plugin such as `@janus-idp/my-new-plugin`

Accessing the plugin in isolation results in quicker iteration and startup times. This approach is specifically for local development, and you can find the necessary configuration in the plugin's `dev/` directory.
--
