[id='proc-add-custom-app-file-openshift_{context}']
= Adding a custom application configuration file to Red Hat OpenShift

To access the {product}, you must add a custom application configuration file to OpenShift. In OpenShift, you can use the following content as a base template to create a ConfigMap named `app-config-rhdh`:

[source]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
----

.Prerequisites

* You have created an account in Red Hat OpenShift.

.Procedure

. Navigate to OpenShift and select the *ConfigMaps* tab.
. Click *Create ConfigMap*.
+
*Create ConfigMap* page appears.
. Select the *YAML view* option in *Configure via* and make the changes to the file, if needed.
. Click *Create*.
. Go to the *Helm* tab.
+
The list of Helm Releases appears on the page.
. Click the three dots corresponding to a Helm release and select *Upgrade*.
. Use one of the following views to edit the Helm configuration:

** Using *Form view* 
+
.. Expand *Root Schema → Backstage chart schema → Backstage parameters → Extra app configuration files to inline into command arguments*. 
.. Click the *Add Extra app configuration files to inline into command arguments* link.
.. Enter the value in the following fields:
+
--
* *configMapRef*: `app-config-rhdh`
* *filename*: `app-config-rhdh.yaml`
--
.. Click *Upgrade*.

** Using *YAML view* 

.. Set the value of the following parameters:
+
--
* *upstream.backstage.extraAppConfig.configMapRef*: `app-config-rhdh`
* *upstream.backstage.extraAppConfig.filename*: `app-config-rhdh.yaml`
--
.. Click *Upgrade*.

