[id='proc-add-custom-app-file-openshift_{context}']
= Adding a custom application configuration file to Red Hat OpenShift

To access the {product}, you must a custom application configuration file to OpenShift. In OpenShift, you can use the following content as a base template to create ConfigMap named `app-config-rhdh`:

[source]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
----

.Prerequisites

* You have created an account in Red Hat OpenShift.

.Procedure

. Navigate to OpenShift and select the *ConfigMaps* tab.
. Click *Create ConfigMap*.
+
*Create ConfigMap* page appears.
. Select the *YAML view* option in *Configure via* and make the changes to the file, if needed.
. Click *Create*.
. Go to the *Helm* tab.
+
The list of Helm Releases appears on the page.
. Click the three dots of a Helm release and select *Upgrade*.
. Add the following values in *Root Schema -> Backstage Chart Schema ->  Backstage Parameters -> Extra App Configuration files to inline into command arguments*:
+
--
* *ConfigMapRef*: `app-config-rhdh`
* *filename*: `app-config-rhdh.yaml`
--
. Click *Upgrade*.




