[id='ref-additional-rhdh-customizations_{context}']
= Additional customizations in {product}

This section describes additional customization options that you can apply to the {product}.

Customizing tab tooltip::
+
--
To customize the tab tooltip, add the following content to your `app-config-rhdh.yaml` file:

[source,yaml]
----
app:
  title: My custom developer hub
----
--

Customizing branding of your {product-short} instance::
+
--
To customize the branding of your {product-short} instance, add the following content to your `app-config-rhdh.yaml` file:

[source,yaml]
----
app:
  branding:
    fullLogo: ${BASE64_EMBEDDED_FULL_LOGO}
    iconLogo: ${BASE64_EMBEDDED_ICON_LOGO}
    theme:
      light:
        primaryColor: ${PRIMARY_LIGHT_COLOR}
        headerColor1: ${HEADER_LIGHT_COLOR_1}
        headerColor2: ${HEADER_LIGHT_COLOR_2}
        navigationIndicatorColor: ${NAV_INDICATOR_LIGHT_COLOR}
      dark:
        primaryColor: ${PRIMARY_DARK_COLOR}
        headerColor1: ${HEADER_DARK_COLOR_1}
        headerColor2: ${HEADER_DARK_COLOR_2}
        navigationIndicatorColor: ${NAV_INDICATOR_DARK_COLOR}
----

In the previous configuration,

* `fullLogo` is the logo on the expanded (pinned) sidebar and expects a base64 encoded image.
* `iconLogo` is the logo on the collapsed (unpinned) sidebar and expects a base64 encoded image.
* `primaryColor` is the color of links and most buttons to the inputted color. The supported formats for `primaryColor` include: 
** `#nnn`
** `#nnnnnn`
** `rgb()`
** `rgba()`
** `hsl()`
** `hsla()`
** `color()`
* `headerColor1` (left-side of the banner) and `headerColor2` (right-side of the banner) changes the color of the header banner of each page, as well as the banner for template cards. The supported formats for `headerColor1` and `headerColor2` include:
** `#nnn`
** `#nnnnnn`
** `rgb()`
** `rgba()`
** `hsl()`
** `hsla()`
** `color()`
* `navigationIndicatorColor` changes the color of the indicator in the sidebar that indicates which tab you are on. The supported formats for `navigationIndicatorColor` include:
** `#nnn`
** `#nnnnnn`
** `rgb()`
** `rgba()`
** `hsl()`
** `hsla()`
** `color()`
--