[id="disabling-telemetry-data-collection_{context}"]
= Disabling telemetry data collection in {product-very-short}

To disable telemetry data collection, you must disable the `analytics-provider-segment` plugin either using the Helm Chart or the {product} Operator configuration. 

[NOTE]
====
If the `analytics-provider-segment` plugin is already present in your dynamic plugins configuration, set the value of the `plugins.disabled` parameter to `true` to disable telemetry data collection.
====

.Procedure

. Disable the `analytics-provider-segment` plugin by using one of the following options:
+
.Using Helm Chart

* Add the following YAML code in your Helm configuration file:
+
[source,yaml]
----
# ...
global:
  dynamic:
    plugins:
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-analytics-provider-segment'
        disabled: true
# ...
----

+
.Using the Operator

.. Perform one of the following steps:
+
* If you have created the `dynamic-plugins-rhdh` ConfigMap file, add the `analytics-provider-segment` plugin to the list of plugins and set its `plugins.disabled` parameter to `true`.
+
* If you have not created the ConfigMap file, create it with the following YAML code:
+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-analytics-provider-segment'
        disabled: true
----

.. Set the value of the `dynamicPluginsConfigMapName` parameter to the name of the ConfigMap file in your `Backstage` custom resource:
+
[source,yaml]
----
# ...
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
# ...
----

. Save the configuration changes.

