:_mod-docs-content-type: PROCEDURE

[id="configure-audit-logs-for-rhdh-on-ocp_{context}"]
= Configure audit logs for {product-short} on {ocp-short}

[role="_abstract"]
Configure logging deployment, log collector, and log forwarding components to enable audit logging for {product-short} on {ocp-short}.

.Prerequisites
* You have access to the {ocp-short} web console.
* You have `cluster-admin` privileges.

.Procedure

. Configure the logging deployment, including both the CPU and memory limits for each logging component.
+
For more information, see {ocp-docs-link}/html-single/logging/index#cluster-logging-memory[{ocp-brand-name} - Configuring your Logging deployment].

. To configure the logging collector, configure the `spec.collection` stanza in the `ClusterLogging` custom resource (CR) to use a supported modification to the log collector and collect logs from `STDOUT`.
+
For more information, see {ocp-docs-link}/html-single/logging/index#cluster-logging-collector[{ocp-brand-name} - Configuring the logging collector].

. To configure log forwarding, send logs to specific endpoints inside and outside your {ocp-short} cluster by specifying a combination of outputs and pipelines in a `ClusterLogForwarder` CR.
+
For more information, see {ocp-docs-link}/html-single/logging/index#cluster-logging-json-log-forwarding_cluster-logging-enabling-json-logging[{ocp-brand-name} - Enabling JSON log forwarding] and {ocp-docs-link}/html-single/logging/index#configuring-log-forwarding[{ocp-brand-name} - Configuring log forwarding].
