[id='proc-customizing-the-learning-paths-by-using-a-customization-service_{context}']
= Customizing the Learning Paths by using a customization service

For advanced scenarios, you can host your {product} customization service to provide data to all configurable {product-short} pages, such as the Learning Paths.
You can even use a different service for each page.

.Procedure
. Deploy your {product-short} customization service on the same {ocp-short} cluster as your {product-short} instance.
You can find an example at link:https://github.com/redhat-developer/red-hat-developer-hub-customization-provider[`red-hat-developer-hub-customization-provider`], that provides the same data as default {product-short} data.
The customization service provides a Learning Paths data URL such as: `pass:c,a,q[http://_<rhdh-customization-provider>_/learning-paths]`.

. Configure the  {product-short} proxy to use your dedicated service to provide the Learning Path data, add the following to the {configuring-book-link}[`{my-app-config-file}` file]:
+
[source,yaml,subs='+quotes']
----
proxy:
  endpoints:
    '/developer-hub/learning-paths':
      target: _<learning_path_data_url>_
      changeOrigin: true
      qsecure: true # <1>
----
<1> Change to "false" in case of using self hosted cluster with a self-signed certificate
