:_mod-docs-content-type: CONCEPT

[id="air-gapped-environment_{context}"]
= Air-gapped environment

[role="_abstract"]
An air-gapped environment ensures security by physically segregating systems from external networks.

Also known as an air-gapped network or isolated network, this isolation prevents unauthorized access, data transfer, or communication between the air-gapped system and external sources.

You can install the {product} in an air-gapped environment to ensure security and meet specific regulatory requirements.

Air-gapped environments fall into two types:

Fully disconnected environment:: In environments without internet access, a fully disconnected installation ensures that {product} can run reliably without external dependencies. This method requires mirroring images to disk and transferring them manually to the air-gapped environment.

Partially disconnected environment:: In a partially disconnected environment, the cluster cannot access external registries, for example, `registry.redhat.io`, but it can access an internal mirror registry. This method requires direct access to an internal mirror registry from the cluster.
