:_mod-docs-content-type: CONCEPT

= Installing and using Ansible plug-ins for {product}

Ansible plug-ins for {product} deliver an Ansible-specific portal experience with curated learning paths,
push-button content creation, integrated development tools, and other opinionated resources.

[IMPORTANT]
====
The Ansible plug-ins are a Technology Preview feature only.

Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.



====

.Additional resources
* link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
* link:https://access.redhat.com/policy/developerhub-support-policy[Red Hat Developer Support Policy]
* {ansible-automation-platform-docs-link}/html-single/installing_ansible_plug-ins_for_red_hat_developer_hub/index[Installing Ansible plug-ins for {product}]
* {ansible-automation-platform-docs-link}/html-single/using_ansible_plug-ins_for_red_hat_developer_hub/index[Using Ansible plug-ins for {product}]

