:_mod-docs-content-type: CONCEPT

[id="con-preinstalled-dynamic-plugins"]
= Preinstalled dynamic plugins

{product} is preinstalled with a selection of dynamic plugins.
//For a complete list of dynamic plugins that are included in this release of {product-short}, see the xref:rhdh-supported-plugins[Dynamic plugins support matrix].

The following preinstalled dynamic plugins are enabled by default:

* `@red-hat-developer-hub/backstage-plugin-analytics-module-adoption-insights`
* `@red-hat-developer-hub/backstage-plugin-adoption-insights`
* `@red-hat-developer-hub/backstage-plugin-adoption-insights-backend`
* `@backstage-community/plugin-analytics-provider-segment`
* `@backstage/plugin-techdocs`
* `@backstage/plugin-techdocs-module-addons-contrib`
* `@backstage/plugin-techdocs-backend`
* `@backstage/plugin-events-backend-module-github`
* `@red-hat-developer-hub/backstage-plugin-extensions`
* `@red-hat-developer-hub/backstage-plugin-extensions-backend`
* `@red-hat-developer-hub/backstage-plugin-catalog-backend-module-extensions`
* `@red-hat-developer-hub/backstage-plugin-global-floating-action-button`
* `@red-hat-developer-hub/backstage-plugin-global-header`
* `@red-hat-developer-hub/backstage-plugin-dynamic-home-page`
* `@red-hat-developer-hub/backstage-plugin-scaffolder-backend-module-orchestrator`
* `@red-hat-developer-hub/backstage-plugin-orchestrator`
* `@red-hat-developer-hub/backstage-plugin-orchestrator-form-widgets`
* `@red-hat-developer-hub/backstage-plugin-orchestrator-backend`
* `@red-hat-developer-hub/backstage-plugin-orchestrator-backend-module-loki`
* `@red-hat-developer-hub/backstage-plugin-quickstart`
* `@backstage-community/plugin-scaffolder-backend-module-regex`

The dynamic plugins that require custom configuration are disabled by default.

Upon application startup, for each plugin that is disabled by default, the `install-dynamic-plugins init container` within the {product-short} pod log displays a message similar to the following:

[source,yaml]
----
======= Skipping disabled dynamic plugin ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
----

To enable this plugin, add a package with the same name to the Helm chart and change the value in the `disabled` field to ‘false’. For example:

[source,java]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        disabled: false
----

[NOTE]
The default configuration for a plugin is extracted from the `dynamic-plugins.default.yaml` file, however, you can use a `pluginConfig` entry to override the default configuration.
