[id="con-dynamic-plugin-cache_{context}"]

= Using the dynamic plugins cache
The dynamic plugins cache in {product} ({product-very-short}) enhances the installation process and reduces platform boot time by storing previously installed plugins. If the configuration remains unchanged, this feature prevents the need to re-download plugins on subsequent boots.

When you enable dynamic plugins cache:

* The system calculates a checksum of each plugin's YAML configuration (excluding `pluginConfig`).
* The checksum is stored in a file named `dynamic-plugin-config.hash` within the plugin's directory.
* During boot, if a plugin's package reference matches the previous installation and the checksum is unchanged, the download is skipped.
* Plugins that are disabled since the previous boot are automatically removed.

== Enabling the dynamic plugins cache
To enable the dynamic plugins cache in {product-very-short}, the plugins directory `dynamic-plugins-root` must be a persistent volume. 

=== Creating a PVC for Dynamic Plugins Cache by using the Operator
For operator-based installations, you must manually create the persistent volume claim (PVC) by replacing the default `dynamic-plugins-root` volume with a PVC named `dynamic-plugins-root`. 

.Procedure 

. Create the persistent volume definition and save it to a file, for example `pvc.yaml`. For example:
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-plugins-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
----

[NOTE]
====
This example uses `ReadWriteOnce` as the access mode which prevents multiple replicas from sharing the PVC across different nodes. 

To run multiple replicas on different nodes, depending on your storage driver, you must use an access mode such as `ReadWriteMany`.
====

. To apply this PVC to your cluster, run the following command:
[source,terminal]
----
oc apply -f pvc.yaml
----

. Replace the default `dynamic-plugins-root` volume with a PVC named `dynamic-plugins-root`. For example:
+
[source,yaml]
----
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: developer-hub
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
----

[NOTE]
To avoid adding a new volume, you must use the `$patch: replace` directive.

=== Creating a PVC for Dynamic Plugins Cache using the Helm Chart
For Helm Chart installations, if you require the dynamic plugin cache to persist across pod restarts, you must create a PersistentVolumeClaim (PVC) and configure the Helm Chart to use it.
.Procedure 

. Create the persistent volume definition. For example: 
+
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-plugins-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
----

[NOTE]
====
This example uses `ReadWriteOnce` as the access mode which prevents multiple replicas from sharing the PVC across different nodes. 

To run multiple replicas on different nodes, depending on your storage driver, you must use an access mode such as `ReadWriteMany`.
====

. To apply this PVC to your cluster, run the following command:
[source,terminal]
----
oc apply -f pvc.yaml
----
. Configure the Helm chart to use the PVC. For example:
+
[source,yaml]
----
extraVolumes:
  - name: dynamic-plugins-root
    persistentVolumeClaim:
      claimName: dynamic-plugins-root
  - name: dynamic-plugins
    configMap:
      defaultMode: 420
      name: '{{ printf "%s-dynamic-plugins" .Release.Name }}'
      optional: true
  - name: dynamic-plugins-npmrc
    secret:
      defaultMode: 420
      optional: true
      secretName: '{{ printf "%s-dynamic-plugins-npmrc" .Release.Name }}'
  - name: dynamic-plugins-registry-auth
    secret:
      defaultMode: 416
      optional: true
      secretName: '{{ printf "%s-dynamic-plugins-registry-auth" .Release.Name }}'
  - name: npmcacache
    emptyDir: {}
  - name: temp
    emptyDir: {}
----

[NOTE]
====
When you configure the Helm chart to use the PVC, you must also include the link:https://github.com/redhat-developer/rhdh-chart/blob/main/charts/backstage/values.yaml#L145-L181[`extraVolumes`] defined in the default Helm chart.
====

== Configuring the dynamic plugins cache
You can set the following optional dynamic plugin cache parameters:

* `forceDownload`: Set to `true` to force a reinstall of the plugin, bypassing the cache. Default is `false`. For example, modify your `dynamic-plugins.yaml` file as follows:
+
[source,yaml]
----
plugins:
  - disabled: false
    forceDownload: true
    package: 'oci://quay.io/example-org/example-plugin:v1.0.0!internal-backstage-plugin-example'
----
