= Installing and using Ansibe plug-ins for {product}

Ansible plug-ins for {product} deliver an Ansible-specific portal experience with curated learning paths,
push-button content creation, integrated development tools, and other opinionated resources.

[IMPORTANT]
====
The Ansible plug-ins are a Technology Preview feature only.

Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].

Additional detail on how Red Hat provides support for bundled community dynamic plugins is available on the https://access.redhat.com/policy/developerhub-support-policy[Red Hat Developer Support Policy] page.
====

== For administrators

To install and configure the Ansible plugins, see
link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/installing_ansible_plug-ins_for_red_hat_developer_hub/index[_Installing Ansible plug-ins for Red Hat Developer Hub_].

== For users

To use the Ansible plugins, see
link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.4/html/using_ansible_plug-ins_for_red_hat_developer_hub/index[_Using Ansible plug-ins for Red Hat Developer Hub_].

