[id="con-extensions-managing-plugins_{context}"]
= Managing plugins by using Extensions
* Users must have the new extensions permissions to access and manage plugin configurations.
In production environment
* Users will be notified that plugin installation is not permitted.
* In development environment 
** Admins can install a plugin using the default configuration preloaded in the editor, or modify the configuration before installing. Upon successful installation, users will be notified that a backend restart is required to complete the installation process.
** Once a plugin is installed, admins can access the Actions drop-down in the plugin’s side panel. Available actions include:
*** Editing the configuration used during installation
*** Disabling or enabling the plugin
*** After performing any of these actions, users will again be notified that a backend restart is required for the changes to take effect.

== RBAC permissions
When RBAC permission framework is enabled, for non-admin users to access Extensions UI, the role associated with your user should have the following permission policies associated with it. Add the following in your permission policies configuration file:
[source,yaml]
----
p, role:default/team_a, extensions-plugin, read, allow
p, role:default/team_a, extensions-plugin, create, allow
g, user:default/<login-id/user-name>, role:default/team_a

permission:
      enabled: true
      rbac:
        admin:
          users:
          - name: user:default/gerry-forde
        pluginsWithPermission:
        - catalog
        - scaffolder
        - permission
        - extensions
----

.Procedure
. Navigate to RBAC.
. Click *Create*.
