[id="con-dynamic-plugin-cache_{context}"]

= Dynamic plugins cache
The dynamic plugins cache feature in {product} ({product-very-short}) optimizes the installation process of dynamic plugins and reduces platform boot time. This feature caches previously installed plugins, eliminating the need to re-download them on subsequent boots if their configuration has not changed.

When you enable dynamic plugins cache, the feature works as follows:

* The system calculates a checksum of each plugin's YAML configuration (excluding `pluginConfig`).
* This checksum is stored in a file named `dynamic-plugin-config.hash` within the plugin's directory.
* During boot, if a plugin's package reference matches the previous installation and the checksum is unchanged, the download is skipped.
* Plugins that have been disabled since the previous boot are automatically removed.

== Enabling the dynamic plugins cache
To enable the dynamic plugins cache in RHDH, the plugins directory `dynamic-plugins-root` must be a persistent volume. 

For Helm chart installations, a persistent volume named `dynamic-plugins-root` is automatically created.

For operator-based installations, you must manually create the PersistentVolumeClaim (PVC) as follows:

[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-plugins-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: rhdh
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root
----

[NOTE]
Future versions of the RHDH operator are planned to automatically create the PVC.

== Configuring the dynamic plugins cache
You can set the following optional dynamic plugin cache parameters:

* `forceDownload`: Set to `true` to force a reinstall of the plugin, bypassing the cache. Default is `false`. For example, modify your `app-config.yaml` file as follows:
+
[source,yaml]
----
plugins:
  - disabled: false
    forceDownload: true
    package: 'oci://quay.io/example-org/example-plugin:v1.0.0!internal-backstage-plugin-example'
----