:_mod-docs-content-type: CONCEPT
[id="con-troubleshoot-why-a-dynamically-loaded-plugin-is-not-visible_{context}"]

= Troubleshoot why a dynamically loaded plugin is not visible

If you skip frontend wiring, the plugin is discovered but not loaded into the application frontend. As a result, the plugin features do not appear or function. This is expected because backend plugins are automatically discovered and loaded, but frontend plugins are only loaded based on the list defined in the `dynamicPlugins.frontend` configuration.

You can expect the following behavior when you skip frontend wiring:

Functionality is disabled:: The Backstage application does not know how to integrate the plugin exports.
Invisible components:: New pages, sidebar links, or custom cards are not rendered.
Unregistered APIs:: Custom utility APIs or API overrides provided by the plugin fail to register in the application API system, causing plugins or components to fail.
Unused assets:: Icons, translations, and themes are not registered or made available for use.