= Using the Dynamic Plugin Factory to convert plugins into dynamic plugins
You can automate the conversion and packaging of standard {product-custom-resource-type} plugins into {product-very-short} dynamic plugins by using the {product-very-short} Dynamic Plugin Factory tool.

[IMPORTANT] 
====
The Dynamic Plugin Factory is maintained as an open-source project by {company-name}, but is not supported or subject to any service level agreement (SLA).
====

The core function of the Dynamic Plugin Factory tool is to streamline the dynamic plugin build process, offering the following capabilities:

Source Code Handling:: Manages cloning, checking out, and applying custom patches to the plugin source.
Dependency Management:: Handles yarn installation and TypeScript compilation.
Packaging:: Uses the {product-very-short} CLI to build, export, and package the final dynamic plugin.
Deployment:: Offers an option to push the resulting container image to registries like Quay or OpenShift.

The Dynamic Plugin Factory tool provides a simplified, reproducible method for developers and platform engineers to create and test dynamic plugins using a pre-configured _dynamic plugin factory_ container and documentation, significantly easing migration and testing.

For more information, see link:https://github.com/redhat-developer/rhdh-dynamic-plugin-factory/blob/main/README.md[{product-very-short} Dynamic Plugin Factory].
