// Module included in the following assemblies:
//
// * assemblies/assembly-rhdh-installing-dynamic-plugins.adoc
// * assemblies/dynamic-plugins/assembly-rhdh-installing-dynamic-plugins.adoc

:_mod-docs-content-type: CONCEPT
[id="con-install-dynamic-plugin-helm_{context}"]
= Installing dynamic plugins using the Helm chart

You can deploy a {product-short} instance using a Helm chart, which is a flexible installation method. With the Helm chart, you can sideload dynamic plugins into your {product-short} instance without having to recompile your code or rebuild the container.

To install dynamic plugins in {product-short} using Helm, add the following `global.dynamic` parameters in your Helm chart:

* `plugins`: the dynamic plugins list intended for installation. By default, the list is empty. You can populate the plugins list with the following fields:
** `package`: a package specification for the dynamic plugin package that you want to install. You can use a package for either a local or an external dynamic plugin installation. For a local installation, use a path to the local folder containing the dynamic plugin. For an external installation, use a package specification from a public NPM repository.
** `integrity` (required for external packages): an integrity checksum in the form of `<alg>-<digest>` specific to the package. Supported algorithms include `sha256`, `sha384` and `sha512`.
** `pluginConfig`: an optional plugin-specific `{my-app-config-file}` YAML fragment. See plugin configuration for more information.
** `disabled`: disables the dynamic plugin if set to `true`. Default: `false`.
* `includes`: a list of YAML files utilizing the same syntax.

[NOTE]
====
The `plugins` list in the `includes` file is merged with the `plugins` list in the main Helm values. If a plugin package is mentioned in both `plugins` lists, the `plugins` fields in the main Helm values override the `plugins` fields in the `includes` file. The default configuration includes the `dynamic-plugins.default.yaml` file, which contains all of the dynamic plugins preinstalled in {product-short}, whether enabled or disabled by default.
====
