:_mod-docs-content-type: CONCEPT
[id="con-troubleshoot-why-a-dynamically-loaded-plugin-is-not-visible_{context}"]

= Troubleshoot why a dynamically loaded plugin is not visible

If you skip front-end wiring, the plugin is discovered but not loaded into the application front-end. As a result, the plugin features do not appear or function. This is expected because backend plugins are automatically discovered and loaded, but front-end plugins are only loaded based on the list defined in the `dynamicPlugins.front-end` configuration.

You can expect the following behavior when you skip front-end wiring:

Disabled functionality:: The {product-custom-resource-type} application is unable to integrate or use the plugin exports.
Invisible components:: New pages, sidebar links, or custom cards do not render in the application UI.
Unregistered APIs:: Custom utility APIs or API overrides provided by the plugin are not registered in the application API system, potentially causing plugins or components to fail.
Unused assets:: Icons, translations, and themes are not registered or made available for use.

[TIP]
====
Sometimes a plugin might not be visible even if there is front-end wiring, which indicates it is misconfigured. To troubleshoot this, check the *Console* tab in the _Developer Tools_ of your browser for specific error messages or warnings.
====