:_mod-docs-content-type: CONCEPT
[id="con-understand-why-wiring-is-required-for-plugin-deployment_{context}"]

= Understand why wiring is required for plugin deployment

Frontend wiring bridges the gap between the dynamically loaded plugin code and the structured components of the {product-short} application.

Frontend components need instructions on where to be registered in the application UI. The application does not automatically know where the UI components of a plugin must appear.

Wiring tells the application the following:

* "Add new pages and routes to the main application." (using `dynamicRoutes`)
* "Inject custom components into existing UI pages." (using `mountPoints`)
* "Customize the application with new icons or themes." (using `appIcons`)

Wiring configuration, typically located in `{my-app-config-file}` or `dynamic-plugins-config.yaml`, provides the application with the metadata (including the component names, paths, and integration points) needed to render and use the plugin features.