:_mod-docs-content-type: CONCEPT
[id="con-consequences-of-skipping-front-end wiring_{context}"]

= Consequences of skipping front-end wiring

If you skip front-end wiring, the plugin is discovered but not loaded into the application front-end. As a result, the plugin features do not appear or function. This behavior is expected because while back-end plug-ins are discovered and loaded automatically, the core application loads front-end plug-ins only based on the list defined in the `dynamicPlugins.front-end` configuration.

You can expect the following behavior when you skip front-end wiring:

Disabled functionality:: The {product-custom-resource-type} application cannot integrate or use the plugin exports.
Invisible components:: New pages, sidebar links, or custom cards do not render in the application UI.
Unregistered APIs:: Custom utility APIs or API overrides provided by the plugin are not registered in the application API system, which can cause plugins or components to fail.
Unused assets:: Icons, translations, and themes are not registered or available for use.

[TIP]
====
If a plugin is not visible even with front-end wiring, the plugin is likely misconfigured. Troubleshoot the issue by checking the *Console* tab in the _Developer Tools_ of your browser for specific error messages or warnings.
====