[id="con-preinstalled-dynamic-plugins"]

= Preinstalled dynamic plugins

{product} is preinstalled with a selection of dynamic plugins. For a complete list of dynamic plugins that are preinstalled in this release of {product-short}, see xref:rhdh-supported-plugins[Preinstalled dynamic plugin descriptions and details].

The following preinstalled dynamic plugins are enabled by default:

%%ENABLED_PLUGINS%%

The dynamic plugins that require custom configuration are disabled by default.

Upon application startup, for each plugin that is disabled by default, the `install-dynamic-plugins init container` within the {product-short} pod log displays a message similar to the following:

[source,yaml]
----
======= Skipping disabled dynamic plugin ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
----

To enable this plugin, add a package with the same name to the Helm chart and change the value in the `disabled` field to ‘false’. For example:

[source,java]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        disabled: false
----

[NOTE]
The default configuration for a plugin is extracted from the `dynamic-plugins.default.yaml`` file, however, you can use a `pluginConfig` entry to override the default configuration.
