:_mod-docs-content-type: PROCEDURE

[id="enabling-the-argo-cd-plugin_{context}"]
= Enabling the Argo CD plugin

The Argo CD plugin provides a visual overview of the application’s status, deployment details, commit message, author of the commit, container image promoted to environment and deployment history.

.Prerequisites

* Add Argo CD instance information to your `app-config.yaml` configmap as shown in the following example:

+
[source,yaml]
----
argocd:
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: argoInstance1
          url: https://argoInstance1.com
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}
        - name: argoInstance2
          url: https://argoInstance2.com
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}
----
+
[NOTE]
Avoid using a trailing slash in the `url`, as it might cause unexpected behavior.

* Add the following annotation to the entity’s `catalog-info.yaml` file to identify the Argo CD applications.

+
[source,yaml]
----
annotations:
  ...
  # The label that Argo CD uses to fetch all the applications. The format to be used is label.key=label.value. For example, rht-gitops.com/janus-argocd=quarkus-app.

  argocd/app-selector: '${ARGOCD_LABEL_SELECTOR}'
----

* (Optional) Add the following annotation to the entity’s `catalog-info.yaml` file to switch between Argo CD instances as shown in the following example:

+
[source,yaml]
----
 annotations:
   ...
    # The Argo CD instance name used in `app-config.yaml`.

    argocd/instance-name: '${ARGOCD_INSTANCE}'
----

+
[NOTE]
====
If you do not set this annotation, the Argo CD plugin defaults to the first Argo CD instance configured in `app-config.yaml`.
====

.Procedure

* Add the following to your dynamic-plugins ConfigMap to enable the Argo CD plugin.
+
[source,yaml]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/roadiehq-backstage-plugin-argo-cd-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-community-plugin-redhat-argocd
        disabled: false
----
