[id="proc-adding-custom-authentication-provider-settings"]

= Adding custom authentication provider settings

You can install new authentication providers from a dynamic plugin that either adds additional configuration support for an existing provider or adds a new authentication provider. These providers are listed in the user settings section under the *Authentication Providers* tab.

You can use the `providerSettings` configuration to add entries for an authentication provider from a dynamic plugin, as shown in the following example:

[source,yaml]
----
dynamicPlugins:
  frontend:
    <package_name>:
      providerSettings:
        - title: My Custom Auth Provider # <1>
          description: Sign in using My Custom Auth Provider # <2>
          provider: core.auth.my-custom-auth-provider # <3>
----
<1> Specify the title for the authentication provider shown above the user's profile image if available.
<2> Specify the description of the authentication provider.
<3> Specify the ID of the authentication provider as provided to the `createApiRef` API call. This value is used to look up the corresponding API factory for the authentication provider to connect the provider's Sign In/Sign Out button.