:_mod-docs-content-type: PROCEDURE

[id="proc-converting-a-custom-plugin-into-a-dynamic-plugin_{context}"]
= Convert a custom plugin into a dynamic plugin

.Procedure
// Do we need this step (TBD)
// . Build the plugin, as follows:
// +
// [source,terminal]
// --
// $ cd plugins/my-plugin
// $ yarn build
// --

. Use the {product-very-short} CLI to prepare the plugin you want to export. The following command uses the plugin files in the `dist` folder that was generated by the `yarn build:all` command, and creates a new `dist-scalprum` folder that contains the necessary configuration and source files to enable dynamic loading:
+
[source,terminal]
--
cd plugins/simple-example
npx @red-hat-developer-hub/cli@latest plugin export
--
+
When this command packages a frontend plugin, it uses a default Scalprum configuration if one is not found. The Scalprum configuration is used to specify the plugin entry point and exports, and then to build a `dist-scalprum` folder that contains the dynamic plugin. The default Scalprum configuration is shown below, however a `scalprum` key can be added to the `package.json` file used by your plugin to set custom values, if necessary:
+
[source,json]
----
{
  "name": "internal.backstage-plugin-simple-example",
  "exposedModules": {
    "PluginRoot": "./src/index.ts"
  }
}
----
+
The following `plugin-manifest.json` file, which {product} uses to load the plugin, is located in the `dist-dynamic/dist-scalprum` folder:
+
[source,json]
----
{
  "name": "internal.backstage-plugin-simple-example",
  "version": "0.1.0",
  "extensions": [],
  "registrationMethod": "callback",
  "baseURL": "auto",
  "loadScripts": [
    "internal.backstage-plugin-simple-example.fd691533c03cb52c30ac.js"
  ],
  "buildHash": "fd691533c03cb52c30acbb5a80197c9d"
}
----

. Package the plugin into a container image and publish it to Quay.io.
+
[source,terminal]
--
export QUAY_USER=_<username>_
export PLUGIN_NAME=simple-example
export VERSION=$(cat package.json | jq .version -r)
npx @red-hat-developer-hub/cli@latest plugin package --tag quay.io/$QUAY_USER/$PLUGIN_NAME:$VERSION
--
. Push to Quay.io
+
[source,terminal]
--
podman push quay.io/$QUAY_USER/$PLUGIN_NAME:$VERSION
--

