[id="rhdh-operator-installing-a-plugin-using-extensions_{context}"]
= Installing a plugin by using Extensions for Operator`
You can install a plugin and configure it by using *Extensions*.

.Prerequisites
* you have setup RHDH with operator https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/release-1.6/install-rhdh-ocp/#assembly-install-rhdh-ocp-operator
* You have setup dynamic plugins
https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/installing_and_viewing_plugins_in_red_hat_developer_hub/rhdh-installing-rhdh-plugins_title-plugins-rhdh-about#proc-config-dynamic-plugins-rhdh-operator_rhdh-installing-rhdh-plugins
* You have setup PVC for dynamic-plugin-cache https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html/configuring_red_hat_developer_hub/using-the-dynamic-plugins-cache_running-behind-a-proxy#proc-creating-a-pvc-for-the-dynamic-plugin-cache-by-using-the-operator_running-behind-a-proxy
* You have enabled RBAC and you have a user with required permissions

.Procedure

. Manually create marketplace configuration file dynamic-plugins.marketplace.yaml in the PVC

.. Create marketplace configuration file dynamic-plugins.marketplace.yaml
+
[source,javascript]
----
echo -e "plugins:\n  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic\n    disabled: false\n    pluginConfig:\n      extensions:\n        installation:\n          enabled: true\n          saveToSingleFile:\n            file: /opt/app-root/src/dynamic-plugins-root/dynamic-plugins.marketplace.yaml" > dynamic-plugins.marketplace.yaml
----
.. Add the following configuration for the extensions ui package, to include the new mount point
+
[source,yaml]
----
- package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace
   disabled: false
   pluginConfig:
     dynamicPlugins:
       frontend:
         red-hat-developer-hub.backstage-plugin-marketplace:
           appIcons:
             - name: marketplace
               importName: MarketplaceIcon
           dynamicRoutes:
             - path: /extensions/catalog
               importName: DynamicMarketplacePluginRouter
           mountPoints:
             - mountPoint: application/provider
               importName: InstallationContextProvider
             - mountPoint: internal.plugins/tab
               importName: DynamicMarketplacePluginContent
               config:
                 path: marketplace
                 title: Catalog
----

.. Copy the file to cluster
+
To get rhdh <pod-name>:
[source,shell]
----
kubectl get pods -n <your-namespace>

kubectl cp ./dynamic-plugins.marketplace.yaml <your-namespace>/<pod-name>:/opt/app-root/src/dynamic-plugins-root/dynamic-plugins.marketplace.yaml
----

. Edit Backstage

Update your Backstage CR to update environment variable NODE_ENV since this feature is disabled for ‘production’:

apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
 name: developer-hub
 namespace: rhdh
spec:
 application:
   dynamicPluginsConfigMapName: dynamic-plugins-rhdh
   extraEnvs:
     envs:
       - name: NODE_ENV
         value: "development"
     secrets:
       - name: secrets-rhdh
   extraFiles:
     mountPath: /opt/app-root/src
   route:
     enabled: true
 database:
   enableLocalDb: true



3. Update your dynamic-plugins-rhdh to add marketplace config file and update marketplace backend config (dynamic-plugins-rhdh is from prereq 2, specified in your Backstage CR under  application.appConfig.dynamicPluginsConfigMapName)
+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
 name: dynamic-plugins-rhdh
 namespace: rhdh
data:
 dynamic-plugins.yaml: |
   includes:
     - dynamic-plugins.default.yaml
     - /dynamic-plugins-root/dynamic-plugins.marketplace.yaml
   plugins: []
----

.Verification
Enable some plugin via UI that is defaultly disabled, restart and see the change

