[id="proc-create-plugin-js-package_{context}"]
= Creating a JavaScript package with dynamic packages

[WARNING]
====
The derived dynamic plugin JavaScript packages must not be published to the public NPM registry. If you must publish to the NPM registry, use a private registry.
====

.Prerequisites
* You have exported a third-party dynamic plugin package.

.Procedure
. Navigate to the `dist-dynamic` directory.
. Run the following command to publish the package to your private NPM registry:
+
--
.Example command to publish a plugin package to an NPM registry
[source,terminal]
----
npm publish --registry <npm_registry_url>
----

[TIP]
====
You can add the following to your `package.json` file before running the `export` command:

.Example `package.json` file
[source,json]
----
{
  "publishConfig": {
    "registry": "<npm_registry_url>"
  }
}
----

If you modify `publishConfig` after exporting the dynamic plugin, re-run the `export-dynamic-plugin` command to ensure the correct configuration is included.
====
--

[role="_additional-resources"]
.Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.6/html-single/installing_and_viewing_plugins_in_red_hat_developer_hub/index#proc-export-third-party-plugins-rhdh_assembly-third-party-plugins[Exporting third-party plugins in {product}]