:_mod-docs-content-type: PROCEDURE

[id="proc-configuring-events-module-for-github"]

= Configuring Events Module for GitHub

Learn how to configure Events Module for use with the {product-very-short} GitHub Discovery feature,
and GitHub organization data.
This is a Developer Preview feature.

[IMPORTANT]
====
Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.

For more information about the support scope of Red Hat Developer Preview features, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

.Prerequisites
* For GitHub Discovery only: you have enabled {product-docs-link}/html-single/integrating_red_hat_developer_hub_with_github/index#enabling-github-repository-discovery[GitHub Discovery].
* For GitHub Organizational Data only: you have enabled {product-docs-link}/html-single/authentication_in_red_hat_developer_hub/index#enabling-user-authentication-with-github [Github Authentication with user ingestion].

.Procedure

. Add your GitHub integration credentials in the `app-config.yaml` file:
+
[source,yaml]
----
integrations:
github:
- host: github.com
token: ${GITHUB_PAT_TOKEN}
----
. Create a GitHub webhook with the following specifications:
** *For Github Discovery Events*: push, repository
** *For Github Organizational Data Events*: organization,team and membership
** *Content Type*: application/json
** *Payload URL*: https://<your_instance_name>/api/events/http/github

. Add the GitHub Events Module to your `dynamic-plugins.yaml` configuration file:
+
[source,yaml]
----
data:
dynamic-plugins.yaml: |
includes:
- dynamic-plugins.default.yaml
plugins:
- package: oci://redhat-developer/rhdh-plugin-export-overlays/backstage-plugin-events-backend-module-github:bs_1.42.5__0.4.3!backstage-plugin-events-backend-module-github
disabled: false
----

. Add the following HTTP events configuration to the `app-config.yaml` file:
+
[source,yaml]
----
events:
  modules:
    github:
      webhookSecret: ${GITHUB_WEBHOOK_SECRET}
----

.Verification
* Github Discovery:
** Trigger a GitHub push event by adding,
modifying or deleting the  `catalog-info.yaml` file in the repository where you set up your webhook.
A record of this event should appear in the pod logs of your {product-very-short} instance.
+
Example of a log with changes to `catalog-info.yaml` file::
[source,code]
----
{"level":"\u001b[32minfo\u001b[39m","message":"Processed Github push event: added 0 - removed 0 - modified 1","plugin":"catalog","service":"backstage","span_id":"47534b96c4afc654","target":"github-provider:providerId","timestamp":"2025-06-15 21:33:14","trace_flags":"01","trace_id":"ecc782deb86aed2027da0ae6b1999e5c"}
----


