= Installation
The Topology plugin enables you to visualize the workloads such as Deployment, Job, Daemonset, Statefulset, CronJob, Pods and Virtual Machines powering any service on your Kubernetes cluster.

.Prerequisites
* You have installed and configured the @backstage/plugin-kubernetes-backend dynamic plugins.
* You have configured the Kubernetes plugin to connect to the cluster using a ServiceAccount.
* The `ClusterRole` must be granted to ServiceAccount accessing the cluster.
[NOTE]
If you have the {product-short} Kubernetes plugin configured, then the `ClusterRole` is already granted.

.Procedure
* The Topology plugin is pre-loaded in {product-short} with basic configuration properties. To enable it, set the disabled property to false as follows:
+
.`{my-app-config-file}` fragment
[source,yaml,subs="+attributes"]
----
auth:
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-community-plugin-topology
        disabled: false
----
