[id="proc-create-plugin-js-package_{context}"]
= Creating a JavaScript package with dynamic packages

[WARNING]
====
The derived dynamic plugin JavaScript packages must not be published to the public NPM registry. If you must publish to the NPM registry, use a private registry.
====

.Prerequisites
* You have exported a third-party dynamic plugin package. For more information, see xref:proc-export-third-party-plugins-rhdh_assembly-third-party-plugins[].

.Procedure
. Navigate to the `dist-dynamic` directory.
. Run the following command to publish the package to your private NPM registry:
+
--
.Example command to publish a plugin package to an NPM registry
[source,bash]
----
npm publish --registry <npm_registry_url>
----

[TIP]
====
You can add the following to your `package.json` file before running the `export` command:

.Example `package.json` file
[source,json]
----
{
  "publishConfig": {
    "registry": "<npm_registry_url>"
  }
}
----

If you modify the `publishConfig` after exporting the dynamic plugin, re-run the `export-dynamic-plugin` command to ensure the correct configuration is included.
====
--