[id="proc-extending-internal-icon-catalog"]

= Extending internal icon catalog

You can use the internal catalog to fetch icons for configured routes with sidebar navigation menu entry.

.Procedure
Add a custom icon to the internal icon catalog for use in a plugin's menu item by using the `appIcons` configuration as shown in the following example:

[source,yaml]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: <plugin_path_or_url>
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          my-plugin:  # <1>
            appIcons:
              - name: fooIcon # <2>
                module: CustomModule # <3>
                importName: FooIcon # <4>
----
<1> Specify the plugin package name.
<2> Specify a name for the icon catalog
<3> Optional: Specify the set of assets you want to access within the plugin. By default, the system uses the `PluginRoot` module if none is specified.
<4> Optional: Specify the actual component name to be rendered as a standalone page. If not specified, the system uses the `default` export.

[NOTE]
====
The `package_name` key under `dynamicPlugins.frontend` **must match** the `scalprum.name` value in your plugin's `package.json`. This ensures your dynamic plugin loads correctly during runtime.
====