[id="proc-extensions-enabling-plugins-installation_{context}"]
= Configuring {product-very-short} to install plugins by using Extensions

When you install a plugin using Extensions UI, the configuration that you use is saved to a `dynamic-plugins.marketplace.yaml` file within the `dynamic-plugins-root` persistent volume. This ensures the configuration is available when you restart the application, allowing you to edit or re-enable the plugin.

You must create a persistent volume claim (PVC) to ensure that the cache persists when you restart the {product-very-short} application. For more information about using the dynamic plugins cache, see link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html-single/configuring_red_hat_developer_hub/index#using-the-dynamic-plugins-cache_running-behind-a-proxy[Using the dynamic plugins cache].

.Prequisites
* You have created a persistent volume claim (PVC) for the dynamic plugins cache with the name *dynamic-plugins-root*.
* You have installed Red Hat Developer Hub using the Helm chart.
* You have installed the OpenShift CLI (`oc`).

.Procedure
. Create the marketplace configuration file and save it as `dynamic-plugins.marketplace.yaml`. For example:
+
[source,yaml]
----
includes:
  - dynamic-plugins.default.yaml

plugins: 
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace
    disabled: false
    pluginConfig:
      dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-marketplace:
                appIcons:
                - name: marketplace
                    importName: MarketplaceIcon
                dynamicRoutes:
                - path: /extensions/catalog
                    importName: DynamicMarketplacePluginRouter
                mountPoints:
                - mountPoint: application/provider
                    importName: InstallationContextProvider
                - mountPoint: internal.plugins/tab
                    importName: DynamicMarketplacePluginContent
                    config:
                    path: marketplace
                    title: Catalog
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-marketplace-backend-dynamic
    disabled: false
    pluginConfig:
      extensions:
        installation:
          enabled: true
          saveToSingleFile:
            file: /opt/app-root/src/dynamic-plugins-root/dynamic-plugins.marketplace.yaml
----
. Copy the file to your cluster by running the following commands:
+
[source,yaml]
----
oc get pods -n <your-namespace>

oc cp ./dynamic-plugins.marketplace.yaml <your-namespace>/<pod-name>:/opt/app-root/src/dynamic-plugins-root/dynamic-plugins.marketplace.yaml
----
. Upgrade the Helm release to use this file and update environment variable to development:
+
[source,yaml]
----
global:
 auth:
   backend:
     enabled: true
 clusterRouterBase: apps.rosa.iuosa-vcqyd-ek4.jryo.p3.openshiftapps.com
 dynamic:
   includes:
     - dynamic-plugins.default.yaml
     - /dynamic-plugins-root/dynamic-plugins.marketplace.yaml
upstream:
 backstage:
   extraEnvVars:
     - name: NODE_ENV
       value: development
----
. Click *Upgrade*