[id="proc-defining-dynamic-routes"]

= Defining dynamic routes for new plugin pages

.Procedure
. Define each route by specifying a unique `path` and, if needed, an `importName` if it is different from the `default` export.
. Expose additional routes in a dynamic plugin by configuring `dynamicRoutes` as shown in the following example:

[source,yaml]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: <plugin_path_or_url>
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          my-plugin: # <1>
            dynamicRoutes:
              - path: /my-plugin # <2>
                module: CustomModule # <3>
                importName: FooPluginPage # <4>
                menuItem: # <5>
                  icon: fooIcon
                  text: Foo Plugin Page
                  enabled: false
                config: # <6>
                  props: ...
----
<1> Specify the plugin package name.
<2> Specify the unique path in the application. The path cannot override existing routes except the `/` home route. You can replace the main home page using the dynamic plugins mechanism.
<3> Optional: Specify the set of assets you want to access within the plugin. By default, the system uses the `PluginRoot` module if none is specified.
<4> Optional: Specify the actual component name as a standalone page. If not specified, the system uses the `default` export.
<5> `menuItem` - Allows you to extend the main sidebar navigation and point to a new route. The `menuItem` accepts the following properties:
* `text`: The label shown to the user
* `icon`: The Backstage system icon name.
* `enabled`: Optional: Allows the user to remove a menuItem from the sidebar when it is set to false.
* `importName`: Specifies the optional name of an exported `SidebarItem` component.
<6> Optional:  Passes `props` to a custom sidebar item
+
To configure a custom `SidebarItem` to enhance experiences such as notification badges, ensure the component accepts the following properties:

[source,yaml]
----
export type MySidebarItemProps = {
  to: string; // supplied by the sidebar during rendering, this will be the path configured for the dynamicRoute
};
----

.Example specifying a custom `SidebarItem` component:
[source,yaml]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: <plugin_path_or_url>
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          my-dynamic-plugin-package-name:
            dynamicRoutes:
              - importName: CustomPage
                menuItem:
                  config:
                    props:
                      text: Click Me!
                  importName: SimpleSidebarItem
                path: /custom_page
----