[id="enabling-users-to-use-the-topology-plugin"]
= Enabling users to use the Topology plugin

The Topology plugin is defining additional permissions. When link:{authorization-book-url}[{authorization-book-title}] is enabled, to enable users to use the Topology plugin, grant them:

* The `topology.view.read` `read` permission to view the Topology panel.
* The `kubernetes.proxy` `use` permission to view the pod logs.
* The `catalog-entity` `read` permission to view the {product} software catalog items.

.Prerequisites
* You are link:{authorization-book-url}#managing-authorizations-by-using-external-files[managing {authorization-book-title} by using external files].

.Procedure
* Add the following permission policies to your `rbac-policy.csv` file to create a `topology-viewer` role that has access to the Topology plugin features, and add the role to the users requiring this authorization:
+
[source]
----
g, user:default/<YOUR_USERNAME>, role:default/topology-viewer
p, role:default/topology-viewer, topology.view.read, read, allow <1>
p, role:default/topology-viewer, kubernetes.proxy, use, allow <2>
p, role:default/topology-viewer, catalog-entity, read, allow <3>
----
<1> Grants the user the ability to see the Topology panel. 
<2> Grants the user the ability to view the pod logs. 
<3> Grants the user the ability to see the catalog item.