[id="proc-export-third-party-plugins-rhdh_{context}"]
= Exporting third-party plugins in {product}

To use dynamic plugins in {product}, the plugins must be exported as separate packages. These packages contain the plugin code and dependencies, ready for dynamic plugin integration into {product-short}.

.Prerequisites
* The `@janus-idp/cli` package is installed. Use the latest version (`@latest` tag) for compatibility with the most recent features and fixes.
* The third-party plugin must have a valid package.json file in its root directory, containing all required metadata and dependencies.
* Node.js and NPM is installed and configured.
* You have access to a private NPM registry for publishing and distributing the exported plugin package.
* The third-party plugin is compatible with your {product} version. For more information, see link:https://github.com/janus-idp/backstage-showcase/blob/main/docs/dynamic-plugins/versions.md[Version compatibility matrix].

.Procedure
. Use the `package export-dynamic-plugin` command from the `@janus-idp/cli` package to export the plugin:
+
--
.Example command to export a third-party plugin
[source,bash]
----
npx @janus-idp/cli@latest package export-dynamic-plugin
----

Ensure that you execute the previous command in the root directory of the plugin's JavaScript package (containing `package.json` file).
--

. Located the exported package in the `dist-dynamic` sub-folder.
. Use `npm pack` or a private NPM registry to package or distribute the plugin. For more information, see xref:proc-package-third-party-dynamic-plugin_{context}[].
+
--
[IMPORTANT]
====
Ensure that you do not push derived dynamic plugin packages to a public NPM registry. Use a private NPM registry only.
====
--

