[id="proc-extensions-installing-plugins_{context}"]
= Installing plugins by using Extensions

[WARNING]
Installation and configuration of plugins by using Extensions will only work in development environments. This feature is not supported in production environments.

.Prequisites
* You have configured {product-very-short} to allow plugins installation from *Extensions*.
* You have configured RBAC to allow the current user to access to manage plugin configuration.

.Procedure
. Navigate to *Extensions*.
. Select a plugin to install.
. Click on the *Install* button.
// Screenshot
The code editor is displayed which displays the plugin default configuration.
. Update the plugin configuration, if necessary
. Click *Install*
. To view the plugins that require a restart, click *View plugins* in the alert message.
. Restart your {product-very-short} pod.

.Verification
. In {product-very-short}, refresh your *Extensions* browser view.
. Select the plugin that you have installed.
. The *Actions* button is displayed.
. Click on *Edit* to view the configuration that you used to install the plugin.





