[id="proc-customizing-theme"]

= Customizing {product} theme

You can customize {product-short} themes from a dynamic plugin with various configurations. The dynamic plugin exports a theme provider function with a signature of `({ children }: { children: ReactNode }): React.JSX.Element` as shown in the following example:

[source,yaml]
----
import { lightTheme } from './lightTheme';
import { darkTheme } from './darkTheme';
import { UnifiedThemeProvider } from '@backstage/theme';
export const lightThemeProvider = ({ children }: { children: ReactNode }) => (
  <UnifiedThemeProvider theme={lightTheme} children={children} />
);
export const darkThemeProvider = ({ children }: { children: ReactNode }) => (
  <UnifiedThemeProvider theme={darkTheme} children={children} />
);
----

You can declare the theme using the `themes` configuration as shown in the following example:

[source,yaml]
----
dynamicPlugins:
  frontend:
    my-plugin: # <1>
      themes:
        - id: light # <2>
          title: Light
          variant: light
          icon: someIconReference
          importName: lightThemeProvider
        - id: dark # <3>
          title: Dark # <4>
          variant: dark # <5>
          icon: someIconReference # <6>
          importName: darkThemeProvider # <7>
----
<1> Specify the plugin package name.
<2> Specify the theme, either `light` or `dark` to replace the default theme. Using 'light' overrides the app-provided light theme
<3> Specify the theme name displayed to the user on the *Settings* page. Using 'dark' overrides the app-provided dark theme
<4> Whether the theme is `light` or `dark`, can only be one of these values.
<5> A string reference to a system or app icon
<6> Specify the name of the exported theme provider function, the function signature should match `({ children }: { children: ReactNode }): React.JSX.Element`