:_mod-docs-content-type: PROCEDURE

[id="proc-converting-a-custom-plugin-into-a-dynamic-plugin_{context}"]
= Convert a custom plugin into a dynamic plugin

.Procedure
// Do we need this step (TBD)
// . Build the plugin, as follows:
// +
// [source,terminal]
// --
// $ cd plugins/my-plugin
// $ yarn build
// --

. Prepare the plugin to be exported by using the Red Hat Developer Hub CLI. The following command uses the plugin files in the `dist` folder that was generated by the `yarn build:all` command, and creates a new `dist-scalprum` folder that contains the necessary configuration and source files to enable dynamic loading:
+
[source,terminal]
--
cd plugins/my-plugin
npx @red-hat-developer-hub/cli@latest plugin export
--
+
.Output from npx command
[source,terminal]
--
Generating standard module federation assets in ../my-plugin/dist

Loaded config from app-config.yaml
[ Module Federation Manifest Plugin ] Manifest will use absolute path resolution via its host at runtime, reason: publicPath='auto'
  328.45 kB  dist/static/6860.df3f4204.chunk.js
  42.57 kB   dist/static/689.64ccc7dd.chunk.js
  ...
  229 B      dist/static/vendor.1441cdb1.js
  189 B      dist/static/main.1441cdb1.js
Packing main package to dist-dynamic/package.json
Customizing main package in dist-dynamic/package.json for dynamic loading
Generating dynamic frontend plugin assets in ../my-plugin/dist-dynamic/dist-scalprum
No scalprum config. Using default dynamic UI configuration:
{
  "name": "internal.backstage-plugin-my-plugin",
  "exposedModules": {
    "PluginRoot": "./src/index.ts"
  }
}
If you wish to change the defaults, add "scalprum" configuration to plugin "package.json" file, or use the '--scalprum-config' option to specify an external config.
[baseline-browser-mapping] The data in this module is over two months old.  To ensure accurate Baseline data, please update: `npm i baseline-browser-mapping@latest -D`
  328.58 kB  dist-scalprum/static/3940.d1284ecc.chunk.js
  42.83 kB   dist-scalprum/static/3144.b3d5f077.chunk.js
...
  270 B      dist-scalprum/static/react-syntax-highlighter_languages_highlight_vbscriptHtml.4befc8c9.chunk.js
  250 B      dist-scalprum/static/react-syntax-highlighter_languages_highlight_plaintext.22fa3943.chunk.js
Saving self-contained config schema in ../my-plugin/dist-dynamic/dist-scalprum/configSchema.json and ../my-plugin/dist-dynamic/dist/.config-schema.json
Filling supported-versions with 1.47.0.
--
+
When this command packages a frontend plugin, it uses a default Scalprum configuration if one is not found. The Scalprum configuration is used to specify the plugin entry point and exports, and then to build a `dist-scalprum` folder that contains the dynamic plugin. The default Scalprum configuration is shown below, however a `scalprum` key can be added to the `package.json` file used by your plugin to set custom values, if necessary:
+
[source,json]
----
{
  "name": "internal.backstage-plugin-my-plugin",
  "exposedModules": {
    "PluginRoot": "./src/index.ts"
  }
}
----
+
The following `plugin-manifest.json` file, which {product} uses to load the plugin, is located in the `dist-dynamic/dist-scalprum` folder:
+
[source,json]
----
{
  "name": "internal.backstage-plugin-my-plugin",
  "version": "0.1.0",
  "extensions": [],
  "registrationMethod": "callback",
  "baseURL": "auto",
  "loadScripts": [
    "internal.backstage-plugin-my-plugin.fd691533c03cb52c30ac.js"
  ],
  "buildHash": "fd691533c03cb52c30acbb5a80197c9d"
}
----

. Package the plugin into a container image and publish it to Quay.io
+
[source,terminal]
--
export QUAY_USER=_<username>_
export PLUGIN_NAME=my-plugin
export VERSION=$(cat package.json | jq .version -r)
npx @red-hat-developer-hub/cli@latest plugin package --tag quay.io/$QUAY_USER/$PLUGIN_NAME:$VERSION
--
+
.Output from `npx` command
[source,terminal]
--
  executing     podman --version ✔ 
Using existing 'dist-dynamic' directory at .
Copying 'dist-dynamic' to '/var/folders/hs/ykpwk4x95dxdvvv2sqf5xf1h0000gn/T/package-dynamic-pluginslvAdr5/internal-backstage-plugin-my-plugin
Writing plugin registry metadata to '/var/folders/hs/ykpwk4x95dxdvvv2sqf5xf1h0000gn/T/package-dynamic-pluginslvAdr5/index.json'
Creating image using podman
  executing     echo "from scratch
COPY . .
" | podman build --annotation io.backstage.dynamic-packages='W3siaW50ZXJuYWwtYmFja3N0YWdlLXBsdWdpbi1teS1wbHVnaW4iOnsibmFtZSI6IkBpbnRlcm5hbC9iYWNrc3RhZ2UtcGx1Z2luLW15LXBsdWdpbi1keW5hbWljIiwidmVyc2lvbiI6IjAuMS4wIiwiYmFja3N0YWdlIjp7InJvbGUiOiJmcm9udGVuZC1wbHVnaW4iLCJwbHVnaW5JZCI6Im15LXBsdWdpbiIsInN1cHBvcnRlZC12ZXJzaW9ucyI6IjEuNDcuMCJ9LCJsaWNlbnNlIjoiQXBhY2hlLTIuMCJ9fV0=' --platform linux/amd64 -t 'quay.io/gforde/my-plugin:0.1.0' -f - . ✔ 
Successfully built image quay.io/gforde/my-plugin:0.1.0 with following plugins:
  internal-backstage-plugin-my-plugin

Here is an example dynamic-plugins.yaml for these plugins: 

plugins:
  - package: oci://quay.io/gforde/my-plugin:0.1.0!internal-backstage-plugin-my-plugin
    disabled: false
--

. Push to Quay.io
+
[source,terminal]
--
podman push quay.io/$QUAY_USER/$PLUGIN_NAME:$VERSION
--

