[id="proc-export-third-party-plugins-rhdh_{context}"]
= Exporting third-party plugins in {product}

To use plugins in {product}, you can export plugins as derived dynamic plugin packages. These packages contain the plugin code and dependencies, ready for dynamic plugin integration into {product-short}.

.Prerequisites
* The `@janus-idp/cli` package is installed. Use the latest version (`@latest` tag) for compatibility with the most recent features and fixes.
* Node.js and NPM is installed and configured.
* The third-party plugin is compatible with your {product} version. For more information, see link:https://github.com/redhat-developer/rhdh/blob/main/docs/dynamic-plugins/versions.md[Version compatibility matrix].
* The third-party plugin must have a valid `package.json` file in its root directory, containing all required metadata and dependencies.
+
--
Backend plugins::
+
To ensure compatibility with the dynamic plugin support and enable their use as dynamic plugins, existing backend plugins must be compatible with the new Backstage backend system. Additionally, these plugins must be rebuilt using a dedicated CLI command.
+
The new Backstage backend system entry point (created using `createBackendPlugin()` or `createBackendModule()`)  must be exported as the default export from either the main package or an `alpha` package (if the plugin instance support is still provided using `alpha` APIs). This doesn't add any additional requirement on top of the standard plugin development guidelines of the plugin instance.
+
The dynamic export mechanism identifies private dependencies and sets the `bundleDependencies` field in the `package.json` file. This export mechanism ensures that the dynamic plugin package is published as a self-contained package, with its private dependencies bundled in a private `node_modules` folder.
+
Certain plugin dependencies require specific handling in the derived packages, such as:
+
* *Shared dependencies* are provided by the {product-very-short} application and listed as `peerDependencies` in `package.json` file, not bundled in the dynamic plugin package. For example, by default, all `@backstage` scoped packages are shared.
+
You can use the `--shared-package` flag to specify shared dependencies, that are expected to be provided by {product} application and not bundled in the dynamic plugin package.
+
To treat a `@backstage` package as private, use the negation prefix (`!`). For example, when a plugin depends on the package in `@backstage` that is not provided by the {product} application. 

* *Embedded dependencies* are bundled into the dynamic plugin package with their dependencies hoisted to the top level. By default, packages with `-node` or `-common` suffixes are embedded.
+
You can use the `--embed-package` flag to specify additional embedded packages. For example, packages from the same workspace that do not follow the default naming convention.
+
The following is an example of exporting a dynamic plugin with shared and embedded packages:
+
.Example dynamic plugin export with shared and embedded packages
[source,terminal]
----
npx @janus-idp/cli@latest export-dynamic-plugin --shared-package '!/@backstage/plugin-notifications/' --embed-package @backstage/plugin-notifications-backend
----
+
In the previous example:
+
* `@backstage/plugin-notifications` package is treated as a private dependency and is bundled in the dynamic plugin package, despite being in the `@backstage` scope.
+
* `@backstage/plugin-notifications-backend` package is marked as an embedded dependency and is bundled in the dynamic plugin package.

Front-end plugins::
+
Front-end plugins can use `scalprum` for configuration, which the CLI can generate automatically during the export process. The generated default configuration is logged when running the following command:
+
.Example command to log the default configuration
[source,terminal]
----
npx @janus-idp/cli@latest export-dynamic
----
+
The following is an example of default `scalprum` configuration:
+
.Default `scalprum` configuration
[source,json,subs="+attributes"]
----
"scalprum": {
  "name": "<package_name>",  // The Webpack container name matches the NPM package name, with "@" replaced by "." and "/" removed.
  "exposedModules": {
    "PluginRoot": "./src/index.ts"  // The default module name is "PluginRoot" and doesn't need explicit specification in the {my-app-config-file} file.
  }
}
----
+
You can add a `scalprum` section to the `package.json` file. For example:
+
.Example `scalprum` customization
[source,json]
----
"scalprum": {
  "name": "custom-package-name",
  "exposedModules": {
    "FooModuleName": "./src/foo.ts",
    "BarModuleName": "./src/bar.ts"
    // Define multiple modules here, with each exposed as a separate entry point in the Webpack container.
  }
}
----
+
Dynamic plugins might need adjustments for {product-short} needs, such as static JSX for mountpoints or dynamic routes. These changes are optional but might be incompatible with static plugins.
+
To include static JSX, define an additional export and use it as the dynamic plugin's `importName`. For example:
+
.Example static and dynamic plugin export
[source,tsx]
----
// For a static plugin
export const EntityTechdocsContent = () => {...}

// For a dynamic plugin
export const DynamicEntityTechdocsContent = {
  element: EntityTechdocsContent,
  staticJSXContent: (
    <TechDocsAddons>
      <ReportIssue />
    </TechDocsAddons>
  ),
};
----
--

.Procedure
* Use the `package export-dynamic-plugin` command from the `@janus-idp/cli` package to export the plugin:
+
--
.Example command to export a third-party plugin
[source,terminal]
----
npx @janus-idp/cli@latest package export-dynamic-plugin
----

Ensure that you execute the previous command in the root directory of the plugin's JavaScript package (containing `package.json` file).

The resulting derived package will be located in the `dist-dynamic` subfolder. The exported package name consists of the original plugin name with `-dynamic` appended.

[WARNING]
====
The derived dynamic plugin JavaScript packages must not be published to the public NPM registry. For more appropriate packaging options, see xref:assembly-package-publish-third-party-dynamic-plugin[]. If you must publish to the NPM registry, use a private registry.
====
--


