[id="proc-customizing-sidebar-menu-items"]

= Customizing menu items in the sidebar navigation

Customize the order and parent-child relationships of plugin menu items in the main sidebar navigation using the menu items configuration as shown in the following example:

[source,yaml]
----
# dynamic-plugins-config.yaml
plugins:
  - plugin: <plugin_path_or_url>
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          my-plugin: # <1>
            menuItems:
              <menu_item_name>: # <2>
                icon: fooIcon # <3>
                title: Foo Plugin Page # <4>
                priority: 10 # <5>
                parent: favorites # <6>
                enabled: false # <7>
----
<1> Specify the plugin package name.
<2> Specify the unique name in the main sidebar navigation (for example, either a standalone menu item or a parent menu item).
* Handling Complex Paths:
** For simple paths like `path: /my-plugin`, the `menu_item_name` should be `my-plugin`.
** For complex paths like `/metrics/users/info`, the `menu_item_name` should represent the full path in dot notation (for example `metrics.users.info`).
** Ignore trailing and leading slashes in paths as follows:
+
*** For `path: /docs`, the `menu_item_name` is `docs`.
*** For `path: /metrics/users`, the `menu_item_name` is `metrics.users`.
<3> Optional: Defines the icon for the menu item, which refers to a Backstage system icon.
<4> Optional: Specify the display title of the menu item.
<5> Optional: Defines the order in which menu items appear. The default priority is `0`.
<6> Optional: Defines the parent menu item to nest the current item under.
<7> Optional: Allows you to remove a `menuItem` from the sidebar when it is set to `false`.

[NOTE]
====
{product} supports up to 3 levels of nested menu items.
====