:_mod-docs-content-type: PROCEDURE

[id="proc-mirror-plugins-catalog-index-fully-disconnected_{context}"]
= Mirroring plugins from a catalog index to a fully disconnected environment

This two-phase process exports plugins to disk from a connected host, transfers them to a restricted network, then imports them to your internal registry.

.Procedure
. Download the mirroring script by running the following command:
+
[source,terminal,subs="+quotes,+attributes"]
----
$ curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/mirror-plugins.sh
----
. To export all plugins to a local directory, run the mirroring script by using the `bash` command with the appropriate set of options:
+
.Example
[source,terminal,subs="+quotes,+attributes"]
----
bash mirror-plugins.sh \
    --plugin-index oci://quay.io/rhdh/plugin-catalog-index:{product-version} \
    --to-dir _</tmp/rhdh-plugins>_
----
where:
`--to-dir _</tmp/rhdh-plugins>_`:: Enter the local directory path.

. To import and push the plugins to your internal registry, run the mirroring script by using the `bash` command with the appropriate set of options:
+
.Example
[source,terminal,subs="+quotes,+attributes"]
----
bash mirror-plugins.sh \
    --from-dir /tmp/rhdh-plugins \
    --to-registry _<my.registry.example.com>_
----
where:
`--from-dir _</tmp/rhdh-plugins>_`:: Enter the local directory path.
`--to-registry _<my.registry.example.com>_`:: Enter the URL for the target mirror registry where you want to mirror the catalog index.
