:_mod-docs-content-type: PROCEDURE

[id="proc-load-plugin-oci-image_{context}"]
= Loading a plugin packaged as an OCI image

.Prerequisites
* The {plugin-type-name} plugin is packaged as a dynamic plugin in an OCI image.
+
For more information about packaging a {plugin-type-name} plugin, see xref:assembly-package-publish-third-party-dynamic-plugin[].

.Procedure
. To retrieve plugins from an authenticated registry, complete the following steps:
.. Log in to the container image registry.
+
[source,yaml]
----
podman login <registry>
----
.. Verify the content of the `auth.json` file created after the login.
+
[source,yaml]
----
cat ${XDG_RUNTIME_DIR:-~/.config}/containers/auth.json
----
.. Create a secret file using the following example:
+
[source,yaml]
----
oc create secret generic _<secret_name>_ --from-file=auth.json=${XDG_RUNTIME_DIR:-~/.config}/containers/auth.json <1>
----
+
** For an Operator-based deployment, replace _<secret_name>_ with `dynamic-plugins-registry-auth`.
** For a Helm-based deployment, replace _<secret_name>_ with `<Helm_release_name>_-dynamic-plugins-registry-auth`.

. Define the plugin with the `oci://` prefix in the following format in `dynamic-plugins.yaml` file:
+
--
`oci://_<image_name>_:<tag>!_<plugin_name>_`

.Example configuration in `dynamic-plugins.yaml` file
[source,yaml]
----
plugins:
  - disabled: false
    package: oci://quay.io/example/image:v0.0.1!backstage-plugin-myplugin
----
--
. To perform an integrity check, use the image digest in place of the tag in the `dynamic-plugins.yaml` file as shown in the following example:
+
--
.Example configuration in `dynamic-plugins.yaml` file
[source,yaml]
----
plugins:
  - disabled: false
    package: oci://quay.io/example/image@sha256:28036abec4dffc714394e4ee433f16a59493db8017795049c831be41c02eb5dc!backstage-plugin-myplugin
----
--
. To apply the changes, restart the {product-very-short} application.
