:_mod-docs-content-type: PROCEDURE

[id="plugin-marketplace-and-filtering-plugins-using-badges_{context}"]
= Navigating the plugin marketplace and filtering plugins using badges

The plugin marketplace includes new indicators that enhance transparency. These changes provide clearer information about the status of each plugin, support level, and other relevant details, allowing you to make informed decisions when you select plugins. By understanding these visual cues and descriptive texts, you can quickly identify the maturity, support, and origin of each plugin.

The marketplace employs the following badges and tags to provide quick visual cues:

* *Certified*
* *Generally Available* (*GA*)
* *Community Plugin*
* *Tech Preview*
* *Dev Preview*
* *Custom Plugin*
+
[NOTE]
====
Hovering your mouse cursor over any badge or tag (such as *GA* or *Certified*) on either the plugin list or details page displays a helper text explanation clarifying its meaning and implications. Hovering over tags such as *tech preview*, or *dev preview* will display a helper text explanation clarifying its meaning and indicating if it is in a technical preview phase or a development preview phase.
====

The plugin details pages include the following fields for additional context: `author`, `tags`, `category`,`publisher`, and `support provider`. The update also changes the `version` text to `{product-custom-resource-type} compatibility version` to offer more precise compatibility information.

The following filter examples are available:

* To view only plugins that are *Generally Available* (*GA*), apply the *GA* filter.

* To find *Certified* plugins, apply the `Certified` in *Support type* filter.

* To explore plugins currently in *Tech Preview*, *Dev Preview*, or *Community Plugin* status, apply the corresponding filter.

.Procedure

. Navigate to the main plugin list page within the {product}.

. On the plugin list page, use the *Support type* filter to refine your plugin listings based on the plugin support status. You can use this filter to quickly narrow down options to plugins that meet your specific support requirements.

. Click the entry of a plugin list page to view its details, which provide an in-depth view of its characteristics.