[id="proc-installing-and-configuring-redis-cache_{context}"]
= Using Redis Cache with dynamic plugins
You can use the Redis cache store to improve {product-very-short} performance and reliability. Plugins in {product-very-short} receive dedicated cache connections, which are powered by Keyv.

== Installing Redis Cache in {product}

.Prerequisites
* You have installed Red Hat Developer Hub by using either the Operator or Helm chart.
* You have an active Redis server. For more information on setting up an external Redis server, see the Redis official documentation.

.Procedure
Add the following code to your `app-config.yaml` file:
[source, yaml]
----
backend:
  cache:
    store: redis
    connection: redis://user:pass@cache.example.com:6379
    useRedisSets: true
----

== Configuring Redis Cache in {product}
=== useRedisSets
The `useRedisSets` option lets you decide whether to use Redis sets for key management. By default, this option is set to `true`.

When `useRedisSets` is enabled (`true`):

* A namespace for the Redis sets is created, and all generated keys are added to that namespace, enabling group management of the keys.

* When a key is deleted, it's removed from the main storage and the Redis set.

* When using the clear function to delete all keys, every key in the Redis set is checked for deletion, and the set itself is also removed.

[NOTE]
In high-performance scenarios, enabling `useRedisSets` can lead to memory leaks. If you're running a high-performance application or service, it is recommended to set `useRedisSets` to `false`.

If you set `useRedisSets` as false, keys will be handled individually and Redis sets are not utilized. Setting `useRedisSets` to `false` could lead to performance issues in production when using the `clear` function, as it will need to iterate over all keys to delete them.
