= Plugin cards
For each plugin card, the following details are displayed:

Badge:: The following badges are defined:
* Certified by Red Hat: Plugins that are produced and supported by Red Hat's partners.
* Verified by Red Hat: Production ready plugins that are supported by Red Hat
* Custom plugin: Plugins are created and added by the customer.
+
[NOTE]
No badge is displayed if a plugin does not match any of these definitions.

Icon:: The plugin icon (base64).
Name:: The plugin name.
Author(s):: A single author name or multiple author names if a plugin is developed by multiple authors.
Category:: The categories that are displayed in the filter and labels. Only one category is shown on the card but any other categories that you select will apply when you use the category filter.
Short description:: Short description that is shown on the cards (text).
Read more link:: Clickable link to open the plugin details page.

= Plugin details
When you click on the *Read more* link on a plugin card, the following details are displayed:

Icon:: The plugin icon (base64).
Name:: The plugin name.
Author(s):: A single author name or multiple author names if a plugin is developed by multiple authors.
Highlights:: A list of plugin features.
Install button:: Button to install the plugin (disabled).
Long description:: Full description of the plugin (Markdown).
Links:: Clickable links providing additional information about the plugin.
Versions:: Displays the plugin's name, version, role, supported version, and installation status based on the plugin's plugin's package name. 