[id="proc-configuring-the-keycloak-plugin"]
= Configuring the Keycloak plugin

.Schedule configuration
You can configure a schedule in the `{my-app-config-file}` file, as follows:

[source,yaml]
----
     catalog:
       providers:
         keycloakOrg:
           default:
             # ...
             # highlight-add-start
             schedule: # optional; same options as in TaskScheduleDefinition
               # supports cron, ISO duration, "human duration" as used in code
               frequency: { minutes: 1 }
               # supports ISO duration, "human duration" as used in code
               timeout: { minutes: 1 }
               initialDelay: { seconds: 15 }
               # highlight-add-end
----

[NOTE]
====
If you have made any changes to the schedule in the `{my-app-config-file}` file, then restart to apply the changes.
====

.Keycloak query parameters

You can override the default Keycloak query parameters in the `app-config.yaml` file, as follows:

[source,yaml]
----
   catalog:
     providers:
       keycloakOrg:
         default:
           # ...
           # highlight-add-start
           userQuerySize: 500 # Optional
           groupQuerySize: 250 # Optional
           # highlight-add-end
----

Communication between {product-short} and Keycloak is enabled by using the Keycloak API. Username and password, or client credentials are supported authentication methods.


The following table describes the parameters that you can configure to enable the plugin under `catalog.providers.keycloakOrg.<ENVIRONMENT_NAME>` object in the `app-config.yaml` file:

|===
| Name | Description | Default Value | Required

| `baseUrl`
| Location of the Keycloak server, such as `pass:c[https://localhost:8443/auth]`.
| ""
| Yes

| `realm`
| Realm to synchronize
| `master`
| No

| `loginRealm`
| Realm used to authenticate
| `master`
| No

| `username`
| Username to authenticate
| ""
| Yes if using password based authentication

| `password`
| Password to authenticate
| ""
| Yes if using password based authentication

| `clientId`
| Client ID to authenticate
| ""
| Yes if using client credentials based authentication

| `clientSecret`
| Client Secret to authenticate
| ""
| Yes if using client credentials based authentication

| `userQuerySize`
| Number of users to query at a time
| `100`
| No

| `groupQuerySize`
| Number of groups to query at a time
| `100`
| No
|===

When using client credentials, the access type must be set to `confidential` and service accounts must be enabled. You must also add the following roles from the `realm-management` client role:

* `query-groups`
* `query-users`
* `view-users`

= Metrics

The Keycloak backend plugin supports link:https://opentelemetry.io/[OpenTelemetry] metrics that you can use to monitor fetch operations and diagnose potential issues.

== Available Counters

.Keycloak metrics
[cols="60%,40%", frame="all", options="header"]
|===
|Metric Name
|Description
| `backend_keycloak_fetch_task_failure_count_total`       | Counts fetch task failures where no data was returned due to an error.
| `backend_keycloak_fetch_data_batch_failure_count_total` | Counts partial data batch failures. Even if some batches fail, the plugin continues fetching others.
|===

== Labels

All counters include the `taskInstanceId` label, which uniquely identifies each scheduled fetch task. You can use this label to trace failures back to individual task executions. 

Users can enter queries in the Prometheus UI or Grafana to explore and manipulate metric data. 

In the following examples, a Prometheus Query Language (PromQL) expression returns the number of backend failures.

.Example to get the number of backend failures associated with a `taskInstanceId` 
[source,subs="+attributes,+quotes"]
----
backend_keycloak_fetch_data_batch_failure_count_total{taskInstanceId="df040f82-2e80-44bd-83b0-06a984ca05ba"} 1
----

.Example to get the number of backend failures during the last hour

[source,subs="+attributes,+quotes"]
----
sum(backend_keycloak_fetch_data_batch_failure_count_total) - sum(backend_keycloak_fetch_data_batch_failure_count_total offset 1h)
----

[NOTE]
====
PromQL supports arithmetic operations, comparison operators, logical/set operations, aggregation, and various functions. Users can combine these features to analyze time-series data effectively.

Additionally, the results can be visualized using Grafana.
====

== Exporting Metrics

You can export metrics using any OpenTelemetry-compatible backend, such as *Prometheus*.

See the link:https://backstage.io/docs/tutorials/setup-opentelemetry[Backstage OpenTelemetry setup guide] for integration instructions.

= Limitations

If you have self-signed or corporate certificate issues, you can set the following environment variable before starting {product-short}:

`NODE_TLS_REJECT_UNAUTHORIZED=0`

[NOTE]
====
The solution of setting the environment variable is not recommended.
====