:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
//
// * assemblies/assembly-rhdh-observability.adoc

[id="customize-the-adoption-insights-plugin-in-rhdh_{context}"]
= Customize the Adoption Insights plugin in {product}

[role="_abstract"]
Customize buffer size, flush interval, debug settings, and licensed users for the Adoption Insights plugin.

.Prerequisites
* You have the `adoption-insights.events.read` {authorization-book-link}#assembly-rbac-permission-policies-reference_title-authorization[permission].

.Procedure

* To customize `maxBufferSize`, `flushInterval`, `debug`, and `licensedUsers` in the Adoption Insights plugin, in your {product} `app-config.yaml` file, update the relevant settings as shown in the following code:
+
[source,yaml]
----
app:
  analytics:
    adoptionInsights:
      maxBufferSize: _<maximum_buffer_size>_
      flushInterval: _<flush_interval>_
      debug: _<debug_value>_
      licensedUsers: _<licensed_users>_
----

`maxBufferSize`::
(Optional) Enter the maximum buffer size for event batching.
The default value is `20`.

`flushInterval`::
(Optional) Enter the flush interval in milliseconds for event batching.
The default value is `5000ms`.

`debug`::
(Optional) Enter `true` to enable debug logging for the Adoption Insights plugin, or `false` to disable it.
The default value is `false`.

`licensedUsers`::
(Optional) Enter the maximum number of licensed users who can access the {product-very-short} instance.
The default value is `100`.

