:_mod-docs-content-type: PROCEDURE

// Module included in the following assemblies:
//
// * assemblies/assembly-rhdh-observability.adoc

[id="customize-the-adoption-insights-plugin-in-rhdh_{context}"]
= Customize the Adoption Insights plugin in {product}

[role="_abstract"]
Customize buffer size, flush interval, debug settings, licensed users, and RBAC permissions for the Adoption Insights plugin.

.Procedure

. To customize `maxBufferSize`, `flushInterval`, `debug`, and `licensedUsers` in the Adoption Insights plugin, in your {product} `app-config.yaml` file, update the relevant settings as shown in the following code:
+
[source,yaml]
----
app:
  analytics:
    adoptionInsights:
      maxBufferSize: _<maximum_buffer_size>_
      flushInterval: _<flush_interval>_
      debug: _<debug_value>_
      licensedUsers: _<licensed_users>_
----

`maxBufferSize`::
(Optional) Enter the maximum buffer size for event batching.
The default value is `20`.

`flushInterval`::
(Optional) Enter the flush interval in milliseconds for event batching.
The default value is `5000ms`.

`debug`::
(Optional) Enter `true` to enable debug logging for the Adoption Insights plugin, or `false` to disable it.
The default value is `false`.

`licensedUsers`::
(Optional) Enter the maximum number of licensed users who can access the {product-very-short} instance.
The default value is `100`.

. Optional: Configure the required RBAC permission for the users who are not administrators, as shown in the following example:
+
[source,yaml]
----
p, role:default/_<your_team>_, adoption-insights.events.read, read, allow
g, user:default/_<your_user>_, role:default/_<your_team>_
----
+
See {authorization-book-link}#assembly-rbac-permission-policies-reference_title-authorization[Permission policies in {product}].

