:_mod-docs-content-type: CONCEPT

= Configure the global header for consistent top-level navigation

[role="_abstract"]
As an administrator, you can configure the {product} global header to create a consistent and flexible navigation bar across your {product-short} instance.
By default, the {product-short} global header includes the following components:

* *Self-service* button provides quick access to a variety of templates, enabling users to efficiently set up services, backend and front-end plugins within {product-short}
* *Support* button that can link an internal or external support page
* *Notifications* button displays alerts and updates from plugins and external services
* *Search* input field allows users to find services, components, documentation, and other resources within {product-short}
* *Plugin extension capabilities* provide a preinstalled and enabled catalog of available plugins in {product-short}
* *User profile* drop-down menu provides access to profile settings, appearance customization, {product-short} metadata, and a logout button
