:_mod-docs-content-type: CONCEPT

= Customize themes and branding to align with corporate standards

[role="_abstract"]
By modifying the visual aspects of the interface, organizations can align {product} with their branding guidelines and improve the overall user experience.

The following default theme configurations are available for {product}:

The {product} theme:: Default theme configurations to make your developer portal look like a standard {product} instance.

The {backstage} theme:: Default theme configurations to make your developer portal look like a standard {backstage} instance.

You can change or disable particular parameters in a default theme or create a fully customized theme by modifying the `{my-app-config-file}` file. From the `{my-app-config-file}` file, you can customize common theme components, including the following components:

* Company name and logo
* Font color, size, and style of text in paragraphs, headings, headers, and buttons
* Header color, gradient, and shape
* Button color
* Navigation indicator color

You can also customize some components from the {product-short} GUI, such as the theme mode (*Light Theme*, *Dark Theme*, or *Auto*).
