:_mod-docs-content-type: CONCEPT

= Configure floating action buttons for quick access to workflows

[role="_abstract"]
Configure any action as a floating button in the {product-short} instance by using the floating action button plugin.

[IMPORTANT]
====
{product-very-short} 1.10 disables the Global Floating Action Button plugin by default. For new deployments, use the Global Header plugin, which uses quick links and starred items to improve navigation.

Existing deployments that explicitly enable the Global Floating Action Button remain functional. However, as the plugin is deprecated, it will be removed in a future {product-very-short} version, and you must eventually adjust your configuration.
====

[role="_additional-resources"]
== Additional resources
* xref:configure-the-global-header-in-rhdh_customizing-rhdh[Configure the Global Header in {product}]
* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.9/html/red_hat_developer_hub_release_notes/deprecated-features[Deprecated features in {product-very-short} 1.9.]
