// Module included in the following assemblies:
// assembly-customize-rhdh-theme.adoc

[id="proc-customize-rhdh-page-theme_{context}"]
= Customizing the page theme header for your {product-short} instance

You can customize the header color for the light and dark theme modes in your {product-short} instance by modifying the `branding.theme` section of the `app-config-rhdh.yaml` file. You can also customize the page headers for additional {product-short} pages, such as the *Home*, *Catalog*, and *APIs* pages.

[source,yaml]
----
app:
  branding:
    theme:
      light: <1>
        palette: {}
        pageTheme:
          default: <2>
            backgroundColor: "<default_light_background_color>" <3>
            fontColor: "<default_light_font_color>" <4>
            shape: none <5>
          apis: <6>
            backgroundColor: "<apis_light_background_color>"
            fontColor: "<apis_light_font_color>"
            shape: none
      dark:
        palette: {}
        pageTheme:
          default:
            backgroundColor: "<default_dark_background_color>"
            fontColor: "<default_dark_font_color>"
            shape: none
----

<1> The theme mode, for example, `light` or `dark`
<2> The `yaml` header for the default page theme configuration
<3> The color of the page header background, for example, `#ffffff` or `white`
<4> The color of the text in the page header, for example, `#000000` or `black`
<5> The pattern on the page header, for example, `wave`, `round`, or `none`
<6> The `yaml` header for a specific page theme configuration, for example, `apis`, `home`

//The page theme name depends on the plugin that you are customizing the page header for.
//can include information about this topic in the future.
