:_mod-docs-content-type: ASSEMBLY

[id="mirror-rhdh-dynamic-plugins-in-disconnected-environments_{context}"]
= Mirror {product} dynamic plugins in disconnected environments

[role="_abstract"]
{product} ({product-very-short}) uses dynamic plugins that are distributed as Open Container Initiative (OCI) artifacts. In disconnected or restricted environments, these plugin artifacts must be mirrored to a registry accessible by your cluster.

To mirror dynamic plugin OCI artifacts for deployments in restricted environments, use the `mirror-plugins.sh` script.

== Prerequisites

* You have installed Skopeo 1.20 or later. Use Skopeo for multi-arch image operations and manifest conversion.

* You have installed `tar` 1.35 or later. Use GNU `tar` for extracting image layers.

* You have installed `jq` 1.7 or later. Use `jq` for JSON parsing and manipulation. See Download jq.

* You have installed Podman 5.6 or later. Use Podman for building catalog index images.

* You have authenticated to the source registry, for example, quay.io or registry.redhat.io for pulling plugin artifacts.

* If mirroring directly to a registry using `--to-registry`, you have authenticated to the target registry.

[NOTE]
====
After mirroring completes, the script generates a `rhdh-plugin-mirroring-summary.txt` file containing mappings of all mirrored plugins. Use this file to reference the correct mirrored plugin URLs when configuring your {product-very-short} deployment.

For Operator deployments, you must configure the {product-custom-resource-type} Custom Resource with the mirrored plugin references. For Helm deployments, you must update your values file with the mirrored plugin references.
====

include::../modules/installing-and-viewing-plugins/proc-mirror-plugins-from-a-catalog-index-to-a-partially-disconnected-environment.adoc[leveloffset=+1]

include::../modules/installing-and-viewing-plugins/proc-mirror-plugins-from-a-catalog-index-to-a-fully-disconnected-environment.adoc[leveloffset=+1]

include::../modules/installing-and-viewing-plugins/proc-mirror-specific-plugins-by-direct-reference.adoc[leveloffset=+1]

include::../modules/installing-and-viewing-plugins/proc-mirror-plugins-from-a-file.adoc[leveloffset=+1]

include::../modules/installing-and-viewing-plugins/proc-combine-multiple-plugin-sources.adoc[leveloffset=+1]

.Additional resources
* link:https://podman.io/docs/installation[Podman Installation Instructions]
* link:https://access.redhat.com/articles/RegistryAuthentication[{rhcr} Authentication]