:_mod-docs-content-type: ASSEMBLY
:_mod-docs-category: Observability

include::artifacts/attributes.adoc[]
:context: audit-logs-in-rhdh
:imagesdir: images
:title: Audit logs in {product}
:subtitle: Tracking user activities, system events, and data changes with {product} audit logs
:abstract: As a {product} ({product-very-short}) administrator, you can track user activities, system events, and data changes with {product-short} audit logs.
[id="{context}"]
= {title}

[role="_abstract"]
Track user activities, system events, and data changes with audit logs to enhance security, automate compliance, and debug issues.

Audit logs are a chronological set of records documenting the user activities, system events, and data changes that affect your {product} users, administrators, or components.
Administrators can view {product-short} audit logs in the {ocp-short} web console to monitor scaffolder events, changes to the RBAC system, and changes to the Catalog database.
Audit logs include the following information:

* Name of the audited event
* Actor that triggered the audited event, for example, terminal, port, IP address, or hostname
* Event metadata, for example, date, time
* Event status, for example, `success`, `failure`
* Severity levels, for example, `info`, `debug`,  `warn`, `error`

You can use the information in the audit log to achieve the following goals:

Enhance security::
Trace activities, including those initiated by automated systems and software templates, back to their source.
Know when software templates are executed, and the details of application and component installations, updates, configuration changes, and removals.

Automate compliance::
Use streamlined processes to view log data for specified points in time for auditing purposes or continuous compliance maintenance.

Debug issues::
Use access records and activity details to fix issues with software templates or plugins.

[NOTE]
====
Audit logs are not forwarded to the internal log store by default because the internal log store does not offer secure storage.
You are responsible for ensuring that the system to which you forward audit logs is compliant with your organizational and governmental regulations, and is properly secured.
====

include::modules/observability_audit-logs-in-rhdh/proc-configure-audit-logs-for-rhdh-on-ocp.adoc[leveloffset=+1]

include::modules/observability_audit-logs-in-rhdh/proc-forward-rhdh-audit-logs-to-splunk.adoc[leveloffset=+1]

include::modules/observability_audit-logs-in-rhdh/proc-view-audit-logs-in-rhdh.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* {ocp-docs-link}/observability/logging/cluster-logging.html[About Logging in {ocp-brand-name}]
