:_mod-docs-content-type: CONCEPT

[id="con-environment-variables-supported-by-the-build-script.adoc_{context}"]
= Environment variables supported by the build script

The `build-sh` script supports the following environment variables to customize the workflow build process without modifying the script itself:

`QUARKUS_EXTENSIONS`::

The `QUARKUS_EXTENSIONS` variable specifies additional link:https://quarkus.io/extensions/[Quarkus] extensions required by the workflow. This variable takes the format of a comma-separated list of fully qualified extension IDs as shown in the following example:
+
[source,yaml]
----
export QUARKUS_EXTENSIONS="io.quarkus:quarkus-smallrye-reactive-messaging-kafka"
----
+
Add Kafka messaging support or other integrations at build time.

`MAVEN_ARGS_APPEND`::

The `MAVEN_ARGS_APPEND` variable appends additional arguments to the *Maven build* command. This variable takes the format of a string of Maven CLI arguments as shown in the following example:
+
[source,yaml]
----
export MAVEN_ARGS_APPEND="-DmaxYamlCodePoints=35000000"
----
+
Control build behavior. For example, set `maxYamlCodePoints` parameter that controls the maximum input size for YAML input files to 35000000 characters (~33MB in UTF-8).