:_mod-docs-content-type: PROCEDURE

[id="con-environment-variables-supported-by-the-build-script.adoc_{context}"]
= Environment variables supported by the build script and required tools

The `build-sh` script supports the following environment variables to customize the workflow build process without modifying the script itself.

* `QUARKUS_EXTENSIONS`

The `QUARKUS_EXTENSIONS` variable specifies additional Quarkus extensions required by the workflow.

This variable takes the format of a comma-separated list of fully qualified extension IDs as shown in the following example:
+
[source,yaml]
----
export QUARKUS_EXTENSIONS="io.quarkus:quarkus-smallrye-reactive-messaging-kafka"
----
+
Add Kafka messaging support or other integrations at build time.

* `MAVEN_ARGS_APPEND`

The `MAVEN_ARGS_APPEND` variable appends additional arguments to the Maven build command.
This variable takes the format of the string of Maven CLI arguments as shown in the following example:
+
[source,yaml]
----
export MAVEN_ARGS_APPEND="-DmaxYamlCodePoints=35000000"
----

.Required tools
[cols="1,3", options="header"]
|===
|Tool |Conceptual Purpose
|podman or docker |Container runtime required for building the workflow images.
|kubectl |Kubernetes CLI
|yq JSON |processor
|curl, git, find, |which Shell utilities
|kn-workflow |CLI for generating workflow manifests
|===