:mod-docs-content-type: CONCEPT
[id="con-helper-scripts-overview_{context}"]
= Helper scripts overview for the Orchestrator on {ocp-short}

The following scripts streamline non-production setup:

* `setup.sh`: Initializes the {product-very-short} environment by creating the required authentication secret and labeling GitOps namespaces based on cluster configuration.

* `plugin-infra.sh`: Installs the OpenShift Serverless infrastructure required by the Orchestrator plugin.

[NOTE]
====
These scripts are intended for quick-start scenarios and are **not recommended for production**.
====

[IMPORTANT]
====
The `setup.sh` script is no longer needed for the core Orchestrator installation in {product-very-short}. The scripts primary function is to ease the installation of GitOps prerequisites like ArgoCD and to connect an authentication provider.
====

For more information on controlling the installation of the Operators, see link:https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/[Install your Operator with OLM].