[id='con-plugin-dependencies.adoc_{context}']
= Plugin dependencies

To run the Orchestrator plugin instance, you need to install the following dependencies:

* A SonataflowPlatform custom resource created in the namespace of the Backstage CR.
* A set of NetworkPolicies to allow traffic between infra resources, such as knative and serverless logic Operator, created in the namespace of Backstage CR, traffic for monitoring, and intra-namespace traffic.

The orchestrator-backend plugin uses the service `sonataflow-platform-data-index-service`, which is created by the _SonataFlowPlatform_ CR. The service communicates with the SonataFlow platform.

[IMPORTANT]
====
The _sonataflowplatform_ CR contains dataIndex service that requires PostgreSQL database as shown in the following example:

[source,bash]
----
      persistence:
        postgresql:
          secretRef:
            name: backstage-psql-secret-{{backstage-name}}
            userKey: POSTGRES_USER
            passwordKey: POSTGRES_PASSWORD
          serviceRef:
            name: backstage-psql-{{backstage-name}} # Name of the Backstage Custom Resource (CR)
            namespace: {{backstage-ns}} # Namespace where the Backstage CR is created
            databaseName: backstage_plugin_orchestrator
----
====

The default implementation of the Orchestrator plugin dependencies uses the following:

* The PostgreSQL database named _backstage_plugin_orchestrator_ created by Backstage for Orchestrator plugin.
* The Secret created by Backstage Operator for the PostgreSQL with *POSTGRES_USER* and *POSTGRES_PASSWORD* keys as the database credentials in the Backstage CR namespace.
* The Service created by Backstage Operator for the PostgreSQL database with the name `backstage-psql-{{backstage-name}}` in the Backstage CR namespace.

For more information about automatically creating 'plugin dependencies' resources when the Backstage CR is applied to the cluster, see link:https://github.com/redhat-developer/rhdh-operator/blob/release-1.7/docs/dynamic-plugins.md#dynamic-plugins-dependency-management[Dynamic plugins dependency management].

To enable the Backstage Operator to work with the SonataFlow platform, you must grant the appropriate permissions to its ServiceAccount. The Backstage Operator automatically creates the required Role and RoleBinding resource in the `profile/rhdh/plugin-rbac directory` directory when creating the SonataFlowPlatform CR in the Backstage CR namespace.
