:_mod-docs-content-type: CONCEPT

[id="the-build-sh-script-functionality-and-important-flags_{context}"]
= The `build-sh` script functionality and important flags

[role="_abstract"]
The `build-sh` script generates workflow manifests, builds workflow images, and optionally pushes images and deploys workflows.

* Generates workflow manifests using the `kn-workflow` CLI.
* Builds the workflow image using `podman` or `docker`.
* Optional: The script pushes the images to an image registry and deploys the workflow using `kubectl`.

You can review the script configuration options and see available flags and their functions by accessing the help menu:

[source,bash]
----
./scripts/build.sh [flags]
----

The following flags are essential for running the script:

[cols="1,3", options="header"]
|===
|Flag |Description
|`-i`, `--image` |Required: Full image path, for example, `quay.io/orchestrator/demo:latest`
|`-w`, `--workflow-directory` |Workflow source directory (default is the current directory)
|`-m`, `--manifests-directory` |Where to save generated manifests
|`--push` |Push the image to the registry
|`--deploy` |Deploy the workflow
|`-h`, `--help` |Show the help message
|===

[TIP]
====
The script also supports builder and runtime image overrides, namespace targeting, and persistence flags.
====