:_mod-docs-content-type: CONCEPT
[id="con-install-components-orchestrator-plugin_{context}"]
= Installing components for the Orchestrator plugin on {ocp-short}

To run the Orchestrator plugin successfully on {ocp-short}, you must first install the required dependencies. The Orchestrator plugin depends on the following components:

** {product} ({product-very-short}) {product-custom-resource-type}
** OpenShift Serverless Logic Operator
** OpenShift Serverless Operator
*** Knative Serving
*** Knative Eventing
** (Optional) An ArgoCD project named orchestrator requires a pre-installed ArgoCD or {company-name} OpenShift GitOps instance in the cluster. It is disabled by default.
** (Optional) Tekton tasks and build pipeline. These require a pre-installed Tekton or {company-name} OpenShift Pipelines instance in the cluster, and are disabled by default.

You can install the components for the Orchestrator plugin on {ocp-short} using one of the following methods:

* Manual installation
* {product-very-short} helper script
* Orchestrator Infrastructure for {product} Helm chart