:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-helm-chart.adoc_{context}"]
= Installing {product} with Orchestrator in an air-gapped environment using Helm chart

.Prerequisites

* You have set up your disconnected environment using a local registry.

* You have mirrored the {product} {product-version} Helm chart images to the local registry. See {installing-in-air-gap-book-link}#assembly-install-rhdh-airgapped-environment-ocp-helm_title-install-rhdh-air-grapped[Installing {product} on {ocp-short} in an air-gapped environment with the Helm chart] for instructions.

* You have mirrored the images for the Serverless Operator {rhoserverless-version} and the Serverless Logic Operator {rhoserverless-version}.

* You have permissions to push NPM packages to a local NPM server.

* Optional: Create and configure a local NPM server.

.Procedure

. Create the ImageTagMirrorSet and ImageDigestMirrorSet for the Serverless Functions (SF) images as shown in the following examples:
+
* Creating `ImageTagMirrorSet` for the SF images:
+
[source,subs="+attributes,+quotes"]
----
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: rhdh-tag-mirror
spec:
 imageTagMirrors:
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-operator-bundle'
     source: registry.redhat.io/openshift-serverless-1/logic-operator-bundle
   - mirrors:
       - '<my.registry.example.com>/openshift4/ose-cli'
     source: registry.redhat.io/openshift4/ose-cli
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-jobs-service-postgresql-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-data-index-postgresql-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-data-index-ephemeral-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-swf-builder-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-swf-devmode-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8
----

* Creating `ImageDigestMirrorSet` for the SF images:
+
[source,subs="+attributes,+quotes"]
----
kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
 name: rhdhorchestrator-mirror
spec:
 imageDigestMirrors:
   # Chart deployment
   - source: registry.redhat.io/openshift4/ose-cli
     mirrors:
       - <my.registry.example.com>/ose-cli
   - source: registry.access.redhat.com/ubi9-minimal
     mirrors:
       - <my.registry.example.com>/ubi9-minimal
   # Serverless workflows
   - source: registry.redhat.io/openshift-serverless-1/logic-rhel8-operator
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-rhel8-operator
   - source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-data-index-postgresql-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-data-index-ephemeral-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-swf-builder-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-swf-devmode-rhel8
   # {product-very-short}
   - source: registry.redhat.io/rhdh/rhdh-rhel9-operator
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-rhel9-operator
   - source: registry.redhat.io/rhdh/rhdh-operator-bundle
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-operator-bundle
   - source: registry.redhat.io/rhdh/rhdh-hub-rhel9
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-hub-rhel9
   # Knative Serving
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-activator-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-activator-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-autoscaler-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-autoscaler-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-autoscaler-hpa-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-autoscaler-hpa-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-webhook-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-webhook-rhel8
   # Knative Serving Ingress
   - source: registry.redhat.io/openshift-serverless-1/kourier-control-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kourier-control-rhel8
   - source: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-service-mesh/proxyv2-rhel8
   # Knative Eventing
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-apiserver-receive-adapter-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-apiserver-receive-adapter-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-webhook-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-webhook-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-channel-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-channel-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-channel-dispatcher-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-channel-dispatcher-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-jobsink-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-jobsink-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-mtchannel-broker-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-mtchannel-broker-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-filter-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-filter-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-ingress-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-ingress-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-mtping-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverle
ss-1/kn-eventing-mtping-rhel8
----
+
[NOTE]
====
If these objects already exist from the previous image mirroring step, you can skip this task.
====

. Wait for all the nodes to update after applying the `ImageTagMirrorSet`.
Track the update using the following command:
+
[source,yaml]
----
oc get mcp -A
----
+
Once all MCPs are applied, the new image configuration propagates to all nodes.

. Download the Node Package Manager (NPM) packages for orchestrator `1.7.1` using the following methods:
+
* Download them as `tgz` files from the following registry:
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator/-/backstage-plugin-orchestrator-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-backend-dynamic/-/backstage-plugin-orchestrator-backend-dynamic-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic/-/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-form-widgets/-/backstage-plugin-orchestrator-form-widgets-1.7.1.tgz
+
* Alternatively, use the NPM packages from link:https://npm.registry.redhat.com[{company-name} NPM registry] as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
npm pack "@redhat/backstage-plugin-orchestrator@1.7.1" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.7.1" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.7.1" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-orchestrator-form-widgets@1.7.1" --registry=https://npm.registry.redhat.com
----

. Push the NPM packages you have downloaded to a local NPM server as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
npm publish backstage-plugin-orchestrator-1.7.1.tgz
npm publish backstage-plugin-orchestrator-backend-dynamic-1.7.1.tgz
npm publish backstage-plugin-orchestrator-form-widgets-1.7.1.tgz
npm publish backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.7.1.tgz
----

. Apply the `orchestrator-infra` Helm chart using the instructions provided in the {installing-in-air-gap-book-link}#assembly-install-rhdh-airgapped-environment-ocp-helm_title-install-rhdh-air-grapped[Installing {product} on {ocp-short} in an air-gapped environment with the Helm chart] guide and approve the install plans.

. Apply the {product-very-short} {product-version} Helm chart. Include the version `1.7.1` and enable the Orchestrator plugin as shown in the following example:
+
[source,yaml]
----
orchestrator.enabled=true
----

. Modify the deployment created by the Helm chart instead of the {product-custom-resource-type} Custom Resource.
+
[NOTE]
====
Helm installs as a default the full URL of the `tgz` files that point towards the {company-name} NPM registry. Therefore, the redirect towards the custom registry fails.
====
+
In the default created `<release name>-dynamic-plugins` ConfigMap, replace the full URLs for the Orchestrator plugins with simplified package references as shown in the following example:
+
[source,yaml]
----
- package: "@redhat/backstage-plugin-orchestrator@1.7.1"
- package: "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.7.1"
- package: "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.7.1"
- package: "@redhat/backstage-plugin-orchestrator-form-widgets@1.7.1"
----

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* Once stable go to the {product-very-short} UI, and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====