:_mod-docs-content-type: PROCEDURE

[id="proc-upgrading-the-openshift-serverless-logic-operator_{context}"]
= Upgrading the OpenShift Serverless Logic Operator for {product} {product-version}

You must upgrade the OpenShift Serverless Logic (OSL) Operator to version {rhoserverless-version} for compatibility with {product} {product-version}. This update includes a base image transition to Red Hat Enterprise Linux (RHEL) 9. See {rhoserverless-link}#serverless-logic-upgrading-operator[OpenShift Serverless Logic Operator documentation] for the supported OpenShift Serverless Logic Operator versions and upgrade process.

Starting with OSL 1.37.0, the Operator subscription name and starting ClusterServiceVersion (CSV) no longer explicitly reference the operating system (OS) version.

In previous releases, the Operator subscription name and starting CSV explicitly included the OS version, such as `logic-operator-rhel8` and `logic-operator-rhel8.v1.36.0`.

[IMPORTANT]
====
Before performing the upgrade, make sure you do not delete the existing `SonataflowPlatform` operands during this process.
When performing the upgrade, you must replace the logic-operator-rhel8 subscription with the logic-operator subscription.
====

.Prerequisites

• You have administrative access to the OpenShift cluster.

.Procedure

. Delete the previous `logic-operator-rhel8` subscription and apply the following configuration to install the `logic-operator` subscription:
+
[source,yaml,subs='+attributes,+quotes']
----
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless-logic
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-serverless-logic
  namespace: openshift-serverless-logic
spec:
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: logic-operator
  namespace: openshift-serverless-logic
spec:
  channel: stable  #  channel of an operator package to subscribe to
  installPlanApproval: Automatic #  whether the update should be installed automatically
  name: logic-operator  #  name of the operator package
  source: redhat-operators  #  name of the catalog source
  sourceNamespace: openshift-marketplace
  startingCSV: logic-operator.v{rhoserverless-version}  # The initial version of the operator
----

. Optional: If your configuration uses an external PostgreSQL database with SSL, add the required datasource environment variables to the `jobService` specification in the `SonataflowPlatform` custom resource as shown in the following configuration:
+
[source,yaml,subs='+attributes,+quotes']
----
jobService:
  enabled: true
  persistence:
    dbMigrationStrategy: service
    postgresql:
      # no additional url params here. We only have currentSchema=jobs-service.
      jdbcUrl: 'jdbc:postgresql://postgress-external-db-primary.postgress-external-db.svc.cluster.local:5432/sonataflow?currentSchema=jobs-service'
      secretRef:
        name: postgres-cred
        passwordKey: POSTGRES_PASSWORD
        userKey: POSTGRES_USER
  podTemplate:
    container:
      env:
        # only this two env vars
        - name: QUARKUS_DATASOURCE_REACTIVE_POSTGRESQL_SSL_MODE
          value: allow
        - name: QUARKUS_DATASOURCE_REACTIVE_TRUST_ALL
          value: 'true'
----