:_mod-docs-content-type: PROCEDURE

[id="proc-install-components-for-orchestrator-plugin.adoc_{context}"]
= Installing the components for the Orchestrator plugin on {ocp-short}

.Prerequisites

* Install {product} with the Orchestrator plugin on {ocp-short} using the following components to support the plugin and its runtime infrastructure:

** OpenShift Serverless Operator
** Knative Serving
** Knative Eventing
** OpenShift Serverless Logic Operator
+
The {product} Operator provisions these automatically or you can install them manually using another Operator.

.Procedure

To install infrastructural components (Operators) that provide the dependencies required by the Orchestrator plugin on {ocp-short}, use the following methods:

* Manual installation
* {product-very-short} helper script
* {product-very-short} Orchestrator Infra Helm Chart
+
These components enable the creation of the `SonataFlowPlatform` custom resource and several supporting `NetworkPolicy` resources.

.Manual installation

The manual installation is suitable for production environments. It is particularly recommended when you have installed the versions of required components, such as when OpenShift Serverless is in use by other applications.

For more information on preparing the required infrastructure, see link:https://docs.redhat.com/en/documentation/red_hat_openshift_serverless/1.36[Red Hat OpenShift Serverless] and carry out the following steps to:

* Prepare for OpenShift Serverless installation.

* Install the OpenShift Serverless Operator.

* Install Knative Serving.

* Install Knative Eventing.

* Install the OpenShift Serverless Logic Operator.

.{product-very-short} helper script

You can install the OpenShift Serverless infrastructure for the Orchestrator plugin using the {product-very-short} helper script. You can use the script in empty clusters, however, use with caution in production clusters because the script installs Operators with automatic upgrades and default settings, which can introduce unplanned changes, version conflicts, or policy misalignments.

For more information on controlling the installation of the Operators, see link:https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/[Install your Operator with OLM].

.Procedure
. Download the `plugin-infra.sh` script as shown in the following example:
+
[source,yaml]
----
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-1.7/config/profile/rhdh/plugin-infra/plugin-infra.sh # Specify the {product} version in the URL or use main
----
. Run the script as shown in the following example:
+
[source,yaml]
----
./plugin-infra.sh
----

.{product-very-short} Orchestrator Infra Helm Chart
You can use {product-very-short} Orchestrator Infra Helm Chart in empty clusters. Use with caution in production clusters because {product-very-short} Orchestrator Infra Helm Chart installs Operators with automatic upgrades and default settings, which might introduce unplanned changes, version conflicts, or policy misalignments.

.Procedure
. Install the required components using the Orchestrator infrastructure helm chart.