:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-operator.adoc_{context}"]
= Installing {product} with Orchestrator in an air-gapped environment using Operator

You can install {product} with Orchestrator plugin in an air-gapped environment using Operator.

In a network-restricted environment, a disconnected installation prevents unauthorized access, data transfer, or communication with external sources.

.Prerequisites

* You have set up your disconnected environment using a local registry.

* You have mirrored the {product} Operator images to the local registry using the included script. For {product-very-short} installation using Operator, the mirroring script automatically deploys the {product-very-short} Operator for you.

* You have mirrored the images for the Serverless Operator `v1.36` and the Serverless Logic Operator `v1.36` to the local registry using tools like Skopeo or podman.

.Procedure

. Create `ImageTagMirrorSet` for the Serverless Functions (SF) images as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
apiVersion: config.openshift.io/v1
kind: ImageTagMirrorSet
metadata:
  name: rhdh-tag-mirror
spec:
 imageTagMirrors:
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-operator-bundle'
     source: registry.redhat.io/openshift-serverless-1/logic-operator-bundle
   - mirrors:
       - '<my.registry.example.com>/openshift4/ose-cli'
     source: registry.redhat.io/openshift4/ose-cli
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-jobs-service-postgresql-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-data-index-postgresql-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-data-index-ephemeral-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-swf-builder-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8
   - mirrors:
       - '<my.registry.example.com>/openshift-serverless-1/logic-swf-devmode-rhel8'
     source: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8
----

. Wait for all the nodes to update after applying the `ImageTagMirrorSet`. You can track the update using `oc get mcp -A`.

. Create `ImageDigestMirrorSet` for the SF images as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
 name: rhdhorchestrator-mirror
spec:
 imageDigestMirrors:
   # Chart deployment
   - source: registry.redhat.io/openshift4/ose-cli
     mirrors:
       - <my.registry.example.com>/ose-cli
   - source: registry.access.redhat.com/ubi9-minimal
     mirrors:
       - <my.registry.example.com>/ubi9-minimal
   # Serverless workflows
   - source: registry.redhat.io/openshift-serverless-1/logic-rhel8-operator
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-rhel8-operator
   - source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-jobs-service-postgresql-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-data-index-postgresql-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-data-index-ephemeral-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-swf-builder-rhel8
   - source: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/logic-swf-devmode-rhel8
   # {product-very-short}
   - source: registry.redhat.io/rhdh/rhdh-rhel9-operator
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-rhel9-operator
   - source: registry.redhat.io/rhdh/rhdh-operator-bundle
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-operator-bundle
   - source: registry.redhat.io/rhdh/rhdh-hub-rhel9
     mirrors:
       - <my.registry.example.com>/rhdh/rhdh-hub-rhel9
   # Knative Serving
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-activator-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-activator-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-autoscaler-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-autoscaler-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-autoscaler-hpa-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-autoscaler-hpa-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-serving-webhook-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-serving-webhook-rhel8
   # Knative Serving Ingress
   - source: registry.redhat.io/openshift-serverless-1/kourier-control-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kourier-control-rhel8
   - source: registry.redhat.io/openshift-service-mesh/proxyv2-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-service-mesh/proxyv2-rhel8
   # Knative Eventing
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-apiserver-receive-adapter-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-apiserver-receive-adapter-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-webhook-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-webhook-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-channel-controller-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-channel-controller-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-channel-dispatcher-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-channel-dispatcher-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-jobsink-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-jobsink-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-mtchannel-broker-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-mtchannel-broker-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-filter-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-filter-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-ingress-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverless-1/kn-eventing-ingress-rhel8
   - source: registry.redhat.io/openshift-serverless-1/kn-eventing-mtping-rhel8
     mirrors:
       - <my.registry.example.com>/openshift-serverle
ss-1/kn-eventing-mtping-rhel8
----

. Install the OpenShift Serverless Operator and OpenShift Serverless Logic Operators using the Operator.

. Download the Node Package Manager (NPM) packages for orchestrator `1.7.1` using the following methods:
+
* Download them as `tgz` files from the following registry:
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator/-/backstage-plugin-orchestrator-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-backend-dynamic/-/backstage-plugin-orchestrator-backend-dynamic-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic/-/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic-1.7.1.tgz
** https://npm.registry.redhat.com/@redhat/backstage-plugin-orchestrator-form-widgets/-/backstage-plugin-orchestrator-form-widgets-1.7.1.tgz
+
* Alternatively, use the NPM packages from link:https://npm.registry.redhat.com.https://npm.registry.redhat.com[{company-name} NPM registry] as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
npm pack "@redhat/backstage-plugin-orchestrator@1.7.0" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-orchestrator-backend-dynamic@1.7.0" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@1.7.0" --registry=https://npm.registry.redhat.com
npm pack "@redhat/backstage-plugin-orchestrator-form-widgets@1.7.0" --registry=https://npm.registry.redhat.com
----

. Push the NPM packages you have downloaded to a local NPM server.
+
Optional: You can create and configure this server.

. Create a {product-custom-resource-type} custom resource (CR).

. Configure the {product-custom-resource-type} CR for the Orchestrator as described in the {orchestrator-book-link}#con-orchestrator-plugin-dependencies-operator.adoc_orchestrator-rhdh[Orchestrator plugin dependencies for Operator installation].
+
Create all the resources and configure the {product-custom-resource-type} instance accordingly. See {release-notes-book-link}#removed-functionality-rhdhbugs-2000[Configuring a custom NPM registry] for instructions on how to point {product-very-short} towards the custom NPM registry.

.Verification

. Go to the {product-very-short} UI.
. {product-very-short} with the Orchestrator is deployed properly.