:_mod-docs-content-type: PROCEDURE

[id="proc-enabling-orchestrator-plugins-components_{context}"]
= Enabling Orchestrator plugins components

To use the Orchestrator, enable the following Orchestrator plugins for {product}, that are disabled by default:

Orchestrator-frontend plugin::

`backstage-plugin-orchestrator`:::
Provides the interface for users to run and monitor workflows within {product-very-short}. You can run and track the execution status of processes.

Orchestrator-backend plugin::

`backstage-plugin-orchestrator-backend`:::
Gets workflow data into {product-short} making sure {product-very-short} processes critical workflow metadata and runtime status fulfilling your need for visibility.

Orchestrator-form-widget::

`backstage-plugin-orchestrator-form-widgets`:::
Provides custom widgets for the workflow execution form, allowing you to customize input fields and streamline the process of launching workflows.

Orchestrator-scaffolder-backend-module::

`scaffolder-backend-module-orchestrator`:::
Provides callable actions from Scaffolder templates, such as `orchestrator:workflow:run` or `orchestrator:workflow:get_params`.

.Prerequisites

* You have installed the following operators:
+
** OpenShift Serverless
** OpenShift Serverless Logic (OSL)
* (Optional) For managing the Orchestrator project, you have an instance of Argo CD or Red Hat OpenShift GitOps in the cluster. It is disabled by default.

* (Optional) To use Tekton tasks and the build pipeline, you have an instance of Tekton or Red Hat OpenShift Pipelines in the cluster. These features are disabled by default.

.Procedure
* Locate your {product-short} configuration and enable the Orchestrator plugins and the supporting notification plugins.
+
[source,yaml,subs="+attributes,+quotes"]
----
plugins:
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator@sha256:7355b244d463187b11174b091b10235167ffc6fbd9466ec3cff0a8b5b04d6e98
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend@sha256:05f14d7c6cc41dd50cdb0adafa97137593caa4c218563fcc00bb30d36ad6bf2f
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator@sha256:6a138dd4c6bb7b98d7af58657395fc3ef3b96768276a2d65d9a7ef5fda52f2b5
    disabled: false
  - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:6e12decf7664c5c3410b1c7308eaa6daabeabbbc7baae5beddcdf52afdb702f8
    disabled: false
  - package: "./dynamic-plugins/dist/backstage-plugin-notifications"
    disabled: false
  - package: "./dynamic-plugins/dist/backstage-plugin-signals"
    disabled: false
  - package: "./dynamic-plugins/dist/backstage-plugin-notifications-backend-dynamic"
    disabled: false
  - package: "./dynamic-plugins/dist/backstage-plugin-signals-backend-dynamic"
    disabled: false
----