:_mod-docs-content-type: PROCEDURE

[id="proc-upgrading-the-orchestrator-plugin_{context}"]
= Upgrading the Orchestrator plugin from `1.7` to {product-version}

You can upgrade an existing `1.7` Operator-backed instance with Orchestrator enabled by upgrading the {product} Operator to {product-version}. After upgrading the Operator to {product-version}, manually update the `dynamic-plugins` ConfigMap to set the Orchestrator plugin versions to `1.8.2`.

.Prerequisites
* You have have a running instance of {product} with Orchestrator `1.7` backed by the Operator.
* You have upgraded the {product} Operator to {product-version}.

.Procedure

. Update your `dynamic-plugins` ConfigMap to set the version of the Orchestrator plugin to `1.8.2`.
+
The following YAML configuration is an example of a `dynamic-plugins` ConfigMap enabling the Orchestrator plugins in {product-very-short} for Operator-backed instances:
+
[source,yaml,subs='+attributes,+quotes']
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator@sha256:7355b244d463187b11174b091b10235167ffc6fbd9466ec3cff0a8b5b04d6e98
        disabled: false
      - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend@sha256:05f14d7c6cc41dd50cdb0adafa97137593caa4c218563fcc00bb30d36ad6bf2f
        disabled: false
        dependencies:
          - ref: sonataflow
      - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator@sha256:6a138dd4c6bb7b98d7af58657395fc3ef3b96768276a2d65d9a7ef5fda52f2b5
        disabled: false
      - package: oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:6e12decf7664c5c3410b1c7308eaa6daabeabbbc7baae5beddcdf52afdb702f8
        disabled: false
----

.Verification
. Navigate to your {product} instance.
+
[NOTE]
====
The upgrade takes a few minutes to complete. The {product} version does not update in the UI until all running {product-custom-resource-type} pods are successfully recreated.
====
. From the profile dropdown in the top menu, click the *Settings* icon and then locate the {product-very-short} metadata card.
. Confirm that the value displayed for {product-very-short} version is {product-version}.
. Alternatively, run the following command in your terminal to wait for all pods in the current project to be in the `running` state:
+
[source,terminal]
----
$ oc get pods -w
----
+
The upgrade is successful when all {product-custom-resource-type}-related pods show a stable *Running* status.