:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-operator.adoc_{context}"]
= Installing {product} with Orchestrator in an air-gapped environment using Operator

You can install {product} with Orchestrator plugin in an air-gapped environment using Operator.

In a network-restricted environment, a disconnected installation prevents unauthorized access, data transfer, or communication with external sources.

.Prerequisites

* You have mirrored the {product} Operator images to the local registry using the included script. For {product-very-short} installation using Operator, the mirroring script automatically deploys the {product-very-short} Operator for you.

include::snip-installing-the-orchestrator-common-prerequisites.adoc[]

.Procedure

include::snip-installing-the-orchestrator-common-steps.adoc[]

. Install the OpenShift Serverless Operator and OpenShift Serverless Logic Operators using the OperatorHub.

. Create a {product-custom-resource-type} custom resource (CR).

. Configure the {product-custom-resource-type} CR for the Orchestrator as described in the {orchestrator-book-link}#con-orchestrator-plugin-dependencies-operator.adoc_orchestrator-rhdh[Orchestrator plugin dependencies for Operator installation].
+
Create all the resources and configure the {product-custom-resource-type} instance accordingly. See {release-notes-book-link}#removed-functionality-rhdhbugs-2000[Configuring a custom NPM registry] for instructions on how to point {product-very-short} towards the custom NPM registry.

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* Once stable go to the {product-very-short} UI, and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====