:_mod-docs-content-type: PROCEDURE

[id="proc-workflow-deployment-errors_{context}"]
= Troubleshoot common workflow deployment errors

Refer to the following checks when diagnosing workflow deployment, connectivity, or configuration failures.

Workflow deployment fails::
+
To understand why your workflow operation fails, examine the container log of the specific workflow instance by running the following command:
+
[source,terminal]
----
$ oc logs my-workflow-xy73lj
----

Workflow fails to reach an HTTPS endpoint because it cannot verify it::
+
When your workflow attempts a REST action that fails the SSL certificate check, it might be because the target endpoint uses a Certificate Authority (CA) that the workflow cannot verify.
This results in an error in the pod log usually looking like this:
+
[source,yaml]
----
sun.security.provider.certpath.SunCertPathBuilderException - unable to find valid certification path to requested target
----
+
To resolve this, load the additional CA certificate into the running workflow container.