:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-helm-chart.adoc_{context}"]
= Installing {product} with Orchestrator in an air-gapped {ocp-short} environment using Helm chart


.Prerequisites

include::snip-installing-the-orchestrator-common-prerequisites.adoc[]

.Procedure

. Mirror the {product} {product-version} Helm chart images to the local registry. See {installing-in-air-gap-book-link}#assembly-install-rhdh-airgapped-environment-ocp-helm_title-install-rhdh-air-grapped[Installing {product} on {ocp-short} in an air-gapped environment with the Helm chart] for instructions.

. Mirror `orchestrator-infra` chart images to the local registry.

include::snip-installing-the-orchestrator-common-steps.adoc[]

. Apply the `orchestrator-infra` Helm chart using the instructions provided in the {installing-in-air-gap-book-link}#assembly-install-rhdh-airgapped-environment-ocp-helm_title-install-rhdh-air-grapped[Installing {product} on {ocp-short} in an air-gapped environment with the Helm chart] guide and approve the install plans.

. Apply the {product-very-short} {product-version} Helm chart. Include the version {product-bundle-version} and enable the Orchestrator plugin as shown in the following example:
+
[source,yaml]
----
orchestrator.enabled=true
----

. The {product-very-short} {product-version} Helm chart defaults to pulling Orchestrator plugins from the official {company-name} NPM registry using full URL references. You must override this behavior to point to your local registry.
+
To configure the Orchestrator plugins to use a custom registry, complete the following steps:
+
* Open your `values.yaml` file.
+
* Explicitly list the Orchestrator plugin packages under the `orchestrator.plugins` section.
You must replace the full URLs with the simplified package references that point to your custom NPM registry as shown in the following example:
+
[source,yaml]
----
- package: "@redhat/backstage-plugin-orchestrator@{product-bundle-version}"
- package: "@redhat/backstage-plugin-orchestrator-backend-dynamic@{product-bundle-version}"
- package: "@redhat/backstage-plugin-scaffolder-backend-module-orchestrator-dynamic@{product-bundle-version}"
- package: "@redhat/backstage-plugin-orchestrator-form-widgets@{product-bundle-version}"
----
+
[NOTE]
====
Helm installs as a default the full URL of the `tgz` files that point towards the {company-name} NPM registry. Therefore, the redirect towards the custom registry fails when trying to access packages from a local registry.
====

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* Once stable go to the {product-very-short} UI, and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====