:_mod-docs-content-type: PROCEDURE

[id="proc-manual-install-orchestrator-plugin_{context}"]
= Installing Orchestrator components manually on {ocp-short}

Use manual installation when you want full control of the setup process and component versions. Manual installation method focuses on setting up the underlying infrastructure.

.Procedure

. Install the OpenShift Serverless components manually by following the instructions in the {rhoserverless-link}[{rhoserverless-brand-name}] documentation.

. You must also configure workflow persistence to prevent workflow context from being lost when the Pod restarts. You can do this configuration at the namespace level using the `SonataFlowPlatform` or `SonataFlow` custom resources (CR). For detailed instructions on configuring persistence using the `SonataFlowPlatform` or `SonataFlow` custom resources, see {rhoserverless-link}/html-single/serverless_logic/index#serverless-logic-managing-persistence[Managing workflow persistence].

. (Optional) If required, deploy a custom PostgreSQL database.
