:_mod-docs-content-type: PROCEDURE

[id="proc-troubleshooting-missing-workflows_{context}"]
= Troubleshooting workflows missing from the {product-very-short} UI

You can perform the following checks to verify the workflow status and connectivity when the deployed workflow is missing from the {product-very-short} Orchestrator UI.

.Prerequisites

* You have administrator privileges to access to the OpenShift cluster where {product-very-short} and SonataFlow services are running.

.Procedure

. Check if the workflow uses GitOps profile. The {product-very-short} Orchestrator UI displays only the workflows that use GitOps profile. Make sure the workflow definition and the sonataflow manifests use this profile.

. Verify that the workflow pod has started and is ready. The readiness of a workflow pod depends on its successful registration with the Data Index. When a workflow initializes, it performs the following actions:
.. It attempts to create its schema in the database (if persistence is active).
.. It attempts to register itself to the Data Index. The workflow pod remains in an unready state until it successfully registers to the Data Index.

. Check if the workflow pod can reach the Data Index service. Connect to the workflows pod. Send the following GraphQL request to the Data Index:
+
[source,bash]
----
curl -g -k  -X POST  -H "Content-Type: application/json" \
                    -d '{"query":"query{ ProcessDefinitions  { id, serviceUrl, endpoint } }"}' \
                    http://sonataflow-platform-data-index-service.sonataflow-infra/graphql
----
+
Use the Data Index service and namespace as defined in your environment, (for example, `sonataflow-platform-data-index-service` and `sonataflow-infra`). Check if the {product-very-short} pod can reach the workflow service by running the following command:
+
[source,bash]
----
curl http://<workflow-service>.<workflow-namespace>/management/processes
----

. Connect to the {product-very-short} pod. Verify the {product-very-short} pod connection to the Data Index service and inspect the {product-very-short} pod logs for messages from the Orchestrator plugin.
+
To inspect the logs, identify the {product-very-short} pod and run the following *oc logs* command:
+
[source,yaml]
----
oc get pods -n <your-namespace>
oc logs <rhdh-pod-name>
----
+
You must find messages indicating it is attempting to fetch workflow information from the Data Index, similar to the following:
+
[source,yaml]
----
{"level":"\u001b[32minfo\u001b[39m","message":"fetchWorkflowInfos() called: http://sonataflow-platform-data-index-service.sonataflow-infra","plugin":"orchestrator","service":"backstage","span_id":"fca4ab29f0a7aef9","timestamp":"2025-08-04 17:58:26","trace_flags":"01","trace_id":"5408d4b06373ff8fb34769083ef771dd"}
----
+
Notice the _"plugin":"orchestrator"_ that can help to filter the messages.

. Make sure the Data Index properties are set in the `-managed-props` ConfigMap of the workflow:
+
[source,yaml]
----
kogito.data-index.health-enabled = true
kogito.data-index.url = http://sonataflow-platform-data-index-service.sonataflow-infra
...
mp.messaging.outgoing.kogito-processdefinitions-events.url = http://sonataflow-platform-data-index-service.sonataflow-infra/definitions
mp.messaging.outgoing.kogito-processinstances-events.url = http://sonataflow-platform-data-index-service.sonataflow-infra/processes
----
+
These properties, along with similar settings for the Job Services, typically indicate that the Openshift Serverless Logic (OSL) Operator successfully registered the Data Index service.

. Confirm that the workflow is registered in the Data Index database. Connect to the database used by the Data Index and run the following command from the PSQL instance pod:
+
[source,bash]
----
PGPASSWORD=<psql password> psql -h localhost -p 5432 -U < user> -d sonataflow
----
+
Replace `<psql password>` and `<user>` with your database credentials.
+
Run the following SQL commands to query the registered workflow definitions:
+
[source,yaml]
----
sonataflow=# SET search_path TO "sonataflow-platform-data-index-service";
sonataflow=# select id, name from definitions;
----
+
You must see your workflows listed in the query results.

. Make sure you have enabled Data Index and Job Service as shown in the following configuration:
+
[source,yaml]
----
services:
    dataIndex:
      enabled: true
    jobService:
      enabled: true
----
+
If you fail to enable the Data Index and the Job Services in the `SonataFlowPlatform` custom resource (CR), the Orchestrator plugin fails to fetch the available workflows.
+
[NOTE]
====
You can also manually edit the `SonataFlowPlatform` CR instance to trigger the re-creation of workflow-related manifests.
====

. Set the RBAC permissions correctly. For more information, see {authorization-book-link}#managing-authorizations-by-using-the-rest-api[RBAC documentation].

[role="_additional-resources"]
.Additional resources

* {monitoring-and-logging-book-link}#configuring-the-application-log-level-by-using-the-operator_assembly-rhdh-observability[Configuring the application log level by using the {product} Operator]