:_mod-docs-content-type: PROCEDURE

[id="proc-enable-orchestrator-plugin_{context}"]
= Enable the Orchestrator plugins using the Operator

You can enable the Orchestrator plugins in {product-very-short} by configuring dynamic plugins in your {product-custom-resource-type} custom resource (CR).

.Prerequisites
* You have installed {product-very-short} on {ocp-short}.
* You have access to edit or create ConfigMaps in the namespace where the {product-custom-resource-type} CR is deployed.

.Procedure

. To enable the Orchestrator plugins with default settings, set `disabled: false` for the corresponding packages:
+
[source,yaml,subs="+attributes,+quotes"]
----
- package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{inherit}}"
 disabled: false
- package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{inherit}}"
  disabled: false
  dependencies:
    - ref: sonataflow
- package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{inherit}}"
  disabled: false
- package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{inherit}}"
  disabled: false
----
+
[NOTE]
====
When you enable the plugins, the pre-loaded plugin configuration are used.
Additionally, the `ref: sonataflow` field installs the OpenShift Serverless and OpenShift Serverless Logic resources. This happens automatically when you are using the Operator.
====
+
.Example: Complete configuration of the Orchestrator plugin
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-plugin
data:
    dynamic-plugins.yaml: |
      includes:
        - dynamic-plugins.default.yaml
      plugins:
        - package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:{{inherit}}"
          disabled: false
                    appIcons:
                      - importName: OrchestratorIcon
                        name: orchestratorIcon
                    dynamicRoutes:
                      - importName: OrchestratorPage
                        menuItem:
                          icon: orchestratorIcon
                          text: Orchestrator
                        path: /orchestrator
                    entityTabs:
                      - path: /workflows
                        title: Workflows
                        mountPoint: entity.page.workflows
                    mountPoints:
                      - mountPoint: entity.page.workflows/cards
                      importName: OrchestratorCatalogTab
                      config:
                        layout:
                          gridColumn: '1 / -1'
                          if:
                            anyOf:
                              - IsOrchestratorCatalogTabAvailable
        - package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend:{{inherit}}"
          disabled: false
          dependencies:
            - ref: sonataflow
        - package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:{{inherit}}"
          disabled: false
        - package: "oci://registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:{{inherit}}"
          disabled: false
---
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: orchestrator
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: orchestrator-plugin
----
+
Where:

`{{inherit}}`::
Enter the correct image digest for your version of {product-very-short}. Refer to the `dynamic-plugins.default.yaml` file.

. Create a secret containing the `BACKEND_SECRET` value as shown in the following example:
+
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
data:
  {my-app-config-file}: |-
    auth:
      environment: development
      providers:
        guest:
          # using the guest user to query the '/api/dynamic-plugins-info/loaded-plugins' endpoint.
          dangerouslyAllowOutsideDevelopment: true
    backend:
      auth:
        externalAccess:
          - type: static
            options:
              token: ${BACKEND_SECRET}
              subject: orchestrator
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-auth-secret
stringData:
  # generated with the command below (from https://backstage.io/docs/auth/service-to-service-auth/#setup):
  # node -p 'require("crypto").randomBytes(24).toString("base64")'
  # notsecret
  BACKEND_SECRET: "R2FxRVNrcmwzYzhhN3l0V1VRcnQ3L1pLT09WaVhDNUEK"
----

. Configure your {product-custom-resource-type} CR to update the secret name in the `extraEnvs` field as shown in the following example:
+
[source,yaml]
----
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: orchestrator
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
    dynamicPluginsConfigMapName: orchestrator-plugin
    extraEnvs:
      secrets:
          # secret that contains the BACKEND_SECRET key
        - name: backend-auth-secret
----

.Verification
* In the {product-very-short} console, confirm that the Orchestrator frontend and backend features are available.
