[id="proc-install-rhdh-with-orchestrator-helm-webui.adoc_{context}"]
= Install {product} ({product-very-short}) using {ocp-short} web console

You can install {product} ({product-very-short}) with the Orchestrator by using the ({ocp-short}) web console. This method is useful if you prefer a graphical interface or want to deploy cluster-wide resources without using the Helm CLI.

.Prerequisites

* You are logged in to the OpenShift Container Platform web console as a cluster administrator.
* You have access to the {product} Helm chart repository.
* Your cluster has internet access or the Helm charts are mirrored in a disconnected environment.

.Procedure

. In the OpenShift web console, go to menu:Helm[Helm Charts].

. Click btn:[Repository] and confirm that the {product} Helm chart repository is available.

. Search for the Orchestrator infrastructure for {product} and click btn:[Install].
+
[IMPORTANT]
====
You must be a cluster administrator to install the Orchestrator Infrastructure for {product} Helm chart because it deploys cluster-scoped resources. As an administrator, you need to manually approve the install plans for OpenShift Serverless and Serverless Logic Operators.
====
+
As a regular user, search for the {product} chart and install it by setting the value of `orchestrator.enabled` to `true`. Otherwise, the Orchestrator will not be deployed.

. Wait until they are successfully deployed.

. Monitor the deployment status by navigating to menu:Workloads[Pods] or menu:Helm[Releases].

.Verification

After deployment completes:

* The orchestrator-related pods are running in the selected namespace.
* Cluster-wide resources are present.
* You can start connecting the orchestrator to your {product} UI.
