:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-operator-partial.adoc_{context}"]
= Installing {product} with Orchestrator in a partially disconnected {ocp-short} environment using the Operator

You can install {product} with Orchestrator plugin in a partial air-gapped environment using Operator.

A disconnected installation prevents unauthorized access, data transfer, or communication with external sources.

You can use the `oc-mirror` command to mirror resources directly to your accessible local mirror registry and apply the generated cluster resources.

.Prerequisites

* You have mirrored the {product} Operator images to the local registry using the {product-very-short} mirroring script. For more information, see {installing-in-air-gap-book-link}#proc-install-rhdh-operator-airgapped-partial.adoc_title-install-rhdh-air-grapped[Installing {product} in a partially disconnected environment with the Operator].

include::snip-installing-the-orchestrator-common-prerequisites.adoc[]

.Procedure

. Create an `ImageSetConfiguration` file for `oc-mirror`. Because `oc-mirror` does not automatically mirror all images required by the Serverless Logic Operator, you must use an `ImageSetConfiguration` file to include them as shown in the following example:
+
[source,subs="+attributes,+quotes"]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  additionalimages:
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-db-migrator-tool-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8:{rhoserverless-version}.0
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
      - name: logic-operator-rhel8
        channels:
        - name: alpha
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.0
      - name: serverless-operator
        channels:
        - name: stable
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.1
----
+
Alternatively, you can use the podman commands to find the missing images and add them to the `additionalimages` list if the versions change:
+
[source,subs="+attributes,+quotes"]
----
IMG=registry.redhat.io/openshift-serverless-1/logic-operator-bundle:{rhoserverless-version}.0-8
mkdir local-manifests-osl
podman create --name temp-container "$IMG" -c "cat /manifests/logic-operator-rhel8.clusterserviceversion.yaml"
podman cp temp-container:/manifests ./local-manifests-osl
podman rm temp-container
yq -r '.data."controllers_cfg.yaml" | from_yaml | .. | select(tag == "!!str") | select(test("^.*\\/.*:.*$"))' ./local-manifests-osl/manifests/logic-operator-rhel8-controllers-config_v1_configmap.yaml
----

. Mirror the images in the `ImageSetConfiguration.yaml` file by running the `oc-mirror` command. For example:
+
[source,subs="+attributes,+quotes"]
----
oc-mirror --config=imagesetconfiguration.yaml docker://<registry URL:port> --workspace file://<workspace folder> --authfile /path/to/authfile  --v2
cd <workspace folder>/working-dir/cluster-resources/
oc apply -f .
----
+
include::snip-installing-the-orchestrator-common-steps.adoc[]
+
. Install the OpenShift Serverless Operator and OpenShift Serverless Logic Operators using the OperatorHub.

. Create a {product-custom-resource-type} custom resource (CR).

. Configure the {product-custom-resource-type} CR for the Orchestrator as described in the {orchestrator-book-link}#con-orchestrator-plugin-dependencies-operator.adoc_orchestrator-rhdh[Orchestrator plugin dependencies for Operator installation].
+
Create all the resources and configure the {product-custom-resource-type} instance accordingly. See {release-notes-book-link}#removed-functionality-rhdhbugs-2000[Configuring a custom NPM registry] for instructions on how to point {product-very-short} towards the custom NPM registry.

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* Once stable, go to the {product-very-short} UI, and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====