:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-helm-chart-partial_{context}"]
= Installing {product} with Orchestrator in a partially disconnected {ocp-short} environment using the Helm chart

You can install {product} ({product-very-short}) with the Orchestrator plugin in a partial {ocp-short} environment using the Helm chart.

A disconnected installation prevents unauthorized access, data transfer, or communication with external sources.

You can use the `oc-mirror` command to mirror resources directly to your accessible local registry and apply the generated cluster resources.

.Prerequisites

include::snip-installing-the-orchestrator-common-prerequisites.adoc[]

.Procedure

. Create an `ImageSetConfiguration` file for `oc-mirror`. You must include the images and operators required by the Serverless Logic Operator in the `ImageSetConfiguration` file, as `oc-mirror` does not automatically mirror all images. Use the following example:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  additionalimages:
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-db-migrator-tool-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel9:{rhoserverless-version}.0
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator@sha256:7355b244d463187b11174b091b10235167ffc6fbd9466ec3cff0a8b5b04d6e98
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend@sha256:05f14d7c6cc41dd50cdb0adafa97137593caa4c218563fcc00bb30d36ad6bf2f
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator@sha256:6a138dd4c6bb7b98d7af58657395fc3ef3b96768276a2d65d9a7ef5fda52f2b5
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:6e12decf7664c5c3410b1c7308eaa6daabeabbbc7baae5beddcdf52afdb702f8

  helm:
    repositories:
      - name: openshift-charts
        url: https://charts.openshift.io
        charts:
          - name: redhat-developer-hub
            version: "{product-bundle-version}"
          - name: redhat-developer-hub-orchestrator-infra
            version: "{product-bundle-version}"
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v<ocp-version>
     # For example: registry.redhat.io/redhat/redhat-operator-index:v{ocp-version}
      packages:
      - name: logic-operator
        channels:
        - name: stable
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.0
      - name: serverless-operator
        channels:
        - name: stable
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.1
----

. Mirror the images in the `ImageSetConfiguration.yaml` file by running the `oc-mirror` command to pull images and charts, and push the images directly to the target registry. For example:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ oc-mirror --config=imagesetconfiguration.yaml docker://<registry URL:port> --workspace file://<workspace folder> --authfile /path/to/authfile  --v2
----
+
[NOTE]
====
The `oc-mirror` command pulls the charts listed in the `ImageSetConfiguration` file and makes them available as `tgz` archives under the `<workspace folder>` directory.
====

. Apply the generated cluster resources to the disconnected cluster. For example:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ cd <workspace folder>/working-dir/cluster-resources/
$ oc apply -f .
----

. Apply the `redhat-developer-hub-orchestrator-infra` Helm chart and approve the install plans. See {installing-in-air-gap-book-link}#assembly-install-rhdh-airgapped-environment-ocp-helm_title-install-rhdh-air-grapped[Air-gapped installation with Helm chart instructions] for details.

. Apply the {product-very-short} {product-version} Helm chart. Include the version {product-bundle-version} and enable the Orchestrator plugin, as shown in the following example:
+
[source,yaml]
----
orchestrator.enabled=true
----

. The {product-very-short} {product-version} Helm chart defaults to pulling Orchestrator plugins from the official {company-name} OCI registry using full URL references. You must override this behavior to point to your local registry.
+
To configure the Orchestrator plugins to use a custom registry, complete the following steps:

** Open your `values.yaml` file.
** Explicitly list the Orchestrator plugin packages under the `orchestrator.plugins` section.
+
You must replace the simplified package references with the full URLs that point to your custom OCI registry. You must explicitly include the `pluginConfig` configuration for each plugin as shown in the following example:
+
[source,yaml]
----
orchestrator:
  plugins:
    - package: oci://<custom_registry_url>/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:<digest>
      disabled: true
      pluginConfig:
        orchestrator:
          dataIndexService:
            url: http://sonataflow-platform-data-index-service
    - package: oci://<custom_registry_url>/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets:<digest>
      disabled: true
      pluginConfig:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-orchestrator-form-widgets: {}
    - package: oci://<custom_registry_url>/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator:<digest>
      disabled: true
      pluginConfig:
        dynamicPlugins:
          frontend:
            red-hat-developer-hub.backstage-plugin-orchestrator:
              appIcons:
              - importName: OrchestratorIcon
                name: orchestratorIcon
              dynamicRoutes:
              - importName: OrchestratorPage
                menuItem:
                  icon: orchestratorIcon
                  text: Orchestrator
                  textKey: menuItem.orchestrator
                path: /orchestrator
              entityTabs:
              - path: /workflows
                title: Workflows
                titleKey: catalog.entityPage.workflows.title
                mountPoint: entity.page.workflows
              mountPoints:
              - mountPoint: entity.page.workflows/cards
                importName: OrchestratorCatalogTab
                config:
                  layout:
                  gridColumn: 1 / -1
                  if:
                    anyOf:
                    - IsOrchestratorCatalogTabAvailable
    - - package: oci://<custom_registry_url>/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator:<digest>
      disabled: true
      pluginConfig:
        orchestrator:
          dataIndexService:
            url: http://sonataflow-platform-data-index-service
----
+
where:

`<custom_registry_url>`::
Enter the address of your custom registry where the OCI images have been mirrored.

`<digest>`::
Locate the image digests for your version of {product-very-short} in the `dynamic-plugins.default.yaml` file. You can extract this file from the plugin catalog index image to verify the default settings for your specific release:
+
[source,bash,subs="+attributes,+quotes"]
----
#!/bin/bash

unpack () {
  local IMAGE="$1"
  DIR="${IMAGE//:/_}"
  DIR="/tmp/${DIR//\//-}"
  rm -fr "$DIR"; mkdir -p "$DIR"; container_id=$(podman create "${IMAGE}")
  podman export $container_id -o /tmp/image.tar && tar xf /tmp/image.tar -C "${DIR}/"; podman rm $container_id; rm -f /tmp/image.tar
  echo "Unpacked $IMAGE into $DIR"
  cd $DIR; tree -d -L 3 -I "usr|root|buildinfo"
}

unpack "registry.access.redhat.com/rhdh/plugin-catalog-index:1.9"

# you can then find the `dynamic-plugins.default.yaml` under /tmp/registry.access.redhat.com/rhdh/plugin-catalog-index_1.9/dynamic-plugins.default.yaml
----

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* After deployment is complete, go to the **{product-very-short}** UI and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====
