:_mod-docs-content-type: PROCEDURE

[id="proc-installing-the-orchestrator-software-templates-chart_{context}"]
= Installing the Orchestrator Software Templates chart

The `orchestrator-software-templates` chart loads the actual software templates into your {product-very-short} instance. This allows users to select workflow templates from the {product-very-short} Catalog.

.Prerequisites

* You have installed the `orchestrator-software-templates-infra` chart for deploying OpenShift Pipelines (Tekton) operator and OpenShift GitOps (ArgoCD) operator in the same namespace as {product-very-short}.

* You have labeled the {product-very-short} namespace to enable GitOps sync:
+
[source,terminal]
----
$ oc label ns rhdh rhdh.redhat.com/argocd-namespace=true
----

* You have created a secret named `orchestrator-auth-secret` in the {product-very-short} namespace containing the following keys:

** `BACKEND_SECRET`: Backend authentication secret
** `K8S_CLUSTER_TOKEN`: Kubernetes cluster token
** `K8S_CLUSTER_URL`: Kubernetes cluster URL
** `GITHUB_TOKEN`: GitHub access token (optional)
** `GITHUB_CLIENT_ID`: GitHub OAuth client ID (optional)
** `GITHUB_CLIENT_SECRET`: GitHub OAuth client secret (optional)
** `GITLAB_HOST`: GitLab host URL (optional)
** `GITLAB_TOKEN`: GitLab access token (optional)
** `ARGOCD_URL`: ArgoCD server URL (optional)
** `ARGOCD_USERNAME`: ArgoCD username (optional)
** `ARGOCD_PASSWORD`: ArgoCD password (optional)

.Procedure
. Install the software templates chart:
+
[source,terminal]
----
$ helm repo add redhat-developer https://redhat-developer.github.io/rhdh-chart
$ helm install my-orchestrator-templates redhat-developer/orchestrator-software-templates --version 0.2.0
----

. Follow the post-installation notes to create a custom `values.yaml` file to update your {product-very-short} configuration.

. Make sure the templates appear in the {product-very-short} UI under the *Create* sidebar menu.
