:_mod-docs-content-type: PROCEDURE

[id="proc-install-rhdh-orchestrator-airgapped-env-using-operator-full_{context}"]
= Installing {product} with Orchestrator in a fully disconnected {ocp-short} environment using the Operator

You can install {product} with Orchestrator plugin in a fully air-gapped environment using the Operator.

A disconnected installation prevents unauthorized access, data transfer, or communication with external sources.

You can use the helper script to install {product} by mirroring the Operator-related images to disk and transferring them to your disconnected environment without any connection to the internet.

.Prerequisites

* You have mirrored the {product} Operator images to the local registry using the {product-very-short} mirroring script. For more information, see {installing-in-air-gap-book-link}#proc-install-rhdh-operator-airgapped-full.adoc_title-install-rhdh-air-grapped[_Installing {product} in a fully disconnected environment with the Operator_].

include::snip-installing-the-orchestrator-common-prerequisites.adoc[]

.Procedure

. Create an `ImageSetConfiguration` file for `oc-mirror`. You must include the images and operators required by the Serverless Logic Operator in the `ImageSetConfiguration` file, as `oc-mirror` does not automatically mirror all images. Use the following example:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  additionalimages:
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-postgresql-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-jobs-service-ephemeral-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-postgresql-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-data-index-ephemeral-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-db-migrator-tool-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel9:{rhoserverless-version}.0
  - name: registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel9:{rhoserverless-version}.0
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator@sha256:7355b244d463187b11174b091b10235167ffc6fbd9466ec3cff0a8b5b04d6e98
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-backend@sha256:05f14d7c6cc41dd50cdb0adafa97137593caa4c218563fcc00bb30d36ad6bf2f
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-scaffolder-backend-module-orchestrator@sha256:6a138dd4c6bb7b98d7af58657395fc3ef3b96768276a2d65d9a7ef5fda52f2b5
  - name: registry.access.redhat.com/rhdh/red-hat-developer-hub-backstage-plugin-orchestrator-form-widgets@sha256:6e12decf7664c5c3410b1c7308eaa6daabeabbbc7baae5beddcdf52afdb702f8
  
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v{ocp-version}
      # For example: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
      - name: logic-operator-rhel9
        channels:
        - name: alpha
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.0
      - name: serverless-operator
        channels:
        - name: stable
          minVersion: {rhoserverless-version}.0
          maxVersion: {rhoserverless-version}.1
----
+
Alternatively, you can use `podman` commands to find the missing images and add them to the `additionalimages` list if the versions change:
+
[source,terminal,subs="+attributes,+quotes"]
----
IMG=registry.redhat.io/openshift-serverless-1/logic-operator-bundle:{rhoserverless-version}.0
mkdir local-manifests-osl
podman create --name temp-container "$IMG" -c "cat /manifests/logic-operator-rhel9.clusterserviceversion.yaml"
podman cp temp-container:/manifests ./local-manifests-osl
podman rm temp-container
yq -r '.data."controllers_cfg.yaml" | from_yaml | .. | select(tag == "!!str") | select(test("^.*\\/.*:.*$"))' ./local-manifests-osl/manifests/logic-operator-rhel9-controllers-config_v1_configmap.yaml
----

. Mirror the images in the `ImageSetConfiguration.yaml` file by running the `oc-mirror` command. For example:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ oc-mirror --config=ImageSetConfiguration.yaml file:///path/to/mirror-archive --authfile /path/to/authfile  --v2
----
+
[NOTE]
====
The `oc-mirror` command generates a local workspace containing the mirror archive files and the required cluster manifests.
====
+
. Transfer the directory specified by `/path/to/mirror-archive` to a bastion host within your disconnected environment.

. From the bastion host which has access to the mirror registry, mirror the images from the disk directory to your target registry. For example:
+
[source,yaml,subs="+attributes,+quotes"]
----
$ oc-mirror --v2 --from <mirror-archive-file> docker://<target-registry-url:port> --workspace file://<workspace folder> --authfile /path/to/authfile
----
+
where:

`<mirror-archive-file>`:: Enter the name of the transferred `tar` file.

`<target-registry-url:port>`:: Enter your local registry, for example, `registry.localhost:5000`.
+
. Apply the cluster-wide resources generated during the push step to redirect all image pulls to your local registry, as shown in the following example:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ cd <workspace folder>/working-dir/cluster-resources/
$ oc apply -f .
----
+
. Install the OpenShift Serverless Operator and OpenShift Serverless Logic Operators using `OperatorHub`.

. Create a {product-custom-resource-type} custom resource (CR).

. Configure the {product-custom-resource-type} CR for the Orchestrator as described in the {orchestrator-book-link}#con-orchestrator-plugin-dependencies-operator.adoc_orchestrator-rhdh[Orchestrator plugin dependencies for Operator installation].
+
Create all the resources and configure the {product-custom-resource-type} instance accordingly.

.Verification

* Restart the {product-very-short} pod and wait for the components to deploy properly.

* Once stable, go to the {product-very-short} UI, and confirm that the Orchestrator UI is accessible and functioning correctly.

[NOTE]
====
The successful accessibility of the Orchestrator UI confirms that the underlying components are running and the cluster recognizes the plugin.
====
