:_mod-docs-content-type: PROCEDURE

[id="proc-creating-and-running-workflows_{context}"]
= Creating and running your serverless workflow project locally

The `kn-workflow` CLI is an essential tool that generates workflow manifests and project structures. To ensure successful development and immediate testing, begin developing a new serverless workflow locally by completing the following steps:

.Procedure
. Use the `kn-workflow` CLI to create a new workflow project, which adheres to the Quarkus structure as shown in the following example:
+
[source,bash]
----
$ kn-workflow quarkus create --name <specify project name, for example ,00_new_project>
----

. Edit the workflow, add schema and specific files, and run it locally from project folder as shown in the following example:
+
[source,bash]
----
$ kn-workflow quarkus run
----
. Run the workflow locally using the `kn-workflow run` which pulls the following image:
+
[source,yaml,subs=+attributes,+quotes]
----
registry.redhat.io/openshift-serverless-1/logic-swf-devmode-rhel8:{rhoserverless-version}
----

. For building the workflow image, the `kn-workflow` CLI pulls the following images:
+
[source,yaml,subs=+attributes,+quotes]
----
registry.redhat.io/openshift-serverless-1/logic-swf-builder-rhel8:{rhoserverless-version}-8
registry.access.redhat.com/ubi9/openjdk-17:1.21-2
----

[role="_additional-resources"]
.Additional resources

* link:https://openshift-knative.github.io/docs/docs/latest/serverless-logic/about.html[About OpenShift Serverless Logic]
* link:https://redhat-scholars.github.io/serverless-workflow/osl/index.html[OpenShift Serverless Logic Tutorial]
* {configuring-book-link}#running-behind-a-proxy[Running {product} behind a corporate proxy]
* link:https://docs.redhat.com/en/documentation/red_hat_build_of_quarkus/3.15/html-single/getting_started_with_red_hat_build_of_quarkus/index#proc_online-maven_quarkus-getting-started[Using the Red Hat-hosted Quarkus repository]