[id="con-telemetry-data-collection-and-analysis_{context}"]
= Telemetry data collection and analysis

The telemetry data collection feature helps in collecting and analyzing the telemetry data to improve your experience with {product}. This feature is enabled by default.

{company-name} collects and analyzes the following data:

Web Analytics::

* Web Analytics use the Segment tool.

* It is the tracking of user behavior and interactions with {product}.

Specifically, it tracks the following:

* Events of page visits and clicks on links or buttons.
* System-related information, for example, locale, time zone, user agent including browser and operating system details.
* Page-related information, for example, title, category, extension name, URL, path, referrer, and search parameters.
* Anonymized IP addresses, recorded as `0.0.0.0`.
* Anonymized username hashes, which are unique identifiers used solely to identify the number of unique users of the {product-very-short} application.

System Observability::

* System Observability uses the OpenTelemetry tool.

* It is the tracking of the performance of the {product-very-short}.

Specifically, it tracks the following metrics:

* Key system metrics such as CPU usage, memory usage, and other performance indicators.
* Information about system components, such as the locale, time zone, and user agent (including details of the browser and operating system).
* Traces and logs monitor system processes, allowing you to troubleshoot potential issues impacting the performance of {product-very-short}.

With {product-very-short}, you can customize the _Web Analytics_ and _System Observability_ configuration based on your needs.