:_mod-docs-content-type: ASSEMBLY
:context: customize-the-tech-radar-page

[id="customize-the-tech-radar-page_{context}"]
= Customize the Tech Radar page in {product}

[role="_abstract"]
In {product}, the Tech Radar page is provided by the `tech-radar` dynamic plugin, which is disabled by default. For information about enabling dynamic plugins in {product} see {configuring-dynamic-plugins-book-link}[{configuring-dynamic-plugins-book-title}].

In {product}, you can configure Learning Paths by passing the data into the `{my-app-config-file}` file as a proxy. The base Tech Radar URL must include the `/developer-hub/tech-radar` proxy.

[NOTE]
====
Due to the use of overlapping `pathRewrites` for both the `tech-radar` and `homepage` quick access proxies, you must create the `tech-radar` configuration (`^api/proxy/developer-hub/tech-radar`) before you create the `homepage` configuration (`^/api/proxy/developer-hub`).

For more information about customizing the Home page in {product}, see xref:customize-the-home-page_customize-the-home-page[Customize the Home page].
====

You can provide data to the Tech Radar page from the following sources:

* JSON files hosted on GitHub or GitLab.
* A dedicated service that provides the Tech Radar data in JSON format using an API.

include::modules/customizing/proc-customize-the-tech-radar-page-by-using-a-json-file.adoc[leveloffset=+1]

include::modules/customizing/proc-customize-the-tech-radar-page-by-using-a-customization-service.adoc[leveloffset=+1]
