:_mod-docs-content-type: ASSEMBLY

[id="locate-software-components-to-discover-assets"]
= Find software components to discover assets

To integrate with existing software, verify ownership, or prevent redundant development, use the Software Catalog in {product} ({product-very-short}). You can use this centralized inventory to discover assets without searching through multiple documentation sources or repositories.

By using the Software Catalog, you can achieve the following outcomes:

Reuse existing code::
Locate shared libraries and components to prevent duplication of effort.

Understand dependencies::
Visualize connections between services and API contracts.

Identify ownership::
Find the team or individual responsible for an asset to facilitate collaboration.

[NOTE]
====
Your administrator must grant specific permissions if you want to add the products you are working on to this catalog. Contact your administrator for more information.
====

include::modules/navigate-rhdh-on-your-first-day/proc-filtering-components-in-software-catalog.adoc[leveloffset=+1]

include::modules/navigate-rhdh-on-your-first-day/proc-analyzing-microservice-dependencies.adoc[leveloffset=+1]

include::modules/navigate-rhdh-on-your-first-day/proc-reviewing-api-contracts.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* {about-book-link}[{about-book-title}]
* {customizing-book-link}[{customizing-book-title}]
