:_mod-docs-content-type: ASSEMBLY

[id="con-policy-effect_{context}"]
= How {product} resolves conflicting permissions

When permission rules for the same access request type and user role conflict, the _policy effect_ determines the outcome. The {product} policy effect increases security in two ways:

* `Deny` rules override `allow` rules.
+ 
The policy effect prioritizes `deny` rules whenever they conflict with `allow` rules. Consider this scenario:
+
[source, Casbin]
.Rule for group_a (Allows access)
p, role:default/allow-role, catalog-entity, read, allow
g, group:default/group_a, role:default/allow-role
+
[source, Casbin]
.Rule for group_b (Denies access)
p, role:default/deny-role, catalog-entity, read, deny
g, group:default/group_b, role:default/deny-role
+
If a user belongs to both `group_a` and `group_b`, the policy effect denies them access.
+
NOTE: Denying access is the default policy effect, meaning that if no rules match an access request, the request is denied.

* Conditional rules override basic rules.
+ 
If a basic rule permits an action but conflicts with a conditional rule, {product-very-short} applies the conditional rule.

include::modules/authorization/con-rbac-policies-best-practices.adoc[leveloffset=+1]
