:_mod-docs-content-type: ASSEMBLY
:context: configuring-external-postgresql-databases
[id="{context}"]
= Configuring external PostgreSQL databases

As an administrator, you can configure and use external PostgreSQL databases in {product}. You can use a PostgreSQL certificate file to configure an external PostgreSQL instance using the Operator or Helm Chart.

[NOTE]
====
{product-short} supports the configuration of external PostgreSQL databases. You can perform maintenance activities, such as backing up your data or configuring high availability (HA) for the external PostgreSQL databases.

By default, the {product} operator or Helm Chart creates a local PostgreSQL database. However, this configuration is not suitable for the production environments. For production deployments, disable the creation of local database and configure {product-short} to connect to an external PostgreSQL instance instead.
====


include::modules/configuring-external-databases/proc-configuring-postgresql-instance-using-the-operator.adoc[leveloffset=+1]


include::modules/configuring-external-databases/proc-configuring-postgresql-instance-using-helm.adoc[leveloffset=+1]


include::modules/configuring-external-databases/proc-migrating-databases-to-an-external-server.adoc[leveloffset=+1]

