:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="assembly-orchestrator-rhdh.adoc"]
endif::[]
ifdef::context[]
[id="assembly-orchestrator-rhdh"]
endif::[]
:context: orchestrator-rhdh
= About Orchestrator in {product}

You can streamline and automate your work by using the Orchestrator in {product}. It enables you to:

* Design, run, and monitor workflows to simplify multi-step processes across applications and services.
* Standardize onboarding, migration, and integration workflows to reduce manual effort and improve consistency.
* Extend {product-very-short} with enterprise-grade Orchestration features to support collaboration and scalability.

[NOTE]
====
Orchestrator currently supports only {ocp-brand-name} ({ocp-short}); it is not available on {aks-brand-name} ({aks-short}), {eks-brand-name} ({eks-short}), or {gke-brand-name} ({gke-short}).
====

To start using Orchestrator in {product-very-short}, you must:

* Install the required infrastructure components, such as Red Hat OpenShift Serverless Operator, Knative Serving, Knative Eventing, and OpenShift Serverless Logic Operator
* Configure your {product-custom-resource-type} custom resource (CR) or Helm values file for Orchestrator
* Import the Orchestrator software templates into the {product} catalog

// orchestrator architecture
include::modules/orchestrator/con-supported-architecture-for-orchestrator.adoc[leveloffset=+1]

// provisioning plugin dependencies
include::modules/orchestrator/con-understanding-orchestrator-plugin-dependencies-operator.adoc[leveloffset=+1]

// installing the components for the orchestrator plugin
include::modules/orchestrator/con-install-components-orchestrator-plugin.adoc[leveloffset=+1]

// Orchestrator Infrastructure for {product} Helm chart
include::modules/orchestrator/proc-helm-install-components-orchestrator-plugin.adoc[leveloffset=+2]

// manual installation
include::modules/orchestrator/proc-manual-install-components-orchestrator-plugin.adoc[leveloffset=+2]

// {product-very-short} helper script
include::modules/orchestrator/con-helper-scripts-overview.adoc[leveloffset=+2]

include::modules/orchestrator/proc-setup-sh-init-script.adoc[leveloffset=+3]

include::modules/orchestrator/proc-plugin-infra-install.adoc[leveloffset=+3]

