:_mod-docs-content-type: ASSEMBLY

[id="configuring-rhdh-events-module"]

= Configuring {product} Events Module

The Events Module is an alternative to scheduled updates for your GitHub user or catalog entities.
You can set up push notifications to make sure your entities are updated whenever changes occur in the external system.
This is a Developer Preview feature.

[IMPORTANT]
====
Developer Preview features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use Developer Preview features for production or business-critical workloads. Developer Preview features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. Developer Preview features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on Developer Preview features without an associated SLA.

For more information about the support scope of Red Hat Developer Preview features, see link:https://access.redhat.com/support/offerings/devpreview/[Developer Preview Support Scope].
====

include::modules/dynamic-plugins/proc-configuring-events-module-for-github.adoc[leveloffset=+1]
