:_mod-docs-content-type: ASSEMBLY

[id="install-product-on-a-supported-kubernetes-platform-in-an-air-gapped-environment-with-the-helm-chart_{context}"]
= Install {product} on a supported Kubernetes platform in an air-gapped environment with the Helm chart

[role="_abstract"]
Install {product} on supported Kubernetes platforms in fully or partially disconnected environments by using the Helm chart.

If you are using a supported Kubernetes platform in a fully disconnected or partially disconnected environment, you can install {product} by using the Helm chart.
Supported Kubernetes platforms include the following:

* {aks-brand-name}
* {eks-brand-name}
* {gke-brand-name}

include::modules/install-rhdh-air-gapped/proc-install-product-on-a-supported-kubernetes-platform-in-a-fully-disconnected-environment-with-the-helm-chart.adoc[leveloffset=+1]

include::modules/install-rhdh-air-gapped/proc-install-product-on-a-supported-kubernetes-platform-in-a-partially-disconnected-environment-with-the-helm-chart.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* {installing-on-aks-book-link}#proc-rhdh-deploy-aks-helm_title-install-rhdh-aks[Deploying {product-short} on {aks-short} with the Helm chart]
* {installing-on-eks-book-link}#proc-rhdh-deploy-eks-helm_title-install-rhdh-eks[Installing {product-short} on {eks-short} with the Helm chart]
* {installing-on-gke-book-link}#proc-rhdh-deploy-gke-helm_title-install-rhdh-gke[Installing {product-short} on {gke-short} with the Helm chart]
