:_mod-docs-content-type: ASSEMBLY

[id="assembly-automating-workflow-deployment-with-orchestrator"]
= Automating workflow deployment with Orchestrator

The Orchestrator plugin for {product} ({product-very-short}) automates the software development lifecycle (SDLC) for serverless workflows. By using the Orchestrator link:https://github.com/rhdhorchestrator/workflow-software-templates[software templates], you bootstrap a complete serverless workflow project that includes a fully operational Git repository, deployment configurations, and automated Continuous Integration (CI) and Continuous Deployment (CD) pipelines.

The Orchestrator plugin integrates these components:

{product-very-short} Helm chart:: Installs the {product-very-short} Orchestrator.

Tekton or Red Hat OpenShift Pipelines:: Manages the `Kubernetes-native` CI pipeline to build images.

ArgoCD or Red Hat OpenShift GitOps:: Manages the CD pipeline to deploy the workflow on the {product-very-short} instance.

Quay.io:: Stores the container images generated by the pipelines.

OpenShift Serverless Logic operator:: Implements serverless workflow specifications

// installing Orchestrator software templates
include::modules/orchestrator/proc-installing-orchestrator-software-templates.adoc[leveloffset=+1]

// installing the Orchestrator Software Templates Infra chart
include::modules/orchestrator/proc-installing-the-orchestrator-software-templates-infra-chart.adoc[leveloffset=+2]

// installing the Orchestrator Software Templates chart
include::modules/orchestrator/proc-installing-the-orchestrator-software-templates-chart.adoc[leveloffset=+2]

// creating a serverless workflow project
include::modules/orchestrator/proc-creating-a-serverless-workflow-project.adoc[leveloffset=+1]

// bootstrapping GitOps resources and triggering pipelines
include::modules/orchestrator/proc-bootstrapping-gitops-resources-and-triggering-pipelines.adoc[leveloffset=+1]

// verifying the deployment
include::modules/orchestrator/proc-verifying-the-deployment.adoc[leveloffset=+1]

// troubleshooting the CI/CD pipeline
include::modules/orchestrator/proc-troubleshooting-the-pipelines.adoc[leveloffset=+1]