ifdef::context[:parent-context-of-about-rhdh: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="about-rhdh"]
endif::[]
ifdef::context[]
[id="about-rhdh_{context}"]
endif::[]
= About {product}

:context: about-rhdh

{product} ({product-very-short}) is an enterprise-grade internal developer portal designed to simplify and streamline software development processes. Combined with {ocp-brand-name}, {product-very-short} empowers platform engineering teams to create customized portals that improve developer productivity, accelerate onboarding, and enable faster application delivery. By reducing friction and complexity, {product-very-short} allows developers to focus on writing high-quality code while adhering to enterprise-class best practices.

{product-very-short} integrates software templates, pre-designed solutions, and dynamic plugins into a centralized platform, providing tailored solutions for operations and development teams in a unified environment.

include::modules/about/con-benefits-of-rhdh.adoc[leveloffset=+1]
include::modules/about/con_integrations-in-rhdh.adoc[leveloffset=+1]
include::modules/about/ref-supported-platforms.adoc[leveloffset=+1]
include::modules/about/ref-rhdh-sizing.adoc[leveloffset=+1]
include::modules/about/ref-customer-support-info.adoc[leveloffset=+1]
