ifdef::context[:parent-context-of-about-rhdh: {context}]

:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="about-rhdh"]
endif::[]
ifdef::context[]
[id="about-rhdh_{context}"]
endif::[]
= About {product} 

:context: about-rhdh

{product} ({product-very-short}) is all about making your development process smoother and more efficient. It unifies all the tools and resources your team needs into one platform, helping you collaborate better and get your applications from code to deployment faster.

== Why use {product}

* *Boost developer productivity:* Say goodbye to common organizational hiccups. With clear guidelines and automated processes your team can focus on what they do best - writing great code.

* *Unified dashboard:* Access everything in one place - from Git repositories and CI/CD pipelines to issue tracking, monitoring, and documentation. With over 150 plugins, it's all curated to fit your company's best practices.

* *Built-in best practices:* Use software templates that encode your organization's standards, making tasks such as creating new applications or setting up CI/CD pipelines a breeze.

* *Easy onboarding:* New developers can get up to speed quickly, thanks to standardized tools and processes that reduce the learning curve.

* *Robust security and access control:* Manage rules and permissions effectively with enterprise-grade role-based access control (RBAC), keeping your projects secure.

* *Scalable documentation:* Keep your code and documentation together in the same repository, so everything stays in sync without relying on separate systems.

// Placeholder to include add Supported platforms .adoc file - https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/661/files#top

include::modules/about/con_elevate-your-development-with-secure-templates.adoc[leveloffset=+1]

[role="_additional-resources"]
== Next steps

* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}#Install%20and%20Upgrade[{product} Installation and upgrade guides]

[role="_additional-resources"]
== Additional resources

* link:https://docs.redhat.com/en/documentation/red_hat_trusted_application_pipeline/{rhtap-version}/html/getting_started_with_red_hat_trusted_application_pipeline/index[Getting Started with Red Hat trusted application pipeline]

* link:https://docs.redhat.com/en/documentation/openshift_container_platform[OpenShift documentation]
