:_mod-docs-content-type: ASSEMBLY
:context: techdocs-addon-installing
[id="techdocs-addon-installing"]
= Installing and configuring a TechDocs add-on

TechDocs add-ons supported by {company-name} are exported to the TechDocs plugin by the`backstage-plugin-techdocs-module-addons-contrib` plugin package, which is preinstalled on {product} and enabled by default. The `<ReportIssue />` add-on is part of the default configuration of this plugin package and comes ready to use in the TechDocs plugin. You can install other supported TechDocs add-ons by configuring the`backstage-plugin-techdocs-module-addons-contrib` plugin package in the {product} ConfigMap or Helm chart, depending on whether you use the Operator or Helm chart for installation. If you want to customize your TechDocs experience beyond the functions of the supported add-ons, you can install third-party add-ons on your TechDocs plugin, including add-ons that you create yourself.

include::modules/techdocs/proc-techdocs-addon-install-operator.adoc[]

include::modules/techdocs/proc-techdocs-addon-install-helm.adoc[]

include::modules/techdocs/proc-techdocs-addon-install-third-party.adoc[]

.Additional resources
* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html/installing_and_viewing_plugins_in_red_hat_developer_hub/rhdh-installing-rhdh-plugins_title-plugins-rhdh-about[Installing dynamic plugins in Red Hat Developer Hub]
* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html/installing_and_viewing_plugins_in_red_hat_developer_hub/assembly-third-party-plugins[Third-party plugins in Red Hat Developer Hub]
