:_mod-docs-content-type: ASSEMBLY

[id="configure-red-hat-developer-hub-events-module_{context}"]

= Configure {product} events module
:context: configure-red-hat-developer-hub-events-module

[role="_abstract"]
Enable real-time updates for GitHub entities by configuring the Events Module with webhooks.

Use the Events Module together with scheduled updates to make sure that the external system updates your GitHub user or catalog entities whenever changes occur.

[IMPORTANT]
====
This is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs). They might not be functionally complete. Red Hat does not recommend using them in production. These features offer early access to upcoming product features. Customers can test functionality and give feedback during the development process.
====

include::modules/configuring-dynamic-plugins/proc-configure-the-github-events-module-plugin.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope]
