:_mod-docs-content-type: ASSEMBLY
:context: about-software-catalogs
[id="{context}"]
= About Software Catalogs

The {product} Software Catalog is a centralized system that gives you visibility into all the software across your ecosystem, including services, websites, libraries, and data pipelines. You can use it to view ownership details and metadata for each component in one place.

The metadata for the components in your Software Catalog is stored as YAML files that live alongside your code in your version control system. The version control repositories can include one or many metadata files. Software Catalog organizes items as entities, which include Components, Resources, and APIs, and other related types. Each entity includes associated metadata such as its owner, type, and other relevant details.

By storing metadata in YAML files alongside the code, you allow {product} to process and display this information through a clear, visual interface. With the Software Catalog, you can manage and maintain your software, stay aware of all software available in your ecosystem, and take ownership of your services and tools.

//[Add a Software Catalog screenshot of the latest build]

The *Overview* page for a component provides key information such as links to the source code, documentation, dependencies, and ownership details. You can customize this page with plugins to suit specific needs.

//[Add any Component screenshot of the latest build]

include::modules/software-catalogs/proc-adding-new-components-to-the-rhdh-instance.adoc[leveloffset=+1]
include::modules/software-catalogs/proc-updating-components-in-the-software-catalog.adoc[leveloffset=+1]
include::modules/software-catalogs/proc-searching-and-filter-software-catalogs.adoc[leveloffset=+1]
include::modules/software-catalogs/proc-viewing-software-catalog-yaml.adoc[leveloffset=+1]
include::modules/software-catalogs/proc-starring-components-in-the-software-catalog.adoc[leveloffset=+1]