:_mod-docs-content-type: ASSEMBLY
:context: configure-techdocs

[id="{context}"]
= Configure TechDocs

[role="_abstract"]
The TechDocs plugin is preinstalled and enabled on a {product-short} instance by default. You can disable or enable the TechDocs plugin, and change other parameters, by configuring the {product} Helm chart or the {product} Operator ConfigMap.

[IMPORTANT]
====
{product} includes a built-in TechDocs builder that generates static HTML documentation from your codebase. However, the default basic setup of the local builder is not intended for production.
====

You can use a CI/CD pipeline with the repository that has a dedicated job to generate docs for TechDocs. The generated static files are stored in {odf-name} or in a cloud storage solution of your choice and published to a static HTML documentation site.

After you configure {odf-name} to store the files that TechDocs generates, you can configure the TechDocs plugin to use the {odf-name} for cloud storage.

//configuring storage
include::modules/customizing-techdocs/con-configuring-storage-for-techdocs-files.adoc[leveloffset=+1]

//configuring storage - Amazon S3
include::modules/techdocs/proc-configure-amazon-s3-for-file-storage.adoc[leveloffset=+2]

//configuring storage - ODF
include::modules/customizing-techdocs/proc-configure-openshift-data-foundation-for-file-storage.adoc[leveloffset=+2]

include::modules/customizing-techdocs/proc-make-object-storage-accessible-to-containers-by-using-the-helm-chart.adoc[leveloffset=+3]

include::modules/customizing-techdocs/ref-example-techdocs-plugin-configuration-for-the-helm-chart.adoc[leveloffset=+4]

include::modules/customizing-techdocs/proc-make-object-storage-accessible-to-containers-by-using-the-operator.adoc[leveloffset=+3]

include::modules/customizing-techdocs/ref-example-techdocs-plugin-configuration-for-the-operator.adoc[leveloffset=+4]

//configuring CI/CD
include::modules/customizing-techdocs/con-configuring-ci-cd-to-generate-and-publish-techdocs-sites.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources

* {configuring-dynamic-plugins-book-link}[{configuring-dynamic-plugins-book-title}]
