:_mod-docs-content-type: ASSEMBLY

ifndef::context[]
[id="assembly-orchestrator-rhdh.adoc"]
endif::[]
ifdef::context[]
[id="assembly-orchestrator-rhdh"]
endif::[]
:context: orchestrator-rhdh
= About Orchestrator in {product}

You can streamline and automate your work by using the Orchestrator in {product}. It enables you to:

* Design, execute, and monitor workflows to simplify multi-step processes across applications and services.
* Standardize onboarding, migration, and integration workflows to reduce manual effort and improve consistency.
* Extend {product-very-short} with enterprise-grade Orchestration features to support collaboration and scalability.

To start using Orchestrator in {product-very-short}, you must:

* Install the required infrastructure components, such as Red Hat OpenShift Serverless Operator, Knative Serving, Knative Eventing, and OpenShift Serverless Logic Operator
* Configure your Backstage custom resource (CR) for Orchestrator
* Import the Orchestrator software templates into the {product} catalog

// orchestrator architecture
include::modules/orchestrator/con-supported-architecture-for-orchestrator.adoc[leveloffset=+1]

// provisioning plugin dependencies
include::modules/orchestrator/con-understanding-orchestrator-plugin-dependencies.adoc[leveloffset=+1]

// installing the components for the orchestrator plugin
include::modules/orchestrator/proc-install-components-for-orchestrator-plugin.adoc[leveloffset=+1]