:_mod-docs-content-type: ASSEMBLY

[id="configuring-rhdh-events-module"]

= Configuring {product} Events Module

The Events module offers an alternative to scheduled updates for your GitHub user or catalog entities. You can set up push notifications to ensure your entities are updated whenever changes occur in the external system.   
This is a Technology Preview feature.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

include::modules/dynamic-plugins/proc-configuring-events-module-for-github.adoc[leveloffset=+1]
