:_mod-docs-content-type: ASSEMBLY
[id="assembly-customize-rhdh-theme"]
= Customizing the appearance of your {product} instance
:context: assembly-customize-rhdh-theme

The following default theme configurations are available for {product}:

The {product} theme:: Default theme configurations to make your developer portal look like a standard {product} instance. For more information, see xref:ref-customize-rhdh-default-rhdh_{context}[]

The Backstage theme:: Default theme configurations to make your developer portal look like a standard Backstage instance. For more information, see xref:ref-customize-rhdh-default-backstage_{context}[]

You can change or disable particular parameters in a default theme or create a fully customized theme by modifying the `app-config-rhdh.yaml` file. From the the `app-config-rhdh.yaml` file, you can customize common theme components, including the following:

* Company name and logo
* Font color, size, and style of text in paragraphs, headings, headers, and buttons
* Header color, gradient, and shape
* Button color
* Navigation indicator color

You can also customize some components from the {product-short} GUI, such as the theme mode (*Light Theme*, *Dark Theme*, or *Auto*).

include::modules/customization/proc-customize-rhdh-theme-mode.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-branding-logo.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-sidebar-logo.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-tab-tooltip.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-palette.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-page-theme.adoc[leveloffset=+1]

include::modules/customization/proc-customize-rhdh-font.adoc[leveloffset=+1]

include::modules/customization/ref-customize-rhdh-default-rhdh.adoc[leveloffset=+1]

include::modules/customization/ref-customize-rhdh-default-backstage.adoc[leveloffset=+1]

include::modules/customization/ref-customize-rhdh-custom-components.adoc[leveloffset=+1]
