:_mod-docs-content-type: ASSEMBLY
[id="assembly-techdocs-plugin_{context}"]
= Configuring the TechDocs plugin in {product}

The {product} TechDocs plugin helps your organization create, find, and use documentation in a central location and in a standardized way. For example:

Docs-like-code approach::
Write your technical documentation in Markdown files that are stored inside your project repository along with your code.

Documentation site generation::
Use MkDocs to create a full-featured, Markdown-based, static HTML site for your documentation that is rendered centrally in {product-short}.

Documentation site metadata and integrations::
See additional metadata about the documentation site alongside the static documentation, such as the date of the last update, the site owner, top contributors, open GitHub issues, Slack support channels, and Stack Overflow Enterprise tags.

Built-in navigation and search::
Find the information that you want from a document more quickly and easily.

Add-ons::
Customize your TechDocs experience with Add-ons to address higher-order documentation needs.

The TechDocs plugin is preinstalled and enabled on a {product-short} instance by default. You can disable or enable the TechDocs plugin, and change other parameters, by configuring the {product} Helm chart or the {product} Operator config map.

[IMPORTANT]
====
{product} includes a built-in TechDocs builder that generates static HTML documentation from your codebase. However, the default basic setup of the local builder is not intended for production.
====

You can use a CI/CD pipeline with the repository that has a dedicated job to generate docs for TechDocs. The generated static files are stored in {odf-name} or in a cloud storage solution of your choice and published to a static HTML documentation site.

After you configure {odf-name} to store the files that TechDocs generates, you can configure the TechDocs plugin to use the {odf-name} for cloud storage.

[role="_additional-resources"]
.Additional resources

* For more information, see link:{LinkPluginsGuide}[Configuring plugins in {product}].

//Configuring storage
include::modules/getting-started/con-techdocs-configure-storage.adoc[leveloffset=+1]

include::modules/getting-started/proc-techdocs-using-odf-storage.adoc[leveloffset=+2]

include::modules/getting-started/proc-techdocs-configure-odf-helm.adoc[leveloffset=+2]

include::modules/getting-started/ref-techdocs-example-config-plugin-helm.adoc[leveloffset=+3]

include::modules/getting-started/proc-techdocs-configure-odf-operator.adoc[leveloffset=+2]

include::modules/getting-started/ref-techdocs-example-config-plugin-operator.adoc[leveloffset=+3]

//Configuring CI/CD
include::modules/getting-started/con-techdocs-config-cicd.adoc[leveloffset=+1]

include::modules/getting-started/proc-techdocs-config-cicd-prep-repo.adoc[leveloffset=+2]

include::modules/getting-started/proc-techdocs-generate-site.adoc[leveloffset=+2]

include::modules/getting-started/proc-techdocs-publish-site.adoc[leveloffset=+2]
