:_mod-docs-content-type: ASSEMBLY
:context: HighAvailability
[id="{context}"]
= Configuring high availability in {product}

Previously, {product} supports a single-instance application. With this configuration, if the instance fails due to software crashes, hardware issues, or other unexpected disruptions, the entire {product} service becomes unavailable, preventing the development workflows or access to the resources. With high availability, you receive a failover mechanism that ensures the service is available even if one or more components fail. By increasing the number of replicas, you can enjoy seamless access to the instance, leading to higher productivity and minimal disruption.

As an administrator, you can configure high availability in {product}. Once you set the high availability option in {product-short}, the {ocp-brand-name} built-in Load Balancer manages the ingress traffic and distributes the load to each pod. The {product-very-short} backend also manages concurrent requests or conflicts on the same resource. 

You can configure high availability in {product-short} by scaling your `replicas` to a number greater than 1 in your configuration file. The configuration file that you use depends on the method that you used to install your {product-short} instance. If you used the Operator to install your {product-short} instance, configure the replica values in your `{product-custom-resource-type}` custom resource. If you used the Helm chart to install your {product-short} instance, configure the replica values in your Helm chart.

include::modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-operator-deployment.adoc[leveloffset=+1]

include::modules/configuring-high-availability/proc-configuring-high-availability-in-rhdh-helm-chart-deployment.adoc[leveloffset=+1]