:_mod-docs-content-type: ASSEMBLY
:context: configuring-techdocs
[id="{context}"]
= Configuring TechDocs

The TechDocs plugin is preinstalled and enabled on a {product-short} instance by default. You can disable or enable the TechDocs plugin, and change other parameters, by configuring the {product} Helm chart or the {product} Operator ConfigMap.

[IMPORTANT]
====
{product} includes a built-in TechDocs builder that generates static HTML documentation from your codebase. However, the default basic setup of the local builder is not intended for production.
====

You can use a CI/CD pipeline with the repository that has a dedicated job to generate docs for TechDocs. The generated static files are stored in {odf-name} or in a cloud storage solution of your choice and published to a static HTML documentation site.

After you configure {odf-name} to store the files that TechDocs generates, you can configure the TechDocs plugin to use the {odf-name} for cloud storage.

[role="_additional-resources"]
.Additional resources

* For more information, see link:{LinkPluginsGuide}[Configuring plugins in {product}].

include::modules/customizing-techdocs/con-techdocs-configure-storage.adoc[leveloffset=+1]

include::modules/customizing-techdocs/proc-techdocs-using-odf-storage.adoc[leveloffset=+2]

include::modules/customizing-techdocs/proc-techdocs-configure-odf-helm.adoc[leveloffset=+2]

include::modules/customizing-techdocs/ref-techdocs-example-config-plugin-helm.adoc[leveloffset=+3]

include::modules/customizing-techdocs/proc-techdocs-configure-odf-operator.adoc[leveloffset=+2]

include::modules/customizing-techdocs/ref-techdocs-example-config-plugin-operator.adoc[leveloffset=+3]

include::modules/customizing-techdocs/con-techdocs-config-cicd.adoc[leveloffset=+1]

include::modules/customizing-techdocs/proc-techdocs-config-cicd-prep-repo.adoc[leveloffset=+2]

include::modules/customizing-techdocs/proc-techdocs-generate-site.adoc[leveloffset=+2]

include::modules/customizing-techdocs/proc-techdocs-publish-site.adoc[leveloffset=+2]
