:_mod-docs-content-type: ASSEMBLY
:context: customizing-learning-paths
[id="{context}"]
= Customizing the Learning Paths in {product}

In {product}, you can configure Learning Paths by passing the data into the `{my-app-config-file}` file as a proxy. The base URL must include the `/developer-hub/learning-paths` proxy.

[NOTE]
====
Due to the use of overlapping `pathRewrites` for both the `learning-path` and `homepage` quick access proxies, you must create the `learning-paths` configuration (`^api/proxy/developer-hub/learning-paths`) before you create the `homepage` configuration (`^/api/proxy/developer-hub`).

For more information about customizing the Home page in {product}, see xref:customizing-the-home-page[Customizing the Home page in {product}].
====

You can provide data to the Learning Path from the following sources:

* JSON files hosted on GitHub or GitLab.
* A dedicated service that provides the Learning Path data in JSON format using an API.

include::modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths-json-files.adoc[]

include::modules/customizing-the-learning-paths/proc-customize-rhdh-learning-paths-dedicated-service.adoc[]
