:_mod-docs-content-type: ASSEMBLY

[id="configure-red-hat-developer-hub-events-module_{context}"]

= Configure {product} Events Module

[role="_abstract"]
Enable real-time updates for GitHub entities by configuring the Events Module with webhooks.

Use the Events Module together with scheduled updates to make sure your GitHub user or catalog entities are updated whenever changes occur in the external system.

[IMPORTANT]
====
This is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, see link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====

include::modules/configuring-dynamic-plugins/proc-configure-the-github-events-module-plugin.adoc[leveloffset=+1]
