:_mod-docs-content-type: ASSEMBLY
:context: configuring-the-global-header-in-rhdh

[id="{context}"]
= Configuring the global header in {product}

[role="_abstract"]
As an administrator, you can configure the {product} global header to create a consistent and flexible navigation bar across your {product-short} instance.
By default, the {product-short} global header includes the following components:

* *Self-service* button provides quick access to a variety of templates, enabling users to efficiently set up services, backend and front-end plugins within {product-short}
* *Support* button that can link an internal or external support page
* *Notifications* button displays alerts and updates from plugins and external services
* *Search* input field allows users to find services, components, documentation, and other resources within {product-short}
* *Plugin extension capabilities* provide a preinstalled and enabled catalog of available plugins in {product-short}
* *User profile* drop-down menu provides access to profile settings, appearance customization, {product-short} metadata, and a logout button

include::modules/configuring-the-global-header/proc-customize-your-product-global-header.adoc[leveloffset=+1]


include::modules/configuring-the-global-header/ref-mount-points-for-dynamic-plugin-integration.adoc[leveloffset=+1]

include::modules/configuring-the-global-header/proc-configure-the-logo-in-the-global-header.adoc[leveloffset=+1]

include::modules/configuring-the-global-header/proc-enable-logo-in-the-sidebar.adoc[leveloffset=+1]

include::modules/configuring-the-global-header/proc-display-the-preferred-username-in-the-profile-dropdown.adoc[leveloffset=+1]

include::modules/configuring-the-global-header/con-quicklinks-and-starred-items-in-global-header.adoc[leveloffset=+1]

include::modules/configuring-the-global-header/proc-enable-quicklinks-and-starred-items-after-an-upgrade.adoc[leveloffset=+1]

