:_mod-docs-content-type: ASSEMBLY
:context: configuring-the-global-header-in-rhdh
[id="{context}"]
= Configuring the global header in {product}

As an administrator, you can configure the {product} global header to create a consistent and flexible navigation bar across your {product-short} instance.
By default, the {product} global header includes the following components:

* *Create* button provides quick access to a variety of templates, enabling users to efficiently set up services, backend and front-end plugins within {product-short}
* *Support* button that can link an internal or external support page
* Notification buttons
* Search input field
* Plugin extension capabilities provide a pre-installed and enabled catalog of available plugins in {product}
* User profile drop-down menu provides access to profile settings, appearance customization, Backstage identity details, {product-short} metadata, and a logout button

include::modules/configuring-the-global-header/proc-customize-rhdh-global-header.adoc[leveloffset=+1]


include::modules/configuring-the-global-header/proc-mount-points.adoc[leveloffset=+1]