:_mod-docs-content-type: ASSEMBLY

[id="assembly-log-levels_{context}"]
= Log Levels

Logging provides insight into how {product} performs at runtime and helps you detect and diagnose issues. With the `LOG_LEVEL` environment variable, you can control the amount and type of information collected by any observability tool described in this guide. 

`LOG_LEVEL` sets the minimum severity level of logged events. You can choose from the following levels, which are listed in order of decreasing verbosity:

- `debug`: Detailed information, typically useful only when troubleshooting.
- `info`: General information about the operation of the application. This is the default level.
- `warn`: Indicates potential issues or situations that might require attention.
- `error`: Indicates errors that have occurred but might not prevent the application from continuing.
- `critical`: Indicates critical errors that require immediate attention and are likely to prevent the application from functioning correctly.

include::modules/observe/proc-configuring-the-application-log-level-by-using-the-operator.adoc[leveloffset=+1]


include::modules/observe/proc-configuring-the-application-log-level-by-using-the-helm-chart.adoc[leveloffset=+1]


