:_mod-docs-content-type: ASSEMBLY
[id="assembly-rhdh-telemetry"]
= Telemetry data collection
:context: assembly-rhdh-telemetry

The telemetry data collection feature is enabled by default. {product} sends telemetry data to Red Hat by using the `backstage-plugin-analytics-provider-segment` plugin.

[IMPORTANT]
====
You can disable the telemetry data collection feature based on your needs. For example, in an air-gapped environment, you can disable this feature to avoid needless outbound requests affecting the responsiveness of the {product-very-short} application. For more details, see the link:{LinkAdminGuide}#disabling-telemetry-data-collection_{context}[Disabling telemetry data collection in {product-very-short}] section.
====

{company-name} collects and analyzes the following data to improve your experience with {product}:

* Events of page visits and clicks on links or buttons.
* System-related information, for example, locale, timezone, user agent including browser and OS details.
* Page-related information, for example, title, category, extension name, URL, path, referrer, and search parameters.
* Anonymized IP addresses, recorded as `0.0.0.0`.
* Anonymized username hashes, which are unique identifiers used solely to identify the number of unique users of the {product-very-short} application.

With {product-very-short}, you can customize the telemetry data collection feature and the telemetry Segment source configuration based on your needs.

include::modules/admin/proc-disabling-telemetry.adoc[leveloffset=+1]

include::modules/admin/proc-enabling-telemetry.adoc[leveloffset=+1]

include::modules/admin/proc-customizing-telemetry-segment.adoc[leveloffset=+1]

