:_mod-docs-content-type: PROCEDURE

[id="populate-the-api-definition-tab-in-rhdh-api-entities_{context}"]
= Populate the API Definition tab in {product-very-short} API entities

[role="_abstract"]
Because {rhoai-short} does not expose the OpenAPI specification by default, the AI platform engineer can take the following steps to provide this information:

.Prerequisites

* You have set up the {openshift-ai-connector-name} with {rhoai-brand-name}. For more information, see xref:set-up-with_{context}[Set up {openshift-ai-connector-name} with {rhoai-brand-name}].
* You have a running AI model server with an accessible endpoint.

.Procedure

. Retrieve OpenAPI JSON: Use a tool such as `curl` to fetch the specification directly from the running endpoint of the AI model server. The following command provides the precise endpoint (`/openapi.json`) and shows how to include a `Bearer` token if the model requires authentication for access.
+
[source,bash]
----
$ curl -k -H "Authorization: Bearer $MODEL_API_KEY" https://$MODEL_ROOT_URL_INCLUDING_PORT/openapi.json | jq > open-api.json
----

. Set Property in {rhoai-short}.
.. In the *{rhoai-short}* dashboard, go to *Model Registry* and select the appropriate *Model Version*.
+
[NOTE]
====
Red Hat recommends using *Model Version* instead of *Registered Model* to maintain stability if the API changes between versions.
====

.. In the **Properties** section, set a key/value pair where the key is `API Spec` and the value is the entire JSON content from the `open-api.json` file.

. Propagation: The {openshift-ai-connector-name} periodically polls the {rhoai-short} Model Registry, propagates this JSON, and renders the interactive API documentation in the *Definition* tab of the {product-very-short} API entity.
