:_mod-docs-content-type: PROCEDURE

[id="enabling-and-authorizing-bulk-import-capabilities"]
= Enabling and authorizing Bulk Import capabilities in {product}

You can enable the Bulk Import feature for users and give them the necessary permissions to access it.

.Prerequisites
* You have {integrating-with-github-book-link}#enabling-github-repository-discovery[enabled GitHub repository discovery].

.Procedure
. The Bulk Import plugins are installed but disabled by default.
To enable the `./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic` and `./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import` plugins, edit your `dynamic-plugins.yaml` with the following content:
+
.`dynamic-plugins.yaml` fragment
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic
    disabled: false
  - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
    disabled: false
----
+
See {installing-and-viewing-plugins-book-link}[{installing-and-viewing-plugins-book-title}].

. Configure the required `bulk.import` RBAC permission for the users who are not administrators as follows:
+
.`rbac-policy.csv` fragment
[source,csv,subs="+quotes"]
----
p, role:default/bulk-import, bulk.import, use, allow
g, user:default/__<your_user>__, role:default/bulk-import
----
+
Note that only {product-short} administrators or users with the `bulk.import` permission can use the Bulk Import feature.
See {authorization-book-link}#ref-rbac-permission-policies_title-authorization[Permission policies in {product}].

.Verification
* The sidebar displays a *Bulk Import* option.
* The *Bulk Import* page shows a list of *Added Repositories*.

