:_mod-docs-content-type: PROCEDURE

[id="proc-importing-multiple-repositories-from-github"]
= Importing multiple GitHub repositories

In {product}, you can select your GitHub repositories and automate their onboarding to the {product-short} catalog.

.Prerequisites
* You have xref:enabling-and-authorizing-bulk-import-capabilities[enabled the Bulk Import feature and gave access to it].

.Procedure
. Click *Bulk Import* in {product-short} left sidebar.
. If your {product-very-short} instance has multiple source control tools configured, select *GitHub* from the *Source control tool* list.
. Select the repositories to import, and validate.
+
{product-short} creates a pull request in each selected repository to add the required `catalog-info.yaml` file.
. For each repository to import, click on the *PR* link to review and merge the changes in GitHub.

.Verification
. Click *Bulk Import* in {product-short} left sidebar.
. Verify that each imported GitHub repository in the *Selected repositories* list has the status _Waiting for approval_ or _Imported_.
. For each _Waiting for approval_ repository, click the pull request link to review and merge the `catalog-info.yaml` file in the corresponding repository.

