= Understanding authentication and user provisioning

{product} requires to identify and authorize users before giving them access to features.
In {product}, authentication and authorization are two separate processes:

Authorization::
Authorization defines what the authenticated identity can access or do in {product-short}.
See link:{authorization-book-url}[{authorization-book-title}].

Authentication::
Authentication defines the user identity, and passes on this information to {product-short}.

Authentication providers:::
The authentication system in {product-short} is handled by external authentication providers.
+
{product-short} supports following authentication providers:
+
--
* xref:assembly-authenticating-with-rhbk[Red Hat Single-Sign On (RHSSO)]
* xref:authenticating-with-github[GitHub]
* xref:assembly-authenticating-with-microsoft-azure[Microsoft Azure]
--
+
For each authentication provider, set up the shared secret that the authentication provider and {product-short} require to communicate, first in the authentication provider, then in {product-short}.
+
[TIP]
.Not recommended for production
====
To explore {product-short} features, you can xref:authenticating-with-the-guest-user_{context}[enable the guest user] to skip configuring authentication and authorization, log in as the guest user, and access all the features.
====

Authentication steps:::
{product-short} uses authentication providers for the following two purposes:

Sign-in::::
{product-short} delegates sign-in to the authentication provider.
+
To sign-in users in {product-short}, configure one (and only one) authentication provider for sign-in.

Identification::::
{product-short} retrieves and stores user and group identities asynchronously.
+
To identify users in {product-short}, configure one or more authentication provider for identification.
+
Consider adding optional additional authentication providers for identification to add more information to the user identity, or enable access to additional external resources, such as your Git provider.

Identities in the {product} software catalog:::::
{product-short} stores user identity information in the {product-short} software catalog.
+
To get, store, and update additional user information, such as group or team ownership, with the intention to use this data to define authorization policies, provision users and groups in the {product-short} software catalog.
+
[TIP]
.Not recommended for production
====
To explore the authentication system and use {product-short} without authorization policies, you can bypass the {product-short} software catalog and start using {product-short} without provisioning the {product-short} software catalog.
====
+
[IMPORTANT]
====
{product-short} uses a one-way synchronization system to provision users and groups from your authentication system to the {product-short} software catalog.
Therefore, deleting users and groups by using {product-short} Web UI or REST API might have unintended consequences.
====
