= Understanding authentication and user provisioning

This module provides an overview of how authentication and user provisioning function within {product}.
Learn about the process from creating user and group entities in the software catalog to user sign-in, and how authentication and catalog plugins enable each step.
Understanding this process is essential for successfully link:{configuring-book-url}[configuring your {product-short} instance], link:{authorization-book-url}[securing access through authorization], and enabling features that rely on synchronized user and group data.

When a user attempts to access {product-short}, {product-short} redirects them to a configured authentication provider, such as xref:assembly-authenticating-with-rhbk[{rhbk-brand-name} ({rhbk})], xref:authenticating-with-github[GitHub], or xref:assembly-authenticating-with-microsoft-azure[{azure-brand-name}].
This external Identity Provider (IdP) is responsible for authenticating the user.

On successful authentication, the {product-short}'s authentication plugin, configured in your `{my-app-config-file}` file, processes the response from the IdP, resolves the identity in the {product-short} software catalog, and establishes a user session within {product-short}.

User and group data needs to be provisioned from the Identity Provider to the {product-short} software catalog to fully enable catalog features.
This is handled asynchronously by catalog provider plugins, also configured in your `{my-app-config-file}` file.
These plugins, query the IdP for relevant user and group information and create or update corresponding entities in the {product-short} catalog.
Scheduled provisioning ensures that the catalog accurately reflects the users and groups in your organization.

Configuring authentication and user provisioning is critical for several reasons.

* First, it secures your Developer Hub instance by ensuring only authenticated users can gain access.
* Second, it enables authorization by allowing you to define access controls based on user and group memberships synchronized from your IdP.
* Finally, provisioning user and group data to the catalog is necessary for various catalog features that rely on understanding entity ownership and relationships between users, groups, and software components.
Without this provisioning step, features like displaying who owns a component in the catalog may not function correctly.

[TIP]
.Not recommended for production
====
To explore {product-short} features, you can:

* To use {product-short} without external IdP, xref:authenticating-with-the-guest-user_{context}[enable the guest user] to skip configuring authentication and authorization, log in as the guest user, and access all {product-short} features.

* To use {product-short} without authorization policies, you can bypass the {product-short} software catalog and start using {product-short} without provisioning the {product-short} software catalog.
====

[IMPORTANT]
====
{product-short} uses a one-way synchronization system to provision users and groups from your authentication system to the {product-short} software catalog.
Therefore, deleting users and groups by using {product-short} Web UI or REST API might have unintended consequences.
====
