[id="creating-a-custom-transformer-to-provision-users-from-rhbk-to-the-software-catalog"]
= Creating a custom transformer to provision users from {rhbk-brand-name} ({rhbk}) to the software catalog

To customize how {rhbk} users and groups are mapped to {product} entities, you can create a backend module that uses the `keycloakTransformerExtensionPoint` to provide custom user and group transformers for the Keycloak backend.

.Prerequisites
* You have xref:provisioning-users-from-rhbk-to-the-software-catalog[enabled provisioning users from {rhbk-brand-name} ({rhbk}) to the software catalog].

.Procedure
. Create a new backend module with the `yarn new` command.

. Add your custom user and group transformers to the `keycloakTransformerExtensionPoint`.

+
The following is an example of how the backend module can be defined:
+
.`plugins/__<module-name>__/src/module.ts`
[source,javascript,subs="+attributes"]
----
import {
  GroupTransformer,
  keycloakTransformerExtensionPoint,
  UserTransformer,
} from '@backstage-community/plugin-catalog-backend-module-keycloak';

const customGroupTransformer: GroupTransformer = async (
  entity, // entity output from default parser
  realm, // Keycloak realm name
  groups, // Keycloak group representation
) => {
  /* apply transformations */
  return entity;
};
const customUserTransformer: UserTransformer = async (
  entity, // entity output from default parser
  user, // Keycloak user representation
  realm, // Keycloak realm name
  groups, // Keycloak group representation
) => {
  /* apply transformations */
  return entity;
};

export const keycloakBackendModuleTransformer = createBackendModule({
  pluginId: 'catalog',
  moduleId: 'keycloak-transformer',
  register(reg) {
    reg.registerInit({
      deps: {
        keycloak: keycloakTransformerExtensionPoint,
      },
      async init({ keycloak }) {
        keycloak.setUserTransformer(customUserTransformer);
        keycloak.setGroupTransformer(customGroupTransformer);
        /* highlight-add-end */
      },
    });
  },
});
----
+
[IMPORTANT]
====
The module's `pluginId` must be set to `catalog` to match the `pluginId` of the `keycloak-backend`; otherwise, the module fails to initialize.
====

. Install this new backend module into your {product-short} backend.
+
[source,javascript,subs="+attributes"]
----
backend.add(import(backstage-plugin-catalog-backend-module-keycloak-transformer))
----

.Verification

* {product-short} imports the users and groups each time when started.
Check the console logs to verify that the synchronization is completed.
+
.Successful synchronization example:
[source,json,subs="+attributes"]
----
{"class":"KeycloakOrgEntityProvider","level":"info","message":"Read 3 Keycloak users and 2 Keycloak groups in 1.5 seconds. Committing...","plugin":"catalog","service":"backstage","taskId":"KeycloakOrgEntityProvider:default:refresh","taskInstanceId":"bf0467ff-8ac4-4702-911c-380270e44dea","timestamp":"2024-09-25 13:58:04"}
{"class":"KeycloakOrgEntityProvider","level":"info","message":"Committed 3 Keycloak users and 2 Keycloak groups in 0.0 seconds.","plugin":"catalog","service":"backstage","taskId":"KeycloakOrgEntityProvider:default:refresh","taskInstanceId":"bf0467ff-8ac4-4702-911c-380270e44dea","timestamp":"2024-09-25 13:58:04"}
----

* After the first import is complete, navigate to the *Catalog* page and select **User** to view the list of users.

* When you select a user, you see the information imported from {rhbk}.

* You can select a group, view the list, and access or review the information imported from {rhbk}.

* You can log in with an {rhbk} account.
