:_mod-docs-content-type: PROCEDURE

[id="create-a-custom-transformer-to-provision-users-from-ldap-to-the-software-catalog"]
= Create a custom transformer to provision users from LDAP to the software catalog

Customize how {product} provisions users and groups to {product} software catalog entities,
by creating a backend module that uses the `keycloakTransformerExtensionPoint` to offer custom user and group transformers for the LDAP backend.

.Prerequisites
* You have xref:enabling-user-authentication-with-ldap-with-optional-steps[enabled provisioning users from LDAP to the software catalog].

.Procedure
. Create a new backend module:
+
[source,shell]
----
$ yarn new
? What type of module would you like to create? backend-plugin-module
? Enter the ID if the plugin [required]? catalog
? Enter the ID of the module [required]? ldap-transformer
----
+
The command creates a plugin named: `catalog-backend-module-ldap-transformer`.

. Install required packages:
+
[source,shell]
----
$ yarn --cwd plugins/catalog-backend-module-ldap-transformer add @backstage/plugin-catalog-backend-module-ldap
----

. Refer to the link:https://github.com/redhat-developer/rhdh-examples/tree/main/plugins/backstage-plugin-catalog-backend-module-ldap-transformer[sample plugin] and implement `plugins/catalog-backend-module-ldap-transformer/src/module.ts`.

. Package and export the plugin as a Dynamic Plugin, and embed the required package for the custom transformer.
+
[source,shell]
----
$ npx @red-hat-developer-hub/cli@latest plugin export \
  --embed-package @backstage/plugin-catalog-backend-module-ldap
----

[IMPORTANT]
====
Verify that the installed plugin version is compatible with the Backstage version

See plugin marketplace for the version to import.
====


.Verification

* {product-short} imports the users and groups each time when started.
Check the console logs to verify the synchronization result.
+
Successful synchronization example:
+
[source,json]
----
FIXME
----

* After the first import is complete, go to the *Catalog* page and select **User** to view the list of users.

* When you select a user, you see the information imported from LDAP.

* You can select a group, view the list, and access or review the information imported from LDAP.

* You can log in with an LDAP account.
