[id="enabling-authentication-with-rhbk"]
= Enabling authentication with {rhbk-brand-name} ({rhbk})

To authenticate users with {rhbk-brand-name} ({rhbk}), enable the OpenID Connect (OIDC) authentication provider in {product}.


.Prerequisites
* You link:{configuring-book-url}[added a custom {product-short} application configuration], and have sufficient permissions to modify it.
* You have sufficient permissions in {rhsso} to create and manage a realm.

.Procedure
. To allow {product-short} to authenticate with {rhbk}, complete the steps in {rhbk}, to link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-create-a-realm[create a realm and a user] and link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-secure-the-first-application[secure the first application]:

.. Use an existing realm, or link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-create-a-realm[create a realm], with a distinctive **Name** such as __<my_realm>__.
Save the value for the next step:
* **{rhbk} realm base URL**, such as: __<your_rhbk_URL>__/realms/__<your_realm>__.

.. To register your {product-short} in {rhbk}, in the created realm, link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html-single/getting_started_guide/index#getting-started-zip-secure-the-first-application[secure the first application], with:
... **Client ID**: A distinctive client ID, such as __<{product-very-short}>__.
... **Valid redirect URIs**: Set to the OIDC handler URL: `https://__<RHDH_URL>__/api/auth/oidc/handler/frame`.
... Navigate to the **Credentials** tab and copy the **Client secret**.
... Save the values for the next step:
* **Client ID**
* **Client Secret**

.. To prepare for the verification steps, in the same realm, get the credential information for an existing user or link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html-single/getting_started_guide/index#getting-started-zip-create-a-user[create a user]. Save the user credential information for the verification steps.

. To add your {rhsso} credentials to your {product-short}, add the following key/value pairs to link:{plugins-configure-book-url}#provisioning-your-custom-configuration[your {product-short} secrets]:
+
`AUTH_OIDC_CLIENT_ID`:: Enter the saved **Client ID**.
`AUTH_OIDC_CLIENT_SECRET`:: Enter the saved **Client Secret**.
`AUTH_OIDC_METADATA_URL`:: Enter the saved **{rhbk} realm base URL**.

. To set up the {rhbk} authentication provider in your {product-short} custom configuration, edit your custom {product-short} ConfigMap such as `app-config-rhdh`, and add the following lines to the `{my-app-config-file}` content:

.. Configure mandatory fields:
+
.`{my-app-config-file}` fragment with mandatory fields to enable authentication with {rhbk}
[source,yaml]
----
auth:
  environment: production # <1>
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL} # <2>
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
signInPage: oidc # <3>
----
<1> Mark the environment as `production` to hide the Guest login in the {product-short} login page.
<2> Configure the OIDC provider with your secrets.
<3> To enable the OIDC provider as default sign-in provider.
+
.. Optional: Consider adding the following optional fields:

`callbackUrl`::
{rhbk} callback URL.
+
.`{my-app-config-file}` fragment with optional `callbackURL` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        callbackUrl: ${AUTH_OIDC_CALLBACK_URL}
----

`tokenEndpointAuthMethod`::
Token endpoint authentication method.
+
.`{my-app-config-file}` fragment with optional `tokenEndpointAuthMethod` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        tokenEndpointAuthMethod: ${AUTH_OIDC_TOKEN_ENDPOINT_METHOD}
----

`tokenSignedResponseAlg`::
Token signed response algorithm.
+
.`{my-app-config-file}` fragment with optional `tokenSignedResponseAlg` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        tokenSignedResponseAlg: ${AUTH_OIDC_SIGNED_RESPONSE_ALG}
----

`scope`::
{rhbk} scope.
+
.`{my-app-config-file}` fragment with optional `scope` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        scope: ${AUTH_OIDC_SCOPE}
----

`signIn`::
`resolvers`:::
After successful authentication, the user signing in must be resolved to an existing user in the {product-short} catalog. To best match users securely for your use case, consider configuring a specific resolver. Enter the resolver list to override the default resolver: `emailLocalPartMatchingUserEntityName`.
+
The authentication provider tries each sign-in resolver in order until it succeeds, and fails if none succeed.
+
WARNING: In production mode, only configure one resolver to ensure users are securely matched. 
`resolver`::::
Enter the sign-in resolver name.
Available values:
* `emailLocalPartMatchingUserEntityName`
* `emailMatchingUserEntityProfileEmail`
* `preferredUsernameMatchingUserEntityName`
+
.`{my-app-config-file}` fragment with optional `resolvers` list
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        signIn:
          resolvers:
            - resolver: preferredUsernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
----

`dangerouslyAllowSignInWithoutUserInCatalog: true`::::
Configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
WARNING: Use this option to explore {product-short} features, but do not use it in production.
+
.`app-config-rhdh.yaml` fragment with optional field to allow signing in users absent from the software catalog
[source,yaml]
----
auth:
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailLocalPartMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: oidc
----

`sessionDuration`::
Lifespan of the user session.
Enter a duration in `ms` library format (such as '24h', '2 days'), ISO duration, or "human duration" as used in code.
+
.`app-config-rhdh.yaml` fragment with optional `sessionDuration` field
[source,yaml,subs="+quotes"]
----
auth:
  providers:
    github:
      production:
        sessionDuration: { hours: 24 }
----

`auth`::

`backstageTokenExpiration`:::
To modify the {product-short} token expiration from its default value of one hour, note that this refers to the validity of short-term cryptographic tokens, not the session duration. The expiration value must be set between 10 minutes and 24 hours.
+
.`{my-app-config-file}` fragment with optional `auth.backstageTokenExpiration` field
[source,yaml,subs="+quotes"]
----
auth:
  backstageTokenExpiration: { minutes: _<user_defined_value>_ }
----
+
[WARNING]
.Security consideration
====
If multiple valid refresh tokens are issued due to frequent refresh token requests, older tokens will remain valid until they expire. To enhance security and prevent potential misuse of older tokens, enable a refresh token rotation strategy in your {rhbk} realm.

. From the *Configure* section of the navigation menu, click *Realm Settings*.
. From the *Realm Settings* page, click the *Tokens* tab.
. From the *Refresh tokens* section of the *Tokens* tab, toggle the *Revoke Refresh Token* to the *Enabled* position.
====

.Verification
. Go to the {product-short} login page.
. Your {product-short} sign-in page displays *Sign in using OIDC* and the Guest user sign-in is disabled.
. Log in with OIDC by using the saved **Username** and **Password** values.

