:_mod-docs-content-type: PROCEDURE

[id="enabling-user-authentication-with-github-as-an-auxiliary-authentication-provider"]
= Enabling user authentication with GitHub as an auxiliary authentication provider

If your primary authentication provider is not GitHub, users might lack the permissions needed for templates or plugins that require GitHub access. The recommended solution is to configure GitHub as an auxiliary authentication provider. This approach uses the primary provider for user identity management and the auxiliary provider to grant the necessary GitHub permissions, without re-resolving the user's identity.

Give users access to these features by configuring GitHub as an auxiliary authentication provider.

.Prerequisites
include::snip-enabling-user-authentication-with-github-common-prerequisites.adoc[]
* You have configured a primary authentication provider to provision user and group identities to the {product} software catalog, and establish {product-short} user sessions.


.Procedure
. Add the `auth.providers.github` section to your `{my-app-config-file}` file:
+
[source,yaml]
----
auth:
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        disableIdentityResolution: true
----
+
where:
`clientId`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_SECRET}`.

`disableIdentityResolution`::
Enter `true` to skip user identity resolution for this provider to enable sign-in from an auxiliary authentication provider.
+
[WARNING]
====
Do not enable this setting on the primary authentication provider you plan on using for sign-in and identity management.
====

.Verification
. Go to the {product-short} login page.
. Log in with your primary authentication provider account.
. In the top user menu, go to *Settings* > *Authentication Providers*.
. In the *GitHub* line, click the *Sign in* button and log in.
. In the *GitHub* line, the button displays *Sign out*.

.Additional resources
* {integrating-with-github-book-link}[{integrating-with-github-book-title}]

