[id="provisioning-users-from-rhsso-to-the-software-catalog"]
= Provisioning users from Red Hat Single-Sign On (RHSSO) to the software catalog

.Prerequisites
* You xref:proc-enabling-authentication-with-rhsso.adoc[enabled authentication with RHSSO]

.Procedure
.
* To enable RHSSO member discovery, edit your custom {product-short} config map, such as app-config-rhdh, and add following lines to the app-config-rhdh.yaml content:
+
--
[id=keycloakOrgProviderId]
.`app-config.yaml` fragment with mandatory `keycloakOrg` fields
[source,yaml]
----
dangerouslyAllowSignInWithoutUserInCatalog: false
catalog:
  providers:
    keycloakOrg:
      default:
        baseUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
----

`baseUrl`::
RHSSO server URL.

`clientId`::
Your {product-short} application client ID in RHSSO.

`clientSecret`::
Your {product-short} application client secret in RHSSO.

Optional: Consider adding following optional  fields:

`realm`::
Realm to synchronize.
Default value: `master`.
+
.`app-config.yaml` fragment with optional `realm` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        realm: master
----

`loginRealm`::
Realm used to authenticate.
Default value: `master`.
+
.`app-config.yaml` fragment with optional `loginRealm` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        loginRealm: master
----

`userQuerySize`::
User number to query simultaneously.
Default value: `100`.
+
.`app-config.yaml` fragment with optional `userQuerySize` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        userQuerySize: 100
----

`groupQuerySize`::
Group number to query simultaneously.
Default value: `100`.
+
.`app-config.yaml` fragment with optional `groupQuerySize` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        groupQuerySize: 100
----

`schedule.frequency`::
To specify custom schedule frequency.
Supports cron, ISO duration, and "human duration" as used in code.
+
.`app-config.yaml` fragment with optional `schedule.frequency` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        schedule:
          frequency: { hours: 1 }
----

`schedule.timeout`::
To specify custom timeout.
Supports ISO duration and "human duration" as used in code.
+
.`app-config.yaml` fragment with optional `schedule.timeout` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        schedule:
          timeout: { minutes: 50 }
----

`schedule.initialDelay`::
To specify custom initial delay.
Supports ISO duration and "human duration" as used in code.
+
.`app-config.yaml` fragment with optional `schedule.initialDelay` field
[source,yaml]
----
catalog:
  providers:
    keycloakOrg:
      default:
        schedule:
          initialDelay: { seconds: 15}
----
--
