:_mod-docs-content-type: PROCEDURE

[id="enabling-user-authentication-with-github-as-an-auxiliary-authentication-provider"]
= Enabling user authentication with GitHub as an auxiliary authentication provider

To use another authentication provider as your main identity provider,
and enable your users to interact with GitHub features such as pull requests, configure GitHub as an auxiliary authentication provider.

.Prerequisites
* You {configuring-book-link}[added a custom {product-short} application configuration] with another authentication provider enabled, and have enough permissions to change it.

include::snip-enabling-user-authentication-with-github-common-steps.adoc[]

. To set up the GitHub authentication provider as an auxiliary authentication provider, add the `auth.providers.github` section to your `{my-app-config-file}` file:
+
[source,yaml]
----
auth:
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        disableIdentityResolution: true
----

`clientId`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_SECRET}`.

`disableIdentityResolution`::
The software catalog is provisioned by the primary authentication provider.
Therefore, enter `true` to skip resolving the user in the {product-short} software catalog.

.Verification

. Go to the {product-short} login page.
. Log in with your primary authentication provider account.
. In the top user menu, go to *Settings* > *Authentication Providers*.
. In the *GitHub* line, click the *Sign in* button and log in.
. In the *GitHub* line, the button now displays *Sign out*.

.Additional resources
* {integrating-with-github-book-link}[{integrating-with-github-book-title}]

