:_mod-docs-content-type: PROCEDURE

[id="enabling-user-authentication-with-github"]
= Enabling user authentication with GitHub

Authenticate users with GitHub by provisioning the users and groups from GitHub to the {product-short} software catalog, and configuring the GitHub authentication provider in {product}.

.Prerequisites
* You {configuring-book-link}[added a custom {product-short} application configuration], and have enough permissions to change it.

include::snip-enabling-user-authentication-with-github-common-steps.adoc[]

. Provision GitHub users and groups to the {product-short} software catalog by adding the `catalog.providers.githubOrg` section to your custom {product-short} `{my-app-config-file}` configuration file:
+
[id=githubProviderId]
[source,yaml]
----
catalog:
  providers:
    githubOrg:
      id: githuborg
      githubUrl: "${GITHUB_URL}"
      orgs: [ "${GITHUB_ORG}" ]
      schedule:
        frequency:
          minutes: 30
        initialDelay:
          seconds: 15
        timeout:
          minutes: 15
----

`id`::
Enter a stable identifier for this provider, such as `githuborg`.
Entities from this provider are associated with this identifier, therefore you must take care not to change it over time since that might lead to orphaned entities or conflicts.

`githubUrl`::
Enter the configured secret variable name: `$\{GITHUB_URL}`.

`orgs`::
Enter the configured secret variable name: `$\{GITHUB_ORG}`.

`schedule.frequency`::
Enter your schedule frequency, in the cron, ISO duration, or "human duration" format.

`schedule.timeout`::
Enter your schedule timeout, in the ISO duration or "human duration" format.

`schedule.initialDelay`::
Enter your schedule initial delay, in the ISO duration or "human duration" format.

. To set up the GitHub authentication provider, add the `auth.providers.github` section to your `{my-app-config-file}` file:
+
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
signInPage: github
----

`environment`::
Enter `production` to disable the Guest login option in the {product-short} login page.

`clientId`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_SECRET}`.

`signInPage`::
Enter `github` to enable the GitHub provider as your {product-short} sign-in provider.
+
Optional: Consider adding optional fields.
ifeval::["{optional-steps}" == "disable"]
See {configuring-book-link}[{configuring-book-title}].
endif::[]
ifeval::["{optional-steps}" == "enable"]
[source,yaml,subs="+quotes"]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
        callbackUrl: __<your_intermediate_service_url/handler>__
        sessionDuration: { hours: 24 }
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: github
----

`callbackUrl`::
Enter the callback URL that GitHub uses when initiating an OAuth flow, such as: __<your_intermediate_service_url/handler>__.
Define it when {product-short} is not the immediate receiver, such as in cases when you use one OAuth app for many {product-short} instances.

`sessionDuration`::
Enter the user session lifespan, in `ms` library format (such as '24h', '2 days'), ISO duration, or "human duration".

`signIn`::

`resolvers`:::
After successful authentication, {product-short} resolves the user signing in to an existing user in the {product-short} catalog.
To best match users securely for your use case, consider configuring a specific resolver.
+
Enter the resolver list to override the default resolver: `usernameMatchingUserEntityName`.
+
The authentication provider tries each sign-in resolver in order until it succeeds, and fails if none succeed.
+
[WARNING]
====
Make sure users are securely matched in production mode, by configuring only one resolver.
====

`resolver`::::
Enter the sign-in resolver name.
Available resolvers:

* `usernameMatchingUserEntityName`
* `preferredUsernameMatchingUserEntityName`
* `emailMatchingUserEntityProfileEmail`

`dangerouslyAllowSignInWithoutUserInCatalog: true`::::
Configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
[WARNING]
====
Do not use `dangerouslyAllowSignInWithoutUserInCatalog` in production. Use this configuration only to explore {product-short} features.
====
endif::[]

.Verification
. Verify user and group provisioning by checking the console logs.
+
Successful synchronization example:
+
[source,json]
----
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Reading GitHub users and teams for org: rhdh-dast","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:githuborg:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:58"}
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Read 7 GitHub users and 2 GitHub groups in 0.4 seconds. Committing...","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:githuborg:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:59"}
----

. To verify GitHub authentication:
.. Go to the {product-short} login page.
.. Your {product-short} sign-in page displays *Sign in using GitHub* and the Guest user sign-in is disabled.
.. Log in with a GitHub account.

.Additional resources
* {integrating-with-github-book-link}[{integrating-with-github-book-title}]

