[id="enabling-authentication-with-rhbk"]
= Enabling authentication with {rhbk-brand-name} ({rhbk})

To authenticate users with {rhbk-brand-name} ({rhbk}), enable the OpenID Connect (OIDC) authentication provider in {product}.


.Prerequisites
* You link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html/administration_guide_for_red_hat_developer_hub/assembly-add-custom-app-file-openshift_admin-rhdh[added a custom {product-short} application configuration], and have sufficient permissions to modify it.
* You have sufficient permissions in {rhbk} to create and manage a realm.

.Procedure
. To allow {product-short} to authenticate with {rhbk}, complete the steps in {rhbk}, to link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-create-a-realm[create a realm and a user] and link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-secure-the-first-application[secure the first application]:

.. Use an existing realm, or link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html/getting_started_guide/getting-started-zip-#getting-started-zip-create-a-realm[create a realm], with a distinctive **Name** such as __<my_realm>__.
Save the value for the next step:
* **{rhbk} realm base URL**, such as: __<your_rhbk_URL>__/realms/__<your_realm>__.

.. To register your {product-short} in {rhbk}, in the created realm, link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html-single/getting_started_guide/index#getting-started-zip-secure-the-first-application[secure the first application], with:
... **Client ID**: A distinctive client ID, such as __<{product-very-short}>__.
... **Valid redirect URIs**: Set to the OIDC handler URL: `https://__<RHDH_URL>__/api/auth/oidc/handler/frame`.
... Navigate to the **Credentials** tab and copy the **Client secret**.
... Save the values for the next step:
* **Client ID**
* **Client Secret**

.. Configure your {rhbk} realm for performance and security:
... Navigate to the **Configure** > **Realm Settings**.
... Set the **Access Token Lifespan** to a value greater than five minutes (preferably 10 or 15 minutes) to prevent performance issues from frequent refresh token requests for every API call.
... Enable the **Revoke Refresh Token** option to improve security by enabling the refresh token rotation strategy.

.. To prepare for the verification steps, in the same realm, get the credential information for an existing user or link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/24.0/html-single/getting_started_guide/index#getting-started-zip-create-a-user[create a user]. Save the user credential information for the verification steps.

. To add your {rhsso} credentials to your {product-short}, add the following key/value pairs to link:{plugins-configure-book-url}#provisioning-your-custom-configuration[your {product-short} secrets]:
+
`AUTH_OIDC_CLIENT_ID`:: Enter the saved **Client ID**.
`AUTH_OIDC_CLIENT_SECRET`:: Enter the saved **Client Secret**.
`AUTH_OIDC_METADATA_URL`:: Enter the saved **{rhbk} realm base URL**.

. To set up the {rhbk} authentication provider in your {product-short} custom configuration, edit your custom {product-short} ConfigMap such as `app-config-rhdh`, and add the following lines to the `app-config-rhdh.yaml` content:
+
--
.`app-config-rhdh.yaml` fragment with mandatory fields to enable authentication with {rhbk}
[source,yaml]
----
auth:
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
signInPage: oidc
----

`environment: production`::
Mark the environment as `production` to hide the Guest login in the {product-short} home page.

`metadataUrl`, `clientId`, `clientSecret`::
To configure the OIDC provider with your secrets.

`sigInPage: oidc`::
To enable the OIDC provider as default sign-in provider.


Optional: Consider adding the following optional fields:

`dangerouslyAllowSignInWithoutUserInCatalog: true`::
+
--
To enable authentication without requiring to provision users in the {product-short} software catalog.
+
WARNING: Use this option to explore {product-short} features, but do not use it in production.
+
.`app-config-rhdh.yaml` fragment with optional field to allow authenticating users absent from the software catalog
[source,yaml]
----
auth:
  environment: production
  providers:
    oidc:
      production:
        metadataUrl: ${AUTH_OIDC_METADATA_URL}
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
signInPage: oidc
dangerouslyAllowSignInWithoutUserInCatalog: true
----
--

`callbackUrl`::
--
{rhbk} callback URL.

.`app-config-rhdh.yaml` fragment with optional `callbackURL` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        callbackUrl: ${AUTH_OIDC_CALLBACK_URL}
----
--

`tokenEndpointAuthMethod`::
--
Token endpoint authentication method.

.`app-config-rhdh.yaml` fragment with optional `tokenEndpointAuthMethod` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        tokenEndpointAuthMethod: ${AUTH_OIDC_TOKEN_ENDPOINT_METHOD}
----
--

`tokenSignedResponseAlg`::
--
Token signed response algorithm.

.`app-config-rhdh.yaml` fragment with optional `tokenSignedResponseAlg` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        tokenSignedResponseAlg: ${AUTH_OIDC_SIGNED_RESPONSE_ALG}
----
--

`scope`::
--
{rhbk} scope.

.`app-config-rhdh.yaml` fragment with optional `scope` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        scope: ${AUTH_OIDC_SCOPE}
----
--

`signIn.resolvers`::
--
Declarative resolvers to override the default resolver: `emailLocalPartMatchingUserEntityName`.
The authentication provider tries each sign-in resolver until it succeeds, and fails if none succeed.

.`app-config-rhdh.yaml` fragment with optional `callbackURL` field
[source,yaml]
----
auth:
  providers:
    oidc:
      production:
        signIn:
          resolvers:
            - resolver: preferredUsernameMatchingUserEntityName
            - resolver: emailMatchingUserEntityProfileEmail
            - resolver: emailLocalPartMatchingUserEntityName
----
--

`auth.backstageTokenExpiration`::
--
To modify the {product-short} token expiration from its default value of one hour, note that this refers to the validity of short-term cryptographic tokens, not the session duration. The expiration value must be set between 10 minutes and 24 hours.

.`app-config-rhdh.yaml` fragment with optional `auth.backstageTokenExpiration` field
[source,yaml,subs="+quotes"]
----
auth:
  backstageTokenExpiration: { minutes: _<user_defined_value>_ }
----
--

--

.Verification
. Go to the {product-short} login page.
. Your {product-short} sign-in page displays *Sign in using OIDC* and the Guest user sign-in is disabled.
. Log in with OIDC by using the saved **Username** and **Password** values.

