[id="enabling-user-authentication-with-github-with-mandatory-steps-only"]
= Enabling user authentication with GitHub (with mandatory steps only)

To authenticate users with GitHub, configure the GitHub authentication provider in {product} and provision the users and groups from GitHub to the {product-short} software catalog.

.Prerequisites
* You link:{configuring-book-url}[added a custom {product-short} application configuration], and have sufficient permissions to modify it.

* You have sufficient permissions in GitHub to create and manage a link:https://docs.github.com/en/apps/overview[GitHub App].
Alternatively, you can ask your GitHub administrator to prepare the required GitHub App.

.Procedure
. To allow {product-short} to authenticate with GitHub, create a GitHub App.
Opt for a GitHub App instead of an OAuth app to use fine-grained permissions and use short-lived tokens.

.. link:https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app[Register a GitHub App] with the following configuration:

GitHub App name::
Enter a unique name identifying your GitHub App, such as `authenticating-with-rhdh-__<GUID>__`.

Homepage URL::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your {product-short} authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/github/handler/frame]`.

Webhook::
Clear "Active", as this is not needed for authentication and catalog providers.

Organization permissions::
Enable `Read-only` access to *Members*.

Where can this GitHub App be installed?::
Select `Only on this account`.

.. In the *General* -> *Clients secrets* section, click *Generate a new client secret*.

.. In the *Install App* tab, choose an account to install your GitHub App on.

.. Save the following values for the next step:

* **Client ID**
* **Client secret**

. To add your GitHub credentials to {product-short}, add the following key/value pairs to link:{configuring-dynamic-plugins-book-url}#provisioning-your-custom-configuration[your {product-short} secrets].
You can use these secrets in the {product-short} configuration files by using their respective environment variable name.

`AUTHENTICATION_GITHUB_CLIENT_ID`::
Enter the saved **Client ID**.

`AUTHENTICATION_GITHUB_CLIENT_SECRET`::
Enter the saved **Client Secret**.

`GITHUB_URL`::
Enter the GitHub host domain: `github.com`.

`GITHUB_ORG`::
Enter your GitHub organization name, such as `__<your_github_organization_name>__`.

. Enable the GitHub organization provisioning plugin (`backstage-plugin-catalog-backend-module-github-org`).
This plugin ingests GitHub users and groups to the {product-short} software catalog.
With the default configuration, the plugin runs every hour and uses your `GITHUB_URL` and `GITHUB_ORG` variables.
+
.`dynamic-plugins.yaml` file fragment
[source,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org'
    disabled: false
----

. To set up the GitHub authentication provider, add the `auth.providers.github` section to the `{my-app-config-file}` file content:
+
.`{my-app-config-file}` file fragment with mandatory fields to enable authentication with GitHub
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
signInPage: github
----

`environment`::
Enter `production` to disable the Guest login option in the {product-short} login page.

`clientId`::
Enter the configured secret variable name: `${GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `${GITHUB_CLIENT_SECRET}`.

`signInPage`::
Enter `github` to enable the GitHub provider as your {product-short} sign-in provider.

.Verification
. To verify user and group provisioning, check the console logs.
+
.Successful synchronization example:
[source,json]
----
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Reading GitHub users and teams for org: rhdh-dast","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:githuborg:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:58"}
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Read 7 GitHub users and 2 GitHub groups in 0.4 seconds. Committing...","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:githuborg:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:59"}
----

. To verify GitHub authentication:
.. Go to the {product-short} login page.
.. Your {product-short} sign-in page displays *Sign in using GitHub* and the Guest user sign-in is disabled.
.. Log in with a GitHub account.

.Additional resources
* link:{integrating-with-github-book-url}[{integrating-with-github-book-title}].
* link:{authentication-book-url}#enabling-user-authentication-with-github[Enabling user authentication with GitHub (with optional steps)].

