[id="enabling-authentication-with-github"]
= Enabling authentication with GitHub

To authenticate users with GitHub, enable the GitHub authentication provider in {product}.

.Prerequisites
* You link:{configuring-book-url}[added a custom {product-short} application configuration], and have sufficient permissions to modify it.
* You have sufficient permissions in GitHub to create and manage a link:https://docs.github.com/en/apps/overview[GitHub App].

.Procedure
. To allow {product-short} to authenticate with GitHub, create a GitHub App.
Opt for a GitHub App instead of an OAuth app to use fine-grained permissions, gain more control over which repositories the application can access, and use short-lived tokens.

.. link:https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app[Register a GitHub App] with the following configuration:

GitHub App name::
Enter a unique name identifying your GitHub App, such as `authenticating-with-{product-very-short}-__<GUID>__`.

Homepage URL::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your {product-short} authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/github/handler/frame]`.

Organization permissions::
Enable `Read-only` access to *Members*.

Where can this GitHub App be installed?::
Select `Only on this account`.

.. In the *General* -> *Clients secrets* section, click *Generate a new client secret*.

.. In the *Install App* tab, choose an account to install your GitHub App on.

.. Save the following values for the next step:

* **Client ID**
* **Client secret**

. To add your GitHub credentials to {product-short}, add the following key/value pairs to link:{configuring-dynamic-plugins-book-url}#provisioning-your-custom-configuration[your {product-short} secrets]:
+
`AUTHENTICATION_GITHUB_CLIENT_ID`::
Enter the saved **Client ID**.

`AUTHENTICATION_GITHUB_CLIENT_SECRET`::
Enter the saved **Client Secret**.

`AUTHENTICATION_GITHUB_HOST_DOMAIN`::
Enter the GitHub host domain: `github.com`.

`AUTHENTICATION_GITHUB_ORGANIZATION`::
Enter your GitHub organization name, such as `__<your_github_organization_name>__'.

. Enable the `backstage-plugin-catalog-backend-module-github-org` plugin.
+
.`dynamic-plugins.yaml` file fragment
[code,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org'
    disabled: false
----

. To provision GitHub users and groups to the {product-short} software catalog, add the `catalog.providers.githubOrg` section to your custom {product-short} `{my-app-config-file}` configuration file:
+
--
[id=githubProviderId]
.`{my-app-config-file}` fragment with mandatory `catalog.providers.githubOrg` fields
[source,yaml]
----
catalog:
  providers:
    githubOrg:
      githubUrl: "${AUTHENTICATION_GITHUB_HOST_DOMAIN}"
      orgs: [ "${AUTHENTICATION_GITHUB_ORGANIZATION}" ]
      schedule:
        frequency:
          minutes: 30
        initialDelay:
          seconds: 15
        timeout:
          minutes: 15
----

`githubUrl` and `orgs`::
Use the {product-short} application information that you have created in GitHub and configured in OpenShift as secrets.

`schedule.frequency`::
Enter your schedule frequency, in the cron, ISO duration, or "human duration" format.

`schedule.timeout`::
Enter your schedule timeout, in the ISO duration or "human duration" format.

`schedule.initialDelay`::
Enter your schedule initial delay, in the ISO duration or "human duration" format.
--

. To set up the GitHub authentication provider, add the `auth.providers.github` section to the `{my-app-config-file}` file content:
+
.`{my-app-config-file}` file fragment with mandatory fields to enable authentication with GitHub
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTHENTICATION_GITHUB_CLIENT_ID}
        clientSecret: ${AUTHENTICATION_GITHUB_CLIENT_SECRET}
signInPage: github
----
+
`environment: production`::
Mark the environment as `production` and disable the Guest login option in the {product-short} login page.
`clientId: ${AUTHENTICATION_GITHUB_CLIENT_ID}` and `clientSecret: ${AUTHENTICATION_GITHUB_CLIENT_SECRET}`::
Apply the GitHub credentials configured in your {product-short} secrets.
`signInPage: github`::
To enable the GitHub provider as your {product-short} sign-in provider.
+
Optional: Consider adding the following optional fields:
+
`callbackUrl`::
Enter the callback URL that GitHub uses when initiating an OAuth flow, such as: __<your_intermediate_service_url/handler>__.
Define it when {product-short} is not the immediate receiver, such as in cases when you use one OAuth app for many {product-short} instances.
+
.`{my-app-config-file}` file fragment with optional `enterpriseInstanceUrl` field
[source,yaml,subs="+quotes"]
----
auth:
  providers:
    github:
      production:
        callbackUrl: __<your_intermediate_service_url/handler>__
----

`sessionDuration`::
Enter the user session lifespan.
Enter a duration in `ms` library format (such as '24h', '2 days'), ISO duration, or "human duration" as used in code.
+
.`app-config-rhdh.yaml` fragment with optional `sessionDuration` field
[source,yaml,subs="+quotes"]
----
auth:
  providers:
    github:
      production:
        sessionDuration: { hours: 24 }
----

`signIn`::

`resolvers`:::
After successful authentication, the user signing in must be resolved to an existing user in the {product-short} catalog.
To best match users securely for your use case, consider configuring a specific resolver.
Enter the resolver list to override the default resolver: `usernameMatchingUserEntityName`.
+
The authentication provider tries each sign-in resolver in order until it succeeds, and fails if none succeed.
+
WARNING: In production mode, only configure one resolver to ensure users are securely matched.

`resolver`::::
Enter the sign-in resolver name.
Available resolvers:

* `usernameMatchingUserEntityName`
* `preferredUsernameMatchingUserEntityName`
* `emailMatchingUserEntityProfileEmail`

`dangerouslyAllowSignInWithoutUserInCatalog: true`::::
Configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
WARNING: Use `dangerouslyAllowSignInWithoutUserInCatalog` to explore {product-short} features, but do not use it in production.
+
.`{my-app-config-file}` file fragment with optional field to allow signing in users absent from the software catalog
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTHENTICATION_GITHUB_CLIENT_ID}
        clientSecret: ${AUTHENTICATION_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: github
----

.Verification
. To verify user and group provisioning, check the console logs.
+
.Successful synchronization example:
[source,json]
----
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Reading GitHub users and teams for org: rhdh-dast","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:production:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:58"}
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Read 7 GitHub users and 2 GitHub groups in 0.4 seconds. Committing...","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:production:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:59"}
----

. To verify GitHub authentication:
.. Go to the {product-short} login page.
.. Your {product-short} sign-in page displays *Sign in using GitHub* and the Guest user sign-in is disabled.
.. Log in with a GitHub account.

