[id="provisioning-users-from-github-to-the-software-catalog"]
= Provisioning users from GitHub to the software catalog

To authenticate users, {product} requires their presence in the software catalog.
Consider configuring {product-short} to provision users from GitHub to the software catalog on schedule, rather than provisioning the users manually.

.Prerequisites
* You have xref:enabling-authentication-with-github[enabled authentication with GitHub], including the following secrets:
** `GITHUB_HOST_DOMAIN`
** `GITHUB_ORGANIZATION`

.Procedure

* To enable GitHub member discovery, edit your custom {product-short} ConfigMap, such as `app-config-rhdh`, and add the following lines to the `{my-app-config-file}` content:
+
--
[id=githubProviderId]
.`{my-app-config-file}` fragment with mandatory `github` fields
[source,yaml]
----
catalog:
  providers:
    github:
      providerId:
        organization: "${GITHUB_ORGANIZATION}"
        schedule:
          frequency:
            minutes: 30
          initialDelay:
            seconds: 15
          timeout:
            minutes: 15
    githubOrg:
      githubUrl: "${GITHUB_HOST_DOMAIN}"
      orgs: [ "${GITHUB_ORGANIZATION}" ]
      schedule:
        frequency:
          minutes: 30
        initialDelay:
          seconds: 15
        timeout:
          minutes: 15
----

`organization`, `githubUrl`, and `orgs`::
Use the {product-short} application information that you have created in GitHub and configured in OpenShift as secrets.

`schedule.frequency`::
To specify custom schedule frequency.
Supports cron, ISO duration, and "human duration" as used in code.

`schedule.timeout`::
To specify custom timeout.
Supports ISO duration and "human duration" as used in code.

`schedule.initialDelay`::
To specify custom initial delay.
Supports ISO duration and "human duration" as used in code.
--

.Verification
. Check the console logs to verify that the synchronization is completed.
+
.Successful synchronization example:
[source,json]
----
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Reading GitHub users and teams for org: rhdh-dast","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:production:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:58"}
{"class":"GithubMultiOrgEntityProvider","level":"info","message":"Read 7 GitHub users and 2 GitHub groups in 0.4 seconds. Committing...","plugin":"catalog","service":"backstage","target":"https://github.com","taskId":"GithubMultiOrgEntityProvider:production:refresh","taskInstanceId":"801b3c6c-167f-473b-b43e-e0b4b780c384","timestamp":"2024-09-09 23:55:59"}
----

. Log in with a GitHub account.

