[id="enabling-authentication-with-microsoft-azure"]
= Enabling authentication with Microsoft Azure

{product} includes a Microsoft Azure authentication provider that can authenticate users by using OAuth.

.Prerequisites
. You have the permission to register an application in Microsoft Azure.
* You link:{configuring-book-url}[added a custom {product-short} application configuration], and have sufficient permissions to modify it.

.Procedure
. To allow {product-short} to authenticate with Microsoft Azure, link:https://learn.microsoft.com/en-us/entra/identity-platform/scenario-web-app-sign-user-app-registration?tabs=aspnetcore#register-an-app-by-using-the-azure-portal[create an OAuth application in Microsoft Azure].

.. In the Azure portal go to link:https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationsListBlade[*App registrations*], create a **New registration** with the configuration:
+
**Name**:: The application name in Azure, such as __<My {product-short}>__.

.. On the *Home > App registrations > __<My {product-short}>__ > Manage > Authentication* page, *Add a platform*, with the following configuration:

*Redirect URI*:: Enter the backend authentication URI set in {product-short}: `pass:c,a,q[{my-product-url}/api/auth/microsoft/handler/frame]`
*Front-channel logout URL*:: Leave blank.
*Implicit grant and hybrid flows*:: Leave all checkboxes cleared.

.. On the *Home > App registrations > __<My {product-short}>__ > Manage > API permissions* page, *Add a Permission*, then add the following *Delegated permission* for the *Microsoft Graph API*:
+
* `email`
* `offline_access`
* `openid`
* `profile`
* `User.Read`
* Optional custom scopes for the Microsoft Graph API that you define both in this section and in the {product-short} configuration (`app-config-rhdh.yaml`).
+
[NOTE]
====
Your company might require you to grant admin consent for these permissions.
Even if your company does not require admin consent, you might do so as it means users do not need to individually consent the first time they access backstage.
To grant administrator consent, a directory administrator must go to the link:https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/user-admin-consent-overview[admin consent] page and click *Grant admin consent for COMPANY NAME*.
====


.. On the *Home > App registrations > __<My {product-short}>__ > Manage > Certificates & Secrets* page, in the *Client secrets* tab, create a *New client secret*.

.. Save for the next step:
- **Directory (tenant) ID**
- **Application (client) ID**
- **Application (client) secret**

. To add your Microsoft Azure credentials to {product-short}, add the following key/value pairs to link:{configuring-dynamic-plugins-book-url}#provisioning-your-custom-configuration[your {product-short} secrets]:
+
`AUTH_AZURE_TENANT_ID`:: Enter your saved *Directory (tenant) ID*.
`AUTH_AZURE_CLIENT_ID`:: Enter your saved *Application (client) ID*.
`AUTH_AZURE_CLIENT_SECRET`:: Enter your saved *Application (client) secret*.

. Set up the Microsoft Azure authentication provider in your {product-short} custom configuration, such as `app-config-rhdh`:
.. Configure mandatory fields:
+
.`app-config-rhdh.yaml` fragment
[source,yaml,subs="+quotes,+attributes"]
----
auth:
  environment: production # <1>
  providers:
    microsoft:
      production:
        clientId: ${AUTH_AZURE_CLIENT_ID} # <2>
        clientSecret: ${AUTH_AZURE_CLIENT_SECRET}
        tenantId: ${AUTH_AZURE_TENANT_ID}
signInPage: microsoft # <3>
----
<1> Mark the environment as production and disable the **Guest** login option in the {product-short} login page.
<2> Apply the Microsoft Azure credentials configured in your {product-short} secrets.
<3> Set the Microsoft Azure provider as your {product-short} sign-in provider.

.. Optional: Consider adding following optional fields:

`domainHint`::
Optional for single-tenant applications.
You can reduce login friction for users with accounts in multiple tenants by automatically filtering out accounts from other tenants.
If you want to use this parameter for a single-tenant application, uncomment and enter the tenant ID.
If your application registration is multi-tenant, leave this parameter blank.
For more information, see link:https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/home-realm-discovery-policy[Home Realm Discovery].
+
.`app-config-rhdh.yaml` fragment with optional `domainHint` field
[source,yaml,subs="+quotes,+attributes"]
----
auth:
  environment: production
  providers:
    microsoft:
      production:
        domainHint: ${AUTH_AZURE_TENANT_ID}
----

`additionalScopes`::
Optional for additional scopes.
To add scopes for the application registration, uncomment and enter the list of scopes that you want to add.
The default and mandatory value lists: `'openid', 'offline_access', 'profile', 'email', 'User.Read'`.
+
.`app-config-rhdh.yaml` fragment with optional `additionalScopes` field
[source,yaml,subs="+quotes,+attributes"]
----
auth:
  environment: production
  providers:
    microsoft:
      production:
        additionalScopes:
           - Mail.Send
----
`sessionDuration`::
Lifespan of the user session.
Enter a duration in `ms` library format (such as '24h', '2 days'), ISO duration, or "human duration" as used in code.
+
.`app-config-rhdh.yaml` fragment with optional `sessionDuration` field
[source,yaml,subs="+quotes"]
----
auth:
  providers:
    microsoft:
      production:
        sessionDuration: { hours: 24 }
----

`signIn` ::

`resolvers`:::
After successful authentication, the user signing in must be resolved to an existing user in the {product-short} catalog. To best match users securely for your use case, consider configuring a specific resolver. Enter the resolver list to override the default resolver: `emailLocalPartMatchingUserEntityName`.
+
The authentication provider tries each sign-in resolver in order until it succeeds, and fails if none succeed.
+
WARNING: In production mode, only configure one resolver to ensure users are securely matched. 

`resolver`::::
Enter the sign-in resolver name.
Available resolvers:

* `userIdMatchingUserEntityAnnotation`
* `emailLocalPartMatchingUserEntityName`
* `emailMatchingUserEntityProfileEmail`

`dangerouslyAllowSignInWithoutUserInCatalog: true`::::
Configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
WARNING: Use `dangerouslyAllowSignInWithoutUserInCatalog` to explore {product-short} features, but do not use it in production.
+
.`app-config-rhdh.yaml` fragment with optional field to allow signing in users absent from the software catalog
[source,yaml]
----
auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${AUTH_AZURE_CLIENT_ID}
        clientSecret: ${AUTH_AZURE_CLIENT_SECRET}
        tenantId: ${AUTH_AZURE_TENANT_ID}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: microsoft
----

[NOTE]
====
This step is optional for environments with outgoing access restrictions, such as firewall rules.
 If your environment has such restrictions, ensure that your {product-very-short} backend can access the following hosts:

* `login.microsoftonline.com`: For obtaining and exchanging authorization codes and access tokens.

* `graph.microsoft.com`: For retrieving user profile information (as referenced in the source code).
If this host is unreachable, you might see an _Authentication failed, failed to fetch user profile_ error when attempting to log in.
====
