:_mod-docs-content-type: PROCEDURE

[id="enabling-auto-logout-for-inactive-users"]
= Enabling auto-logout for inactive users

To enhance security, you can configure {product} to automatically log out users after a specified period of inactivity.
This helps prevent unauthorized access to stale user sessions.

.Prerequisites

* You have administrative access to the {product} configuration files.

.Procedure

. Add the `auth.autologout` section to your `my-app-config.yaml` file.
+
[source,yaml]
----
auth:
  autologout:
    enabled: true
    idleTimeoutMinutes: 0.5
    promptBeforeIdleSeconds: 10
    useWorkerTimers: true
    logoutIfDisconnected: true
----
+
where:

`enabled`::
Enter `true` to enable auto-logout.
+
Enter `false` to disable auto-logout.
+
The default value is `false`.

`idleTimeoutMinutes`::
(Optional) Enter the number of minutes of inactivity before automatically logging out the user.
+
The default value is `0.5` minutes.

`promptBeforeIdleSeconds`::
(Optional) Enter the number of seconds before the auto-logout occurs to prompt the user about the pending logout.
+
The default value is `10` seconds.

`useWorkerTimers`::
(Optional) Enter `true` to use web worker timers for tracking user activity, and avoid issues when your browser stops timers in inactive tabs.
+
Enter `false` to use main thread timers, when your browser does not support web workers. Your browser might stop timers in inactive tabs, which can affect the auto-logout functionality.
+
The default value is `true`.

`logoutIfDisconnected`::
(Optional) Enter `true` to log out the users with no active connection, in case of network issues, or when they have no active {product-short} tab open in their browser.
+
Enter `false` to keep the user logged in during temporary disconnections, or when they have no active {product-short} tab open in their browser.
+
The default value is `true`.

. Restart the {product} application to apply the changes.

.Verification

. Log in to the {product} application.
. Remain inactive for the duration specified in `idleTimeoutMinutes`.
. Observe that a prompt is displayed before the auto-logout occurs, as specified in `promptBeforeIdleSeconds`.
. Confirm that you are automatically logged out after the inactivity period.
