:_mod-docs-content-type: SNIPPET

Authenticate users with GitHub by provisioning the users and groups from GitHub to the {product-short} software catalog, and configuring the GitHub authentication provider in {product}.

.Prerequisites
* You {configuring-book-link}[added a custom {product-short} application configuration], and have enough permissions to change it.
* You have enough permissions in GitHub to create and manage a link:https://docs.github.com/en/apps/overview[GitHub App].
Alternatively, you can ask your GitHub administrator to prepare the required GitHub App.

.Procedure
. To allow {product-short} to authenticate with GitHub, create a GitHub App.
Opt for a GitHub App instead of an OAuth app to use fine-grained permissions, use short-lived tokens, scale with the number of installations by avoiding rate limits, and have a more transparent integration by avoiding to request user input.

.. link:https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app[Register a GitHub App] with the following configuration:

GitHub App name::
Enter a unique name identifying your GitHub App, such as `authenticating-with-rhdh-__<GUID>__`.

Homepage URL::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your {product-short} authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/github/handler/frame]`.

Webhook::
Clear "Active", as this is not needed for authentication and catalog providers.

Organization permissions::
Enable `Read-only` access to *Members*.

Where can this GitHub App be installed?::
Select `Only on this account`.

.. In the *General* -> *Clients secrets* section, click *Generate a new client secret*.

.. In the *Install App* tab, choose an account to install your GitHub App on.

.. Save the following values for the next step:

* **Client ID**
* **Client secret**

. To add your GitHub credentials to {product-short}, add the following key/value pairs to {configuring-book-link}#provisioning-your-custom-configuration[your {product-short} secrets].
You can use these secrets in the {product-short} configuration files by using their environment variable name.

`GITHUB_CLIENT_ID`::
Enter the saved **Client ID**.

`GITHUB_CLIENT_SECRET`::
Enter the saved **Client Secret**.

`GITHUB_URL`::
Enter the GitHub host domain: `github.com`.

`GITHUB_ORG`::
Enter your GitHub organization name, such as `__<your_github_organization_name>__`.

. Enable the GitHub organization provisioning plugin (`backstage-plugin-catalog-backend-module-github-org`).
This plugin imports GitHub users and groups to the {product-short} software catalog.
+
`dynamic-plugins.yaml` file fragment:
+
[source,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org'
    disabled: false
----

. Provision GitHub users and groups to the {product-short} software catalog by adding the `catalog.providers.githubOrg` section to your custom {product-short} `{my-app-config-file}` configuration file:
+
[id=githubProviderId]
[source,yaml]
----
catalog:
  providers:
    githubOrg:
      id: githuborg
      githubUrl: "${GITHUB_URL}"
      orgs: [ "${GITHUB_ORG}" ]
      schedule:
        frequency:
          minutes: 30
        initialDelay:
          seconds: 15
        timeout:
          minutes: 15
----

`id`::
Enter a stable identifier for this provider, such as `githuborg`.
Entities from this provider are associated with this identifier, therefore you must take care not to change it over time since that might lead to orphaned entities or conflicts.

`githubUrl`::
Enter the configured secret variable name: `$\{GITHUB_URL}`.

`orgs`::
Enter the configured secret variable name: `$\{GITHUB_ORG}`.

`schedule.frequency`::
Enter your schedule frequency, in the cron, ISO duration, or "human duration" format.

`schedule.timeout`::
Enter your schedule timeout, in the ISO duration or "human duration" format.

`schedule.initialDelay`::
Enter your schedule initial delay, in the ISO duration or "human duration" format.

. To set up the GitHub authentication provider, add the `auth.providers.github` section to your `{my-app-config-file}` file:
+
[source,yaml]
----
auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
signInPage: github
----

`environment`::
Enter `production` to disable the Guest login option in the {product-short} login page.

`clientId`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `$\{GITHUB_CLIENT_SECRET}`.

`signInPage`::
Enter `github` to enable the GitHub provider as your {product-short} sign-in provider.
