:_mod-docs-content-type: SNIPPET

Optional: Consider adding optional fields to the `auth.providers.microsoft` section in your `{my-app-config-file}` file:

[source,yaml,subs="+quotes,+attributes"]
----
auth:
  environment: production
  providers:
    microsoft:
      production:
        clientId: ${AUTHENTICATION_AZURE_CLIENT_ID}
        clientSecret: ${AUTHENTICATION_AZURE_CLIENT_SECRET}
        tenantId: ${AUTHENTICATION_AZURE_TENANT_ID}
        domainHint: ${AUTHENTICATION_AZURE_TENANT_ID}
        additionalScopes:
           - Mail.Send
        sessionDuration:
          hours: 24
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
              dangerouslyAllowSignInWithoutUserInCatalog: true
signInPage: microsoft
----

`domainHint`::
Optional for single-tenant applications.
You can reduce login friction for users with accounts in multiple tenants by automatically filtering out accounts from other tenants.
If you want to use this parameter for a single-tenant application, uncomment and enter the tenant ID.
If your application registration is multi-tenant, leave this parameter blank.
For more information, see link:https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/home-realm-discovery-policy[Home Realm Discovery].

`additionalScopes`::
Optional for additional scopes.
To add scopes for the application registration, uncomment and enter the list of scopes that you want to add.
The default and mandatory value lists following scopes:
* `openid`
* `offline_access`
* `profile`
* `email`
* `User.Read`

`sessionDuration`::
Lifespan of the user session.
Enter a duration in `ms` library (such as '24h', '2 days'), ISO duration, or "human duration" format.

`signIn.resolvers`::
After successful authentication, {product-short} resolves the user signing in to an existing user in the {product-short} catalog.
To best match users securely for your use case, consider configuring a specific resolver.
+
Enter the resolver list to override the default resolver: `userIdMatchingUserEntityAnnotation`.
+
The authentication provider tries each sign-in resolver in order until it succeeds, and fails if none succeed.
+
WARNING: In production mode, only configure one resolver to ensure users are securely matched.

`resolver`::
Enter the sign-in resolver name.
Available resolvers:

`emailMatchingUserEntityAnnotation`:::
This resolver looks up the user by matching their Microsoft email to the email entity annotation.

`emailLocalPartMatchingUserEntityName`:::
This resolver looks up the user by matching their Microsoft email user name to the user entity name.

`emailMatchingUserEntityProfileEmail`:::
This resolver looks up the user by matching their Microsoft email to the user entity profile email.

`dangerouslyAllowSignInWithoutUserInCatalog: true`::
Configure the sign-in resolver to bypass the user provisioning requirement in the {product-short} software catalog.
+
WARNING: Use `dangerouslyAllowSignInWithoutUserInCatalog` to explore {product-short} features, but do not use it in production.
