`includeTransitiveGroupOwnership`::
Enable this option to add transitive parent groups in the resolved user group membership during authentication. This ensures that a user’s indirect parent groups, in addition to their direct group, are reflected in the user ownership entities.
See: xref:{authorization-book-url}#con-rbac-conditional-policies-rhdh_title-authorization[Conditional policies in {product}].
By default, this option is set to false.
+
.Effect on group membership
====
With this group hierarchy:
----
group_admin
  └── group_developers
    └── user_alice
----

* If `includeTransitiveGroupOwnership: false`, the `user_alice` user is only a member of the `group_developers` group.

* If `includeTransitiveGroupOwnership: true`, the `user_alice` user is a member of both `group_developers` and `group_admin` groups.
====
+
To enable this option:
+
.`app-config-rhdh.yaml` fragment with optional field to include transitive group ownership
[source,yaml]
----
includeTransitiveGroupOwnership: true
auth:
  providers:
# ...
----
