:_mod-docs-content-type: SNIPPET

. Register GitLab OAuth 2 application to allow {product-very-short} to authenticate with GitLab. You must use the required callback URL and permissions.
.. link:https://docs.gitlab.com/integration/oauth_provider/[Register a GitLab OAuth 2 application] using the following configuration:
+
--
GitLab OAuth 2 application name::
Enter a unique name, such as `authenticating-with-rhdh-__<GUID>__`.

Redirect URI::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/gitlab/handler/frame]`.

Authorized application scope::
Enable `email`, `profile`, `openid`, and `read_user`.
--
.. Save the application and record these values for the next step:

* **OAuth 2 Client ID**, available in the *Application ID* field
* **OAuth 2 Client secret**, accessible by selecting *Copy* in the *Secret* field

. Create a link:https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html[GitLab personal access token] with the `read_api` scope. Save this token to use in your OpenShift secret.

. Add your GitLab credentials to {configuring-book-link}#provisioning-your-custom-configuration[your {product-very-short} secrets] using the following key/value pairs.
Use these environment variables in your {product-very-short} configuration files.

`GITLAB_HOST`::
Enter your GitLab host: `<gitlab_host>`.

`GITLAB_CLIENT_ID`::
Enter the saved *OAuth 2 Client ID*.

`GITLAB_CLIENT_SECRET`::
Enter the saved *OAuth 2 Client Secret*.

`GITLAB_TOKEN`::
Enter your *GitLab personal access token*.

`GITLAB_URL`::
Enter the GitLab host domain: __`<gitlab_host_domain>`__.

`GITLAB_PARENT_ORG`::
Enter your GitLab organization name, such as `__<your_gitlab_organization_name>__`.

. Configure the GitLab integration by adding the following section to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
integrations:
  gitlab:
    - host: $\{GITLAB_HOST}
      token: $\{GITLAB_TOKEN}
----

. Enable the GitLab catalog provider plugin in your `dynamic-plugins.yaml` file to import GitLab users and groups to the {product-short} software catalog.
+
[source,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
    disabled: false
----

. Enable provisioning for GitLab users and groups to the {product-short} software catalog by adding the provider section to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
catalog:
  providers:
    gitlab:
      default:
        host: $\{GITLAB_HOST}
        orgEnabled: true
        group: $\{GITLAB_PARENT_ORG}
        restrictUsersToGroup: true
        includeUsersWithoutSeat: true
        schedule:
          initialDelay:
            seconds: 0
          frequency:
            minutes: 50
          timeout:
            minutes: 50
----

`host`::
Enter your GitLab instance address: pass:c,a,q[`${GITLAB_HOST}`].

`orgEnabled`::
Set to `true` to enable the ingestion of GitLab organizational data, such as users and groups. For gitlab.com, you must also provide a value for the `group` parameter.

`group`::
Enter your configured link:https://docs.gitlab.com/user/group/[GitLab parent group]: `${GITLAB_PARENT_ORG}`.

`restrictUsersToGroup`::
Set to `true` to ingest only users who are direct members of the configured group.

`includeUsersWithoutSeat`::
Set to `true` to include users who do not occupy a paid seat. This setting applies only to GitLab SaaS.

`relations`::
Specify the types of group memberships to include during ingestion. You can use the following values:
* `INHERITED`: Includes members of any ancestor groups as members of the current group.
* `DESCENDANTS`: Includes members of any descendant groups as members of the current group.
* `SHARED_FROM_GROUPS`: Includes members of any invited groups as members of the current group.

`schedule.frequency`::
Enter your schedule frequency, in the cron, ISO duration, or "human duration" format.

`schedule.timeout`::
Enter your schedule timeout, in the ISO duration or "human duration" format.

`schedule.initialDelay`::
Enter your schedule initial delay, in the ISO duration or "human duration" format.

. Enable the GitLab authentication provider by adding the GitLab authentication provider section to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml,subs="+quotes,+attributes"]
----
includeTransitiveGroupOwnership: true
signInPage: gitlab
auth:
  environment: production
  session:
    secret: _<name_of_secret>_
  providers:
    gitlab:
      production:
        audience: https://${GITLAB_HOST}
        clientId: $\{GITLAB_CLIENT_ID}
        clientSecret: $\{GITLAB_CLIENT_SECRET}
        callbackUrl: {my-product-url}/api/auth/gitlab/handler/frame
----
+

`audience`::
Enter your GitLab instance address: `pass:c,a,q[https://${GITLAB_HOST}]`

`clientId`::
Enter the configured client ID: `${GITLAB_CLIENT_ID}`.

`clientSecret`::
Enter the configured secret variable name: `${GITLAB_CLIENT_SECRET}`.

`callbackUrl`::
Enter your {product-short} authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/gitlab/handler/frame]`
