[id='con-rbac-config-permission-policies-external-file_{context}']
= Configuration of permission policies defined in an external file

You can configure the permission policies before starting the {product}. If permission policies are defined in an external file, then you can import the same file in the {product-short}. You must define the permission policies using the following Casbin rules format:

[source,format]
---
`p, <ROLE>, <PERMISSION_NAME or PERMISSION_RESOURCE_TYPE>, <PERMISSION_POLICY_ACTION>, <ALLOW or DENY>`
---

You can define roles using the following Casbin rules format:

[source,format]
---
`g, <USER or GROUP>, <ROLE>`
---

[NOTE]
====
For information about the Casbin rules format, see https://casbin.org/docs/category/the-basics[Basics of Casbin rules].
====

The following is an example of permission policies configuration:

[source,csv]
---
`p, role:default/guests, catalog-entity, read, allow`

`p, role:default/guests, catalog.entity.create, create, allow`

`g, user:default/<USER_TO_ROLE>, role:default/guests`

`g, group:default/<GROUP_TO_ROLE>, role:default/guests`
---

If a defined permission does not contain an action associated with it, then add `use` as a policy. See the following example:

[source,csv]
---
`p, role:default/guests, kubernetes.proxy, use, allow`
---

You can define the `policy.csv` file path in the `app-config.yaml` file:

[source,yaml]
----
permission:
  enabled: true
  rbac:
    policies-csv-file: /some/path/rbac-policy.csv
----

You can use an optional configuration value that enables reloading the CSV file without restarting the {product-short} instance.

Set the value of the `policyFileReload` option in the `app-config.yaml` file:

[source,yaml]
----
# ...
permission:
  enabled: true
  rbac:
    policies-csv-file: /some/path/rbac-policy.csv
    policyFileReload: true
    # ...
----
