[id='con-permission-policy-and-role-source']
= Understanding permission policy and role configuration source

You can manipulate permission policies and roles based on the following designated source information:

* CSV file
* Configuration file
* REST API
* Legacy

Each permission policy and role is associated with a source to maintain data consistency.
Therefore, when a policy has been created in a CSV file, you cannot change it by using the REST API.


Managing roles and permission policies originating from CSV files and REST API involves straightforward modification based on their initial source information.

The Configuration file pertains to the default `role:default/rbac_admin` role provided by the RBAC plugin.
The default role has limited permissions to create, read, update, and delete permission policies or roles, and to read catalog entities.

[NOTE]
====
In case the default permissions are insufficient for your administrative requirements, you can create a custom admin role with required permission policies.
====

The legacy source applies to policies and roles defined before RBAC backend plugin version `2.1.3`, and is the least restrictive among the source location options.
You must update the permissions and roles in legacy source to use either REST API or the CSV file sources.

You can use the `GET` requests to query roles and policies and determine the source information, if required.

