:_mod-docs-content-type: PROCEDURE

[id="delete-a-role-in-the-rhdh-web-ui_{context}"]
= Delete a role in the {product} Web UI

[role="_abstract"]
Delete a role in {product-short} by using the Web UI to remove roles that are no longer needed.

You can delete a role in the {product} using the Web UI.

[NOTE]
====
The policies generated from a `policy.csv` or ConfigMap file cannot be edited or deleted using the {product-short} Web UI.
====

.Prerequisites
* You {authorization-book-link}#enabling-and-giving-access-to-rbac_title-authorization[have enabled RBAC and have a policy administrator role in {product-short}].
* The role that you want to delete is created in the {product-short}.

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
The *RBAC* tab is displayed, showing all the created roles in the {product-short}.

. (Optional) Click any role to view the role information on the *OVERVIEW* page.
. Select the delete icon from the *Actions* column for the role that you want to delete.
+
The *Delete this role?* pop-up is displayed on the screen.
. Click *DELETE*.
