:_mod-docs-content-type: PROCEDURE

[id="proc-delegating-rbac-access-api_{context}"]
= Delegating RBAC access in {product} by using API

You can delegate the RBAC access in {product} by using the RBAC backend API.

.Prerequisites
* You have API access using `curl` or another tool.

.Procedure
. Create a new role designated for team leads using the RBAC backend API:
+
--
.Example of creating a new role for the team lead using the RBAC backend API
[source,bash]
----
curl -X POST 'http://localhost:7007/api/permission/roles' \
--header "Authorization: Bearer $ADMIN_TOKEN" \
--header "Content-Type: application/json" \
--data '{
  "memberReferences": ["user:default/team_lead"],
  "name": "role:default/team_lead",
  "metadata": {
    "description": "This is an example team lead role"
  }
}'
----
--

. Allow team leads to read catalog entities and create permissions in the RBAC plugin using the following API request:
+
--
.Example of granting the team lead role permission to create RBAC policies and read catalog entities
[source,bash]
----
curl -X POST 'http://localhost:7007/api/permission/policies' \
--header "Authorization: Bearer $ADMIN_TOKEN" \
--header "Content-Type: application/json" \
--data '[
  {
    "entityReference": "role:default/team_lead",
    "permission": "policy.entity.create",
    "policy": "create",
    "effect": "allow"
  },
  {
    "entityReference": "role:default/team_lead",
    "permission": "catalog-entity",
    "policy": "read",
    "effect": "allow"
  }
]'
----
--

. To ensure team leads can only manage what they own, use the `IS_OWNER` conditional rule as follows:
+
--
.Example `curl` of applying a conditional access policy using the `IS_OWNER` rule for the team lead role
[source,bash]
----
curl -X POST 'http://localhost:7007/api/permission/roles/conditions' \
--header "Authorization: Bearer $ADMIN_TOKEN" \
--header "Content-Type: application/json" \
--data '{
 "result": "CONDITIONAL",
 "pluginId": "permission",
 "resourceType": "policy-entity",
 "conditions": {
   "rule": "IS_OWNER",
   "resourceType": "policy-entity",
   "params": {
     "owners": [
       "user:default/team_lead"
     ]
   }
 },
 "roleEntityRef": "role:default/team_lead",
 "permissionMapping": [
   "read",
   "update",
   "delete"
 ]
}'
----
The previous example of conditional policy limits visibility and control to only owned roles and policies.
--

. Log in to {product-very-short} as team lead and verify the following:
+
--
.. Use the following request and verify that you do not see any roles:
+
.Example `curl` to retrieve roles visible to the team lead
[source,bash]
----
curl -X GET 'http://localhost:7007/api/permission/roles' \
--header "Authorization: Bearer $TEAM_LEAD_TOKEN"

----

.. Use the following request to create a new role for their team:
+
.Example `curl` of team lead creating a new role for their team with ownership assigned
[source,bash]
----
curl -X POST 'http://localhost:7007/api/permission/roles' \
--header "Authorization: Bearer $TEAM_LEAD_TOKEN" \
--header "Content-Type: application/json" \
--data '{
  "memberReferences": ["user:default/team_member"],
  "name": "role:default/team_a",
  "metadata": {
    "description": "This is an example team_a role",
    "owner": "user:default/team_lead"
  }
}'
----
+
[NOTE]
====
You can set the ownership during creation, but you can also update the ownership at any time.
====

.. Use the following request to assign a permission policy to the new role:
+
.Example `curl` for granting read access to catalog entities for the new role
[source,bash]
----
curl -X POST 'http://localhost:7007/api/permission/policies' \
--header "Authorization: Bearer $ADMIN_TOKEN" \
--header "Content-Type: application/json" \
--data '[
  {
    "entityReference": "role:default/team_a",
    "permission": "catalog-entity",
    "policy": "read",
    "effect": "allow"
  }
]'
----

.. Use the following request to verify that only team-owned roles and policies are visible:
+
.Example `curl` to retrieve roles and permission policies visible to the team lead
[source,bash]
----
curl -X GET 'http://localhost:7007/api/permission/roles' \
--header "Authorization: Bearer $TEAM_LEAD_TOKEN"

curl -X GET 'http://localhost:7007/api/permission/policies' \
--header "Authorization: Bearer $TEAM_LEAD_TOKEN"
----
--

.Verification
* Log in as a team lead and verify the following:
+
--
** The RBAC UI is accessible.
** Only the assigned users or group is visible.
** Permissions outside the scoped team are not viewable or editable.
--
* Log in as an administrator and verify that you retain full visibility and control.



