[id='proc-rbac-ui-create-role_{context}']
= Creating a role in the {product} Web UI

You can create a role in the {product} using the Web UI.

.Prerequisites
* You xref:enabling-and-giving-access-to-rbac[have enabled RBAC, have a policy administrator role in {product-short} and have added plugins with permission].

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
--
The *RBAC* tab appears, displaying all the created roles in the {product-short}.
--

. (Optional) Click any role to view the role information on the *OVERVIEW* page.
. Click *CREATE* to create a role.
. Enter the name and description of the role in the given fields and click *NEXT*.
. Add users and groups using the search field, and click *NEXT*.
. Select *Plugin* and *Permission* from the drop-downs in the *Add permission policies* section.
. Select or clear the *Policy* that you want to set in the *Add permission policies* section, and click *NEXT*.
. Review the added information in the *Review and create* section.
. Click *CREATE*.

.Verification

The created role appears in the list available in the *RBAC* tab.


