:_mod-docs-content-type: REFERENCE

[id="ref-rbac-rest-api-endpoints_{context}"]
= Supported RBAC REST API endpoints

The RBAC REST API provides endpoints for managing roles, permissions, and conditional policies in the {product-short} and for retrieving information about the roles and policies.

== Roles

The RBAC REST API supports the following endpoints for managing roles in the {product}.

[GET] /api/permission/roles::
+
--
Returns all roles in {product-short}.

.Example response (JSON)
[source,json]
----
[
  {
    "memberReferences": ["user:default/username"],
    "name": "role:default/guests"
  },
  {
    "memberReferences": [
      "group:default/groupname",
      "user:default/username"
    ],
    "name": "role:default/rbac_admin"
  }
]
----
--

[GET] /api/permission/roles/__<kind>__/__<namespace>__/__<name>__::
+
--
Returns information for a single role in {product-short}.

.Example response (JSON)
[source,json]
----
[
  {
    "memberReferences": [
      "group:default/groupname",
      "user:default/username"
    ],
    "name": "role:default/rbac_admin"
  }
]
----
--

[POST] /api/permission/roles/__<kind>__/__<namespace>__/__<name>__::
+
--
Creates a role in {product-short}.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`body`
|The `memberReferences`, `group`, `namespace`, and `name` the new role to be created.
|Request body
|Required
|===

.Example request body (JSON)
[source,json]
----
{
  "memberReferences": ["group:default/test"],
  "name": "role:default/test_admin"
}
----

.Example response
[source]
----
201 Created
----
--

[PUT] /api/permission/roles/__<kind>__/__<namespace>__/__<name>__::
+
--
Updates `memberReferences`, `kind`, `namespace`, or `name` for a role in {product-short}.

.Request parameters
The request body contains the `oldRole` and `newRole` objects:
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`body`
|The `memberReferences`, `group`, `namespace`, and `name` the new role to be created.
|Request body
|Required
|===

.Example request body (JSON)
[source,json]
----
{
  "oldRole": {
    "memberReferences": ["group:default/test"],
    "name": "role:default/test_admin"
  },
  "newRole": {
    "memberReferences": ["group:default/test", "user:default/test2"],
    "name": "role:default/test_admin"
  }
}
----

.Example response
[source]
----
200 OK
----
--

[DELETE] /api/permission/roles/__<kind>__/__<namespace>__/__<name>__?memberReferences=<VALUE>::
+
--
Deletes the specified user or group from a role in {product-short}.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`kind`
|Kind of the entity
|String
|Required

|`namespace`
|Namespace of the entity
|String
|Required

|`name`
|Name of the entity
|String
|Required

|`memberReferences`
|Associated group information
|String
|Required
|===

.Example response
[source]
----
204
----
--

[DELETE] /api/permission/roles/__<kind>__/__<namespace>__/__<name>__::
+
--
Deletes a specified role from {product-short}.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`kind`
|Kind of the entity
|String
|Required

|`namespace`
|Namespace of the entity
|String
|Required

|`name`
|Name of the entity
|String
|Required
|===

.Example response
[source]
----
204
----
--

== Permission policies

The RBAC REST API supports the following endpoints for managing permission policies in the {product}.

[GET] /api/permission/policies::
+
--
Returns permission policies list for all users.

.Example response (JSON)
[source,json]
----
[
  {
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "read",
    "effect": "allow",
    "metadata": {
      "source": "csv-file"
    }
  },
  {
    "entityReference": "role:default/test",
    "permission": "catalog.entity.create",
    "policy": "use",
    "effect": "allow",
    "metadata": {
      "source": "csv-file"
    }
  },
]
----
--

[GET] /api/permission/policies/__<kind>__/__<namespace>__/__<name>__::
+
--
Returns permission policies related to the specified entity reference.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`kind`
|Kind of the entity
|String
|Required

|`namespace`
|Namespace of the entity
|String
|Required

|`name`
|Name related to the entity
|String
|Required
|===

.Example response (JSON)
[source,json]
----
[
  {
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "read",
    "effect": "allow",
    "metadata": {
      "source": "csv-file"
    }
  },
  {
    "entityReference": "role:default/test",
    "permission": "catalog.entity.create",
    "policy": "use",
    "effect": "allow",
    "metadata": {
      "source": "csv-file"
    }
  }
]
----
--

[POST] /api/permission/policies::
+
--
Creates a permission policy for a specified entity.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`entityReference`
|Reference values of an entity including `kind`, `namespace`, and `name`
|String
|Required

|`permission`
|Permission from a specific plugin, resource type, or name
|String
|Required

|`policy`
|Policy action for the permission, such as `create`, `read`, `update`, `delete`, or `use`
|String
|Required

|`effect`
|Indication of allowing or not allowing the policy
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
[
  {
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "read",
    "effect": "allow"
  }
]
----

.Example response
[source]
----
201 Created
----
--

[PUT] /api/permission/policies/__<kind>__/__<namespace>__/__<name>__::
+
--
Updates a permission policy for a specified entity.

.Request parameters
The request body contains the `oldPolicy` and `newPolicy` objects:
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`permission`
|Permission from a specific plugin, resource type, or name
|String
|Required

|`policy`
|Policy action for the permission, such as `create`, `read`, `update`, `delete`, or `use`
|String
|Required

|`effect`
|Indication of allowing or not allowing the policy
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
{
  "oldPolicy": [
    {
      "permission": "catalog-entity",
      "policy": "read",
      "effect": "allow"
    },
    {
      "permission": "catalog.entity.create",
      "policy": "create",
      "effect": "allow"
    }
  ],
  "newPolicy": [
    {
      "permission": "catalog-entity",
      "policy": "read",
      "effect": "deny"
    },
    {
      "permission": "policy-entity",
      "policy": "read",
      "effect": "allow"
    }
  ]
}
----

.Example response
[source]
----
200
----
--

[DELETE] /api/permission/policies/__<kind>__/__<namespace>__/__<name>__?permission={value1}&policy={value2}&effect={value3}::
+
--
Deletes a permission policy added to the specified entity.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`kind`
|Kind of the entity
|String
|Required

|`namespace`
|Namespace of the entity
|String
|Required

|`name`
|Name related to the entity
|String
|Required

|`permission`
|Permission from a specific plugin, resource type, or name
|String
|Required

|`policy`
|Policy action for the permission, such as `create`, `read`, `update`, `delete`, or `use`
|String
|Required

|`effect`
|Indication of allowing or not allowing the policy
|String
|Required
|===

.Example response
[source]
----
204 No Content
----
--

[DELETE] /api/permission/policies/__<kind>__/__<namespace>__/__<name>__::
+
--
Deletes all permission policies added to the specified entity.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`kind`
|Kind of the entity
|String
|Required

|`namespace`
|Namespace of the entity
|String
|Required

|`name`
|Name related to the entity
|String
|Required
|===

.Example request body (JSON)
[source,json]
----
[
  {
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "delete",
    "effect": "allow"
  },
  {
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "update",
    "effect": "allow"
  }
]
----

.Example response
[source]
----
204 No Content
----
--

[GET] /api/permission/plugins/policies::
+
--
Returns permission policies for all static plugins.

.Example response (JSON)
[source,json]
----
[
  {
    "pluginId": "catalog",
    "policies": [
      {
        "isResourced": true,
        "permission": "catalog-entity",
        "policy": "read"
      },
      {
        "isResourced": false,
        "permission": "catalog.entity.create",
        "policy": "create"
      },
      {
        "isResourced": true,
        "permission": "catalog-entity",
        "policy": "delete"
      },
      {
        "isResourced": true,
        "permission": "catalog-entity",
        "policy": "update"
      },
      {
        "isResourced": false,
        "permission": "catalog.location.read",
        "policy": "read"
      },
      {
        "isResourced": false,
        "permission": "catalog.location.create",
        "policy": "create"
      },
      {
        "isResourced": false,
        "permission": "catalog.location.delete",
        "policy": "delete"
      }
    ]
  },
  ...
]

----
--

[id='rbac-rest-api-permission-endpoints_{context}']
[GET] /api/permission/plugins/id::
+
--
Returns object with list plugin IDs:

.Example response (JSON)
[source,json]
----
[
  {
    "ids": ["catalog", "permission"]
  }
]
----
--

[POST] /api/permission/plugins/id::
+
--
Add more plugins IDs defined in the request object.

Request Parameters: object in JSON format.

.Example request body (JSON)
[source,json]
----
[
  {
    "ids": ["scaffolder"]
  }
]
----

Returns a status code of 200 and JSON with actual object stored in the server:

.Example response (JSON)
[source,json]
----
[
  {
    "ids": ["catalog", "permission", "scaffolder"]
  }
]
----
--

[DELETE] /api/permission/plugins/id::
+
--
Delete plugins IDs defined in the request object.

Request Parameters: object in JSON format.

.Example request body (JSON)
[source,json]
----
[
  {
    "ids": ["scaffolder"]
  }
]
----

Returns a status code of 200 and JSON with actual object stored in the server:

.Example response (JSON)
[source,json]
----
[
  {
    "ids": ["catalog", "permission"]
  }
]
----
--

[NOTE]
In order to prevent an inconsistent state after a deployment restart, the REST API does not allow deletion of plugin IDs that were provided by using the application configuration. These ID values can only be removed through the configuration file. 

== Conditional policies

The RBAC REST API supports the following endpoints for managing conditional policies in the {product}.

[GET] /api/permission/plugins/condition-rules::
+
--
Returns available conditional rule parameter schemas for the available plugins that are enabled in {product-short}.

.Example response (JSON)
[source,json]
----
[
   {
      "pluginId": "catalog",
      "rules": [
         {
            "name": "HAS_ANNOTATION",
            "description": "Allow entities with the specified annotation",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "annotation": {
                     "type": "string",
                     "description": "Name of the annotation to match on"
                  },
                  "value": {
                     "type": "string",
                     "description": "Value of the annotation to match on"
                  }
               },
               "required": [
                  "annotation"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         },
         {
            "name": "HAS_LABEL",
            "description": "Allow entities with the specified label",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "label": {
                     "type": "string",
                     "description": "Name of the label to match on"
                  }
               },
               "required": [
                  "label"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         },
         {
            "name": "HAS_METADATA",
            "description": "Allow entities with the specified metadata subfield",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "key": {
                     "type": "string",
                     "description": "Property within the entities metadata to match on"
                  },
                  "value": {
                     "type": "string",
                     "description": "Value of the given property to match on"
                  }
               },
               "required": [
                  "key"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         },
         {
            "name": "HAS_SPEC",
            "description": "Allow entities with the specified spec subfield",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "key": {
                     "type": "string",
                     "description": "Property within the entities spec to match on"
                  },
                  "value": {
                     "type": "string",
                     "description": "Value of the given property to match on"
                  }
               },
               "required": [
                  "key"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         },
         {
            "name": "IS_ENTITY_KIND",
            "description": "Allow entities matching a specified kind",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "kinds": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     },
                     "description": "List of kinds to match at least one of"
                  }
               },
               "required": [
                  "kinds"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         },
         {
            "name": "IS_ENTITY_OWNER",
            "description": "Allow entities owned by a specified claim",
            "resourceType": "catalog-entity",
            "paramsSchema": {
               "type": "object",
               "properties": {
                  "claims": {
                     "type": "array",
                     "items": {
                        "type": "string"
                     },
                     "description": "List of claims to match at least one on within ownedBy"
                  }
               },
               "required": [
                  "claims"
               ],
               "additionalProperties": false,
               "$schema": "http://json-schema.org/draft-07/schema#"
            }
         }
      ]
   }
   ... <another plugin condition parameter schemas>
]
----
--

[GET] /api/permission/roles/conditions/:id::
+
--
Returns conditions for the specified ID.

.Example response (JSON)
[source,json]
----
{
  "id": 1,
  "result": "CONDITIONAL",
  "roleEntityRef": "role:default/test",
  "pluginId": "catalog",
  "resourceType": "catalog-entity",
  "permissionMapping": ["read"],
  "conditions": {
    "anyOf": [
      {
        "rule": "IS_ENTITY_OWNER",
        "resourceType": "catalog-entity",
        "params": {
          "claims": ["group:default/team-a"]
        }
      },
      {
        "rule": "IS_ENTITY_KIND",
        "resourceType": "catalog-entity",
        "params": {
          "kinds": ["Group"]
        }
      }
    ]
  }
}
----
--

[GET] /api/permission/roles/conditions::
+
--
Returns list of all conditions for all roles.

.Example response (JSON)
[source,json]
----
[
  {
    "id": 1,
    "result": "CONDITIONAL",
    "roleEntityRef": "role:default/test",
    "pluginId": "catalog",
    "resourceType": "catalog-entity",
    "permissionMapping": ["read"],
    "conditions": {
      "anyOf": [
        {
          "rule": "IS_ENTITY_OWNER",
          "resourceType": "catalog-entity",
          "params": {
            "claims": ["group:default/team-a"]
          }
        },
        {
          "rule": "IS_ENTITY_KIND",
          "resourceType": "catalog-entity",
          "params": {
            "kinds": ["Group"]
          }
        }
      ]
    }
  }
]
----
--

[POST] /api/permission/roles/conditions::
+
--
Creates a conditional policy for the specified role.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`result`
|Always has the value `CONDITIONAL`
|String
|Required

|`roleEntityRef`
|String entity reference to the RBAC role, such as `role:default/dev`
|String
|Required

|`pluginId`
|Corresponding plugin ID, such as `catalog`
|String
|Required

|`permissionMapping`
|Array permission action, such as `['read', 'update', 'delete']`
|String array
|Required

|`resourceType`
|Resource type provided by the plugin, such as `catalog-entity`
|String
|Required

|`conditions`
|Condition JSON with parameters or array parameters joined by criteria
|JSON
|Required

|`name`
|Name of the role
|String
|Required

|`metadata.description`
|The description of the role
|String
|Optional
|===

.Example request body (JSON)
[source,json]
----
{
  "result": "CONDITIONAL",
  "roleEntityRef": "role:default/test",
  "pluginId": "catalog",
  "resourceType": "catalog-entity",
  "permissionMapping": ["read"],
  "conditions": {
    "rule": "IS_ENTITY_OWNER",
    "resourceType": "catalog-entity",
    "params": {
      "claims": ["group:default/team-a"]
    }
  }
}
----

.Example response (JSON)
[source,json]
----
{
  "id": 1
}
----
--

[PUT] /permission/roles/conditions/:id::
+
--
Updates a condition policy for a specified ID.

.Request parameters
[cols="15%,45%,15%,25%", frame="all", options="header"]
|===
|Name
|Description
|Type
|Presence

|`result`
|Always has the value `CONDITIONAL`
|String
|Required

|`roleEntityRef`
|String entity reference to the RBAC role, such as `role:default/dev`
|String
|Required

|`pluginId`
|Corresponding plugin ID, such as `catalog`
|String
|Required

|`permissionMapping`
|Array permission action, such as `['read', 'update', 'delete']`
|String array
|Required

|`resourceType`
|Resource type provided by the plugin, such as `catalog-entity`
|String
|Required

|`conditions`
|Condition JSON with parameters or array parameters joined by criteria
|JSON
|Required

|`name`
|Name of the role
|String
|Required

|`metadata.description`
|The description of the role
|String
|Optional
|===

.Example request body (JSON)
[source,json]
----
{
  "result": "CONDITIONAL",
  "roleEntityRef": "role:default/test",
  "pluginId": "catalog",
  "resourceType": "catalog-entity",
  "permissionMapping": ["read"],
  "conditions": {
    "anyOf": [
      {
        "rule": "IS_ENTITY_OWNER",
        "resourceType": "catalog-entity",
        "params": {
          "claims": ["group:default/team-a"]
        }
      },
      {
        "rule": "IS_ENTITY_KIND",
        "resourceType": "catalog-entity",
        "params": {
          "kinds": ["Group"]
        }
      }
    ]
  }
}
----

.Example response
[source]
----
200
----
--

[DELETE] /api/permission/roles/conditions/:id::
+
--
Deletes a conditional policy for the specified ID.

.Example response
[source]
----
204
----
--

== User statistics

The `licensed-users-info-backend` plugin exposes various REST API endpoints to retrieve data related to logged-in users.

No additional configuration is required for the `licensed-users-info-backend` plugin. If the RBAC backend plugin is enabled, then an administrator role must be assigned to access the endpoints, as the endpoints are protected by the `policy.entity.read` permission.

The base URL for user statistics endpoints is `pass:c[http://SERVER:PORT/api/licensed-users-info]`, such as `pass:c[http://localhost:7007/api/licensed-users-info]`.

[GET] /users/quantity::
+
--
Returns the total number of logged-in users.

.Example request
[source,bash]
----
curl -X GET "http://localhost:7007/api/licensed-users-info/users/quantity" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $token"
----

.Example response
[source,json]
----
{ "quantity": "2" }
----
--

[GET] /users::
+
--
Returns a list of logged-in users with their details.

.Example request
[source,bash]
----
curl -X GET "http://localhost:7007/api/licensed-users-info/users" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $token"
----

.Example response
[source,json]
----
[
  {
    "userEntityRef": "user:default/dev",
    "lastTimeLogin": "Thu, 22 Aug 2024 16:27:41 GMT",
    "displayName": "John Leavy",
    "email": "dev@redhat.com"
  }
]
----
--

[GET] /users::
+
--
Returns a list of logged-in users in CSV format.

.Example request
[source,bash]
----
curl -X GET "http://localhost:7007/api/licensed-users-info/users" \
-H "Content-Type: text/csv" \
-H "Authorization: Bearer $token"
----

.Example response
[source,csv]
----
userEntityRef,displayName,email,lastTimeLogin
user:default/dev,John Leavy,dev@redhat.com,"Thu, 22 Aug 2024 16:27:41 GMT"
----
--


