:_mod-docs-content-type: PROCEDURE

[id="make-object-storage-accessible-to-containers-by-using-the-helm-chart_{context}"]
= Make object storage accessible to containers by using the Helm chart

[role="_abstract"]
Add `ObjectBucketClaim` access information to the Helm chart configuration to make it accessible to the {product-short} container as environment variables.

Creating an `ObjectBucketClaim` custom resource (CR) automatically generates both the {product-short} `ObjectBucketClaim` config map and secret. The config map and secret contain `ObjectBucket` access information. The Helm chart uses the following environment variables:

include::snip-objectbucketclaim-environment-variables.adoc[]

.Prerequisites

* You have installed {product} on {ocp-short} using the Helm chart.
* You have created an `ObjectBucketClaim` CR for storing files generated by TechDocs. For more information see xref:configure-for-file-storage_{context}[Using {odf-name} for file storage]

.Procedure

* In the Helm chart values, add the {product-short} `ObjectBucketClaim` secret and config map to the `extraEnvFrom` field. For example:
+
[source,yaml]
----
extraEnvFrom:
  - secretRef:
      name: <rhdh_bucket_claim_name>
  - configMapRef:
      name: <rhdh_bucket_claim_name>
----
