// Module included in the following assemblies:
//
// * assemblies/assembly-configuring-templates.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-creating-a-new-software-component-using-templates_{context}"]
= Creating a new software component using Software Templates

You can create a new software component using the standard templates that the platform engineers have created. With this procedure, the scaffolding process runs in your {product} instance.

.Procedure

To create a new software component, complete the following steps:

. In your {product} instance, go to the *Home > Catalog* page, and click *Self-service*.
. On the *Self-service* page, click *Choose* on the *Templates* tile to initiate the scaffolding process for a template.

+
[NOTE]
====
Each template requires you to provide different information.
====

. Follow the wizard instructions as you enter the required details. You can choose parameters from a set of pre-defined options.
. Optional: In the *Deployment Information* step, you have an option to *Create Workbench for OpenShift AI*.
. In the *Review* step, verify the parameters you have entered and click *Create*.
+
[NOTE]
====
* You can click *Cancel* to abort the software component creation during the template running step only if the current step supports the abort. The abort signal is, then, sent to a task and all the next steps are not executed. 
* During the creation of the software component, click *Show Logs* to view the log information.
====

.Verification

* You can click *Cancel* to abort the software component creation during the template running step only if the current step supports the abort. The abort signal is, then, sent to a task and all the next steps are not executed. 
* During the creation of the software component, click  *Show Logs*to view the log information.