// Module included in the following assemblies:
//
// * assemblies/assembly-configuring-templates.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-viewing-the-results-of-software-component-creation_{context}"]
= Viewing the results of the software component creation in your {product} instance

You can verify the results of the software component creation using various methods.

.Procedure

To view and verify the results of the software component that is created, complete the following steps:

* If your software component is not successfully created, you can click on each section in the *Self-service* page to view the log information from the step that failed.

* If your template is successfully created, you can view the component by clicking the following links on the success page:
** *Source Repository*
** *GitOps Repository*
** *Open Component in Catalog*
** *Open GitOps Resource in Catalog*

* To view the software component that you have just created, click *Open Component in catalog*, or in your {product} instance, go to the *Home* page, and click *Catalog*.
To view the Source Code in your version control, click *Source Code Repository*.