:_mod-docs-content-type: PROCEDURE

[id="configure-the-log-level-with-the-rhdh-operator_{context}"]
= Configure the log level with the {product} Operator

[role="_abstract"]
Configure the application log level through the `LOG_LEVEL` environment variable by using the {product} Operator to control the minimum severity level of events that your application logs.

.Prerequisites

* You have access to the {backstage} custom resource (CR) used to deploy the application.

.Procedure

* Include the environment variable `LOG_LEVEL` in your {backstage} CR. For example:
+
[source,yaml]
----
spec:
  # Other fields omitted
  application:
    extraEnvs:
      envs:
        - name: LOG_LEVEL
          value: debug
----
+
You can use any of the values in the following table.
+
[cols="15%,85%", options="header"]
.`LOG_LEVEL` values in order of increasing severity
|===
|Value
|Description

|`debug`
|Detailed information, typically useful only when troubleshooting.

|`info`
|General information about the operation of the application. This is the default level.

|`warn`
|Potential issues or situations that might require attention.

|`error`
|Errors that occurred during the operation but are not critical.

|`critical`
|Unrecoverable errors that must be addressed immediately to restore functionality.
|===
