[id="enabling-ang-giving-access-to-the-bulk-import-feature"]
= Enabling and giving access to the Bulk Import feature

.Procedure
. To give {product-short} access to GitHub, link:{linkgettingstartedguide}#configuring-github-integration[configure GitHub integration].

. The Bulk Import plugins are installed but disabled by default.
To enable the `./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import-backend-dynamic` and `./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import` plugins,
edit your `dynamic-plugins.yaml` with following content.
See link:{plugins-configure-book-url}[{plugins-configure-book-title}].
+
.`dynamic-plugins.yaml` fragment
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import-backend-dynamic
    disabled: false
  - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-bulk-import
    disabled: false
----

. Only {product-short} administrators or users with the `bulk.import` permission can use the Bulk Import feature.
Configure the required `bulk.import` RBAC permission for the users that are not administrators.
See link:{authorization-book-url}#ref-rbac-permission-policies_title-authorization[Permission policies in Red Hat Developer Hub].


.Verification
* The sidebar displays a *Bulk Import* line.
* The *Bulk Import* page shows a list of *Added Repositories*.

.Troubleshooting
* If clicking on the *Bulk Import* option displays the following error message: _To view the added repositories, contact your administrator to give you the `bulk.import` permission_, it means that your user does not have the necessary permission to use the Bulk Import feature.
Refer back to link:{authorization-book-url}#ref-rbac-permission-policies_title-authorization[Permission policies in Red Hat Developer Hub] for more information on how an administrator can add that permission to your user.
