:_mod-docs-content-type: PROCEDURE

[id="importing-multiple-repositories-from-gitlab"]
= Import multiple GitLab repositories

[role="_abstract"]
Select and import multiple GitLab projects to the {product-short} catalog using Technology Preview bulk import capabilities.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

.Prerequisites
* You have {configuring-dynamic-plugins-book-link}#bulk-importing-github-repositories[enabled the Bulk Import feature and given access to it].
* You have set up a link:https://docs.gitlab.com/user/profile/personal_access_tokens/[GitLab personal access token (PAT)].
* You configured the GitLab integration by adding the following section to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml,subs="+quotes,+attributes"]
----
integrations:
  gitlab:
    - host: ${GITLAB_HOST}
      token: ${GITLAB_TOKEN}
----
* You enabled the GitLab catalog provider plugin in your `dynamic-plugins.yaml` file to import GitLab users and groups:
+
[source,yaml]
----
plugins:
  - package: './dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic'
    disabled: false
----

.Procedure
. In the {product-short} left sidebar, click *Bulk Import*.
. If your {product-very-short} instance has multiple source control tools configured, select GitLab as your *Source control tool* option.
. Select the projects to import, and validate.
+
{product-short} creates a merge request in each selected project to add the required `catalog-info.yaml` file.
. For each project to import, click the *PR* link to review and merge the changes in Gitlab.

.Verification
. Click *Bulk Import* in {product-short} left sidebar.
. Verify that each imported GitLab project in the *Selected projects* list has the status _Waiting for approval_ or _Imported_.
. For projects with the _Waiting for approval_ status, click the merge request link to add the `catalog-info.yaml` file to the project repository.


