[id="managing-the-added-repositories]
= Managing the added repositories
You can oversee and manage the repositories that are imported to the {product-short}.

.Prerequisites
* You have xref:importing-multiple-github-repositories[imported GitHub repositories].


.Procedure
. Click *Bulk Import* in the left sidebar to display all the current repositories that are being tracked as Import jobs, along with their status.

Added:: The repository is added to the {product-short} catalog after the import pull request is merged or if the repository already contained a `catalog-info.yaml` file during the bulk import. 
Note that it may take a few minutes for the entities to be available in the catalog.

Waiting for approval:: There is an open pull request adding a `catalog-info.yaml` file to the repository.
You can:
* Click the *pencil icon* on the right to see details about the pull request or edit the pull request content right from {product-short}.
* Delete the Import job, this action closes the import PR as well.
* To transition the Import job to the _Added_ state, merge the import pull request from the Git repository.

Empty:: {product-short} is unable to determine the import job status because the repository is imported from other sources but does not have a `catalog-info.yaml` file and lacks any import pull request adding it.

[NOTE]
====
* After an import pull request is merged, the import status is marked as _Added_ in the list of Added Repositories, but it might take a few seconds for the corresponding entities to appear in the {product-short} Catalog.
* A location added through other sources (like statically in an `app-config.yaml` file, dynamically when link:{linkgettingstartedguide}#enabling-github-discovery-in-red-hat-developer-hub[enabling GitHub discovery], or registered manually using the "Register an existing component" page) might show up in the Bulk Import list of Added Repositories if the following conditions are met:
** The target repository is accessible from the configured GitHub integrations.
** The location URL points to a `catalog-info.yaml` file at the root of the repository default branch.
====
