[id="understanding-bulk-import-audit-logs"]
= Understanding the Bulk Import audit Logs

The Bulk Import backend plugin adds the following events to the {product-short} audit logs.
See link:{linkgettingstartedguide}#assembly-audit-log[Audit Logs in {product}] for more information on how to configure and view audit logs.

*Bulk Import Events*:

`BulkImportUnknownEndpoint`::
Tracks requests to unknown endpoints.

`BulkImportPing`::
Tracks `GET` requests to the `/ping` endpoint, which allows us to make sure the bulk import backend is up and running.

`BulkImportFindAllOrganizations`::
Tracks `GET` requests to the `/organizations` endpoint, which returns the list of organizations accessible from all configured GitHub Integrations.

`BulkImportFindRepositoriesByOrganization`::
Tracks `GET` requests to the `/organizations/:orgName/repositories` endpoint, which returns the list of repositories for the specified organization (accessible from any of the configured GitHub Integrations).

`BulkImportFindAllRepositories`::
Tracks GET requests to the `/repositories` endpoint, which returns the list of repositories accessible from all configured GitHub Integrations.

`BulkImportFindAllImports`::
Tracks `GET` requests to the `/imports` endpoint, which returns the list of existing import jobs along with their statuses.

`BulkImportCreateImportJobs`::
Tracks `POST` requests to the `/imports` endpoint, which allows to submit requests to bulk-import one or many repositories into the {product-short} catalog, by eventually creating import pull requests in the target repositories.

`BulkImportFindImportStatusByRepo`::
Tracks `GET` requests to the `/import/by-repo` endpoint, which fetches details about the import job for the specified repository.

`BulkImportDeleteImportByRepo`::
Tracks `DELETE` requests to the `/import/by-repo` endpoint, which deletes any existing import job for the specified repository, by closing any open import pull request that could have been created.

.Example bulk import audit logs
[source,json]
----
{
  "actor": {
    "actorId": "user:default/myuser",
    "hostname": "localhost",
    "ip": "::1",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
  },
  "eventName": "BulkImportFindAllOrganizations",
  "isAuditLog": true,
  "level": "info",
  "message": "'get /organizations' endpoint hit by user:default/myuser",
  "meta": {},
  "plugin": "bulk-import",
  "request": {
    "body": {},
    "method": "GET",
    "params": {},
    "query": {
      "pagePerIntegration": "1",
      "sizePerIntegration": "5"
    },
    "url": "/api/bulk-import/organizations?pagePerIntegration=1&sizePerIntegration=5"
  },
  "response": {
    "status": 200
  },
  "service": "backstage",
  "stage": "completion",
  "status": "succeeded",
  "timestamp": "2024-08-26 16:41:02"
}
----
