:_mod-docs-content-type: PROCEDURE

[id="integrating-bulk-import-with-orchestrator-workflows"]
= Setting up a custom scaffolder workflow for bulk import

As an administrator, you can create a scaffolder template specifically for the Bulk Import plugin. You can provide the Scaffolder template within the configuration of your application.

You can run the following tasks with this integration:

* Import existing catalog entities
* Create pull requests for cleanup
* Call webhooks for external system integration

You can execute a custom automation workflow of a Scaffolder template on multiple selected repositories using the bulk import plugin.

.Prerequisites

* You created a Scaffolder template specifically designed for the Bulk Import function and provided the Scaffolder template within the configuration of your application. This template is the core definition of your customized import scenario.

.Procedure

* Configure your {my-app-config-file} configuration to instruct the Bulk Import plugin to use your custom templates.

You can direct the Bulk Import plugin to hand off the entire list of selected repositories to a custom Orchestrator workflow.
To configure the Bulk Import workflow:
+
[source,yaml]
----
bulkImport:
  importTemplate: your-template-entity-reference-or-template-name
  importAPI: `open-pull-requests` | `scaffolder`;
----
where:

`importTemplate:`::
Enter your Scaffolder template entity reference.

`importAPI`::
Set the API to 'scaffolder' to trigger the defined workflow for high-fidelity automation. This field defines the import workflow and currently supports two following options:

`open-pull-requests`:: This is the default import workflow, which includes the logic for creating pull requests for every selected repository.

`scaffolder`:: This workflow uses an import scenario defined in the Scaffolder template to create import jobs. Select this option to use the custom import scenario defined in your Scaffolder template.
+
[IMPORTANT]
====
The Scaffolder template must be generic and not specific to a single repository if you want your custom Scaffolder template to run successfully for every repository in the bulk list.
====

For the {product-very-short} instance to use the Scaffolder functionality, you must run it with the following environment variable enabled:

[source,yaml]
----
export NODE_OPTIONS=--no-node-snapshot
----

.Verification

* The Bulk Import plugin executes the custom Scaffolder template for the list of repositories using the `/task-imports` API endpoint (the `createTaskImportJobs` method).