:_mod-docs-content-type: PROCEDURE

[id="importing-multiple-repositories-from-gitlab"]
= Importing multiple GitLab repositories

In {product}, you can select your GitLab projects and automate their onboarding to the {product-short} catalog.
This feature is a Technology Preview.

[IMPORTANT]
====
Technology Preview features provide early access to upcoming product innovations, enabling you to test functionality and provide feedback during the development process.
However, these features are not fully supported under Red Hat Subscription Level Agreements, may not be functionally complete, and are not intended for production use.
As Red Hat considers making future iterations of Technology Preview features generally available, we will attempt to resolve any issues that customers experience when using these features.
See: link:https://access.redhat.com/support/offerings/techpreview/[Technology Preview support scope].
====

.Prerequisites
* You have {configuring-dynamic-plugins-book-link}#bulk-importing-github-repositories[enabled the Bulk Import feature and given access to it].
* You have set up a link:https://docs.gitlab.com/user/profile/personal_access_tokens/[GitLab personal access token (PAT)].

.Procedure
. Click *Bulk Import* in {product-short} left sidebar.
. If your {product-very-short} instance has multiple source control tools configured, select GitLab as your *Source control tool* option.
. Select the projects to import, and validate.
+
{product-short} creates a merge request in each selected project to add the required `catalog-info.yaml` file.
. For each project to import, click on the *PR* link to review and merge the changes in Gitlab.

.Verification
. Click *Bulk Import* in {product-short} left sidebar.
. Verify that each imported GitLab project in the *Selected projects* list has the status _Waiting for approval_ or _Imported_.
. For each _Waiting for approval_ project, there is a link to the corresponding merge request adding the `catalog-info.yaml` file in the corresponding project.


