= Importing multiple repositories

The Bulk Import feature allows you to view all the GitHub repositories and organizations accessible from the configured GitHub Integrations.
From there, you can pick any number of repositories and onboard them.

.Prerequisites
* You enabled the Bulk Import feature.
* Your RHDH user has access to the Bulk Import feature.

.Procedure
. Click on *Bulk Import* in the left sidebar.
. Click on the *Add* button in the top-right corner.
You will see a list of all repositories accessible from the configured GitHub integrations.
. From the *Repositories* view, you can select any repository, or search for any accessible repositories.
For each repository selected, a `catalog-info.yaml` will be generated.
. From the *Organizations* view, you can select any organization by clicking on *Select* in the third column.
This will allow you to pick one or more repositories that are part of the selected organization.
. Click on *Preview file* to view or edit the details of the pull request for each repository.
The pull request details form will be preloaded with some data, and you can also preview the content of the `catalog-info.yaml`.
If the repository already has a `.github/CODEOWNERS` file, you can select the *Use CODEOWNERS file as Entity Owner* checkbox to use it, rather than having the `content-info.yaml` contain a specific entity owner.
. Click on *Save*.
. Click on *Create pull requests*.
At this point, a set of dry-run checks will be run against the selected repositories to make sure they meet the requirements to be imported, that is:
. Checking that there is no entity in the Developer Hub catalog with the name specified in the repository `catalog-info.yaml`
. Checking that the repository is not empty
. Checking that the repository already has a `.github/CODEOWNERS` file if the *Use CODEOWNERS file as Entity Owner* checkbox was selected for that repository.

If there are any errors, the pull requests will not be created, but you will see a "``Failed to create PR``" error message indicating the failures. Clicking on *Edit* will show more details about the reasons.

If there are no errors, the pull requests will be created, and you will be redirected to the list of Added repositories.

. Review and merge each pull request that creates a `catalog-info.yml` file.

.Verification
* The list of Added repositories displays the repositories you just imported, each with an appropriate status: either "Waiting for approval" or "Added"
* For each "Waiting for approval" Import job listed, there is a corresponding PR adding the `catalog-info.yaml` file in the corresponding repository


