= Importing multiple repositories

The Bulk Import feature allows you to view all the GitHub repositories and organizations accessible from the configured GitHub Integrations.
From there, you can pick any number of repositories and onboard them.

.Prerequisites
* You have xref:enabling-ang-giving-access-to-the-bulk-import-feature[enabled the Bulk Import feature and gave access to it].

.Procedure
. Click *Bulk Import* in the left sidebar.
. Click the *Add* button in the top-right corner to see the list of all repositories accessible from the configured GitHub integrations.
.. From the *Repositories* view, you can select any repository, or search for any accessible repositories.
For each repository selected, a `catalog-info.yaml` is generated.
.. From the *Organizations* view, you can select any organization by clicking on *Select* in the third column.
This option allows you to select one or more repositories from the selected organization.
. Click *Preview file* to view or edit the details of the pull request for each repository.
The pull request details form is preloaded with some data, and you can also preview the content of the `catalog-info.yaml`.
If the repository already has a `.github/CODEOWNERS` file, you can select the *Use CODEOWNERS file as Entity Owner* checkbox to use it, rather than having the `content-info.yaml` contain a specific entity owner.
. Click *Save*.
. Click *Create pull requests*.
At this point, a set of dry-run checks runs against the selected repositories to ensure they meet the requirements for import, such as:
.. Verifying that there is no entity in the {product-short} catalog with the name specified in the repository `catalog-info.yaml`
.. Checking that the repository is not empty
.. Verifying that the repository contains a `.github/CODEOWNERS` file if the *Use CODEOWNERS file as Entity Owner* checkbox is selected for that repository.

** If any errors occur, the pull requests are not created, and you will see a _Failed to create PR_ error message detailing the issues.
To view more details about the reasons, click *Edit*.

** If there are no errors, the pull requests are created, and you will be redirected to the list of added repositories.

. Review and merge each pull request that creates a `catalog-info.yml` file.

.Verification
* The *Added repositories* list displays the repositories you just imported, each with an appropriate status: either _Waiting for approval_ or _Added_.
* For each _Waiting for approval_ import job listed, there is a corresponding pull request adding the `catalog-info.yaml` file in the corresponding repository

