:_mod-docs-content-type: PROCEDURE

[id="integrating-bulk-import-with-orchestrator-workflows"]

= Setting up a custom scaffolder workflow for bulk import

As an administrator, you can create a scaffolder template specifically for the Bulk Import plugin. You can provide the scaffolder template within the configuration of your application.

You can perform the following tasks with this integration:

* Import existing catalog entities
* Create pull requests for cleanup
* Call webhooks for external system integration

The bulk import plugin allows you to execute a custom automation workflow of a Scaffolder template on multiple selected repositories.

.Prerequisites

* Create a Scaffolder template specifically designed for the Bulk Import function and provide the scaffolder template within the configuration of your application. This template is the core definition of your customized import scenario.

.Procedure

* Configure the following fields in your {my-app-config-file} configuration to instruct the Bulk Import plugin to use your custom templates:

** `importTemplate`
** `importAPI`
** `open-pull-requests`
** `scaffolder`

you can direct the Bulk Import plugin to hand off the entire list of selected repositories to a custom Orchestrator workflow.
To configure the Bulk Import workflow:
+
[source,yaml]
----
bulkImport:
  importTemplate: your-template-entity-reference-or-template-name
  importAPI: 'scaffolder', 'orchestrator'
----
where:

`importTemplate:`::
Enter your template entity reference or name of your Scaffolder template.

`importAPI`::
Set the API to 'orchestrator' to trigger the defined workflow for high-fidelity automation. This field defines the import workflow and currently supports two following options:

* `open-pull-requests`: This is the default import workflow, which includes the logic for creating pull requests for every selected repository.
* `scaffolder`: This workflow uses an import scenario defined in the scaffolder template. The import steps depend on the template's content, allowing for various scenarios. These can include importing existing catalog entities from a repository, creating pull requests, calling webhooks, and more. This method offers greater flexibility.
- Select this option to use the custom import scenario defined in your Scaffolder template. This method offers **greater flexibility** for complex scenarios, including importing existing catalog entities from a repository, creating pull requests, or calling webhooks.


[IMPORTANT]
====
The Scaffolder template must be generic and not specific to a single repository if you want your custom Scaffolder template to run successfully for every repository in the bulk list.
====

For the {product-very-short} instance to use the scaffolder functionality, you must run it with the following environment variable enabled:
+
[source,yaml]
----
export NODE_OPTIONS=--no-node-snapshot
----

.Verification

The Bulk Import plugin executes the custom Scaffolder template for the list of repositories using the `/task-imports` API endpoint (the `createTaskImportJobs` method).