:_mod-docs-content-type: PROCEDURE

[id="enable-the-rhdh-plugin-assets-cache_{context}"]
= Enable the {product} plugin assets cache

[role="_abstract"]
Use a Redis cache store to improve {product-short} performance and reliability by caching plugin assets.

.Prerequisites
* You have installed {product}.
* You have an active Redis server.
For more information on setting up an external Redis server, see the link:https://redis.io/docs/latest/[`official Redis documentation`].

.Procedure
. Enable the {product-short} cache by defining Redis as the cache store type and entering your Redis server connection URL in your `{my-app-config-file}` file.
+
.`{my-app-config-file}` file fragment
[source,yaml,subs="+quotes"]
----
backend:
  cache:
    store: redis
    connection: redis://user:pass@cache.example.com:6379
----

. Enable the cache for TechDocs by adding the `techdocs.cache.ttl` setting in your `{my-app-config-file}` file.
This setting specifies how long, in milliseconds, a statically built asset should stay in the cache.
+
.`{my-app-config-file}` file fragment
[source,yaml]
----
techdocs:
  cache:
    ttl: 3600000
----
+
[TIP]
====
Optionally, enable the cache for unsupported plugins that support this feature.
See the documentation for each plugin for details.
====
