:_mod-docs-content-type: PROCEDURE

[id="configure-an-external-postgresql-instance-using-the-operator_{context}"]
= Configure an external PostgreSQL instance using the Operator

[role="_abstract"]
Configure an external PostgreSQL instance by using the {product} Operator instead of the default local PostgreSQL instance.

.Prerequisites

* You meet the {about-book-link}#rhdh-sizing_about-rhdh[Sizing requirements for external PostgreSQL deployments].
* You are using a supported version of PostgreSQL. For more information, see the link:https://access.redhat.com/support/policy/updates/developerhub[Product life cycle page].
* You have the following details:
** `db-host`: Denotes your PostgreSQL instance Domain Name System (DNS) or IP address
** `db-port`: Denotes your PostgreSQL instance port number, such as `5432`
** `username`: Denotes the user name to connect to your PostgreSQL instance
** `password`: Denotes the password to connect to your PostgreSQL instance
* You have installed the {product} Operator.
* Optional: You have a CA certificate, Transport Layer Security (TLS) private key, and TLS certificate so that you can secure your database connection by using the TLS protocol. For more information, refer to your PostgreSQL vendor documentation.

[NOTE]
====
By default, {product-short} uses a database for each plugin and automatically creates it if none is found. You might need the `Create Database` privilege in addition to `PSQL Database` privileges for configuring an external PostgreSQL instance.
====


.Procedure

. Optional: Create a certificate secret to configure your PostgreSQL instance with a TLS connection:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ cat <<EOF | oc -n {my-product-namespace} create -f -
apiVersion: v1
kind: Secret
metadata:
 name: {my-product-database-certificates-secrets} # <certificate_secret_name>
type: Opaque
stringData:
 postgres-ca.pem: |-
  -----BEGIN CERTIFICATE-----
  <ca-certificate-key> # CA certificate key
 postgres-key.key: |-
  -----BEGIN CERTIFICATE-----
  <tls-private-key> # Optional: TLS private key
 postgres-crt.pem: |-
  -----BEGIN CERTIFICATE-----
  <tls-certificate-key> # Optional: TLS certificate key
  # ...
EOF
----

. Create a credential secret to connect to the PostgreSQL instance:
+
[source,terminal,subs="+attributes,+quotes"]
----
$ cat <<EOF | oc -n {my-product-namespace} create -f -
apiVersion: v1
kind: Secret
metadata:
 name: {my-product-database-secrets} # <credential_secret_name>
type: Opaque
stringData: # Credential data to connect with your PostgreSQL instance
 POSTGRES_PASSWORD: <password>
 POSTGRES_PORT: "<db-port>"
 POSTGRES_USER: <username>
 POSTGRES_HOST: <db-host>
 PGSSLMODE: <ssl-mode> # Optional: for TLS connection, based on the required SSL mode
 NODE_EXTRA_CA_CERTS: <abs-path-to-pem-file> # Optional: for TLS connection, e.g. /opt/app-root/src/postgres-crt.pem
EOF
----

. Create your `{product-custom-resource-type}` custom resource (CR):
+
[source,terminal,subs="+attributes,+quotes"]
----
cat <<EOF | oc -n {my-product-namespace} create -f -
apiVersion: rhdh.redhat.com/v1alpha5
kind: Backstage
metadata:
  name: <backstage-instance-name>
spec:
  database:
    enableLocalDb: false # Set to false to disable creating local PostgreSQL instances
  application:
    extraFiles:
      mountPath: <path> # e g /opt/app-root/src
      secrets:
        - name: {my-product-database-certificates-secrets} # Certificate secret name (if TLS connection configured)
          key: postgres-crt.pem, postgres-ca.pem, postgres-key.key # key name as in {my-product-database-certificates-secrets} Secret
    extraEnvs:
      secrets:
        - name: {my-product-database-secrets} # Credential secret name
        # ...
----
+
[NOTE]
====
The environment variables listed in the `{product-custom-resource-type}` CR work with the Operator default configuration. If you have changed the Operator default configuration, you must reconfigure the `{product-custom-resource-type}` CR accordingly.
====

. Apply the `{product-custom-resource-type}` CR to the namespace where you have deployed the {product-short} instance.
