:_mod-docs-content-type: PROCEDURE

[id="display-a-complete-list-of-helm-chart-values-with-helm-cli_{context}"]

= Display a complete list of Helm Chart values with Helm CLI

Use Helm CLI to display the complete list of possible Helm Chart values.

.Procedure

. Pull the released {product-very-short} Helm Chart, including all its dependencies:
+
[,console]
----
$ helm pull redhat-developer-hub \
  --repo https://charts.openshift.io \
  --version {product-chart-version} \
  --untar
----
. View default values:
+
.. View default values of the {product-very-short} Chart.
+
[,console]
----
$ helm show values redhat-developer-hub
----
+
.. View default values of the upstream Backstage Chart. The fields can be set under the `upstream` scope when deploying the {product-very-short} Chart.
+
[,console]
----
$ helm show values redhat-developer-hub/charts/backstage
----
+
.. OPTIONAL: View default values of the upstream PostgreSQL Chart, which is a dependency of the upstream Backstage Chart.
+
[IMPORTANT]
====
Using the local PostgreSQL database is **not recommended for production**,
as you should be using your own external database.
However, it allows for visibility into the local database.
====
... The fields can be set under the `upstream.postgresql` scope when deploying the {product-very-short} Chart.
+
[,console]
----
$ helm show values redhat-developer-hub/charts/backstage/charts/postgresql
----


