:_mod-docs-content-type: REFERENCE

[id="helm-chart-test-namespace-values_{context}"]
= Test namespace values

[role="_abstract"]
Use test namespace values to configure parameters that run when tests are initiated to
verify {product-very-short} deployment.

[cols="1m, 1, 1, 1m"]
|===
d|*Test* |*Description* |*Object* |*Default*

|test
|Tests pod parameters.
|object
|{"enabled":true,"image":{"registry":"quay.io","repository":"curl/curl","tag":"latest"},"injectTestNpmrcSecret":false}

|test.enabled
|Enables the test-connection pod used for testing the release using `helm` test.
|bool
|true

|test.image.registry
|Tests connection pod image registry.
|string
|"quay.io"

|test.image.repository
a|Test connection pod image repository.

[NOTE]
====
The image must contain both the `sh` and `curl` binaries.
====
|string
|"curl/curl"

|test.image.tag
a|Tests connection pod image tag.

[NOTE]
====
The image must contain both the `sh` and `curl` binaries.
====
|string
|"latest"

|test.injectTestNpmrcSecret
a|Injects a fake dynamic plugins `npmrc` secret. Only relevant when `test.enabled` field is set to `true`.

[IMPORTANT]
====
This value is only used for testing purposes and should not be used in production.
====
|bool
|false
|===
