:_mod-docs-content-type: REFERENCE

[id="helm-chart-upstream-namespace-values_{context}"]
= Upstream namespace values

Use the upstream namespace values for configurations that are passed to the upstream Backstage Helm chart.

[IMPORTANT]
====
Specific upstream namespace values are also used in the global configuration of {product-very-short}.
Changing these values in the upstream namespace can override the global configuration.
====

[cols="1m, 1, 1, 1m"]
|===
d|*Key* |*Description* |*Type* d|*Default*

|upstream
|Upstream Backstage
https://github.com/backstage/charts/blob/main/charts/backstage/values.yaml[chart configuration].
|object
e|Openshift-compatible settings

|upstream.backstage.extraVolumes[0]
|Ephemeral volume that contains the dynamic plugins installed by the `initContainer` at start.
|object
|{"ephemeral":{"volumeClaimTemplate":{"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"5Gi"}}}}},"name":"dynamic-plugins-root"}

|upstream.backstage.extraVolumes[0].ephemeral.volumeClaimTemplate.spec.resources.requests.storage
|Size of the ephemeral volume that contains the dynamic plugins.
|string
|"5Gi"

|upstream.backstage.initContainers[0].image
a|Image used by the `initContainer` to install dynamic plugins into the `dynamic-plugins-root`
volume mount.
|string
e|value of ‘upstream.backstage.image’
|===

