:_mod-docs-content-type: PROCEDURE

[id="proc-starting-a-chat-in-developer-lightspeed_{context}"]
= Starting a chat with {ls-short} for the first time

You can start a chat with {ls-short} for quick answers on a number of topics depending on your settings. You can manually start a chat with the {ls-short} or use the following sample prompts we have provided to help you get started:

* *Getting Started with Red Hat Developer Hub*
* *Deploy with Tekton*
* *Create an OpenShift Deployment*

.Procedure

. In the {product-very-short} navigation menu, click *Lightspeed*.
. Start a chat using one of the following methods:
** *Manual entry*: Type your query in the *Send a message* field and press *Enter*.
** *Sample prompts*: Click a prompt tile, such as *Deploy with Tekton*, to start a predefined task.
** *File attachment*: Click the *Attach* icon to upload a file (.yaml, .json, or .txt) for analysis.

.Verification
* The chat window updates to display your query and the response from {ls-short}.