:_mod-docs-content-type: PROCEDURE

[id="proc-customizing-the-chat-history-storage_{context}"]
= Customizing the chat history storage in {ls-short}

By default, the {ls-short} service stores chat history using an in-memory database. This means that if you restart the Pod containing the server, the chat history is lost. You can manually configure {ls-short} to store the chat history persistently as a long-term backup with PostgreSQL by any of the following methods:

* {product-very-short} Operator
* {product-very-short} Helm chart

+
[WARNING]
====
If you configure {ls-short} to store chat history using PostgreSQL, prompts and responses are recorded and can be reviewed by your platform administrators. If any of your user's chat history contains any private, sensitive, or confidential information, this might have data privacy and security implications that you need to assess. For users that wish to have their chat data removed, they must request their respective platform administrator to perform this action. {company-name} does not collect (or have access to) any of this chat history data.
====

.Procedure
Customize the chat history storage using any of the following methods:

* Update your {product-very-short} config file.
** If you are using {ls-short} on an Operator-installed {product-very-short} instance, update `conversation_cache` in your {product-very-short} ConfigMap.
** If you are using {ls-short} on a Helm-installed {product-very-short} instance, update `conversation_cache` in your `values.yaml` file.
+ 
[source,yaml]
----
 conversation_cache:
    type: postgres
    postgres:
      host: _<your_database_host>_
      port: _<your_database_port>_
      db: _<your_database_name>_
   	  user: _<your_user_name>_
	    password: _<postgres_password>_
	    ca_cert_path: postgres_cert.crt
      ssl_mode: "require"
----

* Update `conversation_cache` in your {lcs-short} config file:
+
[source,yaml]
----
 conversation_cache:
   type: "sqlite"
   sqlite:
     db_path: "/tmp/cache.db"
----
