:_mod-docs-content-type: PROCEDURE
[id="proc-gathering-feedback_{context}"]
= Gathering feedback in {ls-short}

Feedback collection is an optional feature configured on the {rcs-short}. This feature gathers user feedback by providing thumbs-up/down ratings and text comments directly from the chat window. {rcs-short} gathers the feedback, along with the user's query and the response of the model, and stores it as a JSON file within the Pods local file system for later collection and analysis by the platform administrator. This can be useful for assessing model performance and improving your users' experience. The collected feedback is stored in the cluster where {product-very-short} and {rcs-short} are deployed, and as such, is only accessible by the platform administrators for that cluster. For users that intend to have their data removed, they must request their respective platform administrator to perform that action as {company-name} does not collect (or have access to) any of this data.

.Procedure

* To enable or disable feedback, in your {rcs-short} configuration file, add the following settings:
+
[source,yaml]
----
llm_providers:
   .......
ols_config:
   ......
  user_data_collection:
    feedback_disabled: <true/false>
    feedback_storage: "/app-root/tmp/data/feedback"
----
