:_mod-docs-content-type: PROCEDURE

[id="fix-404-error-after-cached-dynamic-plugins-configuration-change_{context}"]
= Fix 404 error after cached dynamic plugins configuration change

[role="_abstract"]
When many {product-short} replicas share a single dynamic plugins cache PVC, updating configurations with the Operator can trigger temporary 404 errors. This occurs because the replicas might access inconsistent cache states during the update process, before all replicas have synchronized.

The solution is to use an individual cache per pod.

.Prerequisites
* Your API version is `v1alpha5` or later.

.Procedure

. In the `{product-custom-resource-type}` Custom Resource (CR) file, set `spec.deployment` to use the optional `StatefulSet` as a resource kind. For example:
+
[source,terminal,subs="+attributes,+quotes"]
----
apiVersion: rhdh.redhat.com/v1alpha5
kind: {product-custom-resource-type}
metadata:
  name: _<CR_name>_
...
spec:
 deployment:
  kind: StatefulSet
  patch:
   spec:
     replicas: 2
     template:
       spec:
         volumes:
           - $patch: replace
             name: dynamic-plugins-root
             persistentVolumeClaim:
               claimName: dynamic-plugins-root
     volumeClaimTemplates:
       - apiVersion: v1
         kind: PersistentVolumeClaim
         metadata:
           name: dynamic-plugins-root
         spec:
           accessModes:
             - ReadWriteOnce
           resources:
             requests:
               storage: 1Gi
----
+
[NOTE]
====
Using `StatefulSet` with a single replica can lead to downtime, while the application deletes the old pod and creates a new pod.
====
+
. Wait a few minutes until the Operator reconciles the CR and the `StatefulSet` resource is ready.

. If you are updating an existing CR, remove the earlier `Deployment` resource from the cluster:
+
[source,terminal,subs="+attributes,+quotes"]
----
oc delete deployment -l app.kubernetes.io/instance=_<CR_name>_
----
+
[NOTE]
====
The same requirement applies for changing the resource kind from `StatefulSet` to `Deployment`. You must manually delete the resource created before from the cluster, because the Operator does not automatically remove the legacy resource.
====

