:_mod-docs-content-type: PROCEDURE

[id="configure-proxy-information-in-operator-deployment_{context}"]
= Configure proxy information in Operator deployment

[role="_abstract"]
Configure proxy settings for Operator-based deployments by setting environment variables in the ConfigMap or custom resource file.

* As a cluster administrator with access to the Operator namespace, you can configure the proxy variables in the Operator's default ConfigMap file. This configuration applies the proxy settings to all the users of the Operator.
* As a developer, you can configure the proxy variables in a custom resource (CR) file. This configuration applies the proxy settings to the {product-very-short} application created from that CR.

.Prerequisites

* You have installed the {product} application.

.Procedure

. Perform one of the following steps based on your role:

. As an administrator, set the proxy information in the Operator's default ConfigMap file:
+
.. Search for a ConfigMap file named `backstage-default-config` in the default namespace `rhdh-operator` and open it.
.. Find the `deployment.yaml` key.
.. Set the value of the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables in the `Deployment` spec as shown in the following example:
+
[source,yaml]
----
# ...
  deployment.yaml: |-
    apiVersion: apps/v1
    kind: Deployment
    spec:
      template:
        spec:
          # ...
          initContainers:
            - name: install-dynamic-plugins
              # ...
              env:
                - name: NPM_CONFIG_USERCONFIG
                  value: /opt/app-root/src/.npmrc.dynamic-plugins
                - name: HTTP_PROXY
                  value: 'http://10.10.10.105:3128'
                - name: HTTPS_PROXY
                  value: 'http://10.10.10.106:3128'
                - name: NO_PROXY
                  value: 'localhost,example.org'
              # ...
          containers:
            - name: backstage-backend
              # ...
              env:
                - name: APP_CONFIG_backend_listen_port
                  value: "7007"
                - name: HTTP_PROXY
                  value: 'http://10.10.10.105:3128'
                - name: HTTPS_PROXY
                  value: 'http://10.10.10.106:3128'
                - name: NO_PROXY
                  value: 'localhost,example.org'
----


. As a developer, set the proxy information in your `{product-custom-resource-type}` CR file as shown in the following example:
+
[source,yaml]
----
spec:
  # ...
  application:
    extraEnvs:
      envs:
        - name: HTTP_PROXY
          value: 'http://10.10.10.105:3128'
        - name: HTTPS_PROXY
          value: 'http://10.10.10.106:3128'
        - name: NO_PROXY
          value: 'localhost,example.org'
----

. Save the configuration changes.
