:_mod-docs-content-type: PROCEDURE

[id="create-a-pvc-for-the-dynamic-plugin-cache-using-the-helm-chart_{context}"]
= Create a PVC for the dynamic plugin cache using the Helm Chart

[role="_abstract"]
Create a persistent volume claim for the dynamic plugin cache in Helm deployments to persist the cache across pod restarts.

.Prerequisites
* You have installed {product} using the Helm chart.
* You have installed the {openshift-cli}.

.Procedure
. Create the persistent volume definition.
For example:
+
[source,yaml]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dynamic-plugins-root
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
----
+
[NOTE]
====
This example uses `ReadWriteOnce` as the access mode which prevents many replicas from sharing the PVC across different nodes.
To run many replicas on different nodes, depending on your storage driver, you must use an access mode such as `ReadWriteMany`.
====

. To apply this PVC to your cluster, run the following command:
+
[source,terminal]
----
$ oc apply -f pvc.yaml
----
. Configure the Helm chart to use the PVC.
For example:
+
[source,yaml]
----
upstream:
  backstage:
    extraVolumes:
      - name: dynamic-plugins-root
        persistentVolumeClaim:
          claimName: dynamic-plugins-root
      - name: dynamic-plugins
        configMap:
          defaultMode: 420
          name: '{{ printf "%s-dynamic-plugins" .Release.Name }}'
          optional: true
      - name: dynamic-plugins-npmrc
        secret:
          defaultMode: 420
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-npmrc" .Release.Name }}'
      - name: dynamic-plugins-registry-auth
        secret:
          defaultMode: 416
          optional: true
          secretName: '{{ printf "%s-dynamic-plugins-registry-auth" .Release.Name }}'
      - name: npmcacache
        emptyDir: {}
      - name: temp
        emptyDir: {}
----
+
[NOTE]
====
When you configure the Helm chart to use the PVC, you must also include the `extraVolumes` section defined in the {default-helm-chart-values-link}[default Helm chart values].
====
