:_mod-docs-content-type: PROCEDURE

[id="configure-an-rhdh-instance-with-a-tls-connection-in-kubernetes_{context}"]
= Configure an {product-very-short} instance with a TLS connection in Kubernetes

[role="_abstract"]
Configure {product-very-short} with a TLS connection in Kubernetes to ensure secure connections with third-party applications and external databases.

include::{docdir}/artifacts/snip-technology-preview.adoc[]

.Prerequisites

* You have set up an {azure-short} Red Hat OpenShift (ARO) cluster with a public CA-signed certificate. For more information about obtaining CA certificates, refer to your vendor documentation.
* You have created a namespace and setup a service account with proper read permissions on resources.
+
For example, you can use the following Kubernetes manifest for role-based access control:
+
[source,yaml]
----
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - resourcequotas
      - daemonsets
    verbs:
      - get
      - list
      - watch
#...
----

* You have obtained the secret and the service CA certificate associated with your service account.
* You have created some resources and added annotations to them so the Kubernetes plugin can discover them. You can apply these Kubernetes annotations:

** `backstage.io/kubernetes-id` to label components
** `backstage.io/kubernetes-namespace` to label namespaces


.Procedure

. Enable the Kubernetes plugins in the `dynamic-plugins-rhdh.yaml` file by setting `disabled` to `false`:
+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-kubernetes
        disabled: false
        # ...
----
+
[NOTE]
====
The `backstage-plugin-kubernetes` plugin is currently in link:https://access.redhat.com/support/offerings/techpreview[{technology-preview}]. As an alternative, you can use the `./dynamic-plugins/dist/backstage-plugin-topology-dynamic` plugin, which is Generally Available (GA).
====

. Set the Kubernetes cluster details and configure the catalog sync options in the {configuring-book-link}[`{my-app-config-file}` configuration file]:
+
[source,yaml,subs="+attributes"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: {my-app-config-config-map}
data:
  "{my-app-config-file}": |
  # ...
  catalog:
    rules:
      - allow: [Component, System, API, Resource, Location]
    providers:
      kubernetes:
        openshift:
          cluster: openshift
          processor:
            namespaceOverride: default
            defaultOwner: guests
          schedule:
            frequency:
              seconds: 30
            timeout:
              seconds: 5
  kubernetes:
    serviceLocatorMethod:
      type: 'multiTenant'
    clusterLocatorMethods:
      - type: 'config'
        clusters:
          - url: <target_cluster_api_server_url>
            name: openshift
            authProvider: 'serviceAccount'
            skipTLSVerify: false
            skipMetricsLookup: true
            dashboardUrl: <target_cluster_console_url>
            dashboardApp: openshift
            serviceAccountToken: ${K8S_SERVICE_ACCOUNT_TOKEN}
            caData: ${K8S_CONFIG_CA_DATA}
            # ...
----
+
`url`:: The base URL to the Kubernetes control plane. You can run the `kubectl cluster-info` command to get the base URL.
`skipTLSVerify`:: Set the value of this parameter to `false` to enable the verification of the TLS certificate.
`dashboardUrl`:: (Optional) The link to the Kubernetes dashboard managing the ARO cluster.
`serviceAccountToken`:: (Optional) Pass the service account token by using a `K8S_SERVICE_ACCOUNT_TOKEN` environment variable that you define in your `_<my_product_secrets>_` secret.
`caData`:: Pass the CA data by using a `K8S_CONFIG_CA_DATA` environment variable that you define in your `_<my_product_secrets>_` secret.

. Save the configuration changes.

.Verification

. Run the {product-very-short} application to import your catalog:
+
[source,terminal]
----
$ kubectl -n rhdh-operator get pods -w
----

. Verify that the pod log shows no errors for your configuration.
. Go to *Catalog* and check the component page in the {product-short} instance to verify the cluster connection and the presence of your created resources.

[NOTE]
====
If you meet connection errors, such as certificate issues or permissions, check the message box in the component page or view the logs of the pod.
====

