:_mod-docs-content-type: PROCEDURE
:platform-long: {eks-brand-name} ({eks-short})
:platform: {eks-short}
:platform-id: eks
:installing-the-operator-by-using-olm-xref: xref:proc-installing-the-operator-on-{platform-id}-by-using-olm_{context}

include::snip-exposing-your-operator-based-rhdh-instance-common-prerequisites.adoc[]
* You have an {eks-short} cluster with {aws-short} Application Load Balancer (ALB) add-on installed.
For more information, see https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[Application load balancing on {eks-brand-name}] and https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html[Installing the AWS Load Balancer Controller add-on].
* You have configured a domain name for your {product-short} instance.
The domain name can be a hosted zone entry on Route 53 or managed outside of AWS.
For more information, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html[Configuring Amazon Route 53 as your DNS service] documentation.
* You have an entry in the {aws-short} Certificate Manager (ACM) for your preferred domain name.
Make sure to keep a record of your Certificate ARN.
* You have set the context to the {eks-short} cluster in your current `kubeconfig`.
For more information, see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html[Creating or updating a kubeconfig file for an Amazon {eks-short} cluster].

.Procedure
. Create an Ingress manifest file, named `rhdh-ingress.yaml`, specifying your {product-short} service name as follows:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-rhdh-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # TODO: Using an ALB HTTPS Listener requires a certificate for your own domain. Fill in the ARN of your certificate, e.g.:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-xxx:xxxx:certificate/xxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    external-dns.alpha.kubernetes.io/hostname: {my-product-domain}
spec:
  ingressClassName: alb
  rules:
    - host: {my-product-domain}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {my-product-cr-name}
              port:
                name: http-backend
EOF
----
+
Replace pass:c,a,q[{my-product-domain}] with your {product-short} domain name and update the value of `alb.ingress.kubernetes.io/certificate-arn` with your certificate ARN.

. To deploy the created Ingress, run:
+
[source,terminal,subs="+attributes"]
----
$ kubectl -n {my-product-namespace} apply -f rhdh-ingress.yaml
----

.Verification
* Wait until the DNS name is responsive, indicating that your {product-short} instance is ready for use.
