:_mod-docs-content-type: PROCEDURE
[id="proc-install-rhdh-operator-airgapped-full.adoc_{context}"]
= Installing {product} in a fully disconnected environment with the Operator

In environments without internet access — whether for security, compliance, or operational reasons — a fully disconnected installation ensures that {product} can run reliably without external dependencies.

If your network has access to the registry through a bastion host, you can use the helper script to install {product} by mirroring the Operator-related images to disk and transferring them to your air-gapped environment without any connection to the internet.

.Prerequisites

* You have installed Podman 5.3 or later. For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].
* You have installed Skopeo 1.17 or later.
* You have installed `yq` 4.44 or later.
* You have installed the GNU `sed` command line text editor.
* You have installed `umoci` CLI tool.
* You have an active `oc registry`, `podman`, or `skopeo` session to the `registry.redhat.io` {company-name} Ecosystem Catalog. For more information, see link:link:https://access.redhat.com/articles/RegistryAuthentication[{company-name} Container Registry Authentication].
* You have installed the `opm` CLI tool. For more information, see {ocp-docs-link}/html/cli_tools/opm-cli#olm-about-opm_cli-opm-install[Installing the opm CLI].
* (Recommended) You have installed the {ocp-docs-link}/html-single/disconnected_environments/index#installation-oc-mirror-installing-plugin_about-installing-oc-mirror-v2[`oc-mirror`] tool, with a version corresponding to the version of your {ocp-short} cluster.
* Make sure that your system meets the minimum sizing requirements. See {about-book-link}#rhdh-sizing_about-rhdh[Sizing requirements for {product}].

.Procedure
. Download the mirroring script to disk by running the following command:
+
[source,terminal,subs="+attributes,+quotes"]
----
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/prepare-restricted-environment.sh
----
+
. Run the mirroring script by using the `bash` command with the appropriate set of options:
+
[source,terminal,subs="+attributes,+quotes"]
----
bash prepare-restricted-environment.sh
 --filter-versions "{product-version}"
 --to-dir _<my_pulled_image_location>_
 [--use-oc-mirror true]
----

`--to-dir _<my_pulled_image_location>_`:: Enter the absolute path to a directory where you want to pull all of the necessary images, for example, `/home/user/rhdh-operator-mirror-dir`.
`--use-oc-mirror true`:: (Recommended) Use the `oc-mirror` {ocp-short} CLI plugin to mirror images.
+
[NOTE]
====
The script can take several minutes to complete as it copies multiple images to the mirror registry.
====
+
. Transfer the directory specified by the `--to-dir` option to your disconnected environment.
. From a machine in your disconnected environment that has access to both the cluster and the target mirror registry, run the mirroring script by using the `bash` command with the appropriate set of options:
+
[source,terminal,subs="+quotes,+attributes"]
----
bash _<my_pulled_image_location>_/install.sh
    --from-dir _<my_pulled_image_location>_
    [--to-registry _<my.registry.example.com>_]
    [--use-oc-mirror true]
----
`_<my_pulled_image_location>_/install.sh`:: The downloaded installation script and the absolute path to the directory where it is stored on your system.
`--from-dir _<my_pulled_image_location>_`:: Enter the directory where you want to pull all of the necessary images.
`--to-registry`:: (Optional) Specifies the URL for the target mirror registry where you want to mirror the images.
`--use-oc-mirror true`:: (Recommended) Uses the `oc-mirror` {ocp-short} CLI plugin to mirror images.
+
[IMPORTANT]
====
If you used `oc-mirror` to mirror the images to disk, you must also use `oc-mirror` to mirror the images from disk due to the folder layout that `oc-mirror` uses.
====
+
[NOTE]
====
The script can take several minutes to complete as it automatically installs the {product} Operator.
====

.Verification
* If you are using {ocp-brand-name}, the {product} Operator is in the *Installed Operators* list in the web console.
* If you are using a supported Kubernetes platform, you can check the list of pods running in the `rhdh-operator` namespace by running the following command in your terminal:
+
[source,terminal,subs="+quotes,+attributes"]
----
kubectl -n rhdh-operator get pods
----

.Next steps
* Use the Operator to create a {product} instance on a supported platform. For more information, see the following documentation for the platform that you want to use:
** {installing-on-ocp-book-link}#assembly-install-rhdh-ocp-operator[Installing {product} on {ocp-short} with the Operator]
** {installing-on-eks-book-link}#assembly-install-rhdh-eks-operator[Installing {product-short} on {eks-short} with the Operator]
** {installing-on-aks-book-link}#proc-rhdh-deploy-aks-operator_title-install-rhdh-aks[Installing {product-short} on {aks-short} with the Operator]
** {installing-on-osd-on-gcp-book-link}#proc-install-rhdh-osd-gcp-operator_title-install-rhdh-osd-gcp[Installing {product-short} on {gcp-short} with the Operator]
** {installing-on-gke-book-link}#proc-deploy-rhdh-instance-gke.adoc_title-install-rhdh-gke[Deploying {product-short} on {gke-short} with the Operator]
