[id='proc-enable-signin_{context}']
= Enabling authentication in {product}

Authentication within the {product} facilitates user sign-in, identification, and access to external resources. It supports multiple authentication providers, though one is typically configured for sign-in while the others are used for external resources.

The {product} supports the following authentication providers:

.Supported authentication providers
[cols="50%,50%", frame="all", options="header"]
|===
|Authentication provider
|Value

|Auth0
|`auth0`

|Atlassian
|`atlassian`

|Azure
|`microsoft`

|Azure Easy Auth
|`azure-easyauth`

|Bitbucket
|`bitbucket`

|Bitbucket Server
|`bitbucketServer`

|Cloudflare Access
|`cfaccess`

|GitHub
|`github`

|GitLab
|`gitlab`

|Google
|`google`

|Google IAP
|`gcp-iap`

|OIDC
|`oidc`

|Okta
|`okta`

|OAuth2 Custom Proxy
|`oauth2Proxy`

|OneLogin
|`onelogin`

|SAML
|`saml`
|===

.Prerequisites

* You have installed the {product-short}.
//For more information about installation, see xref:proc-install-rhdh_{context}[].
//replace with link to the installation guide.

.Procedure

. Add the configuration for the desired authentication provider under the `auth` section of the `app-config.yaml` file, such as:
+
--
[source,yaml]
----
auth:
 environment: development
 providers:
   github:
     development:
       clientId: ${AUTH_GITHUB_CLIENT_ID}
       clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
----
--

. Set the authentication provider key as the value to `signInPage` parameter in your `app-config.yaml` file, such as:
+
`signInPage: oidc`

. Start your {product-short} application and sign in.