// Module included in the following assemblies
// assembly-install-rhdh-ocp-operator.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-install-operator_{context}"]
= Installing the {product} Operator

As an administrator, you can install the {product} Operator. Authorized users can use the Operator to install {product} on the following platforms:

* {ocp-brand-name} ({ocp-very-short})
* {eks-brand-name} ({eks-short})
* {aks-brand-name} ({aks-short})

{ocp-very-short} is currently supported from version {ocp-version-min} to {ocp-version}. See also the link:https://access.redhat.com/support/policy/updates/developerhub[Red Hat Developer Hub Life Cycle].

Containers are available for the following CPU architectures:

* AMD64 and Intel 64 (x86_64)

.Prerequisites

* You are logged in as an administrator on the {ocp-short} web console.
* You have configured the appropriate roles and permissions within your project to create or access an application. For more information, see the link:https://docs.openshift.com/container-platform/{ocp-version}/applications/index.html[Red Hat OpenShift documentation on Building applications].

[IMPORTANT]
====
For enhanced security, better control over the Operator lifecycle, and preventing potential privilege escalation, install the {product} Operator in a dedicated default `rhdh-operator` namespace. You can restrict other users' access to the Operator resources through role bindings or cluster role bindings.

You can also install the Operator in another namespace by creating the necessary resources, such as an Operator group. For more information, see link:https://docs.openshift.com/container-platform/latest/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-global-namespaces_olm-adding-operators-to-a-cluster[Installing global Operators in custom namespaces].

However, if the {product} Operator shares a namespace with other Operators, then it shares the same update policy as well, preventing the customization of the update policy. For example, if one Operator is set to manual updates, the {product} Operator update policy is also set to manual. For more information, see link:https://docs.openshift.com/container-platform/latest/operators/understanding/olm/olm-colocation.html#olm-colocation-namespaces_olm-colocation[Colocation of Operators in a namespace].

====

.Procedure

. In the *Administrator* perspective of the {ocp-short} web console, navigate to *Operators > OperatorHub*.
. In the *Filter by keyword* box, enter {product-short} and click the *{product}* Operator card.
. On the *{product} Operator* page, click *Install*.

. On the *Install Operator* page, use the *Update channel* drop-down menu to select the update channel that you want to use:
** The *fast* channel provides y-stream (x.y) and z-stream (x.y.z) updates, for example, updating from version 1.1 to 1.2, or from 1.1.0 to 1.1.1.
+
[IMPORTANT]
====
The `fast` channel includes all of the updates available for a particular version. Any update might introduce unexpected changes in your {product} deployment. Check the release notes for details about any potentially breaking changes.
====

** The *fast-1.1* channel only provides z-stream updates, for example, updating from version 1.1.1 to 1.1.2. If you want to update the {product} y-version in the future, for example, updating from 1.1 to 1.2, you must switch to the *fast* channel manually.

. On the *Install Operator* page, choose the *Update approval* strategy for the Operator:
** If you choose the *Automatic* option, the Operator is updated without requiring manual confirmation.
** If you choose the *Manual* option, a notification opens when a new update is released in the update channel. The update must be manually approved by an administrator before installation can begin.

. Click *Install*.

.Verification

* To view the installed {product} Operator, click *View Operator*.

[role="_additional-resources"]
.Additional resources

* xref:proc-install-rhdh-ocp-operator_{context}[Deploying {product} on {ocp-short} with the Operator]
* link:https://docs.openshift.com/container-platform/{ocp-version}/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster[Installing from OperatorHub using the web console]
