[id="proc-install-rhdh-helm-airgapped-full.adoc_{context}"]
= Installing {product} on {ocp-short} in a fully disconnected environment with the Helm chart

If your network has access to the registry through a bastion host, you can use the Helm chart to install {product} by mirroring specified resources to disk and transferring them to your air-gapped environment without any connection to the internet.

.Prerequisites

* You have set up your workstation.
** You have an account in https://developers.redhat.com/[{rhdeveloper-name}] portal.
** You have access to the charts.openshift.io Helm chart repository.
** You have installed the {openshift-cli} on your workstation.
** You have installed the `oc-mirror` OpenShift CLI (oc) plugin *v2*. For more information, see {ocp-docs-link}/html-single/disconnected_environments/index#installation-oc-mirror-installing-plugin_about-installing-oc-mirror-v2[Installing the oc-mirror OpenShift CLI plugin].
* You have set up your intermediary host.
** Your host has access to the link:https://registry.redhat.io[{company-name} Ecosystem Catalog].
** Your host has access to image registry on the destination host.
See {ocp-docs-link}/html-single/registry/index#securing-exposing-registry[Exposing the registry].
* You have set up your destination host.
** You have installed {ocp-brand-name} {ocp-version-min} or later.
** Your system meets the minimum sizing requirements. See {about-book-link}#rhdh-sizing_about-rhdh[Sizing requirements for {product}].

.Procedure
. Create an `ImageSetConfiguration` file to specify the resources that you want to mirror. For example:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: mirror.openshift.io/v2alpha1
kind: ImageSetConfiguration
mirror:
  helm:
    repositories:
      - name: openshift-charts
        url: https://charts.openshift.io
        charts:
          - name: redhat-developer-hub
            version: "{product-version}"
----
where:
`version: "{product-version}"`:: Enter the {product} version to mirror.

. Mirror the resources specified in the `ImageSetConfiguration.yaml` file by running the `oc-mirror` command. For example:
+
[source,terminal,subs="+quotes"]
----
oc mirror --v2 -c <mirror_config_directory>/ImageSetConfiguration.yaml file://<mirror_archive_directory>/
----
+
--
where:

`<mirror_config_directory>` :: Enter the location of your image set configuration file on your system, for example, `.user`.

`<mirror_archive_directory>` :: Enter the location of your directory where the mirror archive will be created, for example, `pass:[file://.user]`.
--
+
[NOTE]
====
Running the `oc-mirror` command generates a local workspace containing the mirror archive file, the Helm chart, `ImageDigestMirrorSet` (IDMS) and `ImageTagMirrorSet` (ITMS) manifests. The IDMS and ITMS manifests contain files that you must apply against the cluster in a later step.
====
+
Example output:
+
[source,terminal,subs="+quotes"]
----
Creating archive /path/to/mirror-archive/mirror_seq1_000000.tar
----
+
. Transfer the generated archive file (for example, `mirror_seq1_000000.tar`) to the air-gapped environment.
. Connect to your air-gapped environment and make sure that you are also connected to the following objects:
+
* The local target registry
* The target {ocp-short} cluster
+
. From your air-gapped environment, mirror the resources from the archive to the target registry by running the `oc-mirror` command. For example:
+
[source,terminal,subs="+quotes"]
----
oc mirror --v2 -c <image-set-config> --from file://<mirror-archive-directory> docker://<target-registry>
----
+
--
where:

`<mirror_archive_file>` :: Enter the name of the file containing the resources that you want to mirror, for example,`mirror_seq1_0000.tar`.

`<target_registry>` :: Enter the name of the target registry that you want to push the mirrored images to, for example, `docker://registry.localhost:5000`.
--
+
. In your workspace, locate the IDMS and ITMS files by running the following command. For example:
+
[source,terminal,subs="+quotes"]
----
ls _<workspace_directory>/working-dir/cluster-resources/_
----
+
--
where:

`<workspace_directory>` :: Specifies the name of your workspace directory, for example, `oc-mirror-workspace`.

`<results_directory>` :: Specifies the name of your results directory, for example, `results-1738070846`.
--
+
. To mirror the Helm chart, deploy the `IDMS` and `ITMS` files in the disconnected cluster by running the `oc apply` command. For example:
+
[source,terminal,subs="+quotes"]
----
oc apply -f <workspace_directory>/working-dir/cluster-resources
----
+
--
where:

`<workspace-directory>` :: Enter the name of your workspace directory, for example, `oc-mirror-workspace`.

`<results-directory>` :: Enter the name of your results directory, for example, `results-1738070846`.
--
. In your air-gapped environment, deploy the Helm chart to the namespace that you want to use by running the `helm install` command with `namespace` and `set` options. For example:
+
[source,terminal,subs="+quotes"]
----
CLUSTER_ROUTER_BASE=$(oc get route console -n openshift-console -o=jsonpath='{.spec.host}' | sed 's/^[^.]*\.//') helm install <rhdh_instance> <workspace_directory>/working-dir/helm/charts/<archive_file> --namespace <your_namespace> --create-namespace \ --set global.clusterRouterBase="$CLUSTER_ROUTER_BASE"
----
+
--
where:

`<rhdh_instance>` :: Enter the name of your {product} instance, for example, `{my-product-namespace}`.

`<workspace_directory>` :: Enter the name of your workspace directory, for example, `oc-mirror-workspace`.

`<results_directory>` :: Enter the name of your results directory, for example, `results-1738070846`.

`<archive_file>` :: Enter the name of the archive file containing the resources that you want to mirror, for example, `redhat-developer-hub-1.4.1.tgz`.

`<your_namespace>` :: Enter the namespace that you want to deploy the Helm chart to, for example, `{my-product-namespace}`.
--
