[id='proc-install-rhdh_{context}']
= Installing {product}

Administrative users can configure roles, permissions, and other settings to enable other authorized users to install {product} on multiple platforms. You can install {product-short} with a Helm chart or with the {product} Operator. 

For more information about installing {product-short}, see the link:https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html/administration_guide_for_red_hat_developer_hub/index[{product} Administration guide].


[NOTE]
====
You can configure external PostgreSQL databases in {product}. You can also use a PostgreSQL certificate file to configure an external PostgreSQL instance using the Operator or Helm Chart. For more information, see the following sections:

* link:{LinkAdminGuide}#proc-configuring-postgresql-instance-using-operator_admin-rhdh[Configuring an external PostgreSQL instance using the Operator] 
* link:{LinkAdminGuide}#proc-configuring-postgresql-instance-using-helm_admin-rhdh[Configuring an external PostgreSQL instance using the Helm Chart]
====