:_mod-docs-content-type: PROCEDURE
:platform-long: {gke-brand-name} ({gke-short})
:platform: {gke-short}
:platform-id: gke
:installing-the-operator-by-using-olm-xref: xref:proc-installing-the-operator-on-{platform-id}-by-using-olm_{context}
include::snip-running-rhdh-by-using-the-operator-common-prerequisites.adoc[]
* You have configured a domain name for your {product-short} instance.
* You have reserved a static external Premium IPv4 Global IP address that is not attached to any virtual machine (VM).
For more information see link:https://cloud.google.com/vpc/docs/reserve-static-external-ip-address#reserve_new_static[Reserve a new static external IP address]
* You have configured the DNS records for your domain name to point to the IP address that has been reserved.
+
[NOTE]
====
You need to create an `A` record with the value equal to the IP address.
This process can take up to one hour to propagate.
====

.Procedure
. Set up a Google-managed certificate by creating a `ManagedCertificate` object which you must attach to the Ingress as shown in the following example:
+
--
[source,yaml,subs="attributes+"]
----
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: <rhdh_certificate_name>
spec:
  domains:
    - {my-product-domain}
----
--
+
For more information about setting up a Google-managed certificate, see https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs?hl=en#setting_up_a_google-managed_certificate[Setting up a Google-managed certificate].

. Create a `FrontendConfig` object to set a policy for redirecting to HTTPS.
You must attach this policy to the Ingress.
+
--
.Example of a `FrontendConfig` object
[source,yaml,subs="attributes+"]
----
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: <ingress_security_config>
spec:
  sslPolicy: gke-ingress-ssl-policy-https
  redirectToHttps:
    enabled: true
----
--
+
For more information about setting a policy to redirect to HTTPS, see link:https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration?hl=en#https_redirect[HTTP to HTTPS redirects].

. Create an ingress resource using the following template, customizing the names as needed:
+
--
.Example of an ingress resource configuration
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # TODO: this the name of your {product-short} Ingress
  name: my-rhdh
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: <ADDRESS_NAME>
    networking.gke.io/managed-certificates: <rhdh_certificate_name>
    networking.gke.io/v1beta1.FrontendConfig: <ingress_security_config>
spec:
  ingressClassName: gce
  rules:
    # TODO: Set your application domain name.
    - host: {my-product-domain}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              # TODO: my-rhdh is the name of your `{product-custom-resource-type}` custom resource.
              # Adjust if you changed it!
              name: backstage-my-rhdh
              port:
                name: http-backend
----
--



.Verification
* Wait for the `ManagedCertificate` to be provisioned.
This process can take a couple of hours.

* Access {product-very-short} with `pass:a,q[{my-product-url}]`.

// Wait until the DNS name is responsive, indicating that your {product-short} instance is ready for use.

.Additional information
For more information on setting up {gke-short} using Ingress with TLS, see https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/main/ingress/single-cluster/ingress-https[Secure GKE Ingress].
