[id="installing-rhdh-on-kubernetes-with-helm-cli_{context}"]
= Installing {product} on Kubernetes with Helm CLI

You can use the Helm CLI to install {product} on Kubernetes.

.Prerequisites
* A `kubectl` session, with `developer` or `admin` permissions, on a Kubernetes cluster.
* You have installed the Helm CLI.

.Procedure
. Add the OpenShift Helm Charts repository.
+
----
helm repo add openshift-helm-charts https://charts.openshift.io/
----

. Define the _<rhdh>_ Kubernetes namespace name to deploy to:
+
[subs="quotes+"]
----
NAMESPACE=_<rhdh>_
----
. Create the _<rhdh>_ Kubernetes namespace:
+
[subs="quotes+"]
----
kubectl create namespace ${NAMESPACE}
----
. Activate the _<rhdh>_ Kubernetes namespace:
+
[subs="quotes+"]
----
kubectl config set-context --current --namespace=${NAMESPACE}
----

. Install the {product} Helm chart:
+
[subs="attributes+"]
----
helm upgrade redhat-developer-hub -i https://github.com/openshift-helm-charts/charts/releases/download/redhat-redhat-developer-hub-{product-chart-version}/redhat-developer-hub-{product-chart-version}.tgz
----

. Collect the {product-short} database password from your {ocp-short} cluster:
+
----
PASSWORD=$(kubectl get secret redhat-developer-hub-postgresql -o jsonpath="{.data.password}" | base64 -d)
----
. Collect your {ocp-short} cluster router base URL:
+
----
CLUSTER_ROUTER_BASE=$(kubectl get route console -n openshift-console -o=jsonpath='{.spec.host}' | sed 's/^[^.]*\.//')
----

. Configure your {product-short} Helm chart instance with the collected values:
+
[subs="attributes+"]
----
helm upgrade redhat-developer-hub -i "https://github.com/openshift-helm-charts/charts/releases/download/redhat-redhat-developer-hub-{product-chart-version}/redhat-developer-hub-{product-chart-version}.tgz" \
    --set global.clusterRouterBase="$CLUSTER_ROUTER_BASE" \
    --set global.postgresql.auth.password="$PASSWORD"
----

. Display the running {product-short} instance URL:
+
----
echo "https://redhat-developer-hub-$NAMESPACE.$CLUSTER_ROUTER_BASE"
----

.Verification
* Open the running {product-short} instance URL in your browser to use {product-short}.

