// Module included in the following assemblies:
// no assembly

:_mod-docs-content-type: PROCEDURE
[id="proc-install-rhdh-airgapped-environment-ocp-operator_{context}"]
= Installing {product} in an air-gapped environment with the Operator

You can install {product} in a fully disconnected or partially disconnected environment using the {product} Operator. For a list of supported platforms, see the link:https://access.redhat.com/support/policy/updates/developerhub[{product} Life Cycle page].

== Installing {product} on {ocp-short} in a partially disconnected environment with the Operator

On an {ocp-short} cluster operating on a restricted network, public resources are not available. However, deploying the {product} Operator and running {product-short} requires the following public resources:

* Operator images (bundle, operator, catalog)
* Operands images ({product-very-short}, PostgreSQL)

To make these resources available, replace them with their equivalent resources in a mirror registry accessible to your cluster.

You can use a helper script that mirrors the necessary images and provides the necessary configuration to ensure those images will be used when installing the {product} Operator and creating {product-short} instances. This script requires a target mirror registry. You likely have a target mirror registry ready to use if your cluster is already operating on a disconnected network. If you do not already have a target registry, and if you have an {ocp-short} cluster, you might want to expose and leverage the internal cluster registry.

If you are connected to a {ocp-short} cluster, the helper script will detect it and will automatically expose the cluster registry. However, if you are connected to a Kubernetes cluster, you can manually specify the target registry that you want to mirror the images to.

.Prerequisites
* You have an active `oc registry` session to the `registry.redhat.io` {company-name} Ecosystem Catalog. For more information, see link:https://access.redhat.com/RegistryAuthentication[{company-name} Container Registry Authentication].
* You have an active `skopeo` session with administrative access to the target mirror registry. For more information, see link:https://github.com/containers/skopeo#authenticating-to-a-registry[Authenticating to a registry].
* You have installed the `opm` CLI tool. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/opm-cli#olm-about-opm_cli-opm-install[Installing the opm CLI].
* You have installed Podman 5.3 or later. For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].

.Procedure
. In your terminal, navigate to the directory where you want to save the mirroring script.
. Download the mirroring script by running the following command:
+
[source,terminal,subs="attributes+"]
----
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/prepare-restricted-environment.sh
----
+
. Run the mirroring script by running the `bash` command with the appropriate set of options:
* If you do not already have a target mirror registry and want the script to create one for you, use the following example:
+
[source,terminal,subs="+quotes,+attributes"]
----
bash prepare-restricted-environment.sh \
   --prod_operator_index "registry.redhat.io/redhat/redhat-operator-index:v{ocp-version}" \
   --prod_operator_package_name "rhdh" \
   --prod_operator_bundle_name "rhdh-operator" \
   --prod_operator_version "v{product-bundle-version}" \
----
* If you want to use an existing target mirror registry, specify it with the `--use_existing_mirror_registry` option. For example:
+
[source,terminal,subs="+quotes,+attributes"]
----
bash prepare-restricted-environment.sh \
   --prod_operator_index "registry.redhat.io/redhat/redhat-operator-index:v{ocp-version}" \
   --prod_operator_package_name "rhdh" \
   --prod_operator_bundle_name "rhdh-operator" \
   --prod_operator_version "v{product-bundle-version}" \
   --use_existing_mirror_registry "_<my_registry>_"
----
+
[NOTE]
====
The script can take several minutes to complete as it copies multiple images to the mirror registry.
====

.Verification
* If you are using {ocp-brand-name}, the {product} Operator is in the *Installed Operators* list in the web console.
* If you are using a supported Kubernetes platform, you can check the list of pods running in the `rhdh-operator` namespace by running the following command in your terminal:
+
[source,terminal,subs="+quotes,+attributes"]
----
kubectl -n rhdh-operator get pods
----

== Installing {product} on {ocp-short} in a fully disconnected environment with the Operator

If your network has access to the registry through a bastion host or physical disk, you can use the Operator to install {product} by mirroring specified resources and transferring them to your air-gapped environment without any connection to the internet.

.Prerequisites

* You have set up your disconnected environment.
** You have mirrored all of the required images to disk.
** You have manually transferred the mirror folder to the network of the disconnected mirror registry.
** You have mirrored the images from disk to the target mirror registry in your disconnected environment.
** You have installed the Operator in your disconnected environment.
* You have set up your workstation.
** You have an active `oc registry` session to the `registry.redhat.io` {company-name} Ecosystem Catalog. For more information, see link:https://access.redhat.com/RegistryAuthentication[{company-name} Container Registry Authentication].
** You have installed the `opm` CLI tool. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.17/html/cli_tools/opm-cli#olm-about-opm_cli-opm-install[Installing the opm CLI].
** You have installed Podman 5.3 or later. For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].

.Procedure
. Download the mirroring script to disk by running the following command:
+
[source,terminal,subs="attributes+"]
----
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/prepare-restricted-environment.sh
----
+
. Run the mirroring script by running the `bash` command with the appropriate set of options:
+
[source,terminal,subs="+quotes,+attributes"]
----
bash prepare-restricted-environment.sh \
    --index-image "quay.io/rhdh/iib:next-v4.18-x86_64" \
    --ci-index true \
    --to-dir _<my_pulled_image_location>_ \
    [--filter-versions '*'] \
    [--use-oc-mirror true]
----
+
where

_<my_pulled_image_location>_ :: Specifies the directory where you want to pull all of the necessary images with the `--to-dir` option, for example, my.registry.example.com/namespace
+
[NOTE]
====
The script can take several minutes to complete as it copies multiple images to the mirror registry.
====
+
. Transfer the directory specified by the `--to-dir` option to your disconnected environment.
. From a machine in your disconnected environment that has access to both the cluster and the target mirror registry, download the mirroring script from disk by running the following command:
+
[source,terminal,subs="attributes+"]
----
curl -sSLO https://raw.githubusercontent.com/redhat-developer/rhdh-operator/refs/heads/release-{product-version}/.rhdh/scripts/prepare-restricted-environment.sh
----
+
. Run the mirroring script by running the `bash` command with the appropriate set of options:
+
[source,terminal,subs="+quotes,+attributes"]
----
bash prepare-restricted-environment.sh \
    --from-dir _<my_pulled_image_location>_ \
    [--to-registry _<my.registry.example.com>_/_<namespace>_] \
    [--use-oc-mirror true]
----
+
where

_<my_pulled_image_location>_ :: Specifies the directory where you want to pull all of the necessary images with the `--to-dir` option.

_<my.registry.example.com>_ :: Specifies the URL for the target mirror registry where you want to mirror the images.

_<namespace>_ :: Specifies the target namespace where you want to mirror the images.
+
[NOTE]
====
If you used `oc-mirror` to mirror the images to disk, you must also use `oc-mirror` to mirror the images from disk due to the folder layout that `oc-mirror` uses.
====
+
[NOTE]
====
The script can take several minutes to complete as it automatically installs the {product} Operator.
====

.Verification
* If you are using {ocp-brand-name}, the {product} Operator is in the *Installed Operators* list in the web console.
* If you are using a supported Kubernetes platform, you can check the list of pods running in the `rhdh-operator` namespace by running the following command in your terminal:
+
[source,terminal,subs="+quotes,+attributes"]
----
kubectl -n rhdh-operator get pods
----
