[id="proc-deploy-rhdh-instance-gke.adoc_{context}"]
= Deploying the {product-short} instance on {gke-short} with the Operator
You can deploy your {product-short} instance in {gke-short} using the Operator.

.Prerequisites
* A cluster administrator has installed the {product} Operator.
* You have subscribed to `registry.redhat.io`. For more information, see https://access.redhat.com/RegistryAuthentication[{company-name} Container Registry Authentication].
* You have installed `kubectl`. For more information, see https://kubernetes.io/docs/tasks/tools/#kubectl[Install kubetl].

* You have configured a domain name for your {product-short} instance.
* You have reserved a static external Premium IPv4 Global IP address that is not attached to any virtual machine (VM). For more information see https://cloud.google.com/vpc/docs/reserve-static-external-ip-address#reserve_new_static[Reserve a new static external IP address]
* You have configured the DNS records for your domain name to point to the IP address that has been reserved.
+
[NOTE]
====
You need to create an `A` record with the value equal to the IP address. This process can take up to one hour to propagate.
====

.Procedure
. Create a `{my-app-config-file}` config map containing the `{my-app-config-file}` {product-short} configuration file by using the following template:
+
--
.`{my-app-config-file}` fragment
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: {my-app-config-config-map}
data:
  "{my-app-config-file}": |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://<rhdh_domain_name>
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
      baseUrl: https://<rhdh_domain_name>
      cors:
        origin: https://<rhdh_domain_name>
----
--

. Create a `_<my_product_secrets>_` secret and add a key named `BACKEND_SECRET` with a `Base64-encoded` string value as shown in the following example:
+
--
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: `_<my_product_secrets>_` <1>
stringData:
  # TODO: See https://backstage.io/docs/auth/service-to-service-auth/#setup
  BACKEND_SECRET: "xxx"
----
<1> `_<my_product_secrets>_` is your preferred {product-short} secret name, where `_<my_product_secrets>_` specifies the identifier for your secret configuration within {product-short}.

[IMPORTANT]
====
Ensure that you use a unique value of `BACKEND_SECRET` for each {product-short} instance.
====

You can use the following command to generate a key:

[source,terminal]
----
node-p'require("crypto").randomBytes(24).toString("base64")'
----
--

. To enable pulling the PostgreSQL image from the {company-name} Ecosystem Catalog, add the image pull secret in the default service account within the namespace where the {product-short} instance is being deployed:
+
--
[source,terminal]
----
kubectl patch serviceaccount default \
    -p '{"imagePullSecrets": [{"name": "rhdh-pull-secret"}]}' \
    -n <your_namespace>
----
--

. Create your `{product-custom-resource-type}` custom resource (CR) file using the following template:
+
--
.Custom resource fragment
[source,yaml,subs="+quotes,+attributes"]
----
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  # This is the name of your {product-short} instance
  name: my-rhdh
spec:
  application:
    imagePullSecrets:
    - "rhdh-pull-secret"
    route:
      enabled: false
    appConfig:
      configMaps:
        - name: {my-app-config-config-map}
    extraEnvs:
      secrets:
        - name: `_<my_product_secrets>_` <1>
----
<1> `_<my_product_secrets>_` is your preferred {product-short} secret name, where `_<my_product_secrets>_` specifies the identifier for your secret configuration within {product-short}.
--

. Set up a Google-managed certificate by creating a `ManagedCertificate` object which you must attach to the Ingress as shown in the following example:
+
--
[source,yaml,subs="attributes+"]
----
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: <rhdh_certificate_name>
spec:
  domains:
    - <rhdh_domain_name>
----
--
For more information about setting up a Google-managed certificate, see https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs?hl=en#setting_up_a_google-managed_certificate[Setting up a Google-managed certificate].

. Create a `FrontendConfig` object to set a policy for redirecting to HTTPS. You must attach this policy to the Ingress.
+
--
.Example of a `FrontendConfig` object
[source,yaml,subs="attributes+"]
----
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: <ingress_security_config>
spec:
  sslPolicy: gke-ingress-ssl-policy-https
  redirectToHttps:
    enabled: true
----
--
For more information about setting a policy to redirect to HTTPS, see https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-configuration?hl=en#https_redirect[HTTP to HTTPS redirects].

. Create an ingress resource using the following template, customizing the names as needed:
+
--
.Example of an ingress resource configuration
[source,yaml,subs="attributes+"]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # TODO: this the name of your Developer Hub Ingress
  name: my-rhdh
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: <ADDRESS_NAME>
    networking.gke.io/managed-certificates: <rhdh_certificate_name>
    networking.gke.io/v1beta1.FrontendConfig: <ingress_security_config>
spec:
  ingressClassName: gce
  rules:
    # TODO: Set your application domain name.
    - host: <rhdh_domain_name>
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              # TODO: my-rhdh is the name of your `{product-custom-resource-type}` custom resource.
              # Adjust if you changed it!
              name: backstage-my-rhdh
              port:
                name: http-backend
----
--



.Verification

* Wait for the `ManagedCertificate` to be provisioned. This process can take a couple of hours.

* Access {product-very-short} with `https://<rhdh_domain_name>`

// Wait until the DNS name is responsive, indicating that your {product-short} instance is ready for use.

.Additional information
For more information on setting up {gke-short} using Ingress with TLS, see https://github.com/GoogleCloudPlatform/gke-networking-recipes/tree/main/ingress/single-cluster/ingress-https[Secure GKE Ingress].
