// Module included in the following assemblies:
// assembly-install-rhdh-osd-gcp.adoc

[id="proc-install-rhdh-osd-gcp-operator_{context}"]
= Installing {product} on {osd-short} on {gcp-short} using the Operator

You can install {product-short} on {osd-short} on {gcp-short} using the {product} Operator.

.Prerequisites
* You have a valid {gcp-short} account.
* Your {osd-short} cluster is running on {gcp-short}. For more information, see link:https://docs.redhat.com/en/documentation/openshift_dedicated/4/html/installing_accessing_and_deleting_openshift_dedicated_clusters/osd-creating-a-cluster-on-gcp[Creating a cluster on GCP] in {osd-brand-name} documentation.
* You have administrator access to {osd-short} cluster and {gcp-short} project.
* Make sure that your system meets the minimum sizing requirements. See link:{about-book-url}#rhdh-sizing_about-rhdh[Sizing requirements for {product}].

.Procedure

. In the {ocp-short} web console menu, go to *Operators > OperatorHub*.
. In the *Filter by keyword* field, enter {product-short} and click the *{product} Operator* card.
. On the *{product} Operator* page, click *Install*.
. After the installation completes, navigate to *Installed Operators* and select *Red Hat {product-short} Operator*.
. Provision your custom configuration:
+
--
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
data:
  "app-config-rhdh.yaml": |
    app:
      title: {product}
      baseUrl: {my-product-url}
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
      baseUrl: {my-product-url}
      cors:
        origin: {my-product-url}
----
--
+
You must create a config map named `app-config-rhdh` and a Kubernetes Secret containing the `BACKEND_SECRET`. These resources are used by the {product-short} instance for authentication and application settings.
+
For further steps, see xref:{configuring-book-url}#provisioning-and-using-your-custom-configuration[Provisioning your custom {product} configuration].
. Create a config map named `app-config-rhdh` that includes your `{my-app-config-file}` as shown:
+
--
[source,yaml,subs="attributes+"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
data:
  "app-config-rhdh.yaml": |
    app:
      title: {product}
      baseUrl: {my-product-url}
    backend:
      auth:
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
      baseUrl: {my-product-url}
      cors:
        origin: {my-product-url}
----
--
. Create a secret named `{my-product-secrets}` and add a key named `BACKEND_SECRET` with a `Base64-encoded` string as value:
+
--
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: {my-product-secrets}
stringData:
  # TODO: Add the necessary auth secrets for service-to-service auth setup
  BACKEND_SECRET: "xxx" # Replace with your `Base64-encoded` secret
----
--
. Return to the *{product-short} Operator* page and click *Create New Instance*.
. Specify the name and target namespace for the {product-short} deployment.
. Configure required options such as Git integration, secrets, and user permissions.
. Review the configuration, select deployment options, and click *Create*.

.Verification

* To access the {product-short}, navigate to the {product-short} URL provided in the {ocp-short} web console.

.Additional resources
* link:{configuring-book-url}[{configuring-book-title}]
* link:{customizing-book-url}[{customizing-book-title}]
