// Module included in the following assemblies:
// assembly-install-rhdh-osd-gcp.adoc

[id="proc-install-rhdh-osd-gcp-helm_{context}"]
= Installing {product} on {osd-short} on {gcp-short} using the Helm Chart

You can install {product-short} on {osd-short} on {gcp-short} using the {product} Helm Chart.

.Prerequisites
* You have a valid {gcp-short} account.
* Your {osd-short} cluster is running on {gcp-short}. For more information, see link:https://docs.redhat.com/en/documentation/openshift_dedicated/4/html/installing_accessing_and_deleting_openshift_dedicated_clusters/osd-creating-a-cluster-on-gcp[Creating a cluster on GCP] in {osd-brand-name} documentation.
* You have installed Helm 3 or the latest.

.Procedure
. From the *Developer* perspective on the {product-short} web console, click *+Add*.
. From the *Developer Catalog* panel, click *Helm Chart*.
. In the *Filter by keyword* box, enter {product-short} and click the *{product}* card.
. From the {product} page, click *Create*.
. From your cluster, copy the {ocp-short} router host (for example: `apps.<clusterName>.com`).
. Select the radio button to configure the {product-short} instance with either the form view or YAML view. The *Form view* is selected by default.
+
--
.. Using *Form view*
... To configure the instance with the Form view, go to *Root Schema → global → Enable service authentication within Backstage instance* and paste your {ocp-short} router host into the field on the form.

.. Using *YAML view*
... To configure the instance with the YAML view, paste your {ocp-short} router hostname in the `global.clusterRouterBase` parameter value as shown in the following example:
+
[source,yaml]
----
global:
  auth:
    backend:
      enabled: true
  clusterRouterBase: apps.<clusterName>.com
  # other {product} Helm Chart configurations
----
--

. Edit the other values if needed, then click *Create* and wait for the database and {product-short} to start.

.Verification

* To access the the {product-short}, click the *Open URL* icon.

.Additional resources
* link:{LinkAdminGuide}[{Administration guide for {product}}]
