[id='con-rbac-rest-api_{context}']
= Role-based Access Control (RBAC) REST API

{product} provides RBAC REST API that you can use to manage the permissions and roles in the {product-short}. This API supports you to facilitate and automate the maintenance of {product-short} permission policies and roles.

Using the RBAC REST API, you can perform the following actions:

* Retrieve information about all permission policies or specific permission policies, or roles
* Create, update, or delete a permission policy or a role
* Retrieve permission policy information about static plugins

The RBAC REST API requires the following components:

Authorization::
+
--

The RBAC REST API requires Bearer token authorization for the permitted user role. For development purposes, you can access a web console in a browser. When you refresh a token request in the list of network requests, you find the token in the response JSON.

`Authorization: Bearer $token`

For example, on the *Homepage* of the {product-short}, you can navigate to the *Network* tab and search for the `query?term=` network call. Alternatively, you can go to the *Catalog* page and select any Catalog API network call to acquire the Bearer token.
--

HTTP methods::
+
--

The RBAC REST API supports the following HTTP methods for API requests:

* `GET`: Retrieves specified information from a specified resource endpoint
* `POST`: Creates or updates a resource
* `PUT`: Updates a resource
* `DELETE`: Deletes a resource
--

Base URL::
+
--

The base URL for RBAC REST API requests is `pass:c[http://SERVER:PORT/api/permission/policies]`, such as `pass:c[http://localhost:7007/api/permission/policies]`.
--

Endpoints::
+
--

RBAC REST API endpoints, such as `/api/permission/policies/[kind]/[namespace]/[name]` for specified kind, namespace, and username, are the URI that you append to the base URL to access the corresponding resource.

Example request URL for `/api/permission/policies/[kind]/[namespace]/[name]` endpoint is:

`pass:c[http://localhost:7007/api/permission/policies/user/default/johndoe]`

[NOTE]
====
If at least one permission is assigned to `user:default/johndoe`, then the example request URL mentioned previously returns a result if sent in a `GET` response with a valid authorization token. However, if permission is only assigned to roles, then the example request URL does not return an output.
====
--

Request data::
+
--

HTTP `POST` requests in the RBAC REST API may require a JSON request body with data to accompany the request.

Example `POST` request URL and JSON request body data for
`pass:c[http://localhost:7007/api/permission/policies]`:

[source,json]
----
{
    "entityReference": "role:default/test",
    "permission": "catalog-entity",
    "policy": "delete",
    "effect": "allow"
}
----
--

HTTP status codes::
+
--

The RBAC REST API supports the following HTTP status codes to return as responses:

* `200` OK: The request was successful.
* `201` Created: The request resulted in a new resource being successfully created.
* `204` No Content: The request was successful, but there is no additional content to send in the response payload.
* `400` Bad Request: input error with the request
* `401` Unauthorized: lacks valid authentication for the requested resource
* `403` Forbidden: refusal to authorize request
* `404` Not Found: could not find requested resource
* `409` Conflict: request conflict with the current state and the target resource
--

Source::
+
--
Each permission policy and role created using the RBAC plugin is associated with a source to maintain data consistency within the plugin. You can manipulate permission policies and roles based on the following designated source information:

* CSV file
* Configuration file
* REST API
* Legacy

Managing roles and permission policies originating from CSV files and REST API involves straightforward modification based on their initial source information.

The Configuration file pertains to the default `role:default/rbac_admin` role provided by the RBAC plugin. The default role has limited permissions to create, read, update, and delete permission policies or roles, and to read catalog entities. 

[NOTE]
====
In case the default permissions are insufficient for your administrative requirements, you can create a custom admin role with required permission policies.
====

The legacy source applies to policies and roles defined before RBAC backend plugin version `2.1.3`, and is the least restrictive among the source location options. You must update the permissions and roles in legacy source to use either REST API or the CSV file sources. 

You can use the `GET` requests to query roles and policies and determine the source information, if required.
--
