[id='con-rbac-config-permission-policies-admin_{context}']
= Configuration of permission policies administrators

The permission policies for users and groups in the {product-short} are managed by permission policy administrators. Only permission policy administrators can access the Role-Based Access Control REST API.

The purpose of configuring policy administrators is to enable a specific, restricted number of authenticated users to access the RBAC REST API. The permission policies are defined in a `policy.csv` file, which is referenced in the `app-config-rhdh` ConfigMap. OpenShift platform administrators or cluster administrators can perform this task with access to the namespace where {product} is deployed.

You can set the credentials of a permission policy administrator in the `app-config.yaml` file as follows:

[source,yaml]
----
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: user:default/joeuser
----

The permission policy role (`role:default/rbac_admin`) is a default role in {product-short} and includes some permissions upon creation, such as creating, reading, updating, and deleting permission policies/roles, as well as reading from the catalog.

If the default permissions are not adequate for your requirements, you can define a new administrator role tailored to your requirements using relevant permission policies. Alternatively, you can use the optional super user admin configuration value, which grants unrestricted permissions across {product-short}.

You can set the `superUsers` in the `app-config.yaml` file as follows:

[source,yaml]
----
permission:
  enabled: true
  rbac:
    admin:
      superUsers:
        - name: user:default/joeuser
----
