[id='con-rbac-conditional-policies-rhdh_{context}']
= Conditional policies in {product}

The permission framework in {product} provides conditions, supported by the RBAC backend plugin (`backstage-plugin-rbac-backend`). The conditions work as content filters for the {product-short} resources that are provided by the RBAC backend plugin. 

The RBAC backend API stores conditions assigned to roles in the database. When you request to access the frontend resources, the RBAC backend API searches for the corresponding conditions and delegates them to the appropriate plugin by its plugin ID. In case you are assigned to multiple roles with different conditions, then the RBAC backend merges the conditions using the `anyOf` criteria.

Conditional criteria::
+
--
A condition in {product-short} is a simple condition with a rule and parameters. However, a condition can also contain a parameter or an array of parameters combined by conditional criteria. The supported conditional criteria includes:

* `allOf`: Ensures that all conditions within the array must be true for the combined condition to be satisfied.

* `anyOf`: Ensures that at least one of the conditions within the array must be true for the combined condition to be satisfied.

* `not`: Ensures that the condition within it must not be true for the combined condition to be satisfied.
--

Conditional object::
+
--
The plugin specifies the parameters supported for conditions. You can access the conditional object schema from the RBAC API endpoint to understand how to construct a conditional JSON object, which is then utilized through the RBAC backend plugin API.

A conditional object contains the following parameters:

.Conditional object parameters
[cols="30%,45%,25%", frame="all", options="header"]
|===
|Parameter
|Type
|Description

|`result`
|String
|Always has the value `CONDITIONAL`

|`roleEntityRef`
|String
|String entity reference to the RBAC role, such as `role:default/dev`

|`pluginId`
|String
|Corresponding plugin ID, such as `catalog`

|`permissionMapping`
|String array
|Array permission actionn, such as `['read', 'update', 'delete']`

|`resourceType`
|String
|Resource type provided by the plugin, such as `catalog-entity`

|`conditions`
|JSON
|Condition JSON with parameters or array parameters joined by criteria

|===
--


