[id='proc-rbac-ui-delete-role_{context}']
= Deleting a role in the {product} Web UI

You can delete a role in the {product} using the Web UI.

[NOTE]
====
The policies generated from a `policy.csv` or ConfigMap file cannot be edited or deleted using the {product-short} Web UI.
====

.Prerequisites
* You have an administrator role in the {product-short}.
* You have installed the `@janus-idp/backstage-plugin-rbac` plugin in {product-short}.
//For more information, see xref:rhdh-installing-dynamic-plugins[].
//Cannot xref across titles. Convert xref to a link.
* You have configured the required permission policies. For more information, see xref:con-rbac-config-permission-policies_admin-rhdh[].
* The role that you want to delete is created in the {product-short}.

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
--
The *RBAC* tab appears, displaying all the created roles in the {product-short}.
--

. (Optional) Click any role to view the role information on the *OVERVIEW* page.
. Select the delete icon from the *Actions* column for the role that you want to delete.
+
*Delete this role?* pop-up appears on the screen.
. Click *DELETE*.