[id='generating-postgresql-certificate-for-aws-rds_{context}']
= Generating PostgreSQL certificate for AWS RDS

For Amazon Web Services (AWS) Relational Database Service (RDS), you can generate a PostgreSQL certificate file in the .pem format. The content of this file is used to create a PostgreSQL secret for {product-short} configuration.


.Prerequisites
* You have an AWS account with active subscription and a PostgreSQL instance on link:https://aws.amazon.com/rds/postgresql/[Amazon RDS for PostgreSQL].
* You are using PostgreSQL version 15 on AWS RDS.
* You have your database host, database port, username, and password handy. The database port that is usually used is `5432`.
* You have installed the {product-very-short} application by using one of the following options:
** {product} Operator
** Helm Chart 
* Optional: You have installed the `psql` client to check your database connection.

.Procedure

. Optional: Check your database connection by running the following command:
+
[source,bash]
----
psql -h <db-host> -p <db-port> -U <username> -P <password>
----
+
.Example output
[source,bash]
----
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)
Type "help" for help.
postgres=>
(type ‘\q’ to quit from psql CLI)
----

. Go to the link:https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.CertificatesAllRegions[Certificate bundles for all AWS Regions] or link:https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.RegionCertificates[Certificate bundles for specific AWS Regions] site and download a certificate file of the .pem format.

. Use the .pem certificate file to create a PostgreSQL secret. For more information, see link:{LinkAdminGuide}#proc-creating-secrets-for-postgresql_admin-rhdh[Creating PostgreSQL secrets].
