[id='proc-rbac-config-conditional-policy-file_{context}']
= Configuring conditional policies defined in an external file

You can configure and manage conditional policies that are defined in an external file. To define conditional policies, you can directly edit the configuration files and pass them to {product-short}, instead of using the {product-short} web UI or API. You can configure {product-short} to use these files instead of the default files.

.Prerequisites
* You are logged in to your {ocp-short} account using the {ocp-short} web console.
* You have defined conditional policies in a YAML file, which includes role references, permission mappings, and conditions.
+
--
The following is an example of a YAML file defining conditional policies:

.Example YAML file defining conditional policies
[source,yaml]
----
---
result: CONDITIONAL
roleEntityRef: 'role:default/test'
pluginId: catalog
resourceType: catalog-entity
permissionMapping:
  - read
  - update
conditions:
  rule: IS_ENTITY_OWNER
  resourceType: catalog-entity
  params:
    claims:
      - 'group:default/team-a'
      - 'group:default/team-b'
---
result: CONDITIONAL
roleEntityRef: 'role:default/test'
pluginId: catalog
resourceType: catalog-entity
permissionMapping:
  - delete
conditions:
  rule: IS_ENTITY_OWNER
  resourceType: catalog-entity
  params:
    claims:
      - 'group:default/team-a'
----
--
* You have defined roles and associated policies in a CSV file that serves as a basis for creating roles and permissions. Ensure that you mount the CSV file to {product-short}.
+
For more information, see xref:ref-rbac-conditional-policy-definition_title-authorization[] and xref:con-rbac-config-permission-policies-external-file_title-authorization[].

.Procedure

. In {ocp-short}, create a ConfigMap to hold the policies as shown in the following example:
+
--
.Example ConfigMap
[source, yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-conditional-policy
  namespace: rhdh
data:
  rbac-policy.yaml: |
    p, role:default/guests, catalog-entity, read, allow

    result: CONDITIONAL
    roleEntityRef: 'role:default/test'
    pluginId: catalog
    resourceType: catalog-entity
    permissionMapping:
      - read
      - update
    conditions:
      rule: IS_ENTITY_OWNER
      resourceType: catalog-entity
      params:
        claims:
          - 'group:default/team-a'
          - 'group:default/team-b'
----
--

. Open `app-config.yaml` file and specify the path to both the `conditionalPoliciesFile` and `policies-csv-file` as shown in the following example:
+
--
.Example `app-config.yaml` file
[source,yaml]
----
permission:
  enabled: true
  rbac:
    conditionalPoliciesFile: /some/path/conditional-policies.yaml
    policies-csv-file: /some/path/rbac-policy.csv
----
--

. To enable automatic reloading of the policy file without restarting the application, add the `policyFileReload` option and set it to `true`:
+
--
.Example `app-config.yaml` file 
[source,yaml]
----
permission:
  enabled: true
  rbac:
    conditionalPoliciesFile: /some/path/conditional-policies.yaml
    policies-csv-file: /some/path/rbac-policy.csv
    policyFileReload: true
----
--

. Optional: Define nested conditional policies in the YAML file as needed.
+
--
.Example for nested conditional policies
[source,yaml]
----
{
  "result": "CONDITIONAL",
  "roleEntityRef": "role:default/developer",
  "pluginId": "catalog",
  "resourceType": "catalog-entity",
  "permissionMapping": ["delete"],
  "conditions": {
  "allOf": [
    {
      "anyOf": [
        {
          "rule": "IS_ENTITY_KIND",
          "resourceType": "catalog-entity",
          "params": {
            "kinds": [
              "group"
            ]
          }
        },
        {
          "rule": "IS_ENTITY_OWNER",
          "resourceType": "catalog-entity",
          "params": {
            "claims": [
              "$ownerRefs"
            ]
          }
        }
      ]
    },
    {
      "not": {
        "rule": "IS_ENTITY_KIND",
        "resourceType": "catalog-entity",
        "params": {
          "kinds": [
            "api"
          ]
        }
      }
    }
  ]
}
}
----

In the previous example, the `role:default/developer` is granted the condition to delete catalog entities only if they are the entity owner or if the catalog entity belongs to a group. However, this condition does not apply if the catalog entity is an API.
--

