// Module included in the following assemblies:
//
// * assemblies/assembly-rhdh-integration-aws.adoc
//

[id="proc-rhdh-deploy-eks-using-helm_{context}"]
= Deploying {product} on {eks-name} ({eks-short}) using Helm Chart

When you deploy {product-short} in {eks-name} ({eks-short}) using Helm Chart, it orchestrates a robust development environment within the AWS ecosystem.

.Prerequisites

* You have an {eks-short} cluster with AWS Application Load Balancer (ALB) add-on installed. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[Application load balancing on Amazon {product-short}] and https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html[Installing the AWS Load Balancer Controller add-on].
* You have installed the link:https://kubernetes.io/docs/reference/kubectl/[`kubectl` CLI].
* You are logged into your cluster using `kubectl`, and have `developer` or `admin` permissions.
* You have configured a domain name for your {product-short} instance. The domain name can be a hosted zone entry on Route 53 or managed outside of AWS. For more information, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html[Configuring Amazon Route 53 as your DNS service] documentation.
* You have an entry in the AWS Certificate Manager (ACM) for your preferred domain name. Make sure to keep a record of your Certificate ARN.
* You have subscribed to `registry.redhat.io`. For more information, see https://access.redhat.com/RegistryAuthentication[{company-name} Container Registry Authentication].
* You have set the context to the {eks-short} cluster in your current `kubeconfig`. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html[Creating or updating a kubeconfig file for an Amazon {eks-short} cluster].
* You have installed Helm 3 or the latest. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/helm.html[Using Helm with Amazon {eks-short}].

.Procedure

. Go to your terminal and run the following command to add the Helm chart repository containing the {product-short} chart to your local Helm registry:
+
[source,terminal]
----
helm repo add openshift-helm-charts https://charts.openshift.io/
----

. Create and activate the _<rhdh>_ namespace:
+
[source,terminal,subs="quotes+"]
----
DEPLOYMENT_NAME=_<redhat-developer-hub>_
NAMESPACE=_<rhdh>_
kubectl create namespace ${NAMESPACE}
kubectl config set-context --current --namespace=${NAMESPACE}
----

. Create a pull secret, which is used to pull the {product-short} images from the {company-name} Ecosystem, by running the following command:
+
[source,terminal]
----
kubectl create secret docker-registry rhdh-pull-secret \
    --docker-server=registry.redhat.io \
    --docker-username=<user_name> \ <1>
    --docker-password=<password> \ <2>
    --docker-email=<email> <3>
----
<1> Enter your username in the command.
<2> Enter your password in the command.
<3> Enter your email address in the command.

. Create a file named `values.yaml` using the following template:
+
[source,yaml,subs="attributes+"]
----
global:
  # TODO: Set your application domain name.
  host: <your {product-short} domain name>


route:
  enabled: false


upstream:
  service:
    # NodePort is required for the ALB to route to the Service
    type: NodePort


  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb


      alb.ingress.kubernetes.io/scheme: internet-facing


      # TODO: Using an ALB HTTPS Listener requires a certificate for your own domain. Fill in the ARN of your certificate, e.g.:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxx:xxxx:certificate/xxxxxx


      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'


      alb.ingress.kubernetes.io/ssl-redirect: '443'


      # TODO: Set your application domain name.
      external-dns.alpha.kubernetes.io/hostname: <your rhdh domain name>


  backstage:
    image:
      pullSecrets:
      - rhdh-pull-secret
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000
  postgresql:
    image:
      pullSecrets:
      - rhdh-pull-secret
    primary:
      podSecurityContext:
        enabled: true
        # you can assign any random value as fsGroup
        fsGroup: 3000
  volumePermissions:
    enabled: true
----

. Run the following command in your terminal to deploy {product-short} using the latest version of Helm Chart and using the `values.yaml` file created in the previous step:
+
[source,terminal,subs="attributes+"]
----
helm install rhdh \
  openshift-helm-charts/redhat-developer-hub \
  [--version {product-chart-version}] \
  --values /path/to/values.yaml
----
+
[NOTE]
====
For the latest chart version, see https://github.com/openshift-helm-charts/charts/tree/main/charts/redhat/redhat/redhat-developer-hub
====

. Configure your {product-short} Helm chart instance with the {product-short} database password and router base URL values from your cluster:
+
[source,terminal,subs="attributes+"]
----
PASSWORD=$(kubectl get secret redhat-developer-hub-postgresql -o jsonpath="{.data.password}" | base64 -d)
CLUSTER_ROUTER_BASE=$(kubectl get route console -n openshift-console -o=jsonpath='{.spec.host}' | sed 's/^[^.]*\.//')
helm upgrade $DEPLOYMENT_NAME -i "https://github.com/openshift-helm-charts/charts/releases/download/redhat-redhat-developer-hub-{product-chart-version}/redhat-developer-hub-{product-chart-version}.tgz" \
    --set global.clusterRouterBase="$CLUSTER_ROUTER_BASE" \
    --set global.postgresql.auth.password="$PASSWORD"
----

. Display the running {product-short} instance URL, by running the following command:
+
[source,terminal]
----
echo "https://$DEPLOYMENT_NAME-$NAMESPACE.$CLUSTER_ROUTER_BASE"
----

.Verification

* Open the running {product-short} instance URL in your browser to use {product-short}.

.Upgrade

* To upgrade the deployment, run the following command:
+
[source,terminal,subs="attributes+"]
----
helm upgrade $DEPLOYMENT_NAME -i https://github.com/openshift-helm-charts/charts/releases/download/redhat-redhat-developer-hub-{product-chart-version}/redhat-developer-hub-{product-chart-version}.tgz
----

.Delete

* To delete the deployment, run the following command:
+
[source,terminal]
----
helm -n $NAMESPACE delete $DEPLOYMENT_NAME
----
