[id="proc-configuring-postgresql-instance-using-operator_{context}"]
= Configuring an external PostgreSQL instance using the Operator

You can configure and use a PostgreSQL instance by using the {product} Operator. By default, the Operator creates and manages a local instance of PostgreSQL in the same namespace where you have deployed the {product-very-short} instance. However, you can change this default setting to configure an external PostgreSQL database server, for example, AWS RDS or Azure database. 

.Prerequisites

* You have the following details:
** `db-host`: Denotes your PostgreSQL instance Domain Name System (DNS) or IP address 
** `db-port`: Denotes your PostgreSQL instance port number, usually `5432`
** `username`: Denotes the user name to connect to your PostgreSQL instance
** `password`: Denotes the password to connect to your PostgreSQL instance

* You have a PostgreSQL certificate of the .pem format so that you can secure your database connection using the Secure Socket Layer (SSL) or Transport Layer Security (TLS) protocol. For more information, see link:{LinkAdminGuide}#postgresql-certificate-for-aws-rds_admin-rhdh[Downloading PostgreSQL certificate for AWS RDS] or link:{LinkAdminGuide}#generating-postgreSQL-certificate-for-azure-database_admin-rhdh[Generating PostgreSQL certificate for Azure database].

[NOTE]
====
By default, {product-short} uses a database for each plugin and automatically creates it if none is found. As an administrator, know that users might need the `Create Database` privilege in addition to `PSQL Database` privileges.  
====
 

.Procedure

. Create a credential secret to connect with the PostgreSQL instance:
+
[source,yaml]
----
cat <<EOF | oc -n <your-namespace> create -f -
apiVersion: v1
kind: Secret
metadata:
 name: <cred-secret> <1>
type: Opaque
stringData: <2>
 POSTGRES_PASSWORD: <password>
 POSTGRES_PORT: "<db-port>"
 POSTGRES_USER: <username>
 POSTGRES_HOST: <db-host>
 PGSSLMODE: require #  for TLS connection <3>
 NODE_EXTRA_CA_CERTS: <abs-path-to-pem-file> # for TLS connection, e.g. /opt/app-root/src/postgres-crt.pem <4>
EOF
----
<1> Provide the name of the credential secret.
<2> Provide credential data to connect with your PostgreSQL instance.
<3> Optional: Provide the value only if you need a TLS connection for your PostgreSQL instance.
<4> Optional: Provide the value only if you need a TLS connection for your PostgreSQL instance.

. Optional: Create a certificate secret with the PostgreSQL certificate file only if you need a TLS connection for your PostgreSQL instance:
+
[source,yaml]
----
cat <<EOF | oc -n <your-namespace> create -f -
apiVersion: v1
kind: Secret
metadata:
 name: <crt-secret>
type: Opaque
stringData:
 postgres-crt.pem: |-
   -----BEGIN CERTIFICATE-----
   MIIFqDCCA5CgAwIBAgIQHtOXCV/YtLNHcB6qvn9FszANBgkqhkiG9w0BAQwFADBl
   # ... 
----

. Create a `Backstage` custom resource (CR):
+
[source,yaml]
----
cat <<EOF | oc -n <your-namespace> create -f -
apiVersion: rhdh.redhat.com/v1alpha1
kind: Backstage
metadata:
 name: <backstage-instance-name>
spec:
 database:
   enableLocalDb: false <1>
 application: 
    extraFiles:
     mountPath: <path> # e g /opt/app-root/src
     secrets:
       - name: <crt-secret> <2>
         key: postgres-crt.pem # key name as in <crt-secret> Secret
    extraEnvs:
      secrets:
        - name: <cred-secret> <3>
        # ... 
----
<1> Set the value of the `enableLocalDb` parameter to `false` to disable creating local PostgreSQL instances.
<2> Optional: Provide the name of the certificate secret only for a TLS connection. 
<3> Provide the name of the credential secret that you created.
+
[NOTE]
====
The environment variables listed in the `Backstage` CR work with the Operator default configuration. If you have changed the Operator default configuration, you must reconfigure the `Backstage` CR accordingly.
====