:_newdoc-version: 2.18.3
:_template-generated: 2024-10-18

:_mod-docs-content-type: CONCEPT

[id="benefits-of-rhdh_{context}"]
= Benefits of {product}

{product} is designed to streamline developer workflow by providing a consistent self-service experience and can simplify application development through pre-built resources and enhanced collaboration tools. The following are the benefits of {product}:

* Increased developer productivity. Increases productivity by eliminating common organizational challenges, enabling seamless collaboration, and providing clear guidelines for creating, developing, and deploying applications.

* Unified self-service dashboard. Provides development teams with a unified dashboard covering various aspects such as Git, CI/CD, SAST/DAST, Supply Chain, OpenShift/Kubernetes cluster, JIRA, monitoring, API, documentation, and more, facilitated by over 150 plugins. All curated by a platform engineering team, aligning with the company’s best practices.

* Best practices through software templates. Automates organizational best practices by encoding common tasks such as creating new applications, running Ansible jobs, and establishing CI/CD pipelines for production deployment in Git.

* Scalable technical documentation. Code and documentation resides in the same repository, eliminating dependencies on proprietary document systems.

* Efficient onboarding for new developers. New developers can adapt quickly and become productive within a short timeframe.

* Robust enterprise Role-Based Access Control (RBAC). Empowers administrators to create roles, assign users or groups to roles, and implement robust security policies for enhanced access control.