:_mod-docs-content-type: PROCEDURE

[id="proc-resolving-authentication-issues-when-tool-are-not-found.adoc_{context}"]
= Resolving authentication issues when tools are not found

If your MCP client connects to the server but cannot find deployed tools, an authentication or configuration issue is likely.

.Procedure

. Verify the authentication token.
.. Configure a static token for the {product-very-short} MCP server.
.. Set this token as the bearer token in your MCP client and make sure the authorization header is the configuration specifies `Bearer` before the token, for example, `Bearer <mcp_token>`.
. Check the MCP endpoint configuration.
.. Confirm that the MCP server URL properly resolves, particularly if you are using a desktop client.
.. Use *legacy SSE endpoint* if your MCP client requires it instead of the Streamable endpoint. (For more details, see the *Configuration* topic).
. Verify your {product-very-short} `{my-app-config-file}` file for duplicate backend entries and make sure that the indentation is accurate.
.. Make sure that the configuration for the static token and MCP plugin sources go under an existing backend field, if one is present.
.. If you are unsure, see {model-context-protocol-link}#proc-configuring-model-context-protocol[the sample app configuration provided in the reference procedure].