:_mod-docs-content-type: PROCEDURE

[id="proc-retrieving-software-catalog-data-through-mcp-tool_{context}"]
= Retrieving Software Catalog data through the MCP tool

The Software Catalog MCP lists Backstage entities, such as *Components*, *Systems*, *Resources*, *APIs*, *Locations*, *Users*, and *Groups*. 

By default, the tool returns results in a JSON array format. Each entry in the JSON array contains an entity with the following fields: `name`, `description`,`type`, `owner`, `tags`, `dependsOn`, and `kind`. 

The optional `verbose` parameter returns the entire {backstage} entity object(s).

The following examples show common queries:

* “Fetch all ai-model resources in the {backstage} catalog”
* “Fetch the API definition for the beneficiary-management-api API”
* “Construct a curl command based on the API definition for the “insert beneficiary” endpoint in the beneficiary-management-api”

.Procedure
* Use the parameters as shown in the following table to configure your Software Catalog MCP tool plugin.

|===
| Name | Description | Example

| `kind`
| Filters entities by their {backstage} kind.
| "Component"

| `type`
| Filter entities by their {backstage} type. (Requires the `kind` parameter)
| "model-server"

| `name`
| Specifies the name of the {backstage} entity to retrieve.
| "vllm-model-server"

| `owner`
| Filters entities by their owner.
| "test-platform"

| `lifecycle`
| Filters entities by their lifecycle.
| "development"

| `tags`
| Filters entities by their tags.
| ["genai, "ibm", "llm", ...]

| `verbose`
| If set to `true`, the system returns the full {backstage} entity object instead of the shortened output.
| `true`

|===
