:_mod-docs-content-type: PROCEDURE

[id="proc-resolving-common-problems-with-mcp-clients-and-tools.adoc_{context}"]
= Resolving common problems with MCP client and tools

The following procedures guide you through resolving common issues when using a Model Communication Protocol (MCP) client for tool calling.

== Resolving the `Model does not support tool calling` error

This error indicates that the model configured in your MCP client lacks the required functionality to handle tool calls. The error message appears similar to: `Invalid request: model gemma3:27b does not support tool calls`.

.Procedure

. Consult your model documentation to confirm its support for tool calling.
. If the current model does not support tool calling, change the model that your MCP client uses to a tool-calling compatible model.

== Resolve authentication issues when tools are not found

If your MCP client connects to the server but cannot find deployed tools, an authentication or configuration issue is likely.

.Procedure

. Verify the authentication token.
.. Configure a static token for the RHDH MCP server.
.. Set this token as the bearer token in your MCP client and make sure the authorization header is the configuration specifies `Bearer` before the token, for example, `Bearer <mcp_token>`.
. Check the MCP endpoint configuration.
.. Confirm that the MCP server URL properly resolves, particularly if you are using a desktop client.
.. Use *legacy SSE endpoint* if your MCP client requires it instead of the Streamable endpoint. (For more details, see the *Configuration* topic).
. Verify your {product-very-short} {my-app-config-file} for duplicate backend entries and make sure that the indentation is accurate.
.. Make sure that the configuration for the static token and MCP plugin sources go under an existing backend field, if one is present.
.. If you are unsure, see {model-context-protocol-link}#proc-configuring-model-context-protocol[the sample app configuration provided in the reference procedure].

== Resolve nonsensical MCP tool output

Nonsensical output often occurs when smaller models or models with smaller context sizes cannot effectively manage repeated tool calls within the same context window.

.Procedure

To improve the quality of the tool output, take the following actions:

. Select an appropriate model for tool calling.
.. Verify that the model has good support for tool calling.
.. Make sure your model is not too small. We recommend a model with at least 7 billion parameters and a context window of 32k.
. Refine your queries.
.. Use more well-defined queries that limit the amount of data returned in the response from the tool.
. If possible, increase the context window size of the model. We recommend at least 32k for these MCP tools.