:_mod-docs-content-type: PROCEDURE

[id="proc-configure-mcp-tools-for-developer-lightspeed_{context}"]
= Configuring the {product-very-short} Model Context Protocol (MCP) tools for {ls-short} (Optional)

To leverage Model Context Protocol (MCP) servers like, the {model-context-protocol-link}[server in {product-very-short} with {ls-short}], you must first integrate them into the Llama Stack service. Configuring MCP in {lcs-short} enables the deployed {lcs-short} and Llama Stack to use external tools and retrieve real-time data. This integration allows the virtual assistant to execute complex actions and incorporate current operational context into its responses.

Configuration requires synchronizing settings across three components: the Llama Stack tool definition, the {lcs-short} MCP server endpoint definition, and the {ls-brand-name} plugin MCP authorization token.

For more information on configuring {ls-short}, see {developer-lightspeed-link}#proc-installing-and-configuring-lightspeed_developer-lightspeed[Installing and configuring {ls-brand-name}].

.Prerequisites

* You have configured {model-context-protocol-link}[MCP tools in your {product} instance].

.Procedure
. Configure the Llama Stack tool definition by defining the MCP provider in the `tool_runtime` section of the Llama Stack configuration file (`run.yaml`), as shown in the following code:
+
[source,yaml]
----
providers:
  tool_runtime:
    - provider_id: model-context-protocol
      provider_type: remote::model-context-protocol
      config: {}
----

. Configure the {lcs-short} MCP server endpoint by defining the MCP server endpoints in the {lcs-short} configuration file (`lightspeed-stack.yaml`), as shown in the following code:
+
[source,yaml]
----
mcp_servers:
  - name: mcp::backstage
    provider_id: model-context-protocol
    url: https://<RHDH_HOST>/api/mcp-actions/v1
----

where:

`<RHDH_HOST>`:: Hostname of your {product-very-short} instance
+
[IMPORTANT]
====
`provider_id` must match the Llama Stack definition (`model-context-protocol`).
====

. Configure the {ls-brand-name} plugin authorization token by specifying the MCP servers and providing the token for authentication in the {ls-brand-name} plugin configuration file (`lightspeed-app-config.yaml`), as shown in the following code:
+
[source,yaml]
----
lightspeed:
  mcpServers:
  - name: mcp::backstage
    token: ${MCP_TOKEN}
----
+
[IMPORTANT]
====
`name` must match the {lcs-name} definition (`mcp::backstage`).
====

[NOTE]
====
Self-hosted models might provide inconsistent or poor performance when using tool calling features, such as the Model Context Protocol (MCP). It is recommended to use the latest foundation models from providers like `OpenAI`` when experimenting with this integration to ensure the most reliable functionality.
====