:_mod-docs-content-type: PROCEDURE

[id="proc-retrieving-techdocs-urls-and-metadata-using-fetch-techdocs_{context}"]
= Retrieving TechDocs URLs and metadata using `fetch-techdocs`

The `fetch-techdocs` TechDocs MCP tool lists all {backstage} entities with TechDocs. By default, the tool returns results in a JSON array format. Each entry includes entity details and TechDocs metadata, like last update timestamp and build information. 

By default, each entry in the JSON array is an entity with the following fields: `name`, `title`, `tags`, `description`, `owner`, `lifecycle`, `namespace`, `kind`, `techDocsUrl`, `matadataUrl` and `metadata`.

The following examples show common queries:

* “Fetch all techdocs from the {backstage} server”
* “Fetch all techdocs of the default namespace”
* “Fetch all techdocs created by user:john.doe”

.Procedure
* Use the parameters as shown in the following table to configure your `fetch-techdocs` TechDocs MCP tool.

|===
| Name | Description | Example

| `entityType`
| Filters entities by their type.
| "Component"

| `namespace`
| Filter entities by their namespace.
| "default"

| `owner`
| Filters entities by owner.
| "user:john.doe"

| `lifecycle`
| Filters entities by their lifecycle.
| "development"

| `tags`
| Filters entities by their tags.
| ["genai, "ibm", "llm", "granite", "conversational", "task-text-generation"]

|===
