:_mod-docs-content-type: PROCEDURE

[id="proc-techdocs-find-docs_{context}"]
= Searching for relevant content in TechDocs

To view technical content, locate specific documents in *TechDocs* by using the search bar or filters.

The TechDocs Documentation page displays all documentation imported into your {product} instance. You can locate documentation by using keywords or filters:

* *Search*: Enter a keyword in the search bar to find documents containing that term.
* *Filter by Owner*: View documents owned by a specific user or group.
* *Filter by Tags*: View documents containing a specific tag.
* *Filter by Owned*: View documents owned by you or a group to which you belong.
* *Filter by Starred*: View documents you added to favorites.

The *All* field displays the total number of documents that have been imported into TechDocs. If you search or filter, this field updates to show the number of of documents that meet the search and filter criteria that you applied.

.Prerequisites

* The TechDocs plugin is enabled and configured.
* Documentation is imported into TechDocs.
* You have the required roles and permissions to add and view documentation to TechDocs.

.Procedure

. In the {product} navigation menu, click *Docs*.
. On the *Documentation* page, use the search bar, filters, or both to locate the document that you want to view.
