:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="verify-api-contracts-before-integrating-with-backend-services_{context}"]
= Verify API contracts before integrating with backend services

:context: verify-api-contracts-before-integrating-with-backend-services

[role="_abstract"]
To integrate with existing services and understand component communication, use the {product} ({product-very-short}) API browser to locate, inspect, and validate API definitions in a centralized interface. You can review API contracts and test endpoints to verify responses directly from the portal.

Apart from viewing specifications, you can use the interactive interface to test available endpoints and review data models. This verification confirms that your application correctly interfaces with backend services before you begin integration.

include::../modules/get-started_navigate-rhdh-on-your-first-day/proc-test-api-endpoints-interactively.adoc[leveloffset=+1]

include::../modules/get-started_navigate-rhdh-on-your-first-day/ref-select-supported-api-specifications.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources
* {customizing-book-link}[{customizing-book-title}]
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
