:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-configure-odf-operator_{context}"]
= Making object storage accessible to containers by using the Operator

Creating a `ObjectBucketClaim` Custom Resource (CR) automatically generates both the {product-short} `ObjectBucketClaim` config map and secret. The config map and secret contain `ObjectBucket` access information. Adding the access information to the Operator configuration makes it accessible to the {product-short} container by adding the following environment variables to the container:

* `BUCKET_NAME`
* `BUCKET_HOST`
* `BUCKET_PORT`
* `BUCKET_REGION`
* `BUCKET_SUBREGION`
* `AWS_ACCESS_KEY_ID`
* `AWS_SECRET_ACCESS_KEY`

These variables are then used in the TechDocs plugin configuration.

.Prerequisites

* You have installed {product} on {ocp-short} using the Operator.
* You have created an `ObjectBucketClaim` CR for storing files generated by TechDocs.

.Procedure

* In the {product-short} `Backstage` CR, enter the name of the {product-short} `ObjectBucketClaim` config map as the value for the `spec.application.extraEnvs.configMaps` field and enter the {product-short} `ObjectBucketClaim` secret name as the value for the `spec.application.extraEnvs.secrets` field. For example:
+
[source,yaml]
----
apiVersion: objectbucket.io/v1alpha1
kind: Backstage
metadata:
 name: <name>
spec:
  application:
    extraEnvs:
      configMaps:
        - name: <rhdh_bucket_claim_name>
      secrets:
        - name: <rhdh_bucket_claim_name>
----
