[id='proc-customize-rhdh-tech-radar-page_{context}']
= Customizing the Tech Radar page in {product}

In {product}, the Tech Radar page is not enabled using the dynamic plugin feature in the Helm chart.

Similar to Home page customization, the base Tech Radar URL must include the `/developer-hub/tech-radar` proxy.

[NOTE]
====
Due to the use of overlapping `pathRewrites` for both the `tech-radar` and `homepage` quick access proxies, you must create the `tech-radar` configuration (`^api/proxy/developer-hub/tech-radar`) before you create the `homepage` configuration (`^/api/proxy/developer-hub`).

For more information about customizing the Home page in {product}, see xref:proc-customize-rhdh-homepage_rhdh-getting-started[].
====


You can provide data to the Tech Radar page by using the following sources:

* JSON files hosted on GitHub or GitLab. To access the data from the JSON files, add the following code to the `app-config.yaml` file:
+
[source,yaml]
----
proxy:
  endpoints:
    # Other Proxies
    # customize developer hub instance
    '/developer-hub':
      target: <DOMAIN_URL> # i.e https://raw.githubusercontent.com/
      pathRewrite:
        '^/api/proxy/developer-hub/tech-radar': <path to json file> # i.e /janus-idp/backstage-showcase/main/packages/app/public/tech-radar/data-default.json
	 '^/api/proxy/developer-hub': <path to json file> # i.e /janus-idp/backstage-showcase/main/packages/app/public/homepage/data.json
      changeOrigin: true
      secure: true

      # Change to "false" in case of using self hosted cluster with a self-signed certificate
      headers:
	<HEADER_KEY>: <HEADER_VALUE> # optional and can be passed as needed i.e Authorization can be passed for private GitHub repo and PRIVATE-TOKEN can be passed for private GitLab repo
----

* A separate service that provides the Tech Radar data in JSON format using an API.

.Prerequisites

* You have installed the {product} using Helm Chart. For more information, see xref:proc-install-rhdh_rhdh-getting-started[].

.Procedure

To use a separate service to provide the Tech Radar data, complete the following steps:

. Add the following code to the `app-config-rhdh.yaml` file:
+
[source,yaml]
----
proxy:
  endpoints:
    # Other Proxies
    '/developer-hub/tech-radar':
      target: ${TECHRADAR_DATA_URL}
      changeOrigin: true
      # Change to "false" in case of using self hosted cluster with a self-signed certificate
      secure: true
----
where the `TECHRADAR_DATA_URL` is defined as `pass:c[http://<SERVICE_NAME>/tech-radar]`, for example, `pass:c[http://rhdh-customization-provider/tech-radar]`.
+
[NOTE]
====
You can define the `TECHRADAR_DATA_URL`  either by adding it to `rhdh-secrets` or directly replacing it with its value in your custom ConfigMap.
====
+
[NOTE]
====
Ensure that the API request call returns the response in JSON format.
====
+
. Delete the {product-short} pod to ensure that the new configurations are loaded correctly.
