[id='proc-add-custom-app-file-openshift-helm_{context}']
= Adding a custom application configuration file to {ocp-short} using the Helm chart

You can use the {product} Helm chart to add a custom application configuration file to your {ocp-short} instance.

.Prerequisites

* You have created an {ocp-brand-name} account.

.Procedure

. From the {ocp-short} web console, select the *ConfigMaps* tab.
. Click *Create ConfigMap*.
. From *Create ConfigMap* page, select the *YAML view* option in *Configure via* and make changes to the file, if needed.
. Click *Create*.
. Go to the *Helm* tab to see the list of Helm releases.
. Click the overflow menu on the Helm release that you want to use and select *Upgrade*.
. Use either the *Form view* or *YAML view* to edit the Helm configuration.

** Using *Form view*
+
.. Expand *Root Schema → Backstage chart schema → Backstage parameters → Extra app configuration files to inline into command arguments*.
.. Click the *Add Extra app configuration files to inline into command arguments* link.
.. Enter the value in the following fields:
+
--
* *configMapRef*: `app-config-rhdh`
* *filename*: `app-config-rhdh.yaml`
--
.. Click *Upgrade*.

** Using *YAML view*

.. Set the value of the `upstream.backstage.extraAppConfig.configMapRef` and `upstream.backstage.extraAppConfig.filename` parameters as follows:
+
[source, yaml]
----
# ... other Red Hat Developer Hub Helm Chart configurations
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: app-config-rhdh
        filename: app-config-rhdh.yaml
# ... other Red Hat Developer Hub Helm Chart configurations
----
.. Click *Upgrade*.
