[id="proc-techdocs-configure-odf-helm_{context}"]

= Configuring {odf-name} with the Helm chart

You can use the Helm chart to configure {odf-name} to store files generated by the TechDocs plugin.

.Prerequisites

* An {ocp-short} administrator has installed the {odf-name} Operator in {ocp-brand-name}. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.15/html/deploying_openshift_data_foundation_using_amazon_web_services/deploy-using-dynamic-storage-devices-aws#installing-openshift-data-foundation-operator-using-the-operator-hub_cloud-storage[Installing {company-name} {odf-name} Operator] in the {ocp-short} documentation.
* An {ocp-short} administrator has created an {odf-name} cluster and configured the `StorageSystem`. For more information, see link:https://access.redhat.com/documentation/en-us/red_hat_openshift_data_foundation/4.15/html/deploying_openshift_data_foundation_using_amazon_web_services/deploy-using-dynamic-storage-devices-aws#creating-an-openshift-data-foundation-service_cloud-storage[Creating an {odf-name} cluster] in the {ocp-short} documentation.

.Procedure

. In the OpenShift Container Platform web console, create an `ObjectBucketClaim` CR where the generated TechDocs files are stored. For example:
+
[source]
----
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: rhdh-bucket-claim
spec:
  generateBucketName: rhdh-bucket-
  storageClassName: openshift-storage.noobaa.io
----
+
[NOTE]
====
Creating the {product-short} `ObjectBucketClaim` CR automatically creates both the Developer Hub `ObjectBucketClaim` config map and secret. The config map and secret have the same name as the `ObjetBucketClaim` CR.
====

. In the `upstream.backstage`key in the Helm chart,  enter the name of the Developer Hub `ObjectBucketClaim` secret as the value for the `extraEnvVarsSecrets` field and the `extraEnvVarsCM` field. For example:
+
[source]
----
   extraEnvVarsSecrets:
     - <rhdh_bucket_claim_name>rhdh-bucket-claim
   extraEnvVarsCM:
     - <rhdh_bucket_claim_name>rhdh-bucket-claim
----
