:_mod-docs-content-type: PROCEDURE

[id="proc-customize-rhdh-page-theme_{context}"]
= Customizing the page theme header for your {product-short} instance

You can customize the header color for the light and dark theme modes in your {product-short} instance by modifying the `branding.theme` section of the `{my-app-config-file}` file. You can also customize the page headers for additional {product-short} pages, such as the *Home*, *Catalog*, and *APIs* pages.

[source,yaml]
----
app:
  branding:
    theme:
      light:
        palette: {}
        pageTheme:
          default:
            backgroundColor: "<default_light_background_color>"
            fontColor: "<default_light_font_color>"
            shape: none
          apis:
            backgroundColor: "<apis_light_background_color>"
            fontColor: "<apis_light_font_color>"
            shape: none
      dark:
        palette: {}
        pageTheme:
          default:
            backgroundColor: "<default_dark_background_color>"
            fontColor: "<default_dark_font_color>"
            shape: none
# ...
----
`light`:: Enter the theme mode, such as `light` or `dark`.
`default`:: Enter the default page theme configuration
`backgroundColor`::: Enter the page header background color, such as `#ffffff` or `white`.
`fontColor`::: Enter the page header text color, such as `#000000` or `black`.
`shape`::: Enter the page header pattern, such as `wave`, `round`, or `none`.
`apis::` Enter the page id to configure, such as `apis` or `home`.

//The page theme name depends on the plugin that you are customizing the page header for.
//can include information about this topic in the future.
