[id='proc-customize-rhdh-sidebar-menuitems_{context}']
= Customizing the sidebar menu items for your {product-short} instance

The sidebar menu in {product} consists of two main parts that you can configure:

* *Dynamic plugin menu items*: Your preferences and your active plugins define dynamically one part of the sidebar menu.
* *Main menu items*: The core navigation structure of sidebar is static.

.Procedure

. To configure *Dynamic plugin menu item*, add the following content to your `{my-app-config-file}` file:
+
[source,yaml]
----
dynamicPlugins:
  frontend:
    <package_name>: # <1>
      menuItems: # <2>
        <menu_item_name>: # <3>
          icon: # home | group | category | extension | school | _<your_icon>_ # <4>
          title: _<plugin_page_title>_ # <5>
          priority: 10 # <6>
          parent: favorites # <7>
----
<1> `_<package_name>_`: Specifies the name of the package. This name is the same as the `scalprum.name` key in the plugin `package.json`.
<2> `menuItems`: (Optional) Use to configure plugin menu items in the main sidebar navigation.
<3> `_<menu_item_name>_`: Specifies a unique name in the main sidebar navigation for either a standalone menu item or a parent menu item. If this field specifies a plugin menu item, the name of the menu item must match the name using in the corresponding path in `dynamicRoutes`. For example, if `dynamicRoutes` defines `path: /my-plugin`, then `menu_item_name` must be defined as `my-plugin`.
<4> `icon`: (Optional) Specifies the icon for the menu item. You can use default icons, such as: `home`, `group`, `category`, `extension`, and `school`. You can also use an SVG or HTML image icon, such as: `icon: <svg width="20px" height="20px" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" fill="#ffffff">...</svg>`  or `icon: https://img.icons8.com/ios-glyphs/20/FFFFFF/shop.png`.
<5> `title`: (Optional) Specifies the title of the menu item. Omit it when the title is already specified in the `dynamicRoutes` configuration under `menuItem.text`.
<6> `priority`: (Optional) Sets the order in which menu items appear in the sidebar. The default priority is 0, which places the item at the bottom of the list. A higher priority value places the item higher in the sidebar. You can define this field for each section.
<7> `parent`: (Optional) Specifies the parent menu item under which the current item is nested. If this field is used, the parent menu item must be defined elsewhere in the `menuItems` configuration of any enabled plugin. You can define this field for each section.

. To add *Main menu item* to the dynamic plugins configuration, add the `default.` prefix to its key in your `{my-app-config-file}` file:
+
[source,yaml]
----
dynamicPlugins:
  frontend:
    default.main-menu-items: # <1>
      menuItems:
        default._<menu_item_name>_: # <2>
          parent: _<my_menu_group>_ # <3>
          priority: 10 <4>
        default._<menu_group_parent_item_name>_: # <4>
          icon: _<my_menu_group_icon>_ # <5>
          title: _<my_menu_group_title>_ # <6>
          priority: 100 # <7>
----
<1> `default.main-menu-items`: Specifies the key for configuring static main menu items. The `default.` prefix identifies an item as a main menu item. You can add the `default.` prefix to both individual menu items or parent menu group configuration, such as `default.<menu_group_parent_item_name>` in the previous example.
<2> `default._<menu_item_name>_`: Specifies the key of the menu item configuration. `default.` prefix is required for a main menu item key.
<3> `parent`: (Optional) Specifies the parent menu item for this item.
<4> `priority`: (Optional) Specifies the order of this menu item within its menu level.
<5> `icon`: Specifies the icon for the menu group. Required for parent menu items.
<6> `title`: Specifies the title for the menu group. Required for parent menu items.
<7> `priority`: (Optional) Specifies the order of the parent menu item in the sidebar.
+
[NOTE]
====
The default priority of main menu items determines their order in the sidebar. You can customize the order of the static main menu items by adjusting their priority values. Ensure that the priority and title of each item is clear to facilitate easy reordering. 
====