// Module included in the following assemblies:
// assembly-customizing-the-appearance.adoc

[id="proc-customize-rhdh-branding_{context}"]
= Customizing the theme mode color palettes for your {product-short} instance

You can customize the color palettes of the light and dark theme modes in your {product-short} instance by configuring the `light.palette` and `dark.palette` parameters in the `branding.theme` section of the `{my-app-config-file}` file, as shown in the following example:

[source,yaml]
----
app:
  branding:
    theme:
      light:
        palette:
          primary:
            main: <light_primary_color>
          navigation:
            indicator: <light_indicator_color>
        pageTheme:
          default:
            backgroundColor: [<light_background_color_1>, <light_background_color_2>]
      dark:
        palette:
          primary:
            main: <dark_primary_color>
          navigation:
            indicator: <dark_indicator_color>
        pageTheme:
          default:
            backgroundColor: [<dark_background_color_1>, <dark_background_color_2>]
# ...
----
`light:palette:primary:main`:: The main primary color for the light color palette, for example, `#ffffff` or `white`
`light:palette:navigation:indicator`:: The color of the navigation indicator for the light color palette, which is a vertical bar that indicates the selected tab in the navigation panel, for example, `#FF0000` or `red`
`light:pageTheme:default:backgroundColor`:: The background color for the default page theme for the light color palette, for example, `#ffffff` or `white`
`dark:palette:primary:main`:: The main primary color for the dark color palette, for example, `#000000` or `black`
`dark:palette:navigation:indicator`:: The color of the navigation indicator for the dark color palette, which is a vertical bar that indicates the selected tab in the navigation panel, for example, `#FF0000` or `red`
`dark:pageTheme:default:backgroundColor`:: The background color for the default page theme for the dark color palette, for example, `#000000` or `black`

.Additional resources
* xref:proc-customizing-rhdh-theme-mode_{context}[]
