:_mod-docs-content-type: PROCEDURE

[id="proc-modifying-or-adding-rhdh-custom-menuitem_{context}"]
= Modifying or adding a custom menu items for your {product-short} instance

Modify a main menu item or add a custom menu item using the following step:

.Procedure
* In the `{my-app-config-file}` file, add a section to the `default.main-menu-items` > `menuItems` section. Use the `default.` prefix to identify the key as a main menu item.
+
[source,yaml]
----
dynamicPlugins:
  frontend:
    default.main-menu-items:
      menuItems:
        default._<menu_group_parent_item_name>_:
          icon: # home | group | category | extension | school | _<my_icon>_
          title: _<menu_group_parent_title>_ 
          priority: 10
        default._<menu_item_name>_:
          parent: _<menu_group_parent_item_name>_ 
          icon:  # home | group | category | extension | school | _<my_icon>_
          title: _<my_menu_title>_ 
          to: _<path_to_the_menu_target_page>_ 
          priority: 100
          enabled: true
----
`default._<menu_group_parent_item_name>_`:: (Optional) Enter the menu group parent item name to configure static main menu items. If no `default._<menu_item_name>_` has a `parent` value set, this field is not needed.
`icon`:: Enter the menu icon. Required for parent menu items.
`title`:: Enter the menu group title. Required for parent menu items.
`priority`:: (Optional) Enter the order of this menu item within its menu level.
`default._<menu_item_name>_`:: Enter the menu item name for which you want to override the default value. Add the `default.` prefix to identify a main menu item.
`parent`:: (Optional) Enter the parent menu item for this item. Required if <menu_item_name> is specified as the child of any menu items.
`icon`:: (Optional) Enter the menu icon. To use the default icon, set the icon as an (`" "`) empty string.
`title`:: (Optional) Enter the menu group title. Only required for adding a new custom main menu item. To hide a default main menu item title from the sidebar, set the title as an (`" "`) empty string.
// Update <8> for release 1.6 as this option (currently a  workaround) would be added as a functionality. RHIDP-6333.
`to`:: (Optional) Enter the path that the menu item navigates to. If it is not set, it defaults to the home page.
`priority`:: (Optional) Enter the order of this menu item within its menu level.
`enabled`:: (Optional) If this field is used to display the menu item in the sidebar, set the value to `true`. To hide the menu item from the sidebar, set the value to `false`.

+
[source,yaml]
----
default.main-menu-items:
      menuItems:
        default.catalog:
          icon: category
          title: My Catalog
          priority: 5
        default.learning-path:
          title: ''
        default.parentlist:
          title: Overview
          icon: bookmarks
        default.home:
          parent: default.parentlist
        default.references:
          title: References
          icon: school
          to: /references
          enabled: true
----
`icon`:: Specifies if you want to change the icon default menu item for the catalog.
`title`:: Specifies an empty string `" "` to hide the learning path from the default sidebar.
`default.parentlist`:: Introduces the parent menu item.
`parent`:: Nests home menu under the `default.parentlist` parent menu item.
`title`:: Specifies a name for `default.references`
`icon`:: Displays the `school` icon.
`to`:: Redirects `default.references` to the `/references` page.
`enabled`:: (Optional) If this field is used to display the menu item in the sidebar, set the value to `true`. To hide the menu item from the sidebar, set the value to `false`.
