:_mod-docs-content-type: CONCEPT

[id="prov-overriding-translations_{context}"]
= Overriding translations
In {product-very-short} 1.8, English and French are the supported languages. You can implement translations for other languages by using a JSON file to override the existing translation strings, and by updating the `i18n` section of your `{my-app-config-file}` configuration file to include the JSON translation override file.

.Prerequisites
* You have enabled localization in your {product-very-short} application.

.Procedure
// This feature is not being included in 1.8
// . In the top user menu, go to *Settings* > *General*.
// . Click on the download link in the *Translations* panel to download the default English translation strings.
. Create the JSON file containing all your translation as shown in the following example:
+
[id=i18n-enable]
.`allTranslations.json` fragment with translation string overrides
[source,json]
----
{
  "plugin.global-floating-action-button": {
    "fr": {
      "fab.quay.label": "QUAY French JSON",
      "fab.quay.tooltip": "QUAY french tooltip JSON",
      "fab.rbac.label": "RBAC French JSON",
      "fab.rbac.tooltip": "RBAC french tooltip JSON"
    },
    "en": {
      "fab.quay.label": "QUAY EN JSON",
      "fab.rbac.label": "RBAC EN JSON",
      "fab.rbac.tooltip": "RBAC EN tooltip JSON"
    }
  },
  "plugin.global-header": {
    "fr": {
      "applicationLauncher.developerHub": "Developer Hub French JSON"
    },
    "en": {
      "applicationLauncher.developerHub": "Developer Hub EN JSON"
    }
  }

}
----
. Log in to your cluster and create a config map for your translations override strings:
+
[source,bash]
----
oc create configmap all-translations \
    --from-file=/<path-to>/allTranslations.json
----

. Update your deployment configuration based on your installation method:

.. For an Operator-installed {product-very-short} instance, update your `{product-custom-resource-type}` custom resource (CR).
... In the `spec.application.extraFiles` section, add the translations custom app configuration as shown in the following example:
+
.Backstage custom resource fragment
[source,yaml,subs="+quotes"]
----
apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
spec:
  application:
    extraFiles:
      mountPath: /opt/app-root/src/translations
      configMaps:
        - name: all-translations
----

.. For a Helm-installed {product-very-short} instance, update your {product-short} `{backstage}` Helm chart to mount in the {product-short} filesystem your files from the `all-translations` config map:

... In the {product-short} Helm chart, go to *Root Schema* → *Backstage chart schema* → *Backstage parameters* → *Backstage container additional volume mounts*.

... Select *Add {backstage} container additional volume mounts* and add the following values:

mountPath::
`/opt/app-root/src/translations`
name::
`all-translations`

... Add the translations to the *{backstage} container additional volumes* in the {product-short} Helm chart:

name::
`all-translations`
configMap::
defaultMode:::
  `420`
name:::
`all-translations`

. Update the `i18n` section to your custom {product-short} `{my-app-config-file}` configuration file to include the following translation override file:
+
[id=i18n-override]
.`{my-app-config-file}` fragment with localization `i18n` fields
[source,yaml,subs="+quotes"]
----
i18n:
  locales: # List of supported locales. Must include `en`, otherwise the translation framework will fail to load.
    - en
    - fr
  defaultLocale: en # Optional. Defaults to `en` if not specified.
  overrides: # List of JSON translation files applied in order (last file wins).  Each file may override/add translations for one or more plugins/locales
    - /opt/app-root/src/translations/all-translations.json
----

