:_mod-docs-content-type: CONCEPT

[id="proc-enabling-localization-in-sidebar-menu-items_{context}"]
= Enabling sidebar menu items localization in {product-very-short}

You can enable translation key support for sidebar menu items, so that users can onboard in their preferred language. In {product-short}, all existing and newly created sidebar menu items support localization using the `titleKey` translation key. 

[NOTE]
If a translation key is present but the corresponding localized string is missing, the system defaults to the original text defined in the sidebar menu items configuration (`title`). If no translation key is defined at all, the original text is displayed.

.Prerequisites
* You have enabled localization in your {product-very-short} application.

.Procedure 

. For *all* sidebar menu items (both existing and new) in your configuration file, you must define both the original text and the new localization keys. For example, in the `dynamicPlugins.frontend.default.main-menu-items.menuItems.default.home` section of your `{my-app-config-file}` file, add the `titleKey`, as follows:
+
.Example `{my-app-config-file}` fragment
[source,yaml,subs="+quotes"]
----
dynamicPlugins:
  frontend:
    default.main-menu-items:
        menuItems:
          default.home:
            title: Home
            titleKey: menuItem.home
            icon: home
            priority: 100
            enabled: true
----
. In your translation file, map the `titleKey` from the first step to the localized strings for each supported language.
+
.Example `allTranslations.json` fragment
[source,yaml,subs="+quotes"]
----
{
  "rhdh": {
    "en": {
      "menuItem.home": "Home"
    },
    "fr": {
      "menuItem.home": "Accueil"
    }
  }
}
----