[id='proc-modifying-or-adding-rhdh-custom-menuitem_{context}']
= Modifying or adding a custom menu items for your {product-short} instance

Modify a main menu item or add a custom menu item using the following step:

.Procedure
* In the `{my-app-config-file}` file, add a section to the `default.main-menu-items` > `menuItems` section. Use the `default.` prefix to identify the key as a main menu item.
+ 
[source,yaml]
----
dynamicPlugins:
  frontend:
    default.main-menu-items:
      menuItems:
        default._<menu_group_parent_item_name>_: # <1>
          icon: # home | group | category | extension | school | _<my_icon>_ # <2>
          title: _<menu_group_parent_title>_ # <3>
          priority: 10 # <4>
        default._<menu_item_name>_: # <5>
          parent: _<menu_group_parent_item_name>_ # <6>
          icon:  # home | group | category | extension | school | _<my_icon>_ # <7>
          title: _<my_menu_title>_ # <8>
          to: _<path_to_the_menu_target_page>_ # <9>
          priority: 100 # <10>
----
<1> `default._<menu_group_parent_item_name>_`: (Optional) Enter the menu group parent item name to configure static main menu items. If no `default._<menu_item_name>_` has a `parent` value set, this field is not needed.
<2> `icon`: Enter the menu icon. Required for parent menu items.
<3> `title`: Enter the menu group title. Required for parent menu items.
<4> `priority`: (Optional) Enter the order of this menu item within its menu level.
<5> `default._<menu_item_name>_`: Enter the menu item name for which you want to override the default value. Add the `default.` prefix to identify a main menu item.
<6> `parent`: (Optional) Enter the parent menu item for this item. Required if <menu_item_name> is specified as the child of any menu items.
<7> `icon`: (Optional) Enter the menu icon. To use the default icon, set the icon as an (`" "`) empty string.
<8> `title`: (Optional) Enter the menu group title. Only required for adding a new custom main menu item. To hide a default main menu item title from the sidebar, set the title as an (`" "`) empty string.
// Update <8> for release 1.6 as this option (currently a  workaround) would be added as a functionality. RHIDP-6333.
<9> `to`: (Optional) Enter the path that the menu item navigates to. If it is not set, it defaults to the home page.
<10> `priority`: (Optional) Enter the order of this menu item within its menu level.

+
.Example `mainItems` configuration
[source,yaml]
----
default.main-menu-items:
      menuItems:
        default.catalog:
          icon: category # <1>
          title: My Catalog 
          priority: 5
        default.learning-path: 
          title: '' # <2>
        default.parentlist: # <3>
          title: Overview 
          icon: bookmarks
        default.home:
          parent: default.parentlist # <4>
        default.references:
          title: References # <5>
          icon: school # <6>
          to: /references # <7>
----
<1> `icon`: Specifies if you want to change the icon default menu item for the catalog.
<2> `title`: Specifies an empty string `" "` to hide the learning path from the default sidebar.
<3> `default.parentlist`: Introduces the parent menu item.
<4> `parent`: Nests home menu under the `default.parentlist` parent menu item.
<5> `title`: Specifies a name for `default.references`
<6> `icon`: Displays the `school` icon.
<7> `to`: Redirects `default.references` to the `/references` page.