:_mod-docs-content-type: CONCEPT

[id="con-metadata-generation"]
= Metadata generation

The Operator automatically generates specific metadata values for all objects at runtime to ensure your {product-custom-resource-type} application functions properly.

For all the objects, `metadata.name` is generated according to the rules defined in the Default Configuration files, particularly the resource name column. For example, {product-custom-resource-type} Custom Resource named `mybackstage` creates Kubernetes Deployment resource called `backstage-mybackstage`.

The following is per-object generated metadata:

* `deployment.yaml`
** `spec.selector.matchLabels[rhdh.redhat.com/app] = backstage-<cr-name>`
** `spec.template.metadata.labels[rhdh.redhat.com/app] = backstage-<cr-name>`
* `service.yaml`
** `spec.selector[rhdh.redhat.com/app] = backstage-<cr-name>`
* `db-statefulset.yaml`
** `spec.selector.matchLabels[rhdh.redhat.com/app] = backstage-psql-<cr-name>`
** `spec.template.metadata.labels[rhdh.redhat.com/app] = backstage-psql-<cr-name>`
* `db-service.yaml`
** `spec.selector[rhdh.redhat.com/app] = backstage-psql-<cr-name>`