:_mod-docs-content-type: PROCEDURE

[id="proc-mounting-additional-files-in-your-custom-configuration-using-rhdh-operator"]
= Mounting additional files in your custom configuration by using the {product} Operator

You can use the {product-very-short} Operator to mount extra files, such as a ConfigMap, Secret or PVCs, to the container in a preferred location.

The `mountPath` field specifies the location where a ConfigMap or Secret is mounted.
The behavior of the mount, whether it includes or excludes a `subPath`, depends on the specification of the `key` or `mountPath` fields.

* If `key` and `mountPath` are not specified: Each key or value is mounted as a `filename` or content with a `subPath`.
* If `key` is specified with or without `mountPath`: The specified key or value is mounted with a `subPath`.
* If only `mountPath` is specified: A directory containing all the keys or values is mounted without a `subPath`.

[NOTE]
====
* {ocp-short} does not automatically update a volume mounted with `subPath`. By default, the {product-very-short} Operator monitors these ConfigMaps or Secrets and refreshes the {product-very-short} Pod when changes occur.
* For security purposes, {product} does not give the Operator Service Account read access to Secrets. As a result, mounting files from Secrets without specifying both mountPath and key is not supported.
====

.Prerequisites
* You have developer permissions to access the {ocp-short} cluster containing your {product-short} instance using the {openshift-cli}.
* {installing-on-ocp-book-link}[Your {ocp-short} administrator has installed the {product} Operator in {ocp-short}].

.Procedure
. In {ocp-short}, create your ConfigMap, Secret, and PVCs with the following YAML codes:

* Example of `{my-extra-file-configmap}` ConfigMap:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: {my-extra-file-configmap}
data:
  file11.txt: |
    My file11 content
  file 12.txt: |
    My file12 content
----

* Example of {product} Secret:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: `_<my_product_secrets>_`
StringData:
  secret11.txt: |
    secret-content
----
+
where:

`apiVersion.metadata.name`:: Specifies your preferred {product-short} secret name, specifying the identifier for your secret configuration within {product-short}.

* Example of PVC:
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: _<pvc_claim>_
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
----

For more information, see xref:provisioning-your-custom-configuration[Provisioning and using your custom {product} configuration] and {configuring-book-link}#con-mounts-for-default-secret-pvc-mounts_provisioning-and-using-your-custom-configuration[Mounts for default Secrets and Persistent Volume Claims (PVCs)].

By default, files mount only to the backstage-backend container. If the containers field is not specified, the volume mounts only to the `backstage-backend` container. You can also specify other targets, including a list of containers by name (such as `dynamic-plugin-install` or `selectcustom` sidecars) or select all containers in the {backstage} Pod.