:_mod-docs-content-type: PROCEDURE

[id="provision-your-custom-configuration-for-getting-started_{context}"]
= Provision your custom {product} configuration

[role="_abstract"]
Provision custom config maps and secrets on {platform-long} to configure {product} before running the application.

include::snip-provision-configuration-tip.adoc[]

.Prerequisites
include::snip-provision-configuration-common-prerequisite.adoc[]
include::snip-provisioning-your-custom-configuration-prerequisites-in-setting-up-and-configuring-your-first-rhdh-instance-context.adoc[]

.Procedure
include::snip-provision-configuration-secrets-intro.adoc[]
+
--
.. Enter your custom logo.
+
[source,subs="+attributes,+quotes"]
----
BASE64_EMBEDDED_FULL_LOGO="data:image/svg+xml;base64,<base64_full_logo_data>"
BASE64_EMBEDDED_ICON_LOGO="data:image/svg+xml;base64,<base64_icon_logo_data>"
----

`BASE64_EMBEDDED_FULL_LOGO`::
Enter your logo for the expanded (pinned) sidebar as a base64 encoded SVG image.
+
To encode your logo in base64, run:
+
[source]
----
$ base64 -i logo.svg
----

`BASE64_EMBEDDED_ICON_LOGO`::
Enter your logo for the collapsed (unpinned) sidebar as a base64 encoded SVG image.

.. Enter the connection string to your Redis server that caches plugin assets.
+
[source]
----
REDIS_CONNECTION=rediss://user:pass@cache.example.com:6379
----

.. Enter your GitHub integration credentials:
+
[source,subs="+quotes"]
----
GITHUB_INTEGRATION_APP_ID=__<Enter_the_saved_App_ID>_
GITHUB_INTEGRATION_CLIENT_ID=_<Enter_the_saved_Client_ID>_
GITHUB_INTEGRATION_CLIENT_SECRET=_<Enter_the_saved_Client_Secret>_
GITHUB_INTEGRATION_HOST_DOMAIN=github.com
GITHUB_INTEGRATION_ORGANIZATION=_<Enter_your_github_organization_name>_
GITHUB_INTEGRATION_PRIVATE_KEY_FILE= _<Enter_the_saved_Private_key>_
----

.. Enter your PostgreSQL database secrets:
+
[source,subs="+quotes"]
----
POSTGRES_PASSWORD: <postgres-password>
POSTGRES_PORT: "<postgres-port>"
POSTGRES_USER: <postgres-username>
POSTGRES_HOST: <postgres-host>
PGSSLMODE: verify-full
NODE_EXTRA_CA_CERTS: /opt/app-root/src/postgres-crt.pem
----

.. {authentication-book-link}[Enter your authentication secrets].
--
include::snip-provision-configuration-appconfig-intro.adoc[]
+
--
.. For a production environment, start with the following setup:
+
.`{my-app-config-file}`
[source,yaml,subs="+attributes,+quotes"]
----
app:
  title: _<{product}>_
  branding:
    fullLogo: ${BASE64_EMBEDDED_FULL_LOGO}
    fullLogoWidth: 110px
    iconLogo: ${BASE64_EMBEDDED_ICON_LOGO}
backend:
  cache:
    store: redis
    connection: ${REDIS_CONNECTION}
techdocs:
  cache:
    ttl: 3600000
catalog:
  providers:
    _<enter_your_provider_configuration>_
integrations:
    _<enter_your_integrations_configuration>_
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: user:default/<your_policy_administrator_name>
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
----
Most fields use environment variables that you defined in secrets in the earlier step.
`app`::
`title`::: Enter your {product-short} instance display name, such as _<{product}>_.
`branding`::: Set your custom logo.
+
Optionally, customize the width of the branding logo by changing the value for the `fullLogoWidth` field. The following units are supported: integer, `px`, `em`, `rem`, percentage.
`backend`::
`cache`::: Enable the plugins assets cache.
`techdocs`::
`cache`::: Enable the `TechDocs` cache.
`catalog`::
`provider`:::
Enter your catalog provider configuration.
`integrations`::
Enter your repository discovery configuration.
[id='enabling-and-giving-access-to-rbac']
`permissions`:: Enable Role-based access control.
Enter your policy administrator name.

.. Additionally, {authentication-book-link}[provision users and enable authentication with your external identity provider].
--

include::snip-provision-configuration-dynamic-plugins-step.adoc[]

include::snip-provision-configuration-cluster-step.adoc[]

.Next steps
.. Provision your PostgreSQL TLS certificates to the `{my-product-database-secrets}` secret in the _<{my-product-namespace}>_ project.
+
[source,terminal,subs="+attributes,+quotes"]
----
$ oc create secret generic {my-product-secrets} --from-file=postgres-ca.pem --from-file=postgres-crt.pem --from-file=postgres-key.key --namespace={my-product-namespace}
----
