:_mod-docs-content-type: PROCEDURE

[id="preparing-your-external-services"]
= Preparing your external services

{product} relies on external services.
Prepare the following required external services:

PostgreSQL database::
{product-short} stores data in a PostgreSQL database.
Use an external database for resiliency and include it in your disaster recovery plan.

Redis cache::
For efficiency, {product-short} caches plugin and Techdocs assets when your provide a Redis cache server.

GitHub API access::
Provide credentials to a GitHub app to enable access to the GitHub API for repository discovery.

Connection to your identity provider::
Provide credentials to your identity provider to enable user provisioning and authentication.

.Procedure
* Get your external PostgreSQL database connection strings and certificates.
postgres-host::: Your PostgreSQL instance Domain Name System (DNS) or IP address.
postgres-port::: Your PostgreSQL instance port number, such as 5432.
postres-username::: The user name to connect to your PostgreSQL instance.
postgres-password::: The password to connect to your PostgreSQL instance.
postgres-ca.pem:::
postgres-key.key:::
postgres-crt.pem:::
For security, use TLS certificates to secure the connection to the database.

. Get your Redis cache server connection string, such as `rediss://user:pass@cache.example.com:6379`.
For security, consider using a `rediss` secure server connection.

. Create a GitHub App to allow {product-short} to access the GitHub API for repository.
Opt for a GitHub App instead of an OAuth app to use fine-grained permissions, gain more control over which repositories the application can access, and use short-lived tokens.

.. link:https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app[Register a GitHub App] with the following configuration:

GitHub App name::
Enter a unique name identifying your GitHub App, such as `integrating-with-rhdh-__<GUID>__`.

Homepage URL::
Enter your {product-short} URL: `pass:c,a,q[{my-product-url}]`.

Authorization callback URL::
Enter your {product-short} authentication backend URL: `pass:c,a,q[{my-product-url}/api/auth/github/handler/frame]`.

Webhook::
Clear "Active", as this is not needed for authentication and catalog providers.

App permissions::
Select permissions to define the level of access for the app.
Adapt permissions to your needs:

Reading software components:::

Contents::::
`Read-only`

Commit statuses::::
`Read-only`

Reading organization data:::

Members::::
`Read-only`

Publishing software templates:::
Set permissions if you intend to use the same GitHub App for software templates.

Administration::::
`Read & write` (for creating repositories)

Contents::::
`Read & write`

Metadata::::
`Read-only`

Pull requests::::
`Read & write`

Issues::::
`Read & write`

Workflows::::
`Read & write` (if templates include GitHub workflows)

Variables::::
`Read & write` (if templates include GitHub Action Repository Variables)

Secrets::::
`Read & write` (if templates include GitHub Action Repository Secrets)

Environments::::
`Read & write` (if templates include GitHub Environments)

Organization permissions::
Members:::
`Read-only`

Where can this GitHub App be installed?::
Select `Only on this account`.

.. In the *General* -> *Clients secrets* section, click *Generate a new client secret*.

.. In the *General* -> *Private keys* section, click *Generate a private key*.

.. In the *Install App* tab, choose an account to install your GitHub App on.

.. Save the following values for the next step:

* **App ID**
* **Client ID**
* **Client secret**
* **Private key**
