
:_mod-docs-content-type: PROCEDURE

[id="proc-injecting-custom-files-and-environment-variables-into-backstage-containers"]
= Injecting custom files and environment variables into {backstage} containers

You must use the `spec.application` path to configure the injection of custom files and environment variables into your {backstage} Pod containers. This ensures necessary configurations, credentials, and dependencies (such as certificates) are available at runtime.

By default, resources inject into the **`backstage-backend`** container. You can also specify other targets, including a list of containers by name (such as `dynamic-plugin-install` or custom sidecars) or opt to in all containers in the {backstage} Pod.

.Procedure
. To configure resource injection, use the following fields under `spec.application`:

.. File Injection (`spec.application.extraFiles`): Define external file resources to be mounted as volumes from pre-created ConfigMaps, Secrets, or PVCs.
** **File Sources:**
*** `configMaps`:: Sources file volumes from Kubernetes ConfigMaps.
*** `secrets`:: Sources file volumes from Kubernetes Secrets.
*** `pvcs`:: Sources volume claims from Kubernetes Persistent Volume Claims (PVCs).

.. Environment Variable Injection (`spec.application.extraEnvs`): Define the environment variables to be injected into the targeted containers.
** **Environment Sources:**
*** `configMaps`:: Injects environment variables sourced from Kubernetes ConfigMaps.
*** `secrets`:: Injects environment variables sourced from Kubernetes Secrets.
*** `envs`:: Injects hardcoded environment variables defined directly in the manifest.