
:_mod-docs-content-type: PROCEDURE

[id="proc-injecting-custom-files-and-environment-variables-into-backstage-containers"]
= Injecting extra files and environment variables into {backstage} containers

By default, files mount only to the `backstage-backend` container. If the `containers` field is not specified, the volume mounts to the `backstage-backend` container only. You can also specify other targets, including a list of containers by name (such as `dynamic-plugin-install` or custom sidecars) or opt to in all containers in the {backstage} Pod.

. To mount files and injecting environment variables into different container targets, apply the configuration to your `{product-custom-resource-type} custom resource (CR)` as shown in the following code:
+
[source,yaml]
----
spec:
  application:
    # Default mount path for extraFiles without a specific mountPath
    extraFiles:
      mountPath: /my/path 
      configMaps:
        - name: cm1 # Mounts all entries from cm1 to /my/path/
        - name: cm2
          key: file21.txt # Mounts only 'file21.txt'
          containers:
            - "*" # Targets all containers
        - name: cm3
          mountPath: /my/cm3/path # Mounts all entries as a directory
          containers:
            - backstage-backend
            - install-dynamic-plugins
      secrets:
        - name: secret1
          key: file3.txt # Must specify key for security
          containers:
            - install-dynamic-plugins
        - name: secret2
          mountPath: /my/secret2/path # Mounts all secret entries as a directory
      pvcs:
        - name: myclaim1 # Mounts to /my/path/myclaim1 (using default mountPath)
        - name: myclaim2
          mountPath: /vol/my/claim # Overrides default mountPath

    extraEnvs:
      configMaps:
        - name: cm1
          key: ENV_VAR1
          containers:
            - "*" # Injects into all containers
      secrets:
        - name: secret1 # Injects all keys from secret1
      envs:
        - name: MY_VAR
          value: "my-value"
          containers:
           - install-dynamic-plugins # Targets only this container
----

The following explicit options are supported:

* No or empty field: Mounts only to the `backstage-backend` container.
* `*` (asterisk) as the first and only array element: Mounts to all containers.
* Explicit container names (for example, `install-dynamic-plugins`): Mounts only to the listed containers.

.Verification

The files are mounted with the following paths and container targets:

[cols="1,2,3,2", options="header"]
|===
| Resource | Target type | Path(s) or name(s) | Container(s)

| ConfigMap (`cm1`)
| File
| `/my/path/file11.txt`, `/my/path/file12.txt`
| `backstage-backend`

| ConfigMap (`cm2`)
| File
| `/my/path/file21.txt`
| All

| ConfigMap (`cm3`)
| Directory
| `/my/cm3/path/`
| `backstage-backend`, `install-dynamic-plugins`

| Secret (`secret1`)
| File
| `/my/path/file3.txt`
| `install-dynamic-plugins`

| Secret (`secret2`)
| Directory
| `/my/secret2/path/`
| `backstage-backend`

| PVC (`myclaim1`)
| Directory
| `/my/path/myclaim1`
| `backstage-backend`

| ConfigMap (`cm1`)
| Env Var
| `ENV_VAR1`
| All

| Secret (`secret1`)
| Env Var
| `ENV_VAR3`, `ENV_VAR4`
| `backstage-backend`

| CRD (`envs`)
| Env Var
| `MY_VAR = my-value`
| `install-dynamic-plugins`
|===