.. For a production environment, start with the following setup:
+
.`{my-app-config-file}`
[source,yaml,subs="+attributes,+quotes"]
----
app:
  title: _<{product}>_
  branding:
    fullLogo: ${BASE64_EMBEDDED_FULL_LOGO}
    fullLogoWidth: 110px
    iconLogo: ${BASE64_EMBEDDED_ICON_LOGO}
backend:
  cache:
    store: redis
    connection: ${REDIS_CONNECTION}
techdocs:
  cache:
    ttl: 3600000
catalog:
  providers:
    github:
      providerId:
        organization: "${GITHUB_INTEGRATION_ORGANIZATION}"
        schedule:
          frequency:
            minutes: 30
          initialDelay:
            seconds: 15
          timeout:
            minutes: 15
integrations:
  github:
    - host: ${GITHUB_INTEGRATION_HOST_DOMAIN}
      apps:
        - appId: ${GITHUB_INTEGRATION_APP_ID}
          clientId: ${GITHUB_INTEGRATION_CLIENT_ID}
          clientSecret: ${GITHUB_INTEGRATION_CLIENT_SECRET}
          privateKey: |
            ${GITHUB_INTEGRATION_PRIVATE_KEY_FILE}
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: user:default/<your_policy_administrator_name>
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
----
Most fields use environment variables that you defined in secrets in the previous step.
`app`::
`title`::: Enter your Developer Hub instance display name, such as _<{product}>_.
`branding`::: Set your custom logo.
+
Optionally, customize the width of the branding logo by changing value for the `fullLogoWidth` field. The following units are supported: integer, px, em, rem, percentage.
`backend`::
`cache`::: Enable the plugins assets cache.
`techdocs`::
`cache`::: Enable the Techdocs cache.
`catalog`::
`provider`:::
`github`:::: Enable GitHub repository discovery.
`integrations`::
`github`::: Enable GitHub repository discovery.
[id='enabling-and-giving-access-to-rbac']
`permissions`:: Enable Role-based access control.
Enter your policy administrator name.

.. Additionally, link:{authentication-book-url}[provision users and enabling authentication with your external identity provider].
