.. For a production environment, start with the following setup:
+
.`{my-app-config-file}`
[source,yaml,subs="+attributes,+quotes"]
----
app:
  title: _<{product}>_
  branding:
    fullLogo: ${BASE64_EMBEDDED_FULL_LOGO}
    fullLogoWidth: 110px
    iconLogo: ${BASE64_EMBEDDED_ICON_LOGO}
backend:
  cache:
    store: redis
    connection: ${REDIS_CONNECTION}
techdocs:
  cache:
    ttl: 3600000
catalog:
  providers:
    _<enter_your_provider_configuration>_
integrations:
    _<enter_your_integrations_configuration>_
permission:
  enabled: true
  rbac:
    admin:
      users:
        - name: user:default/<your_policy_administrator_name>
    pluginsWithPermission:
      - catalog
      - scaffolder
      - permission
----
Most fields use environment variables that you defined in secrets in the previous step.
`app`::
`title`::: Enter your Developer Hub instance display name, such as _<{product}>_.
`branding`::: Set your custom logo.
+
Optionally, customize the width of the branding logo by changing value for the `fullLogoWidth` field. The following units are supported: integer, px, em, rem, percentage.
`backend`::
`cache`::: Enable the plugins assets cache.
`techdocs`::
`cache`::: Enable the Techdocs cache.
`catalog`::
`provider`:::
Enter your catalog provider configuration.
`integrations`::
Enter your repository discovery configuration.
[id='enabling-and-giving-access-to-rbac']
`permissions`:: Enable Role-based access control.
Enter your policy administrator name.

.. Additionally, link:{authentication-book-url}[provision users and enable authentication with your external identity provider].
