// Module included in the following assemblies:
// assembly-audit-log.adoc
[id="con-audit-log-config_{context}"]
= Configuring audit logs for {product-short} on {ocp-short}

Use the {ocp-short} web console to configure the following {ocp-short} logging components to use audit logging for {product-short}:

Logging deployment::
Configure the logging environment, including both the CPU and memory limits for each logging component. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/logging/index#cluster-logging-memory[{ocp-brand-name} - Configuring your Logging deployment].

Logging collector::
Configure the `spec.collection` stanza in the `ClusterLogging` custom resource (CR) to use a supported modification to the log collector and collect logs from `STDOUT`. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/logging/index#cluster-logging-collector[{ocp-brand-name} - Configuring the logging collector].

Log forwarding::
Send logs to specific endpoints inside and outside your {ocp-short} cluster by specifying a combination of outputs and pipelines in a `ClusterLogForwarder` CR. For more information, see link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/logging/index#cluster-logging-json-log-forwarding_cluster-logging-enabling-json-logging[{ocp-brand-name} - Enabling JSON log forwarding] and link:https://docs.redhat.com/en/documentation/openshift_container_platform/4.16/html-single/logging/index#configuring-log-forwarding[{ocp-brand-name} - Configuring log forwarding].
