:_mod-docs-content-type: PROCEDURE

[id="view-live-logs-with-azure-kubernetes-service-aks_{context}"]
= View live logs with {aks-name} ({aks-short})

[role="_abstract"]
Access live data logs generated by Kubernetes objects for your {product-short} instance on {aks-short}.

.Prerequisites

* You have deployed {product-short} on {aks-short}.

For more information, see {installing-on-aks-book-link}#assembly-install-rhdh-aks[{installing-on-aks-book-title}].

.Procedure

. Navigate to the {azure-short} Portal.
. Search for the resource group `<your-ResourceGroup>` and locate your {aks-short} cluster `<your-Cluster>`.
. Select *Kubernetes resources -> Workloads* from the menu.
. Select the `<your-rhdh-cr>-developer-hub` (in case of Helm Chart installation) or `<your-rhdh-cr>-backstage` (in case of Operator-backed installation) deployment.
. Click *Live Logs* in the left menu.
. Select the pod.
+
NOTE: There must be only single pod.

.Verification

* Live log data is collected and displayed.
