[id="proc-enabling-telemetry-using-operator_{context}"]
= Enabling telemetry data collection using the Operator

You can enable the telemetry data collection feature by using the Operator.

.Prerequisites

* You have logged in as an administrator in the {ocp-short} web console.
* You have installed {product} on {ocp-short} using the Operator.

.Procedure

. Perform one of the following steps:
+
* If you have created the `dynamic-plugins-rhdh` ConfigMap file and not configured the `analytics-provider-segment` plugin, add the plugin to the list of plugins and set its `plugins.disabled` parameter to `false`.
+
* If you have created the `dynamic-plugins-rhdh` ConfigMap file and configured the `analytics-provider-segment` plugin, search the plugin in the list of plugins and set its `plugins.disabled` parameter to `false`.
+
* If you have not created the ConfigMap file, create it with the following YAML code:
+
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-analytics-provider-segment'
        disabled: false
----

. Set the value of the `dynamicPluginsConfigMapName` parameter to the name of the ConfigMap file in your `Backstage` custom resource:
+
[source,yaml]
----
# ...
spec:
  application:
    dynamicPluginsConfigMapName: dynamic-plugins-rhdh
# ...
----

. Save the configuration changes.

