:_mod-docs-content-type: PROCEDURE

[id="configuring-the-application-log-level-by-using-the-operator_{context}"]
= Configure the log level with the {product} Operator

Using the {product} Operator, you can configure the application log level through the environment variable `LOG_LEVEL`. This sets the minimum severity level of events for your application to log.

.Prerequisites
* Access to the {backstage} custom resource (CR) used to deploy the application.

.Procedure
* Include the environment variable `LOG_LEVEL` in your {backstage} CR. For example:
+
[source,yaml]
----
spec:
  # Other fields omitted
  application:
    extraEnvs:
      envs:
        - name: LOG_LEVEL
          value: debug
----
You can use any of the values in the following table.

[cols="15%,85%", options="header"]
.`LOG_LEVEL` values in order of increasing severity
|===
|Value
|Description

|`debug`
|Detailed information, typically useful only when troubleshooting.

|`info`
|General information about the operation of the application. This is the default level.

|`warn`
|Potential issues or situations that might require attention.

|`error`
|Non-fatal errors that occurred during the operation.

|`critical`
|Fatal errors that must be addressed immediately to restore functionality.
|===




