[id='proc-view-logs-aks_{context}']
= Viewing logs with Azure Kubernetes Services (AKS)

You can access live data logs generated by Kubernetes objects and collect log data in Container Insights within AKS.

.Prerequisites

* You have deployed {product-short} on {aks-short}.

For more information, see xref:{installing-on-aks-book-url}#assembly-install-rhdh-aks[{installing-on-aks-book-title}].

.Procedure

View live logs from your {product-short} instance::
+
--
. Navigate to the Azure Portal.
. Search for the resource group `<your-ResourceGroup>` and locate your AKS cluster `<your-Cluster>`.
. Select *Kubernetes resources -> Workloads* from the menu.
. Select the `<your-rhdh-cr>-developer-hub` (in case of Helm Chart installation) or `<your-rhdh-cr>-backstage` (in case of Operator-backed installation) deployment.
. Click *Live Logs* in the left menu.
. Select the pod.
+
NOTE: There must be only single pod.

Live log data is collected and displayed.
--

View real-time log data from the Container Engine::
+
--
. Navigate to the Azure Portal.
. Search for the resource group `<your-ResourceGroup>` and locate your AKS cluster `<your-Cluster>`.
. Select *Monitoring* -> *Insights* from the menu.
. Go to the *Containers* tab.
. Find the backend-backstage container and click it to view real-time log data as it's generated by the Container Engine.
--
