:_mod-docs-content-type: PROCEDURE

[id="proc-admin-enabling-metrics-ocp-operator_{context}"]
= Enabling metrics monitoring in a {product} Operator installation on an {ocp-short} cluster

You can enable and view metrics for an Operator-installed {product} instance from the {ocp-short} web console. Metrics are exposed through an HTTP service endpoint under the `/metrics` canonical name.

By setting the `spec.monitoring.enabled` field to `true` in your {product} custom resource (CR), you instruct the Operator to automatically create and manage the necessary `ServiceMonitor` to scrape metrics from the service endpoint.

.Prerequisites

* Your {ocp-short} cluster has {ocp-docs-link}/html-single/monitoring/index#enabling-monitoring-for-user-defined-projects[monitoring for user-defined projects] enabled.
* You have installed {product} on {ocp-short} using the {product} Operator.
* You have installed the {openshift-cli}.

.Procedure

. Use the *OpenShift CLI* (`oc`) to edit your existing {product} CR.
+
[source,bash]
----
oc edit Backstage <instance-name>
----
. In the CR, locate the `spec` field and add the `monitoring` configuration block.
+
[source,yaml]
----
spec:
  monitoring:
    enabled: true
----
. Save the {product-very-short} CR. The {product-very-short} Operator detects the configuration and automatically creates the corresponding `ServiceMonitor` custom resource (CR).
+
[NOTE]
====
The Operator automatically configures the `ServiceMonitor` with the correct labels (`app.kubernetes.io/instance` and `app.kubernetes.io/name`) that match your Backstage CR. The `ServiceMonitor` will be named `metrics-<cr-name>`. No additional label configuration is required.
====

.Verification

. From the {ocp-short} web console, select the *Observe* view.
. Click the *Metrics* tab to view metrics for {product} pods.
. From the {ocp-short} web console, click **Project > Services** and verify the labels for `backstage-developer-hub`.
