// Module included in the following assemblies:
// assembly-audit-log.adoc

:_mod-docs-content-type: REFERENCE
[id="ref-audit-log-scaffolder-events.adoc_{context}"]
= Scaffolder events

{product-short} audit logs can include the following scaffolder events:

`ScaffolderParameterSchemaFetch`:: Tracks `GET` requests to the `/v2/templates/:namespace/:kind/:name/parameter-schema` endpoint which return template parameter schemas
`ScaffolderInstalledActionsFetch`:: Tracks `GET` requests to the `/v2/actions` endpoint which grabs the list of installed actions
`ScaffolderTaskCreation`:: Tracks `POST` requests to the `/v2/tasks` endpoint which creates tasks that the scaffolder executes
`ScaffolderTaskListFetch`:: Tracks `GET` requests to the `/v2/tasks` endpoint which fetches details of all tasks in the scaffolder.
`ScaffolderTaskFetch`:: Tracks `GET` requests to the `/v2/tasks/:taskId` endpoint which fetches details of a specified task `:taskId`
`ScaffolderTaskCancellation`:: Tracks `POST` requests to the `/v2/tasks/:taskId/cancel` endpoint which cancels a running task
`ScaffolderTaskStream`:: Tracks `GET` requests to the `/v2/tasks/:taskId/eventstream` endpoint which returns an event stream of the task logs of task `:taskId`
`ScaffolderTaskEventFetch`:: Tracks `GET` requests to the `/v2/tasks/:taskId/events` endpoint which returns a snapshot of the task logs of task `:taskId`
`ScaffolderTaskDryRun`:: Tracks `POST` requests to the `/v2/dry-run` endpoint which creates a dry-run task. All audit logs for events associated with dry runs have the `meta.isDryLog` flag set to `true`.
`ScaffolderStaleTaskCancellation`:: Tracks automated cancellation of stale tasks
`ScaffolderTaskExecution`:: Tracks the `initiation` and `completion` of a real scaffolder task execution (will not occur during dry runs)
`ScaffolderTaskStepExecution`:: Tracks `initiation` and `completion` of a scaffolder task step execution
`ScaffolderTaskStepSkip`:: Tracks steps skipped due to `if` conditionals not being met
`ScaffolderTaskStepIteration`:: Tracks the step execution of each iteration of a task step that contains the `each` field.
