:_mod-docs-content-type: PROCEDURE
[id="proc-customizing-rhdh-metadata-card_{context}"]
= Customizing the {product-very-short} Metadata card on the Settings page

The *Settings* page in {product} contains a *{product-very-short} Metadata* card. By default, the *{product-very-short} Metadata* card shows the *{product-very-short} Version* and *Backstage Version* of your {product} instance. When you click the *Show more* icon, the card expands to also show *Upstream*, *Midstream*, and *Build Time* information.

You can override the default to show custom build information about your {product} instance in the card. You can customize the card title as well as the card contents.

.Procedure

To customize the *{product-very-short} Metadata* card, complete the following step:

* In your app-config.yaml file, configure the `buildinfo` field. For example:
+
[source,yaml,subs=+attributes,+quotes]
----
buildInfo:
  title: _<build_info_card_title>_
  card:
    TechDocs builder: '_<techdocs_builder>_'
    Authentication provider: '_<authentication_provider>_'
    RBAC: disabled
----
+
where

_<build_info_card_title>_ :: Specifies the title that you want to display in the *{product-very-short} Build info* card.
_<techdocs_builder>_ :: Specifies whether to generate and publish the docs or to only fetch the docs when using the default build strategy. Example values are `local` or `external`.
_<authentication_provider>_ :: Specifies the authentication provider that you want to use. Example values are `GitHub` or `GitLab`.
+
[NOTE]
====
If you want to generate and publish the docs when using the default build strategy, set the `techdocs.builder` field to `local` in your app-config.yaml file. If you only want to fetch the docs without generating and publishing them, set the `techdocs.builder` field to `external`.
====

.Result
The *Settings* page displays a card with a custom title and custom build information about your {product} instance.