[id='customizing-the-backend-secret']
= Customizing {product} backend secret

The default {product} configuration defines the {product-short} backend secret for service to service authentication.

You can define your custom {product-short} backend secret.

.Prerequisites
* You link:{configuring-book-url}[added a custom {product-short} application configuration], and have sufficient permissions to modify it.

.Procedure

. To define the {product-short} backend secret,
add to your custom `{my-product-secrets}.txt` file the `BACKEND_SECRET` environment variable with a base64 encoded string.
Use a unique value for each {product-short} instance.
+
[source,terminal,subs="+attributes"]
----
$ echo > {my-product-secrets}.txt "BACKEND_SECRET=$(node -p 'require("crypto").randomBytes(24).toString("base64")')"
----
+
.`{my-product-secrets}.txt` example
----
BACKEND_SECRET=3E2/rIPuZNFCtYHoxVP8wjriffnN1q/z
----

. Add your backend secret to  your custom `{my-app-config-file}` file.
+
.`{my-app-config-file}` excerpt defining the backend secret
[source,yaml,subs="+attributes,+quotes"]
----
backend:
  auth:
    externalAccess:
      - type: legacy
        options:
          subject: legacy-default-config
          secret: "${BACKEND_SECRET}"
----

