:_mod-docs-content-type: PROCEDURE
[id="proc-customizing-rhdh-metadata-card_{context}"]
= Customizing the {product-very-short} Metadata card on the Settings page

The *Settings* page in {product} contains a *{product-very-short} Metadata* card. By default, the *{product-very-short} Metadata* card shows the *{product-very-short} Version* and *Backstage Version* of your {product} instance. When you click the *Show more* icon, the card expands to also show *Upstream*, *Midstream*, and *Build Time* information.

You can override the default to show custom build information about your {product} instance in the card. You can customize the card title as well as the card contents.

.Procedure

To customize the *{product-very-short} Metadata* card, complete the following step:

* In your app-config.yaml file, configure the `buildinfo` field. For example:
+
[source,yaml,subs=+attributes,+quotes]
----
buildInfo:
  title: <build_info_card_title>
  card:
    TechDocs builder: '<techdocs_builder>'
    Authentication provider: '_<authentication_provider>_'
    RBAC: disabled
----
+
where

_<build_info_card_title>_ :: Specifies the title that you want to display in the *{product-very-short} Build info* card.
_<authentication_provider>_ :: Specifies the authentication provider that you want to use, for example, `GitHub` or `GitLab`.
_<techdocs_builder>_ :: Specifies the TechDocs builder that you want to use, for example, `local`.

.Result
The *Settings* page displays a card with a custom title and custom build information about your {product} instance.