[id='con-rhdh-overview_{context}']
= Overview of {product}

{product} ({product-short}) serves as an open developer platform designed for building developer portals. Using {product-short}, the engineering teams can access a unified platform that streamlines the development process and provides a variety of tools and resources to build high-quality software efficiently.

The goal of {product-short} is to address the difficulties associated with creating and sustaining developer portals using:

* A centralized dashboard to view all available developer tools and resources to increase productivity
* Self-service capabilities, along with guardrails, for cloud-native application development that complies with enterprise-class best practices
* Proper security and governance for all developers across the enterprise

The {product} simplifies decision-making by providing a developer experience that presents a selection of internally approved tools, programming languages, and various developer resources within a self-managed portal. This approach contributes to the acceleration of application development and the maintenance of code quality, all while fostering innovation.
