[id='con-rbac-config-permission-policies-external-file_{context}']
= Configuration of permission policies defined in an external file

You can follow this approach of configuring the permission policies before starting the {product}. If permission policies are defined in an external file, then you can import the same file in the {product-short}. The permission policies need to be defined in Casbin rules format. For information about the Casbin rules format, see https://casbin.org/docs/category/the-basics[Basics of Casbin rules].

The following is an example of permission policies configuration:

`p, role:default/guests, catalog-entity, read, deny`

`p, role:default/guests, catalog.entity.create, create, deny`

`g, user:default/<USER_TO_ROLE>, role:default/guests`

If a defined permission does not contain an action associated with it, then add use as a policy. See the following example:

`p, role:default/guests, kubernetes.proxy, use, deny`

You can define the file path in the `app-config.yaml` file:

[source,yaml]
----
permission:
  enabled: true
  rbac:
    policies-csv-file: /some/path/rbac-policy.csv
----