[id='proc-customize-rhdh-tech-radar-page_{context}']
= Customizing the Tech Radar page in {product}

In {product}, the Tech Radar page is provided by the `tech-radar` dynamic plugin, which is disabled by default. For information about enabling dynamic plugins in {product} see link:{configuring-dynamic-plugins-url}[{configuring-dynamic-plugins-title}].

In {product}, you can configure Learning Paths by passing the data into the `app-config.yaml` file as a proxy. The base Tech Radar URL must include the `/developer-hub/tech-radar` proxy.

[NOTE]
====
Due to the use of overlapping `pathRewrites` for both the `tech-radar` and `homepage` quick access proxies, you must create the `tech-radar` configuration (`^api/proxy/developer-hub/tech-radar`) before you create the `homepage` configuration (`^/api/proxy/developer-hub`).

For more information about customizing the Home page in {product}, see xref:customizing-the-home-page[Customizing the Home page in {product}].
====

You can provide data to the Tech Radar page from the following sources:

* JSON files hosted on GitHub or GitLab.
* A dedicated service that provides the Tech Radar data in JSON format using an API.

== Using hosted JSON files to provide data to the Tech Radar page

.Prerequisites

* You have installed {product} by using either the Operator or Helm chart. For more information, see link:{installing-on-ocp-book-url}[{installing-on-ocp-book-title}].
* You have specified the data sources for the Tech Radar plugin in the `integrations` section of the `app-config.yaml` file. For example, to configure GitHub as an integration, see link:{authentication-book-url}#authenticating-with-github[Authenticating with GitHub].

.Procedure

To access the data from the JSON files, complete the following step:

. Enable the `./dynamic-plugins/dist/backstage-community-plugin-tech-radar` and `/dynamic-plugins/dist/backstage-community-plugin-tech-radar-backend-dynamic` plugins.
. Add the following code to the `app-config.yaml` file:
+
[source,yaml]
----
techRadar:
    url: ${TECH_RADAR_DATA_URL} <1>
----
<1>  `TECH_RADAR_DATA_URL` is the URL from which the JSON data is loaded.

== Using a dedicated service to provide data to the Tech Radar page

When using a dedicated service, you can do the following:

* Use the same service to provide the data to all configurable {product-short} pages or use a different service for each page.
* Use the https://github.com/redhat-developer/red-hat-developer-hub-customization-provider[`red-hat-developer-hub-customization-provider`] as an example service, which provides data for both the Home and Tech Radar pages. The `red-hat-developer-hub-customization-provider` service provides the same data as default {product-short} data. You can fork the `red-hat-developer-hub-customization-provider` service repository from GitHub and modify it with your own data, if required.
* Deploy the `red-hat-developer-hub-customization-provider` service and the {product-short} Helm chart on the same cluster.

.Prerequisites

* You have installed the {product} using Helm Chart.
For more information, see xref:{installing-on-ocp-book-url}#assembly-install-rhdh-ocp-helm[{installing-on-ocp-book-title} with the Helm chart].

.Procedure

To use a separate service to provide the Tech Radar data, complete the following steps:

. Add the dedicated service as an allowed host by adding the following code to the `app-config.yaml` file:
+
[source,yaml]
----
backend:
   reading:
        allow:
          - host: 'hostname'
----
. Add the following to the `app-config.yaml` file:
+
[source,yaml]
----
techRadar:
    url: ${TECH_RADAR_DATA_URL} <1>
----
<1> `TECH_RADAR_DATA_URL` is the URL from which the JSON data is loaded.
