[id='proc-customizing-rhdh-tech-radar-page-by-using-a-customization-service_{context}']
= Customizing the Tech Radar page by using a customization service

For advanced scenarios, you can host your {product} customization service to provide data to all configurable {product-short} pages, such as the Tech Radar page.
You can even use a different service for each page.

.Prerequisites
* You have specified the data sources for the Tech Radar plugin in the `integrations` section of the `{my-app-config-file}` file.
For example, to configure GitHub as an integration, see link:{authentication-book-url}#authenticating-with-github[Authenticating with GitHub].

* You have enabled the `./dynamic-plugins/dist/backstage-community-plugin-tech-radar` and `/dynamic-plugins/dist/backstage-community-plugin-tech-radar-backend-dynamic` plugins.

.Procedure
. Deploy your {product-short} customization service on the same {ocp-short} cluster as your {product-short} instance.
You can find an example at link:https://github.com/redhat-developer/red-hat-developer-hub-customization-provider[`red-hat-developer-hub-customization-provider`], that provides the same data as default {product-short} data.
The customization service provides a Tech Radar data URL such as: `pass:c,a,q[http://_<rhdh-customization-provider>_/tech-radar]`.

. Add the dedicated service as an allowed host by adding the following code to the `{my-app-config-file}` file:
+
[source,yaml,subs='+quotes']
----
backend:
   reading:
        allow:
          - host: '_<rhdh_customization_provider_base_url>_'
----
`_<rhdh_customization_provider_base_url>_`:: Enter the base URL of your Tech Radar data URL, such as: `pass:c,a,q[_<rhdh-customization-provider>_]`.

. Add the following to the `{my-app-config-file}` file:
+
[source,yaml,subs='+quotes']
----
techRadar:
    url: _<tech_radar_data_url>_
----

`_<tech_radar_data_url>_`:: Enter your Tech Radar data URL, such as: `pass:c,a,q[http://_<rhdh-customization-provider>_/tech-radar]`.
