:_mod-docs-content-type: CONCEPT

[id="con-default-base-urls"]
= Default base URLs

The Operator automatically sets the base URLs for your {product-custom-resource-type} application in the default `app-config` ConfigMap known as `backstage-appconfig-{CR_name}`. The Operator does so based on your Route parameters and the OpenShift cluster ingress domain.

The Operator follows these rules to set the base URLs for your application:

* If the cluster is not OpenShift, the Operator makes no changes.
* If you explicitly set the `spec.application.route.enabled` field in your Custom Resource (CR) to `false`, no changes are made.
* If you define `spec.application.route.host` in the {product-custom-resource-type} CR, the base URLs are set to `https://<spec.application.route.host>`.
* If you specify the `spec.application.route.subdomain` the {product-custom-resource-type} CR, the base URLs are set to `https://<spec.application.route.subdomain>.<cluster_ingress_domain>`.
* If no custom host or subdomain is provided, the Operator sets the base URLs to `https://backstage-{cr_name}-<namespace>.<cluster_ingress_domain>`, which is the default domain for the created _Route_ resource.

The Operator updates the following base URLs in the default `app-config` ConfigMap:

* `app.baseUrl`
* `backend.baseUrl`
* `backend.cors.origin`

[NOTE]
====
You can perform these actions on a best-effort basis and only on OpenShift. During an error or on non-OpenShift clusters, you can still override these defaults by providing a custom `app-config` ConfigMap.
====

