[id="proc-configuring-pvc-secret-mounting_{context}"]
= Configuring Persistent Volume Claim (PVC) mounting

You can configure which containers the Persistent Volume Claim (PVC) mounts to by adding `rhdh.redhat.com/containers` to your configuration. You can configure multiple secrets by using annotations to specify mount paths for each secret and target specific containers where the secrets should mount. Adding annotations ensures flexible storage and secrets management across different containers. The `default-config/deployment.yaml` defines the dynamic plugins directory, as shown in the following example:

[source,yaml]
----
- ephemeral:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
  name: dynamic-plugins-root
----

.Prerequisites

* You have sufficient administrative permission.

.Procedure

To configure which container the PVC mounts to, add `rhdh.redhat.com/mount-path` annotation to your configuration as shown in the following examples:

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: _<my_claim>_
  annotations:
    rhdh.redhat.com/mount-path: /mount/path/from/annotation
----
where:

`rhdh.redhat.com/mount-path`:: Specifies which container the PVC mounts to.
<my_claim>:: Specifies the PVC to mount.
+
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: _<my_secret>_
  annotations:
    rhdh.redhat.com/mount-path: /mount/path/from/annotation
----
where:

<my_secret>:: Specifies the Secret name.

To configure which container the PVC mounts to, add `rhdh.redhat.com/containers` to your configuration. You can configure multiple secrets within a single YAML file as shown in the following example:

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: _<my_secret>_
  annotations:
    rhdh.redhat.com/containers: `*`
----

[IMPORTANT]
====
Set it to `*` to mount it to all containers in the deployment.
====

You can use commas to separate the list of containers to mount as shown in the following example:

[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
  annotations:
    rhdh.redhat.com/containers: "init-dynamic-plugins,backstage-backend"
----