:_mod-docs-content-type: PROCEDURE
[id="proc-configure-mount-path-secrets-pvcs_{context}"]
= Configuring mount paths for Secrets and PVCs

By default, the mount path is the {product-short} container's working directory. If you do not define the mount path, it defaults to `/opt/app-root/src`.

You can add the `rhdh.redhat.com/mount-path` annotation to specify a custom path.

.Procedure

. To specify a PVC mount path, add the `rhdh.redhat.com/mount-path` annotation to your configuration file as shown in the following example:
+
.Example specifying where the PVC mounts
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: _<my_claim>_
  annotations:
    rhdh.redhat.com/mount-path: /mount/path/from/annotation
----
where:

`rhdh.redhat.com/mount-path`:: Specifies which mount path the PVC mounts to (in this case, `/mount/path/from/annotation` directory).
<my_claim>:: Specifies the PVC to mount.

. To specify a Secret mount path, add the `rhdh.redhat.com/mount-path` annotation to your configuration file as shown in the following example:
+
.Example specifying where the Secret mounts
[source,yaml,subs="+attributes,+quotes"]
----
apiVersion: v1
kind: Secret
metadata:
  name: _<my_secret>_
  annotations:
    rhdh.redhat.com/mount-path: /mount/path/from/annotation
----
where:

<my_secret>:: Specifies the Secret name.