[id='proc-install-operator_{context}']

= Installing the {product} Operator

As an administrator, you can install the {product} Operator. Authorized users can use the Operator to install {product} on the following platforms:

* {ocp-brand-name} ({ocp-very-short})
* {eks-brand-name} ({eks-short})
* {aks-brand-name} ({aks-short})

{ocp-very-short} is currently supported from version {ocp-version-min} to {ocp-version}. See also the link:https://access.redhat.com/support/policy/updates/developerhub[Red Hat Developer Hub Life Cycle].

Containers are available for the following CPU architectures:

* AMD64 and Intel 64 (x86_64)

.Prerequisites

* You are logged in as an administrator on the {ocp-short} web console.
* You have configured the appropriate roles and permissions within your project to create an application. For more information, see the link:https://docs.openshift.com/container-platform/{ocp-version}/applications/index.html[Red Hat OpenShift documentation on Building applications].

.Procedure

. In the *Administrator* perspective of the {ocp-short} web console, navigate to *Operators* > *OperatorHub*.

. In the *Filter by keyword* box, enter {product-short} and click the *{product}* Operator card.

. On the *{product} Operator* page, click *Install*.

. On the *Install Operator* page, click *Install*.

.Verification
To view the installed {product} Operator, click *View operator*.

[NOTE]
For enhanced security, deploy the {product} Operator in a dedicated default namespace such as `rhdh-operator`. The cluster administrator can restrict other users' access to the operator resources through role bindings or cluster role bindings. You can choose to deploy the operator in the `openshift-operators` namespace instead, however, the {product} operator shares the namespace with other operators, and therefore any users who can create workloads in that namespace can get their privileges escalated from all operators' service accounts.

.Additional resources

* For more information about installing {product-short}, see xref:proc-install-rhdh-ocp-operator_admin-rhdh[Deploying {product} on {ocp-short} using the Operator].
* For more information about installing Operators, see link:https://docs.openshift.com/container-platform/{ocp-version}/operators/admin/olm-adding-operators-to-cluster.html#olm-installing-from-operatorhub-using-web-console_olm-adding-operators-to-a-cluster[Installing from OperatorHub using the web console].
