[id='proc-rbac-ui-create-role_{context}']
= Creating a role in the {product} Web UI

You can create a role in the {product} using the Web UI.

.Prerequisites
* You have an administrator role in the {product-short}.
* You have installed the `@janus-idp/backstage-plugin-rbac` plugin in {product-short}. For more information, see xref:rhdh-installing-dynamic-plugins_admin-rhdh[].
* You have configured the required permission policies. For more information, see xref:con-rbac-permission-policies_admin-rhdh[].

.Procedure

. Go to *Administration* at the bottom of the sidebar in the {product-short}.
+
--
The *RBAC* tab appears, displaying all the created roles in the {product-short}.
--

. (Optional) Click any role to view the role information on the *OVERVIEW* page.
. Click *CREATE* to create a role.
. Enter the name and description of the role in the given fields and click *NEXT*.
. Add users and groups using the search field, and click *NEXT*.
. Select *Plugin* and *Permission* from the drop-downs in the *Add permission policies* section.
. Select or clear the *Policy* that you want to set in the *Add permission policies* section, and click *NEXT*.
. Review the added information in the *Review and create* section.
. Click *CREATE*.

.Verification

The created role appears in the list available in the *RBAC* tab.


