[id='proc-rhdh-deploy-eks-using-helm_{context}']
= Deploying {product} in Elastic Kubernetes Services (EKS) using Helm Chart

When you deploy {product-short} in Elastic Kubernetes Services (EKS) using Helm Chart, it orchestrates a robust development environment within the AWS ecosystem.

.Prerequisites

* You have an EKS cluster with AWS Application Load Balancer (ALB) add-on installed. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[Application load balancing on Amazon EKS] and https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html[Installing the AWS Load Balancer Controller add-on].
* You have configured a domain name for your {product-short} instance. The domain name can be a hosted zone entry on Route 53 or managed outside of AWS. For more information, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/dns-configuring.html[Configuring Amazon Route 53 as your DNS service] documentation.
* You have an entry in the AWS Certificate Manager (ACM) for your preferred domain name. Make sure to keep a record of your Certificate ARN.
* You have subscribed to `registry.redhat.io`. For more information, see https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication].
* You have set the context to the EKS cluster in your current `kubeconfig`. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html[Creating or updating a kubeconfig file for an Amazon EKS cluster].
* You have installed `kubectl`. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installing or updating kubectl].
* You have installed Helm 3 or the latest. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/helm.html[Using Helm with Amazon EKS].

.Procedure 

. Go to your terminal and run the following command to add the Helm chart repository containing the {product-short} chart to your local Helm registry:
+
--
[source]
----
$ helm repo add openshift-helm-charts https://charts.openshift.io/
----
--

. Create a pull secret using the following command:
+
--
[source]
----
$ kubectl create secret docker-registry rhdh-pull-secret \
    --docker-server=registry.redhat.io \
    --docker-username=<user_name> \ <1>
    --docker-password=<password> \ <2>
    --docker-email=<email> <3>
----
<1> Enter your username in the command.
<2> Enter your password in the command.
<3> Enter your email address in the command. 

The created pull secret is used to pull the {product-short} images from the Red Hat Ecosystem.
--

. Create a file named `values.yaml` using the following template:
+
--
[source,yaml]
----
global:
  # TODO: Set your application domain name.
  host: <your rhdh domain name>


route:
  enabled: false


upstream:
  service:
    # NodePort is required for the ALB to route to the Service
    type: NodePort


  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb


      alb.ingress.kubernetes.io/scheme: internet-facing


      # TODO: Using an ALB HTTPS Listener requires a certificate for your own domain. Fill in the ARN of your certificate, e.g.:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xxx:xxxx:certificate/xxxxxx


      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'


      alb.ingress.kubernetes.io/ssl-redirect: '443'


      # TODO: Set your application domain name.
      external-dns.alpha.kubernetes.io/hostname: <your rhdh domain name>


  backstage:
    image:
      pullSecrets:
      - rhdh-pull-secret
    podSecurityContext:
      # you can assign any random value as fsGroup
      fsGroup: 2000
  postgresql:
    image:
      pullSecrets:
      - rhdh-pull-secret
    primary:
      podSecurityContext:
        enabled: true
        # you can assign any random value as fsGroup
        fsGroup: 3000
  volumePermissions:
    enabled: true
----
--

. Run the following command in your terminal to deploy {product-short} using the latest version of Helm Chart and using the values.yaml file created in the previous step:
+
--
[source]
----
helm install rhdh \
  openshift-helm-charts/redhat-developer-hub \
  [--version 1.1.1] \  <1>
  --values /path/to/values.yaml
----
<1> version `1.1.1` is the latest version of the Helm Chart.
--

.Verification

Wait until the DNS name is responsive, indicating that your {product-short} instance is ready for use.




