[id='proc-rbac-ui-manage-roles_{context}']
= Managing role-based access controls (RBAC) using the {product} Web UI

Administrators can use the {product-short} web interface (Web UI) to allocate specific roles and permissions to individual users or groups. Allocating roles ensures that access to resources and functionalities is regulated across the {product-short}.

With the administrator role in {product-short}, you can assign permissions to users and groups, which allow users or groups to view, create, modify, and delete the roles using the {product-short} Web UI.

To access the RBAC features in the Web UI, you must install and configure the `@janus-idp/backstage-plugin-rbac` plugin as a dynamic plugin. For more information about installing a dynamic plugin, see xref:con-rhdh-installing-dynamic-plugins_admin-rhdh[].

After you install the `@janus-idp/backstage-plugin-rbac` plugin, the *Administration* option appears at the bottom of the sidebar. When you can click *Administration*, the RBAC tab appears by default, displaying all of the existing roles created in the {product-short}. In the RBAC tab, you can also view the total number of users, groups, and the total number of permission policies associated with a role. You can also edit or delete a role using the *Actions* column.