[id='disabling-telemetry-in-local-environment_{context}']
= Disabling telemetry in a local environment

By default, the `analytics-provider-segment` plugin is disabled when you run the {product-short} application locally without using the `dynamic-plugins.default.yaml` file. However, if you run the application using the `dynamic-plugins.default.yaml` file, you can disable telemetry data collection based on your needs.

.Prerequisites
* You have an administrator role in the {product-short}.
* You have installed the `analytics-provider-segment` plugin in {product-short}. For more information, see link:{LinkAdminGuide}#rhdh-installing-dynamic-plugins[Dynamic plugin installation].

.Procedure

. Add the following YAML code in your `dynamic-plugins.default.yaml` configuration file:
+
[source,yaml]
----
dynamicPlugins:
  plugins:
    - package: './dynamic-plugins/dist/janus-idp-backstage-plugin-analytics-provider-segment'
      disabled: true
----

. Save the configuration changes.

. Delete the `dynamic-plugins-root/janus-idp-backstage-plugin-analytics-provider-segment` plugin directory to stop loading of the plugin.
