[id='proc-rhdh-deploy-aks_{context}']

= Deploying {product} on {aks-name} ({aks-short})

You can deploy your {product-short} application on Azure Kubernetes Services (AKS) to access a comprehensive solution for building, testing, and deploying applications.

.Prerequisites
* You have an Azure account with active subscription.
* You have installed Azure CLI in your machine and configured the Resource Group and Cluster. For more information, see https://learn.microsoft.com/en-us/cli/azure/install-azure-cli[How to install the Azure CLI].
+
--
You can perform the following steps to configure the Resource Group and Cluster:

** To access Azure, ensuring you're logged in to our designated tenant use the following command:
+
[source]
----
az login [--tenant=<optional-directory-name>]
----

** To create a Resource Group, run the following command:
+
[source]
----
az group create --name <your_ResourceGroup> --location <location>
----
+
[TIP]
====
you can retrieve available regions using `az account list-locations -o table`.
====

** Create an AKS cluster:
+
[source]
----
az aks create \
--resource-group <your_ResourceGroup> \
--name <your_ClusterName> \
--enable-managed-identity \
--generate-ssh-keys
----
+
You can refer to `--help` for additional options.

** Connect to your cluster:
+
[source]
----
az aks get-credentials --resource-group <your_ResourceGroup> --name <your_ClusterName>
----
+
The previous command configures the Kubernetes client and sets the current context in the `kubeconfig` to point to your AKS cluster.
--

* You have installed `kubectl`. For more information, see https://docs.aws.amazon.com/eks/latest/userguide/install-kubectl.html[Installing or updating kubectl].
* You have installed Helm 3 or the latest.


Comparison of AKS specifics with the base {product-short} deployment::
+
--
* *Permissions issue*: {product-short} containers might encounter permission-related errors, such as `Permission denied` when attempting certain operations. This error can be addresssed by adjusting the `fsGroup` in the `PodSpec.securityContext`.

* *Ingress configuration*: In AKS, configuring ingress is essential for accessing the installed {product-short} instance. Accessing the {product-short} instance requires enabling the Routing add-on, an NGINX-based Ingress Controller, using the following commands:
+
[source]
----
az aks approuting enable --resource-group <your_ResourceGroup> --name <your_ClusterName>
----
+
[TIP]
====
You might need to install the Azure CLI extension `aks-preview`. If the extension is not installed automatically, you might need to install it manually using the following command:

[source]
----
az extension add --upgrade -n aks-preview --allow-preview true
----
====

[NOTE]
====
After you install the Ingress Controller, the 'app-routing-system' namespace with the Ingress Controller will be deployed in your cluster. Note the address of your {product-short} application from the installed Ingress Controller (for example, 108.141.70.228) for later access to the {product-short} application, later referenced as `<app_address>`.

[source,bash]
----
kubectl get svc nginx --namespace app-routing-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
----
====

* *Namespace management*: You can create a dedicated namespace for {product-short} deployment in AKS using the following command:
+
[source,bash]
----
kubectl create namespace <your_namespace>
----
--
