[id='enabling-authentication']
= Enabling authentication in {product}

Authentication within {product} facilitates user sign-in, identification, and access to external resources.
It supports multiple authentication providers.

Usually, set up:

- One provider for sign-in and identification.
- Additional providers for accessing external resources.

The {product} supports the following authentication providers:

Auth0:: `auth0`
Atlassian:: `atlassian`
Microsoft Azure:: `microsoft`
Microsoft Azure Easy Auth:: `azure-easyauth`
Bitbucket:: `bitbucket`
Bitbucket Server:: `bitbucketServer`
Cloudflare Access:: `cfaccess`
GitHub:: `github`
GitLab:: `gitlab`
Google:: `google`
Google IAP:: `gcp-iap`
OIDC:: `oidc`
Okta:: `okta`
OAuth 2 Custom Proxy:: `oauth2Proxy`
OneLogin:: `onelogin`
SAML:: `saml`

For each provider, follow the dedicated procedure to:

. Set up in your provider the secrets that {product} requires to communicate with the provider.
. Add the authentication provider secrets in {product}.
. Configure {product} to use the authentication provider.
