:_mod-docs-content-type: PROCEDURE
[id="authenticating-with-the-guest-user_{context}"]
= Authenticating with the Guest user

To explore {product-short} features, you can skip configuring authentication and authorization. 
After the default installation, you can log in as a Guest user and access all the features.

.Prerequisites
* You link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}/html/administration_guide_for_red_hat_developer_hub/assembly-add-custom-app-file-openshift_admin-rhdh[added a custom {product-short} application configuration], and have sufficient permissions to modify it.
See link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/{product-version}#Install%20and%20Upgrade[Installing RHDH].

.Procedure

* To set up the guest user in your {product-short} custom configuration, edit your custom Developer Hub config map, such as `app-config-rhdh`, and add following lines to the `app-config-rhdh.yaml` content:
+
.`app-config-rhdh.yaml` fragment
[code,yaml]
----
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
----

.Verification
. Go to the {product-short} login page.
. To log in with the Guest user account, click **Enter** in the **Guest** tile.
. In the {product-short} **Settings** page, your profile name is **Guest**.
. You can use {product-short} features.
