[id="rhdh-installing-dynamic-plugins"]
= Installing a dynamic plugin package
The dynamic plugin support is based on the backend plugin manager package, which is a service that scans a configured root directory (dynamicPlugins.rootDirectory in the app config) for dynamic plugin packages, and loads them dynamically.

== Helm deployment

Since version 2.10.1, the Helm Chart for deploying the showcase application introduces new values.

The updated Helm values introduce a new global.dynamic parameter, comprising two fields:

* `plugins`: This field encompasses the list of dynamic plugins slated for installation. By default, it is an empty list. A package can be specified either as a local relative path (starting with ./) to the dynamic plugin's folder or as a package specification in an NPM repository.

* `includes`: This field contains a roster of YAML files utilizing the same syntax. The plugins list from these files will be incorporated, and potentially overridden, by the plugins list in the primary Helm values. The default configuration includes the `dynamic-plugins.default.yaml` file, which encompasses all the dynamic plugins included in the showcase application container image, whether enabled or disabled by default.

== Installing a dynamic plugin using the Helm Chart

To include a dynamic plugin in the showcase, you can achieve this by appending an entry to the `global.dynamic.plugins` list. Each entry should contain the following fields:

* `package`: a package specification of the dynamic plugin package to be installed (can be from a local path or an NPM repository)

* `integrity`: (optional for local packages) An integrity checksum in the form of <alg>-<digest> for the specific package. Supported algorithms include `sha256`, `sha384` and `sha512`.

* `pluginConfig`: an optional plugin-specific app-config yaml fragment. See plugin configuration for more details.

* `disabled`: disables the dynamic plugin if set to `true`. Default: `false`.

== Examples

.Example 1: Enabling two plugins from a local and remote source, one requiring a specific app-config
[source,java]
----
global:
  dynamic:
    plugins:
      - package: <a local package-spec used by npm pack>
      - package: <a remote package-spec used by npm pack>
        integrity: sha512-<some hash>
        pluginConfig: ...
----

.Example 2: Disabling a plugin from an included file
[source,java]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: <some imported plugins listed in dynamic-plugins.default.yaml>
        disabled: true
----

.Example 3: Enabling a plugin from an included file
[source,java]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: <some imported plugins listed in dynamic-plugins.custom.yaml>
        disabled: false
----

== Dynamic plugins included in the Showcase container image

The showcase docker image comes pre-loaded with a selection of dynamic plugins, with most being initially deactivated due to the need for mandatory configuration. 

The complete list of these plugins is detailed in the xref:rhdh-supported-plugins[Dynamic Plugins Matrix] 

Upon application startup, for each plugin that is disabled by default, the install-dynamic-plugins init container within the backstage Pod's log will display a line similar to the following:

<Content missing>

To activate this plugin, simply add a package with the same name and adjust the disabled field in the Helm Chart values as shown below:

[source,java]
----
global:
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-dynamic
        disabled: false
----

While the plugin's default configuration is extracted from the dynamic-plugins.default.yaml file, you still have the option to override it by incorporating a pluginConfig entry into the plugin configuration.