:_mod-docs-content-type: CONCEPT

[id="con-monitor-portfolio-health-with-aggregated-kpis.adoc_{context}"]
= Monitor portfolio health with aggregated KPIs

When you oversee a large portfolio of applications, use aggregated Key Performance Indicators (KPIs) to identify high-level health trends and technical risks. By consolidating metrics, such as open PRs with a status of *Error*, *Warning* or *Success*, from multiple entities in the Software Catalog, you can assess the health of your entire team from a single dashboard.

To maintain {product-very-short} performance, the Scorecard plugin fetches data from external sources on schedule and saves them to a database. Although the backend calculates KPIs in real time using this stored data, the synchronization of metrics for each entity occurs hourly by default. You have the option to customize the refresh schedule to balance your requirement for current data with the system processing load.

The aggregation endpoint (`/metrics/:metricId/catalog/aggregations`) summarizes metrics based on entity ownership. By default, the plugin only considers direct ownership, which includes the following entities:

* Entities you own directly.
* Entities owned by groups where you are a direct member.

The plug-in does not traverse nested group hierarchies unless you {authentication-book-link}#enabling-transitive-parent-groups[enable transitive parent group ownership].