:_mod-docs-content-type: PROCEDURE

[id="proc-viewing-scorecards-in-rhdh_{context}"]
= Viewing Scorecard metrics in {product}

As a developer, you can view the GitHub and Jira metrics using Scorecards in your {product-very-short} instance to quickly gain at-a-glance visibility into the health and readiness of your software components. By accessing the *Scorecard* tab in your {product-very-short} instance, you eliminate context switching and can immediately verify security, compliance, and development metrics (like GitHub and Jira data).

.Prerequisites

* You have installed your {product-very-short} instance.
* You have either the GitHub or Jira Scorecard (or both) configured in your {product-very-short} instance.
* You must have permissions to read the Scorecard metrics.

.Procedure
. In your {product-very-short} navigation menu, go to *Catalog*.
. Select the software component (catalog entity) that has Scorecard metrics configured.
. On the component *Service* page, go to the *Scorecard* tab.
. To view the desired metrics, select the corresponding tile.