:_mod-docs-content-type: PROCEDURE

[id="proc-configuring-github-scorecards-in-rhdh-instance_{context}"]
= Configuring GitHub Scorecards to view GitHub metrics in your {product} instance

To achieve enhanced visibility and control over your software components, you must configure the GitHub Scorecards plugin to integrate GitHub metrics directly into your {product-very-short} catalog. This allows engineering teams to centralize development data, quickly identify risks, and accelerate decision-making related to component health and security. 

To enable the GitHub metrics integration, you must create and configure a GitHub App to grant {product-very-short} access to the GitHub API.

.Prerequisites

* You have {install-category-link}[installed your {product-very-short} instance].
* You have {scorecard-plugin-book-link}#proc-installing-scorecard-plugin-in-rhdh-instance[installed the Scorecard images].
* You must have permissions in GitHub to create and manage a https://docs.github.com/en/apps/overview[GitHub App].
* You must have {configuring-book-link}[added a custom {product-very-short} application configuration] and have enough permissions to change it.

.Procedure
To install and configure GitHub Scorecards in your {product-very-short} instance, complete the following steps:

. To allow {product-very-short} to access the GitHub API, you must create and configure a GitHub App and add the necessary integration to your configuration file:
.. Create a https://docs.github.com/en/apps/overview[GitHub App] with the required permissions (Read-only for Contents to allow reading repositories).
.. In the *General > Clients secrets* section, click *Generate a new client secret*.
.. In the *General > Private keys* section, click *Generate a private key*.
.. In the *Install App* tab, choose an account to install your GitHub App on.
.. Enter the following values and click *Save*:
*** *App ID*
*** *Client ID*
*** *Client Secret*
*** *Private key*
.. To add your GitHub credentials to {product-very-short}, add the following key/value pairs to your {configuring-book-link}#provisioning-your-custom-configuration[your {product-very-short} secrets]. You can use these secrets in the {product-very-short} configuration files by using their respective environment variable names. 
+
`GITHUB_INTEGRATION_APP_ID`:: Enter the saved *App ID*.
`GITHUB_INTEGRATION_CLIENT_ID`:: Enter the saved *Client ID*.
`GITHUB_INTEGRATION_CLIENT_SECRET`:: Enter the saved *Client Secret*.
`GITHUB_INTEGRATION_HOST_DOMAIN`:: Enter the GitHub host doman: `github.com`
`GITHUB_INTEGRATION_ORGANIZATION`:: Enter your GitHub organization name, such as, `_<your_github_organization_name>_`
`GITHUB_INTEGRATION_PRIVATE_KEY_FILE`:: Enter the saved *Private key*.

. Configure the GitHub integration in your {product-very-short} `{my-app-config-file}` file by adding the `integrations.github` section:
+
[source,yaml]
----
integrations:
  github:
    - host: ${GITHUB_INTEGRATION_HOST_DOMAIN}
      apps:
        - appId: ${GITHUB_INTEGRATION_APP_ID}
          clientId: ${GITHUB_INTEGRATION_CLIENT_ID}
          clientSecret: ${GITHUB_INTEGRATION_CLIENT_SECRET}
          privateKey: |
            ${GITHUB_INTEGRATION_PRIVATE_KEY_FILE}
----

. Install the GitHub Scorecard plugin by adding the following code to your {product-very-short} `dynamic-plugins-config.yaml` file:
+
[source,yaml]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github:bs_1.42.5__1.0.0!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github
    disabled: false
----

. To link a component to the GitHub data source, edit the `catalog-info.yaml` file for your {product-very-short} entity and add the required annotations as shown in the following code.
+
[source,yaml]
----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  annotations:
    # Required: GitHub project slug in format "owner/repository"
    github.com/project-slug: myorg/my-service
    # Required: Entity source location
    backstage.io/source-location: url:https://github.com/myorg/my-service
spec:
  type: service
  lifecycle: production
  owner: _<your_team_name>_
----
+
where:

`annotations:github.com/project-slug`:: The GitHub repository format, for example, `owner/repository`.
`annotations:backstage.io/source-location`:: The entity source location format, for example, `url:https://github.com/owner/repository`.
`spec:owner`:: Your team name.
+
[NOTE]
====
You must add the team entity to the Catalog to ensure the provided permissions are applicable.
====

. Statically ingest the catalog entity by adding the `catalog.locations` section in your {product-very-short} `{my-app-config-file}` file that links to the `catalog-info.yaml` file:
+
[source,yaml]
----
catalog:
  locations:
    - type: url
      target: https://github.com/owner/repo/catalog-info.yaml
----

. (Optional) To customize the thresholds for the **GitHub Open Pull Requests** (`github.open_prs`) metric, add the following section to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
scorecard:
  plugins:
    github:
      open_prs:
        thresholds:
          rules:
            - key: success
              expression: '<10'
            - key: warning
              expression: '10-50'
            - key: error
              expression: '>50'
----
+
where:

`scorecard:plugins:github:open_prs:thresholds`:: Lists the default threshold values for the GitHub open PRs metric.

[NOTE]
====
To read more information about how to customize the threshold values, see link:https://documentation.example.com/scorecard-plugins-thresholds/[Thresholds in Scorecard plugins].
====