:_mod-docs-content-type: PROCEDURE

[id="proc-integrating-jira-health-metrics-using-scorecards_{context}"]
= Integrating Jira health metrics using Scorecards

You can configure the Jira Scorecard plugin to display project tracking and delivery velocity data in your {product-very-short} instance. This integration centralizes development status and facilitates the evaluation of component readiness.

The plugin supports Jira Cloud (API v3) and Jira Data Center (API v2).

.Prerequisites

* You must have administrator privileges for Jira and {product-very-short}.
* You have {install-category-link}[installed your {product-very-short} instance].
* You have {scorecard-plugin-book-link}#proc-installing-scorecard-plugin-in-rhdh-instance[installed the Scorecard images].
* You must have {configuring-book-link}[added a custom {product-very-short} application configuration] and have sufficient permissions to change it.

.Procedure
To install and configure Jira Scorecards in your {product-very-short} instance, complete the following steps:

[NOTE]
====
You must use the proxy setup to ensure configuration compatibility if you also use the Roadie Jira Frontend Plugin.
====

. Generate a Jira configuration token using one of the following methods, depending on your Jira product:
** Jira Cloud: https://id.atlassian.com/manage-profile/security/api-tokens[Create a personal token]. You must create a `Base64-encoded` string using the following plain text format: `your-atlassian-email:your-jira-api-token`.
+
[source,bash]
----
$ echo -n 'your-atlassian-email:your-jira-api-token' | base64
----
** Jira datacenter: Create a https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html[Personal Access Token (PAT)] in your Jira datacenter account.

. Add Jira secrets: Define the following key/value pairs in {configuring-book-link}#provisioning-your-custom-configuration[your {product-very-short} secrets]:
+
`JIRA_TOKEN`:: Enter your generated Jira token.
`JIRA_BASE_URL`:: Enter your Jira base URL.

. Configure the plugin: In your {product-very-short} `dynamic-plugins-config.yaml` file, enable the plugin using either a direct setup or a proxy setup.
** Use a direct setup: 
... Add the following code to your {product-very-short} `dynamic-plugins-config.yaml` file:
+
[source,yaml]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira:bs_1.45.3__2.3.5!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira
    disabled: false
----
... In your {product-very-short} `{my-app-config-file}` file, add the following direct setup settings:
+
[source,yaml]
----
jira:
  baseUrl: ${JIRA_BASE_URL}
  token: ${JIRA_TOKEN}
  product: _<jira_product>_
----
where:

`baseUrl`:: The base URL of your Jira instance, configured under ${JIRA_BASE_URL} in your {product-very-short} secrets.
`token`:: The Jira token (Base64 string for Cloud, PAT for Data Center), configured under ${JIRA_TOKEN} in your {product-very-short} secrets.
`product`:: Enter the supported product: `cloud` or `datacenter`.

** Use a proxy setup: 
... In your {product-very-short} `dynamic-plugins-config.yaml` file, add the following code:
+
[source,yaml]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira:bs_1.45.3__2.3.5!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-jira
    disabled: false
----

... In your {product-very-short} `{my-app-config-file}` file, add the following proxy settings:
+
[source,yaml]
----
proxy:
  endpoints:
    '/jira/api':
      target: ${JIRA_BASE_URL}
      headers:
        Accept: 'application/json'
        Content-Type: 'application/json'
        X-Atlassian-Token: 'no-check'
        Authorization: ${JIRA_TOKEN} # Must be configured in your environment
jira:
  proxyPath: /jira/api
  product: cloud # Change to 'datacenter' if using Jira Datacenter
----
+
where:

`target`:: The base URL of your Jira instance, configured under ${JIRA_BASE_URL} in your {product-very-short} secrets.
`Authorization`:: The Jira token, configured under ${JIRA_TOKEN} in your {product-very-short} secrets. Set the token value as one of the following values:
* For *Cloud*: `Basic YourCreatedCloudToken`
* For *Data Center*: `Bearer YourJiraToken`

. Annotate catalog entities: Add the Jira project key to the `metadata.annotations` section of the `catalog-info.yaml` file for your component:
+
[source,yaml]
----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  annotations:
    jira/project-key: PROJECT
    jira/component: Component
    jira/label: UI
    jira/team: 9d3ea319-fb5b-4621-9dab-05fe502283e
    jira/custom-filter: 'reporter = "abc@xyz.com" AND resolution is not EMPTY'
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
----
+
where:

`jira/project-key`:: Required: Enter the Jira project key.
`jira/component`:: Optional: Enter the Jira component name.
`jira/label`:: Optional: Enter the Jira label.
`jira/team`:: Optional: Enter the Jira team ID (not the team title).
`jira/custom-filter`:: Optional: Enter a custom Jira Query Language (JQL) filter.

. Ingest the catalog entity: Add the location of your `catalog-info.yaml` to the `catalog.locations` section in the {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
catalog:
  locations:
    - type: url
      target: https://github.com/<owner>/<repository>/catalog-info.yaml
----

. Optional: Define metric thresholds and filters: To customize health criteria or filter issues, add the *Jira Open Issues* metric thresholds to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
scorecard:
  plugins:
    jira:
      open_issues:
        thresholds:
          rules:
            - key: success
              expression: '<10'
            - key: warning
              expression: '10-50'
            - key: error
              expression: '>50'
----
+
where:

`scorecard:plugins:jira:open_issues:thresholds`:: Lists the default threshold values for the *Jira Open Issues* metric.

. Optional: Define global or custom mandatory filters that entities can override by adding the following code to your {product-very-short} `{my-app-config-file}` file:
+
[source,yaml]
----
scorecard:
  plugins:
    jira:
      open_issues:
        options:
          mandatoryFilter: Type = Task AND Resolution = Unresolved
          customFilter: priority in ("Critical", "Blocker")
----
+
where:

`mandatoryFilter`:: Optional: Replaces the default filter (`type = Bug and resolution = Unresolved`).
`customFilter`:: Optional: Specifies a global custom filter. The entity annotation `jira/custom-filter` overrides this value.

For more information about how to customize the threshold values, see {scorecard-plugin-book-link}#con-manage-metric-thresholds-in-scorecard-plugin[Thresholds in Scorecard plugins].

