:_mod-docs-content-type: PROCEDURE

[id="proc-configuring-github-scorecards-in-rhdh-instance_{context}"]
= Configuring GitHub Scorecards to view GitHub metrics in your {product} instance

You can view GitHub metrics for software components registered in the {product-very-short} catalog. To allow the {product-very-short} to access the GitHub API, you must create a GitHub App and configure the necessary integration.

.Prerequisites

* You have installed your {product-very-short} instance.
* You have {scorecard-plugin-book-link}#proc-installing-scorecard-plugin-in-rhdh-instance[installed the Scorecard images].
* You must have permissions in GitHub to create and manage a https://docs.github.com/en/apps/overview[GitHub App].
* You must have {configuring-book-link}[added a custom {product-very-short} application configuration] and have enough permissions to change it.

.Procedure
To configure GitHub Scorecards in your RHDH instance, complete the following steps:

. To allow {product-very-short} to access the GitHub API, you must create and configure a GitHub App and add the necessary integration to your configuration file by completing the following steps:
.. Create a https://docs.github.com/en/apps/overview[GitHub App] with the required permissions (Read-only for Contents to allow reading repositories).
.. Generate a client secret and a private key.
.. Install the app on the desired account/organization.
.. Save the following values:
*** `App ID`
*** `Client ID`
*** `Client secret`
*** `Private key`
.. Add your GitHub credentials to {configuring-book-link}#provisioning-your-custom-configuration[your {product-very-short} secrets] using the following key/value pairs. You can use these secrets in the {product-very-short} configuration files by using their respective environment variable names. 
*** `GITHUB_INTEGRATION_APP_ID`
*** `GITHUB_INTEGRATION_CLIENT_ID`
*** `GITHUB_INTEGRATION_CLIENT_SECRET`
*** `GITHUB_INTEGRATION_HOST_DOMAIN` (e.g., `github.com`)
*** `GITHUB_INTEGRATION_PRIVATE_KEY_FILE`

. Configure the GitHub integration in your `{product-very-short} {my-app-config-file}`, by adding the `integrations.github` section:
+
[source,yaml]
----
integrations:
  github:
    - host: ${GITHUB_INTEGRATION_HOST_DOMAIN}
      apps:
        - appId: ${GITHUB_INTEGRATION_APP_ID}
          clientId: ${GITHUB_INTEGRATION_CLIENT_ID}
          clientSecret: ${GITHUB_INTEGRATION_CLIENT_SECRET}
          privateKey: |
            ${GITHUB_INTEGRATION_PRIVATE_KEY_FILE}
----

. Configure the GitHub Scorecard plugin in your `{product-very-short} dynamic-plugins-config.yaml` by adding the following code to your `{product-very-short} dynamic-plugins-config.yaml`:
+
[source,yaml]
----
plugins:
  - package: oci://ghcr.io/redhat-developer/rhdh-plugin-export-overlays/red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github:bs_1.42.5__1.0.0!red-hat-developer-hub-backstage-plugin-scorecard-backend-module-github
    disabled: false
----
where:

. In your {product-very-short} entity that you want to configure for the GitHub Scorecard plugin, in the `catalog-info.yaml` file, link a component to the data source by adding the required annotations as shown in the following code:
+
[source,yaml]
----
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  annotations:
    # Required: GitHub project slug in format "owner/repository"
    github.com/project-slug: myorg/my-service
    # Required: Entity source location
    backstage.io/source-location: url:https://github.com/myorg/my-service
spec:
  type: service
  lifecycle: production
  owner: _<your_team_name>_
----
+
Where:
+
`annotations:github.com/project-slug`:: The GitHub repository format, for example, `owner/repository`.
`annotations:backstage.io/source-location`:: The entity source location format, for example, `url:https://github.com/owner/repository`.
`spec:owner`:: Your team name.

[NOTE]
====
You must add the team entity to the Catalog to ensure the provided permissions are applicable.
====

. (Optional) Configure metric threshold values.

.. To customize the thresholds for the **GitHub Open Pull Requests** (`github.open_prs`) metric, add the following section to your `app-config.yaml` file:
+
[source,yaml]
----
scorecard:
  plugins:
    github:
      open_prs:
        thresholds:
          rules:
            - key: success
              expression: '<10'
            - key: warning
              expression: '10-50'
            - key: error
              expression: '>50'
----
where:

`scorecard:plugins:github:open_prs:thresholds`:: Lists the default threshold values for the GitHub open PRs metric.

[NOTE]
====
To read more information about how to customize the threshold values, see link:https://documentation.example.com/scorecard-plugins-thresholds/[Thresholds in Scorecard plugins].
====