:_mod-docs-content-type: CONCEPT
[id="con-about-adoption-insights_{context}"]
= About Adoption Insights

As organizations generate an increasing number of data events, there is a growing need for detailed insights into the adoption and engagement metrics of the internal developer portal. These insights help platform engineers make data-driven decisions to improve its performance, usability, and translate them into actionable insights. 

You can use Adoption Insights in {product} to visualize key metrics and trends to get information about the usage of {product-short} in your organization. The information provided by Adoption Insights in {product-short} pinpoints areas of improvement, highlights popular features, and evaluates progress toward adoption goals. You can also monitor user growth against license users and identify trends over time. 

The Adoption Insights dashboard in {product-short} includes the following cards:

* *Active users*
* *Total nuber of users*
* *Top catalog entities*
* *Top 3 templates*
* *Top 3 techdocs*
* *Top 3 plugins*
* *Portal searches*