:_mod-docs-content-type: PROCEDURE
[id="enable-the-adoption-insights-plugin_{context}"]
= Enable the Adoption Insights plugin

[role="_abstract"]
Enable the Adoption Insights plugin after migrating from the Developer Preview version or if previously disabled.

The Adoption Insights plugin is preinstalled and enabled on a {product-short} instance by default.

.Procedure

. If you previously used the Developer Preview of the Adoption Insights plugin and enabled the plugin manually, remove those earlier plugins as they are no longer required, and Adoption Insights is enabled by default.
+
In your `dynamic-plugins.yaml` file, remove the references to the following plugins:
+
* `red-hat-developer-hub-backstage-plugin-adoption-insights`
* `red-hat-developer-hub-backstage-plugin-adoption-insights-backend`
* `red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights`

. Enable the `backstage-community-plugin-analytics-provider-segment` plugin by setting `disabled` to `false`:
+
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
    disabled: false
----
