:_mod-docs-content-type: PROCEDURE
[id="proc-modify-number-of-displayed-records_{context}"]
= Modifying the number of displayed records

== Modifying the number of displayed records in Top catalog entities

You can modify the number of records that are displayed in the *Top catalog entities* card. You can select any of the following number of records for display:

* *Top 3*
* *Top 5*
* *Top 10*
* *Top 20*

By default, the top three most viewed catalog entities are displayed. 

.Procedure

* Go to *Administration -> Adoption Insights* and click the *Down* arrow next to *3 rows* to change the number of displayed records.

== Modifying the number of displayed records in Top 3 templates

You can modify the number of records that are displayed in the *Top 3 templates* card. You can select any of the following number of records for display:

* *Top 3*
* *Top 5*
* *Top 10*
* *Top 20*

By default, the top three most viewed templates are displayed. 

.Procedure

* Go to *Administration -> Adoption Insights* and click the *Down* arrow next to *3 rows* to change the number of displayed records.

== Modifying the number of displayed records in Top 3 techdocs

You can modify the number of records that are displayed in the *Top 3 techdocs* card. You can select any of the following number of records for display:

* *Top 3*
* *Top 5*
* *Top 10*
* *Top 20*

By default, the top three most viewed TechDocs are displayed. 

.Procedure

* Go to *Administration -> Adoption Insights* and click the *Down* arrow next to *3 rows* to change the number of displayed records.

== Modifying the number of displayed records in Top 3 plugins

You can modify the number of records that are displayed in the *Top 3 plugins* card. You can select any of the following number of records for display:

* *Top 3*
* *Top 5*
* *Top 10*
* *Top 20*

By default, the top three most viewed plugins are displayed. 

.Procedure

* Go to *Administration -> Adoption Insights* and click the *Down* arrow next to *3 rows* to change the number of displayed records.