:_mod-docs-content-type: PROCEDURE
[id="proc-configure-adoption-insights_{context}"]
= Configuring the Adoption Insights plugin in {product}

The Adoption Insights plugin is preinstalled and enabled on a {product-short} instance by default. You can disable or enable the Adoption Insights plugin and change other parameters, by configuring the `app-config` ConfigMap, which is created by the {product} Helm chart or Operator.

[IMPORTANT]
====
If you previously used the Developer Preview of the Adoption Insights plugin and enabled the plugin manually, you must remove those earlier plugins as they are no longer required, and Adoption Insights is enabled by default.

In your dynamic plugins ConfigMap, for example: `dynamic-plugins-rhdh.yaml`, remove the references to `red-hat-developer-hub-backstage-plugin-adoption-insights`, `red-hat-developer-hub-backstage-plugin-adoption-insights-backend`, and `red-hat-developer-hub-backstage-plugin-analytics-module-adoption-insights`. Additionally update the `package.disabled` value of the `backstage-community-plugin-analytics-provider-segment` plugin to `false` as shown in the following example:

.`dynamic-plugins.yaml` fragment
[source,yaml]
----
plugins:
  - package: ./dynamic-plugins/dist/backstage-community-plugin-analytics-provider-segment
    disabled: false
----
====