:_mod-docs-content-type: ASSEMBLY

[id="assembly-enabling-configuring-the-jfrog-plugin_{context}"]
= Enabling and configuring the JFrog plugin
:context: assembly-installing-configuring-jfrog

JFrog Artifactory is a front-end plugin that displays the information about your container images stored in the JFrog Artifactory repository. The JFrog Artifactory plugin is preinstalled with {product-short} and disabled by default. To use it, you need to enable and configure it first.

[IMPORTANT]
====
The JFrog Artifactory plugin is a Technology Preview feature only.

Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].

Additional detail on how Red Hat provides support for bundled community dynamic plugins is available on the https://access.redhat.com/policy/developerhub-support-policy[Red Hat Developer Support Policy] page.
====

include::../modules/dynamic-plugins/proc-enabling-the-jfrog-plugin.adoc[leveloffset=+1]

include::../modules/dynamic-plugins/proc-configuring-the-jfrog-plugin.adoc[leveloffset=+1]
