:_mod-docs-content-type: ASSEMBLY

[id="assembly-mirroring-dynamic-plugins-in-disconnected-environments_{context}"]
= Mirroring {product} dynamic plugins in disconnected environments

{product} (product-very-short) uses dynamic plugins that are distributed as Open Container Initiative (OCI)artifacts. In disconnected or restricted environments, these plugin artifacts must be mirrored to a registry accessible by your cluster.

This guide explains how to use the `mirror-plugins.sh` script to mirror dynamic plugin OCI artifacts for deployments in restricted environments.

== Prerequisites
The following tools are required to run the mirroring script:

* You have installed Skopeo 1.20 or later.
//* skopeo >= 1.20 - For multi-arch image operations and manifest conversion. See Installing Skopeo.

* You have installed `tar` 1.35 or later.
//* tar >= 1.35 - GNU tar for extracting image layers.

* You have installed `jq` 1.7 or later.
//* jq >= 1.7 - For JSON parsing and manipulation. See Download jq.

* You have installed Podman 5.6 or later.
For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].
//* podman >= 5.6 - For building catalog index images. See Podman Installation Instructions.

* You have authenticated to the source registry, for example, quay.io or registry.redhat.io for pulling plugin artifacts. See Red Hat Container Registry Authentication.

* When mirroring directly to a registry using `--to-registry`, you have authenticated to the target registry.

////
.Prerequisites
* You have installed Podman 5.3 or later.
For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].
* You have installed Skopeo 1.17 or later.
* You have installed `yq` 4.44 or later.
* You have installed the GNU `sed` command line text editor.
* You have installed `umoci` CLI tool.
* You have an active `oc registry`, `podman`, or `Skopeo` session to the {rhcr-long}.
For more information, see link:link:https://access.redhat.com/articles/RegistryAuthentication[{company-name} Container Registry Authentication].
* You have an active `Skopeo` session with administrative access to the target mirror registry.
For more information, see link:https://github.com/containers/skopeo#authenticating-to-a-registry[Authenticating to a registry].
* You have installed the `opm` CLI tool.
For more information, see {ocp-docs-link}/html/cli_tools/opm-cli#olm-about-opm_cli-opm-install[Installing the opm CLI].
* If you are using an {ocp-short} cluster, you have the following prerequisites:
** Recommended: You have installed the `oc-mirror` tool, with a version corresponding to the version of your {ocp-short} cluster.
* If you are using a supported Kubernetes cluster, you have the following prerequisites:
** You have installed the Operator Lifecycle Manager (OLM) on the disconnected cluster.
** You have a mirror registry that is reachable from the disconnected cluster.
* Make sure that your system meets the minimum sizing requirements.
See {about-book-link}#rhdh-sizing_about-rhdh[Sizing requirements for {product}].
////

// Partially disconnected environment
include::../modules/dynamic-plugins/proc-mirror-plugins-catalog-index-patially-disconnected.adoc[leveloffset=+1]

// Fully disconnected environment
include::../modules/dynamic-plugins/proc-mirror-plugins-catalog-index-fully-disconnected.adoc[leveloffset=+1]

// Mirroring specific plugins by direct reference
include::../modules/dynamic-plugins/proc-mirror-specific-plugins-direct-reference.adoc[leveloffset=+1]

// Mirroring plugins from a file
include::../modules/dynamic-plugins/proc-mirror-plugins-from-file.adoc[leveloffset=+1]

// Mixed mode: Combining multiple plugin sources
include::../modules/dynamic-plugins/proc-mirror-plugins-combining-multiple-sources.adoc[leveloffset=+1]

== Using mirrored plugins
After mirroring completes, the script generates a `rhdh-plugin-mirroring-summary.txt` file containing mappings of all mirrored plugins. Use this file to reference the correct mirrored plugin URLs when configuring your {product-very-short} deployment.

For Operator deployments, you must configure the Backstage Custom Resource with the mirrored plugin references. For Helm deployments, you must update your values file with the mirrored plugin references. 
//See link:TBC[Red Hat Developer Hub] documentation for configuration details.
