:_mod-docs-content-type: ASSEMBLY
[id="assembly-enabling-configuring-the-nexus-plugin_{context}"]
= Enabling and configuring the Nexus Repository Manager plugin
:context: assembly-installing-configuring-nexus

The Nexus Repository Manager plugin displays the information about your build artifacts in your {product-short} application. The build artifacts are available in the Nexus Repository Manager.

[IMPORTANT]
====
The Nexus Repository Manager plugin is a Technology Preview feature only.

Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].

Additional detail on how {company-name} provides support for bundled community dynamic plugins is available on the https://access.redhat.com/policy/developerhub-support-policy[Red Hat Developer Support Policy] page.
====

include::../modules/dynamic-plugins/proc-enabling-the-nexus-plugin.adoc[leveloffset=+1]

include::../modules/dynamic-plugins/proc-configuring-the-nexus-plugin.adoc[leveloffset=+1]