:_mod-docs-content-type: ASSEMBLY

= Extending {product} with custom plugins

You can extend {product} with your own custom plugins. However, to add a custom plugin to the {product} pre-built container image, you must bundle and install your custom plugin as a dynamic plugin.

To integrate a custom plugin into {product-short}:

. First, obtain the plugin's source code.
. Export the plugin as a dynamic plugin package.
. Package and publish the dynamic plugin.
. Install the plugin in the {product-short} environment.

[NOTE]
====
Standard {product-custom-resource-type} deployments statically compile plugins into the application itself. {product} supports dynamic plugins, meaning you can add plugins to an existing instance without recompiling the underlying {product-custom-resource-type} application.
====

include::../modules/dynamic-plugins/con-custom-plugin-conversion.adoc[leveloffset=+1]

include::../modules/dynamic-plugins/proc-custom-plugin-conversion.adoc[leveloffset=+1]

include::../modules/dynamic-plugins/con-custom-plugin-add-to-rhdh.adoc[leveloffset=+1]

