:_mod-docs-content-type: ASSEMBLY

[id="assembly-mirroring-dynamic-plugins-in-disconnected-environments_{context}"]
= Mirroring {product} dynamic plugins in disconnected environments

{product} ({product-very-short}) uses dynamic plugins that are distributed as Open Container Initiative (OCI) artifacts. In disconnected or restricted environments, these plugin artifacts must be mirrored to a registry accessible by your cluster.

To mirror dynamic plugin OCI artifacts for deployments in restricted environments, use the `mirror-plugins.sh`.
.Prerequisites

* You have installed Skopeo 1.20 or later. Use Skopeo for multi-arch image operations and manifest conversion.

* You have installed `tar` 1.35 or later. Use GNU `tar` for extracting image layers.

* You have installed `jq` 1.7 or later. Use `jq` for JSON parsing and manipulation. See Download jq.

* You have installed Podman 5.6 or later. Use Podman for building catalog index images. For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].

* You have authenticated to the source registry, for example, quay.io or registry.redhat.io for pulling plugin artifacts. See link:https://access.redhat.com/articles/RegistryAuthentication[Red Hat Container Registry Authentication].

* If mirroring directly to a registry using `--to-registry`, you have authenticated to the target registry.
== Using mirrored plugins
After mirroring completes, the script generates a `rhdh-plugin-mirroring-summary.txt` file containing mappings of all mirrored plugins. Use this file to reference the correct mirrored plugin URLs when configuring your {product-very-short} deployment.

For Operator deployments, you must configure the Backstage Custom Resource with the mirrored plugin references. For Helm deployments, you must update your values file with the mirrored plugin references. 

== Prerequisites
The following tools are required to run the mirroring script:

* You have installed Skopeo 1.20 or later. Use Skopeo for multi-arch image operations and manifest conversion.

* You have installed `tar` 1.35 or later. Use GNU `tar` for extracting image layers.

* You have installed `jq` 1.7 or later. Use `jq` for JSON parsing and manipulation. See Download jq.

* You have installed Podman 5.6 or later. Use Podman for building catalog index images. For more information, see link:https://podman.io/docs/installation[Podman Installation Instructions].

* You have authenticated to the source registry, for example, quay.io or registry.redhat.io for pulling plugin artifacts. See link:https://access.redhat.com/articles/RegistryAuthentication[Red Hat Container Registry Authentication].

* When mirroring directly to a registry using `--to-registry`, you have authenticated to the target registry.

// Partially disconnected environment
include::../modules/dynamic-plugins/proc-mirror-plugins-catalog-index-patially-disconnected.adoc[leveloffset=+1]

// Fully disconnected environment
include::../modules/dynamic-plugins/proc-mirror-plugins-catalog-index-fully-disconnected.adoc[leveloffset=+1]

// Mirroring specific plugins by direct reference
include::../modules/dynamic-plugins/proc-mirror-specific-plugins-direct-reference.adoc[leveloffset=+1]

// Mirroring plugins from a file
include::../modules/dynamic-plugins/proc-mirror-plugins-from-file.adoc[leveloffset=+1]

// Mixed mode: Combining multiple plugin sources
include::../modules/dynamic-plugins/proc-mirror-plugins-combining-multiple-sources.adoc[leveloffset=+1]