:_mod-docs-content-type: PROCEDURE

[id="proc-upgrade-rhdh-helm_{context}"]
= Upgrading the {product} Helm Chart

You can upgrade to a later version of {product} in {ocp-short} by using either the web console or the CLI.

* {ocp-short} web console
+
[WARNING]
====
If you have installed {product-short} manually using the Helm CLI, the Helm chart release upgrade in the OpenShift Developer Console is going to fail. The failure is due to the limitations when using the {ocp-short} console to upgrade a Helm release that was initially deployed using the Helm CLI. You can bypass this limitation by using the Helm CLI to upgrade.
However, if you still want to upgrade using the console, select the Helm Chart version from the drop-down list and select the {product-short} version you want to upgrade to. Before performing this step, save your `values.yaml` configuration file in a different location.
====
+
[IMPORTANT]
====
You can upgrade {product} directly from any previous version to the latest release without installing intermediate versions. Before upgrading, you must review the release notes for every skipped version to identify breaking changes, deprecations, or required migration steps. For example, if upgrading from version 1.5 to 1.7, check the release notes for both 1.6 and 1.7.
====
. In the *Developer* perspective, click *Helm* to open the *Helm Releases* tab.

. Click the overflow menu on the Helm release that you want to use and select *Upgrade*.

. On the *Upgrade Helm Release* page, select the version of {product-short} that you want to upgrade to from the chart version drop-down list.

. Click *Upgrade*.
+
[NOTE]
====
It might take a few minutes to delete the resources in the older versions and to start the newer versions of the {product-short} pods.
====

. Close all open {product-short} web pages, and log in again to verify that the upgrade was successful.

* {ocp-short} CLI

. Log in to the {ocp-short} cluster as the cluster administrator and switch to the project or namespace in which {product-short} was installed.
+
[source,terminal,subs="+attributes,+quotes"]
----
oc login -u <user> -p <password> https://api.<HOSTNAME>:6443
oc project {my-product-namespace}
----

. For a new version of the {product-short} Helm chart, run the following upgrade command:
+
[source,terminal,subs="attributes+"]
----
helm upgrade -i rhdh -f new-values.yml \
  openshift-helm-charts/redhat-developer-hub --version {product-chart-version}
----
+
[NOTE]
====
You can also provide extra values to the chart by creating a `new-values.yml` file on your workstation with values that override the attributes in the installed chart or by adding new attributes.
====
