// Module included in the following assemblies:
//
// * assemblies/assembly-admin-templates.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-adding-templates_{context}"]
= Importing an existing template to {product}

You can add an existing template to your {product} instance by using the Catalog Processor.

.Prerequisites

* You have created a directory or repository that contains at least one template YAML file.
* If you want to use a template that is stored in a repository such as GitHub or GitLab, you must configure a {product} integration for your provider.

.Procedure

* In the `app-config.yaml` configuration file, modify the `catalog.rules` section to include a rule for templates, and configure the `catalog.locations` section to point to the template that you want to add, as shown in the following example:
+
[source,yaml]
----
# ...
catalog:
  rules:
    - allow: [Template] # <1>
  locations:
    - type: url # <2>
      target: https://<repository_url>/example-template.yaml # <3>
# ...
----
<1> To allow new templates to be added to the catalog, you must add a `Template` rule.
<2> If you are importing templates from a repository, such as GitHub or GitLab, use the `url` type.
<3> Specify the URL for the template.

.Verification

. Click the *Catalog* tab in the navigation panel.
. In the *Kind* drop-down menu, select *Template*.
. Confirm that your template is shown in the list of existing templates.
