// Module included in the following assemblies:
//
// * assemblies/assembly-techdocs-addons-removing.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-addon-remove-helm_{context}"]
== Removing an external TechDocs add-on from your Helm chart

If you no longer want to use the functionality of a TechDocs add-on that are imported from a particular plugin that you installed on your {product} instance with the Helm chart, you can temporarily disabled it or permanently remove it from your Helm chart. The `disabled` status is controlled at the plugin level, therefore, disabling the plugin disables all of the TechDocs add-ons in the disabled plugin package.

.Procedure
* In the `plugins` section of the Helm chart, do one of the following actions based on whether you want to disable or remove a TechDocs add-on:
** To temporarily disable all of the TechDocs add-ons in a particular plugin package, change the value of the `disabled` field to `true`. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: true
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
                  - importName: _<external_techdocs_add-on>_
----
+
where:

_<external_techdocs_add-on>_:: Specifies the external TechDocs add-on that you want to remove, for example, `TextSize`.
** To permanently remove one or more TechDocs add-ons from a plugin package, delete `importName: _<external_techdocs_add-on>` for each external TechDocs add-on that you want to remove. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
                  - importName: _<external_techdocs_add-on>_
----
+
where:

_<external_techdocs_add-on>_:: Specifies the external TechDocs add-on that you want to remove, for example, `TextSize`.

//.Next steps