// Module included in the following assemblies:
//
// * assemblies/assembly-techdocs-addons-using.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-addon-use-report-issue_{context}"]
= Using the ReportIssue TechDocs add-on

If you find an error in your organization's TechDocs documentation, you can use the `ReportIssue` add-on to open a new GitHub or GitLab issue directly from the documentation. `ReportIssue` automatically imports the text that you highlight in the document into a new issue template in your repository.

.Prerequisites
* The `ReportIssue` add-on is installed and enabled in your TechDocs plugin.
* You have permissions to create issues in the repository where documentation issues are reported.

.Procedure
. In your TechDocs documentation, highlight the text that you want to report an issue for.
. Click the text in the `ReportIssue` box, for example, *Open new GitHub issue*.
. From the new issue page in your repository, use the template to create the issue that you want to report.
+
[NOTE]
====
The default issue title is *Documentation feedback: _<highlighted_text>_*, where _<highlighted_text>_ is the text that you highlighted in your TechDocs documentation.

In the issue description, _<highlighted_text>_ is the default value for the *The highlighted text* field.
====

.Verification
* The issue that you created is listed on the issues page in your repository.
