// Module included in the following assemblies:
//
// * assemblies/assembly-techdocs-addons-installing.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-addon-install-helm_{context}"]
== Installing and configuring an external TechDocs add-on using the Helm chart

You can use the {product} Helm chart to install a TechDocs add-on on your {product} instance as a dynamic plugin.

.Procedure
. In your Helm chart, add the `global.dynamic` parameters required to install a dynamic plugin, as shown in link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.4/html/installing_and_viewing_plugins_in_red_hat_developer_hub/rhdh-installing-rhdh-plugins_title-plugins-rhdh-about#con-install-dynamic-plugin-helm_rhdh-installing-rhdh-plugins[Installing dynamic plugins using the Helm chart ]
+
[NOTE]
====
The default configuration includes the `dynamic-plugins.default.yaml` file, which contains all of the dynamic plugins, including TechDocs add-ons, that are preinstalled in {product}, whether they are enabled or disabled by default.
====
. In your Helm chart, add the default `backstage-plugin-techdocs-module-addons-contrib` package configuration. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
----
+
[NOTE]
====
Preinstalled add-ons, such as `ReportIssue`, are included in the default package configuration. Additional add-ons are installed by manually adding them to the configuration file.
====

. In the `techdocsAddons` section of the Helm chart, add `importName: _<external_techdocs_add-on>` for each external TechDocs add-on that you want to install. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
global:
  dynamic:
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
                  - importName: _<external_techdocs_add-on>_
----
+
where:

_<external_techdocs_add-on>_:: Specifies the external TechDocs add-on that you want to install, for example, `TextSize`.

//.Next steps