// Module included in the following assemblies:
//
// * assemblies/assembly-using-techdocs.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-pipeline-github-actions_{context}"]
= Generating TechDocs Pipelines with GitHub Actions

{product} ({product-very-short}) includes a built-in TechDocs builder, however, the default setup is not intended for production use. Deploying TechDocs documentation in a production environment involves the following actions:

* *Building the documentation in a CI/CD system*
* *Publishing the generated documentation site to external object storage*, such as AWS S3, to ensure that the generated documentation persists between restarts of {product-very-short} and can handle larger documentation workloads.
* *Configuring TechDocs in your {product-very-short} deployment to run in read-only mode* so that TechDocs reads the static generated documentation files from the cloud storage bucket without attempting to generate them at runtime.

You can implement a TechDocs pipeline using GitHub Actions to automatically generate and publish your TechDocs whenever a user in your organization makes a change to a documentation file stored in your GitHub respository.

.Prerequisites

* The TechDocs plugin is enabled and configured on your {product-very-short} instance.
* Your organization has documentation files stored in a remote repository.
* You have an mkdocs.yaml file located in the root directory of your repository.
* You have the `catalog.entity.create` and `catalog.location.create` permissions to import documentation into TechDocs from a remote repository.
* You have an AWS S3 bucket created to store your TechDocs sites.
* Minimal IAM Policies are configured for your S3 bucket, granting both Write and Read access.
* An IAM User has been created, the necessary policy attached, and an access key generated.

.Procedure

. Set up the GitHub Actions workflow
.. On GitHub, create a fork of the `rhdh-techdocs-pipeline` repository.
+
[NOTE]
====
The `rhdh-techdocs-pipeline` repository contains a `generate-and-publish-techdocs.yaml` workflow that automatically generates TechDocs from the docs folder and publishes them to an Amazon S3 bucket.
====
+
.. Use the GitHub GUI to make sure that all of the permissions required to run the workflow are enabled.
.. Add the *Repository secrets* required to connect the workflow to your AWS account.
+
[NOTE]
====
The default `mkdocs.yaml` file in the `rhdh-techdocs-pipeline` workflow installs the `techdocs-core` and `minify` plugins.
====
.. Optional: Modify the default structure of the `rhdh-techdocs-pipeline` repository or the default files within it to meet the needs of your organization.
.. Optional: Add other `mkdocs` plugins that you want to use by adding the name of the plugins to the `plugins` section of the `mkdocs.yaml` file and to the `steps.name: install mkdocs and mkdocs plugins` section of the `generate-and-publish-techdocs.yaml` file.
. Update the `app-config.yaml` file to enable your Amazon S3 bucket to serve TechDocs to your {product-very-short} instance.
.. In the Developer perspective of {ocp-short} console, click *ConfigMaps* and select your {product-very-short} `app-config.yaml` file.
.. In the `techdocs` section of the `app-config.yaml` file, set `builder` to `external`.
.. Set `publisher.type` to `awsS3`.
.. In the `aws` section, set `accounts.accountId` to `$(AWS_ACCOUNT_ID)`, set `accounts.accessKeyId` to `$(AWS_ACCESS_KEY_ID)`, and set `accounts.secretAccessKey` to `$(AWS_SECRET_ACCESS_KEY)`.
.. In the `catalog` section, set `locations.type` to `url` and set `locations.target` to the url to the `catalog-info.yaml` file in your `rhdh-techdocs-pipeline` repository.
. Click *Save*.
. In the navigation menu of the {ocp-short} console, click *Topology* and restart the pod.
+
[NOTE]
====
Changes to the `docs` folder or the `mkdocs.yaml` file trigger the `rhdh-techdocs-pipeline` workflow to run. After the `rhdh-techdocs-pipeline` workflow runs successfully, the generated TechDocs are uploaded to your Amazon S3 bucket.
====

.Verification
. Go to your {product-very-short} instance and click *Docs* to see the TechDocs served from your Amazon S3 bucket.
