// Module included in the following assemblies:
//
// * assemblies/assembly-techdocs-add-docs.adoc

:_mod-docs-content-type: PROCEDURE
[id="proc-techdocs-add-docs-github_{context}"]
== Importing documentation into TechDocs from a remote repository

Teams can store their documentation files in the same remote repository where they store their code files. You can import documentation into your TechDocs plugin from a GitHub repository that contains the documentation files that your team uses.

.Prerequisites

* Your organization has documentation stored in a GitHub repository.
* You have the `catalog.entity.create` and `catalog.location.create` permissions to import documentation into TechDocs from a remote repository.

.Procedure

. In your {product} instance, click *Catalog > Self-service > Register Existing Component*.
. In the *Select URL* box, enter the URL to the `catalog-info.yaml` file that you want to import from your repository using the following format:
+
`https://github.com/_<project_name>_/_<repo_name>_/blob/_<branch_name>_/_<file_directory>_/catalog-info.yaml`
+
. Click *Analyze*
. Click *Finish*

.Verification

. In the {product} navigation menu, click *Docs*.
. Verify that the documentation that you imported is listed in the table on the Documentation page.
