:_mod-docs-content-type: PROCEDURE

[id="remove-an-external-techdocs-add-on-from-your-configmap_{context}"]
= Remove an external TechDocs add-on from your ConfigMap

[role="_abstract"]
Disable or permanently remove an external TechDocs add-on from your {product} ConfigMap when you no longer need it.

The `disabled` status is controlled at the plugin level, therefore, disabling the plugin disables all of the TechDocs add-ons in the disabled plugin package.

.Procedure

. From the Developer perspective in the {ocp-short} web console, click *ConfigMaps*.
. From the *ConfigMaps* page, click the ConfigMap that contains the TechDocs add-on that you want to remove.
. Select the *YAML view* option in the *Configure via* field.
. In the `plugins` section of the ConfigMap, do one of the following actions based on whether you want to disable or remove a TechDocs add-on:
** To temporarily disable all of the TechDocs add-ons in a particular plugin package, change the value of the `disabled` field to `true`. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: true
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
                  - importName: _<external_techdocs_add-on>_
----
+
where:

_<external_techdocs_add-on>_:: Specifies the external TechDocs add-on that you want to remove, for example, `TextSize`.
** To remove one or more TechDocs add-ons from your {product} instance, delete `importName: _<external_techdocs_add-on>_` for each external TechDocs add-on that you want to remove from the `techdocsAddons` section of your ConfigMap. For example:
+
[source,yaml,subs="+quotes,+attributes"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: dynamic-plugins-rhdh
data:
  dynamic-plugins.yaml: |
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      - package: ./dynamic-plugins/dist/backstage-plugin-techdocs-module-addons-contrib
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              backstage.plugin-techdocs-module-addons-contrib:
                techdocsAddons:
                  - importName: ReportIssue
                  - importName: _<external_techdocs_add-on>_
----
+
where:

_<external_techdocs_add-on>_:: Specifies the external TechDocs add-on that you want to remove, for example, `TextSize`.
. Click *Save*.
. In the web console navigation menu, click *Topology* and wait for the {product} pod to start.
. Click the *Open URL* icon to start using the {product} platform with the new configuration changes.

//.Next steps
