[id='con-breaking-changes_{context}']
= Breaking changes

This section lists breaking changes with {product} {product-version}:

== Configuration change in the GitHub Organization catalog provider  

The GitHub Organization catalog module for the new backend system switched to a new `GithubMultiOrgEntityProvider` provider, which allows ingesting data from multiple GitHub organizations. This new provider brings in changes to the default plugin configuration settings. Because this is a breaking configuration change, you must upgrade the `@backstage/plugin-catalog-backend-module-github-org` plugin and reconfigure it in the following manner:

.Configuring the `@backstage/plugin-catalog-backend-module-github-org` plugin
--
[source,yaml]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    ...
    catalog:
      providers:
        githubOrg:
          id: production
          githubUrl: "${GITHUB_URL}"
          orgs: [ "${GITHUB_ORG}" ] <1>
    ...
----

<1> Replace `${GITHUB_ORG}` with the GitHub organization you want to ingest users from.
--

For more information, see the link:{LinkGettingStartedGuide}#enabling-github-organization-member-discovery-in-red-hat-developer-hub[Enabling GitHub organization member discovery in {product}] section in the _Getting started guide_.
