[id='con-release-notes-overview_{context}']
= About this release

The release notes provide high-level coverage of the features that have been implemented in {product} {product-version} and document known issues in this release.

Some features within this release may be available as a Technology Preview, providing access to upcoming product features, enabling customers to test functionality and to provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, read https://access.redhat.com/support/offerings/techpreview[Technology Preview Support Scope]. 

Benefits of {product} include:

* *Increased developer productivity*: Increases productivity by eliminating common organizational challenges, enabling seamless collaboration, and providing clear guidelines for creating, developing, and deploying applications.
* *Unified self-service dashboard*: Provides development teams with a unified dashboard covering various aspects such as Git, CI/CD, SAST/DAST, Supply Chain, OpenShift/Kubernetes cluster, JIRA, monitoring, API, documentation, and more, facilitated by over 150 plugins. All curated by a platform engineering team, aligning with the company's best practices.
* *Best practices through software templates*: Automates organizational best practices by encoding common tasks such as creating new applications, running Ansible jobs, and establishing CI/CD pipelines for production deployment in Git.
* *Scalable technical documentation*: Code and documentation resides in the same repository, eliminating dependencies on proprietary document systems.
* *Efficient onboarding for new developers*: New developers quickly adapt and become productive within a short timeframe.
* *Robust enterprise Role-Based Access Control (RBAC)*: Empowers administrators to create roles, assign users or groups to roles, and implement robust security policies for enhanced access control.

== Supported platforms
* OpenShift Container Platform 4.12, 4.13, 4.14, 4.15 
* Red Hat OpenShift Service on AWS (ROSA)
* Azure Red Hat OpenShift (ARO)
* Amazon Elastic Kubernetes Service (EKS)
* Microsoft Azure Kubernetes Service (AKS)
* [Technical Preview] Google Kubernetes Engine (GKE)

== Supported architectures

Containers are available for the following CPU architectures:

* AMD64 and Intel 64 (x86_64)

== Upgrading the {product} Helm Chart 

You can upgrade to a new version of {product} by using:

* OpenShift web console

. In the *Developer* perspective, click *Helm* to open the *Helm Releases* tab.

. Click the three dots next to the Helm release entry and select *Upgrade*.

. In the *Upgrade Helm Release* page, select the version of {product-short} that you want to upgrade to from the chart version drop-down list. 

. Click *Upgrade*. 
+
[NOTE]
====
You must wait while the resources in the older versions are deleted and newer versions of the {product-short} pods are launched.
====

. Close all open {product-short} web pages, and log in again to verify that the upgrade was successful.

* OpenShift CLI

. Log in to the OpenShift cluster as the cluster administrator and switch to the `devhub` project.
+
[source]
----
oc login -u <user> -p <password> https://api.<HOSTNAME>:6443
oc project devhub
----

. For a new version of the {product-short} helm chart, run the following upgrade command:
+
[source,subs="attributes+"]
----
helm upgrade -i rhdh -f new-values.yml \
  openshift-helm-charts/redhat-developer-hub --version {product-chart-version}
----
+
[NOTE]
====
You can also provide extra values to the chart by creating a `new-values.yml` file on your workstation with values that override the attributes in the installed chart or by adding new attributes.
====
