[id='con-relnotes-techpreview-features_{context}']
= Technology preview

This section lists features that are in Technology Preview in {product} {product-version}.

[IMPORTANT]
====
These features are for Technology Preview only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs), might not be functionally complete, and Red Hat does not recommend using them for production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information on Red Hat Technology Preview features, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Scope].
====

== Plugins available in {product}

{product} incorporates various dynamic plugins. Red Hat fully supports certain plugins, while others are community-supported projects. Some plugins are enabled by default, while others require configuration and are consequently disabled by default.

For more information about how to enable, disable, or configure dynamic plugins, see the link:{LinkAdminGuide}#rhdh-installing-dynamic-plugins[Installing dynamic plugins] section in the _Administration guide_.

To get a comprehensive list of supported dynamic plugins, see the link:{LinkAdminGuide}#rhdh-supported-plugins[Dynamic plugins included in {product}] section in the _Administration guide_.
