[id='con-release-notes-overview_{context}']
= About this release

The release notes provide high-level coverage of the features that have been implemented in {product} {product-version} and document known issues in this release.

Some features within this release may be available as a Technology Preview, providing access to upcoming product features, enabling customers to test functionality and to provide feedback during the development process.

For more information about the support scope of Red Hat Technology Preview features, read https://access.redhat.com/support/offerings/techpreview[Technology Preview Support Scope]. 

Benefits of {product} include:

* *Increased developer productivity*: Increases productivity by eliminating common organizational challenges, enabling seamless collaboration, and providing clear guidelines for creating, developing, and deploying applications.
* *Unified self-service dashboard*: Provides development teams with a unified dashboard covering various aspects such as Git, CI/CD, SAST/DAST, Supply Chain, OpenShift/Kubernetes cluster, JIRA, monitoring, API, documentation, and more, facilitated by over 150 plugins. All curated by a platform engineering team, aligning with the company's best practices.
* *Best practices through software templates*: Automates organizational best practices by encoding common tasks such as creating new applications, running Ansible jobs, and establishing CI/CD pipelines for production deployment in Git.
* *Scalable technical documentation*: Code and documentation resides in the same repository, eliminating dependencies on proprietary document systems.
* *Efficient onboarding for new developers*: New developers quickly adapt and become productive within a short timeframe.
* *Robust enterprise Role-Based Access Control (RBAC)*: Empowers administrators to create roles, assign users or groups to roles, and implement robust security policies for enhanced access control.
* *Enterprise-grade support*: Enable enterprises to concentrate on their core business by ensuring business continuity for the development team with 24x7 enterprise support.

	

