[id='con-relnotes-notable-features_{context}']
= New features

This section highlights new features in {product} {product-version}.

== {product} Operator is now generally available (GA)

You can use the {product} Operator to install {product-short} on your OpenShift Container Platform cluster. For more information, see the link:{LinkAdminGuide}#proc-install-rhdh-operator[Installing {product} using the Operator] section in the _Administration guide_.

== Change in productized version  

{product} productized version is now based on the upstream Backstage project v1.23.4. 


== Ability to manage role-based access controls (RBAC) using the web interface  

As an administrator, you can now use {product-short} to assign specific roles and permissions to individual users or groups. Using the {product-short} web interface, you can perform the following actions:

* Creating a role 
* Editing a role and related permissions
* Deleting a role

For more information, see the link:{LinkAdminGuide}#con-rbac-overview[Role-Based Access Control in {product}] section in the _Administration guide_.


==  Migration of the {product} to the new backend system  

{product} {product-version} is now migrated to the Backstage new backend system. With this migration, you might notice the following functionality-related changes in the {product-short} application:

=== Configuration change in the GitHub Organization catalog provider  

The GitHub Organization catalog module for the new backend system switched to a new `GithubMultiOrgEntityProvider` provider, which allows ingesting data from multiple GitHub organizations. This new provider brings in changes to the default plugin configuration settings.

=== New Scaffolder Identity client

Identity client functioning differs slightly between the one provided by the new backend system Scaffolder plugin and the one used in the previous release.

The new backend system's Scaffolder plugin utilizes an identity service that introduces slight differences impacting error handling. For example, when encountering an invalid authorization header in a request, {product-short} logs the error into the console instead of discarding it.

=== Enable all GitLab actions

{product} {product-version} enables all GitLab actions by default.

== Support for Elastic Kubernetes Services (EKS)

You can now install and use the {product} on an EKS cluster. 

For more information, see the link:{LinkAdminGuide}#con-rhdh-integration-aws[{product} integration with Amazon Web Services] section in the _Administration guide_.

== Support for Azure Kubernetes Services (AKS)

You can now install and use the {product} on an AKS cluster. 


== Support for viewing installed plugins using the web interface 

As an administrator, you can now use the {product-short} web interface to view a table of plugins that are installed. This feature uses the `dynamic-plugins-info` frontend component, which generates a table of plugins that are currently installed in the {product}. You can apply client-side sorting, filtering, and pagination to the plugins table.


== Supported plugins in {product} {product-version}

To get a comprehensive list of supported dynamic plugins, see the link:{LinkAdminGuide}#rhdh-supported-plugins[Dynamic plugins included in {product}] section in the _Administration guide_.
