= Release notes for Red Hat Developer Hub 0.2

Red Hat Developer Hub 0.2 is a version of Backstage that Red Hat supports. It comes integrated with pre-built plug-ins, configuration settings, and deployment mechanisms, which enables you to streamline your end-to-end development environment. 

The Red Hat Developer Hub includes:

* Software catalog to manage all your microservices, pipelines, and libraries
* Plug-ins to expand the customizability and functionality
* Tech Docs to create, maintain, and use technical documentation easily
* Golden Path Templates (GPTs) to accelerate typical application development use cases

== About this release

The Red Hat Developer Hub 0.2 is Developer Preview only. Features and known issues that exist in RHDH 0.2 are included in this topic. This Developer Preview software is not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using RHDH in production. 

Developer Preview provides early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

For more information about the support scope of Red Hat Developer Preview features, read link:https://access.redhat.com/support/offerings/devpreview[Developer Preview Support Scope].

== Notable features

The Red Hat Developer Hub 0.2 provides the following customization capabilities:

* Ability to use Golden Path Templates (GPTs) that injects the best practices of an application development
* Ability to customize technology radar, which helps you map out a tech strategy that keeps you ahead of the curve
* Ability to customize your home page to highlight specific information



//== Known issues

