:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="customize-rhdh-theme-and-branding_{context}"]
= Customize {product} theme and branding

:previouscontext: {context}
:context: customize-rhdh-theme-and-branding

[role="_abstract"]
By modifying the visual aspects of the interface, organizations can align {product} with their branding guidelines and improve the overall user experience.

The following default theme configurations are available for {product}:

The {product} theme:: Default theme configurations to make your developer portal look like a standard {product} instance.

The {backstage} theme:: Default theme configurations to make your developer portal look like a standard {backstage} instance.

You can change or disable particular parameters in a default theme or create a fully customized theme by modifying the `{my-app-config-file}` file. From the `{my-app-config-file}` file, you can customize common theme components, including the following components:

* Company name and logo
* Font color, size, and style of text in paragraphs, headings, headers, and buttons
* Header color, gradient, and shape
* Button color
* Navigation indicator color

You can also customize some components from the {product-short} GUI, such as the theme mode (*Light Theme*, *Dark Theme*, or *Auto*).

include::../modules/shared/proc-switch-the-theme-mode-for-your-rhdh-instance.adoc[leveloffset=+1]

include::../modules/shared/proc-customize-the-branding-logo-of-your-rhdh-instance.adoc[leveloffset=+1]

include::../modules/shared/proc-customize-the-theme-mode-color-palettes-for-your-rhdh-instance.adoc[leveloffset=+1]

include::../modules/shared/proc-customize-the-page-theme-header-for-your-rhdh-instance.adoc[leveloffset=+1]

include::../modules/shared/proc-customize-the-font-for-your-rhdh-instance.adoc[leveloffset=+1]

include::../modules/shared/ref-default-rhdh-theme.adoc[leveloffset=+1]

include::../modules/shared/ref-default-theme.adoc[leveloffset=+1]

include::../modules/shared/proc-load-a-custom-rhdh-theme-by-using-a-dynamic-plugin.adoc[leveloffset=+1]

include::../modules/shared/ref-custom-component-options-for-your-rhdh-instance.adoc[leveloffset=+1]

:context: {previouscontext}
:!previouscontext:

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
