:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="configure-a-floating-action-button-in-rhdh_{context}"]
= Configure a floating action button in {product}

:previouscontext: {context}
:context: configure-a-floating-action-button-in-rhdh

[role="_abstract"]
Configure any action as a floating button in the {product-short} instance by using the floating action button plugin.

[IMPORTANT]
====
As of {product-very-short} 1.9, the Global Floating Action Button plugin is disabled by default and is link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.9/html/red_hat_developer_hub_release_notes/deprecated-features[deprecated]. The Global Header plugin provides equivalent and improved navigation capabilities by using quick links and starred items.

For new deployments, use the Global Header instead. See xref:configure-the-global-header-in-rhdh_customizing-rhdh[Configure the Global Header in {product}]. 

Existing deployments that explicitly enable the Global Floating Action Button are not affected and you can continue to use this plugin. However, as the plugin is deprecated, it will be removed in a future {product-very-short} version, and you might need to adjust your configuration in future versions. 
====

include::../modules/shared/proc-configure-a-floating-action-button-as-a-dynamic-plugin.adoc[leveloffset=+1]

// Localization
include::../modules/shared/con-floating-action-button-localization-support.adoc[leveloffset=+1]

include::../modules/shared/con-internal-translation-implementation.adoc[leveloffset=+1]
// END Localization

include::../modules/shared/ref-floating-action-button-parameters.adoc[leveloffset=+1]

:context: {previouscontext}
:!previouscontext:

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
