:_mod-docs-content-type: ASSEMBLY
ifdef::context[:parent-context: {context}]

[id="configure-the-global-header-in-rhdh_{context}"]
= Configure the global header in {product}

:previouscontext: {context}
:context: configure-the-global-header-in-rhdh

[role="_abstract"]
As an administrator, you can configure the {product} global header to create a consistent and flexible navigation bar across your {product-short} instance.
By default, the {product-short} global header includes the following components:

* *Self-service* button provides quick access to a variety of templates, enabling users to efficiently set up services, backend and front-end plugins within {product-short}
* *Support* button that can link an internal or external support page
* *Notifications* button displays alerts and updates from plugins and external services
* *Search* input field allows users to find services, components, documentation, and other resources within {product-short}
* *Plugin extension capabilities* provide a preinstalled and enabled catalog of available plugins in {product-short}
* *User profile* drop-down menu provides access to profile settings, appearance customization, {product-short} metadata, and a logout button

include::../modules/shared/proc-customize-your-rhdh-global-header.adoc[leveloffset=+1]


include::../modules/shared/ref-mount-points-for-dynamic-plugin-integration.adoc[leveloffset=+1]

include::../modules/shared/proc-configure-the-logo-in-the-global-header.adoc[leveloffset=+1]

include::../modules/shared/proc-enable-logo-in-the-sidebar.adoc[leveloffset=+1]

include::../modules/shared/proc-display-the-preferred-username-in-the-profile-dropdown.adoc[leveloffset=+1]

include::../modules/shared/con-quicklinks-and-starred-items-in-the-global-header.adoc[leveloffset=+1]

include::../modules/shared/proc-enable-quicklinks-and-starred-items-after-an-upgrade.adoc[leveloffset=+1]

:context: {previouscontext}
:!previouscontext:

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
