:_mod-docs-content-type: SNIPPET

[IMPORTANT]
====
This section describes {developer-preview} features in the Model Context Protocol plugin. {developer-preview} features are not supported by Red Hat in any way and are not functionally complete or production-ready. Do not use {developer-preview} features for production or business-critical workloads. {developer-preview} features provide early access to functionality in advance of possible inclusion in a Red Hat product offering. Customers can use these features to test functionality and provide feedback during the development process. {developer-preview} features might not have any documentation, are subject to change or removal at any time, and have received limited testing. Red Hat might provide ways to submit feedback on {developer-preview} features without an associated SLA.

For more information about the support scope of Red Hat {developer-preview} features, see https://access.redhat.com/support/offerings/devpreview/[{developer-preview} Support Scope].
====
